// GENERATED CODE - DO NOT MODIFY BY HAND

package intl

import "strings"

// CountryCode represents an ISO 3166-1 alpha-2 country code.
type CountryCode string

// Country codes.
const (
	CountryAF CountryCode = "AF"
	CountryAX CountryCode = "AX"
	CountryAL CountryCode = "AL"
	CountryDZ CountryCode = "DZ"
	CountryAS CountryCode = "AS"
	CountryAD CountryCode = "AD"
	CountryAO CountryCode = "AO"
	CountryAI CountryCode = "AI"
	CountryAQ CountryCode = "AQ"
	CountryAG CountryCode = "AG"
	CountryAR CountryCode = "AR"
	CountryAM CountryCode = "AM"
	CountryAW CountryCode = "AW"
	CountryAU CountryCode = "AU"
	CountryAT CountryCode = "AT"
	CountryAZ CountryCode = "AZ"
	CountryBS CountryCode = "BS"
	CountryBH CountryCode = "BH"
	CountryBD CountryCode = "BD"
	CountryBB CountryCode = "BB"
	CountryBY CountryCode = "BY"
	CountryBE CountryCode = "BE"
	CountryBZ CountryCode = "BZ"
	CountryBJ CountryCode = "BJ"
	CountryBM CountryCode = "BM"
	CountryBT CountryCode = "BT"
	CountryBO CountryCode = "BO"
	CountryBQ CountryCode = "BQ"
	CountryBA CountryCode = "BA"
	CountryBW CountryCode = "BW"
	CountryBV CountryCode = "BV"
	CountryBR CountryCode = "BR"
	CountryIO CountryCode = "IO"
	CountryVG CountryCode = "VG"
	CountryBN CountryCode = "BN"
	CountryBG CountryCode = "BG"
	CountryBF CountryCode = "BF"
	CountryBI CountryCode = "BI"
	CountryCV CountryCode = "CV"
	CountryKH CountryCode = "KH"
	CountryCM CountryCode = "CM"
	CountryCA CountryCode = "CA"
	CountryKY CountryCode = "KY"
	CountryCF CountryCode = "CF"
	CountryTD CountryCode = "TD"
	CountryCL CountryCode = "CL"
	CountryCN CountryCode = "CN"
	CountryCX CountryCode = "CX"
	CountryCC CountryCode = "CC"
	CountryCO CountryCode = "CO"
	CountryKM CountryCode = "KM"
	CountryCG CountryCode = "CG"
	CountryCD CountryCode = "CD"
	CountryCK CountryCode = "CK"
	CountryCR CountryCode = "CR"
	CountryCI CountryCode = "CI"
	CountryHR CountryCode = "HR"
	CountryCU CountryCode = "CU"
	CountryCW CountryCode = "CW"
	CountryCY CountryCode = "CY"
	CountryCZ CountryCode = "CZ"
	CountryDK CountryCode = "DK"
	CountryDJ CountryCode = "DJ"
	CountryDM CountryCode = "DM"
	CountryDO CountryCode = "DO"
	CountryEC CountryCode = "EC"
	CountryEG CountryCode = "EG"
	CountrySV CountryCode = "SV"
	CountryGQ CountryCode = "GQ"
	CountryER CountryCode = "ER"
	CountryEE CountryCode = "EE"
	CountrySZ CountryCode = "SZ"
	CountryET CountryCode = "ET"
	CountryFK CountryCode = "FK"
	CountryFO CountryCode = "FO"
	CountryFJ CountryCode = "FJ"
	CountryFI CountryCode = "FI"
	CountryFR CountryCode = "FR"
	CountryGF CountryCode = "GF"
	CountryPF CountryCode = "PF"
	CountryTF CountryCode = "TF"
	CountryGA CountryCode = "GA"
	CountryGM CountryCode = "GM"
	CountryGE CountryCode = "GE"
	CountryDE CountryCode = "DE"
	CountryGH CountryCode = "GH"
	CountryGI CountryCode = "GI"
	CountryGR CountryCode = "GR"
	CountryGD CountryCode = "GD"
	CountryGP CountryCode = "GP"
	CountryGU CountryCode = "GU"
	CountryGT CountryCode = "GT"
	CountryGG CountryCode = "GG"
	CountryGN CountryCode = "GN"
	CountryGW CountryCode = "GW"
	CountryGY CountryCode = "GY"
	CountryHT CountryCode = "HT"
	CountryHM CountryCode = "HM"
	CountryHN CountryCode = "HN"
	CountryHK CountryCode = "HK"
	CountryHU CountryCode = "HU"
	CountryIS CountryCode = "IS"
	CountryIN CountryCode = "IN"
	CountryID CountryCode = "ID"
	CountryIR CountryCode = "IR"
	CountryIQ CountryCode = "IQ"
	CountryIE CountryCode = "IE"
	CountryIM CountryCode = "IM"
	CountryIL CountryCode = "IL"
	CountryIT CountryCode = "IT"
	CountryJM CountryCode = "JM"
	CountryJP CountryCode = "JP"
	CountryJE CountryCode = "JE"
	CountryJO CountryCode = "JO"
	CountryKZ CountryCode = "KZ"
	CountryKE CountryCode = "KE"
	CountryKI CountryCode = "KI"
	CountryKW CountryCode = "KW"
	CountryKG CountryCode = "KG"
	CountryLA CountryCode = "LA"
	CountryLV CountryCode = "LV"
	CountryLB CountryCode = "LB"
	CountryLS CountryCode = "LS"
	CountryLR CountryCode = "LR"
	CountryLY CountryCode = "LY"
	CountryLI CountryCode = "LI"
	CountryLT CountryCode = "LT"
	CountryLU CountryCode = "LU"
	CountryMO CountryCode = "MO"
	CountryMG CountryCode = "MG"
	CountryMW CountryCode = "MW"
	CountryMY CountryCode = "MY"
	CountryMV CountryCode = "MV"
	CountryML CountryCode = "ML"
	CountryMT CountryCode = "MT"
	CountryMH CountryCode = "MH"
	CountryMQ CountryCode = "MQ"
	CountryMR CountryCode = "MR"
	CountryMU CountryCode = "MU"
	CountryYT CountryCode = "YT"
	CountryMX CountryCode = "MX"
	CountryFM CountryCode = "FM"
	CountryMD CountryCode = "MD"
	CountryMC CountryCode = "MC"
	CountryMN CountryCode = "MN"
	CountryME CountryCode = "ME"
	CountryMS CountryCode = "MS"
	CountryMA CountryCode = "MA"
	CountryMZ CountryCode = "MZ"
	CountryMM CountryCode = "MM"
	CountryNA CountryCode = "NA"
	CountryNR CountryCode = "NR"
	CountryNP CountryCode = "NP"
	CountryNL CountryCode = "NL"
	CountryNC CountryCode = "NC"
	CountryNZ CountryCode = "NZ"
	CountryNI CountryCode = "NI"
	CountryNE CountryCode = "NE"
	CountryNG CountryCode = "NG"
	CountryNU CountryCode = "NU"
	CountryNF CountryCode = "NF"
	CountryKP CountryCode = "KP"
	CountryMK CountryCode = "MK"
	CountryMP CountryCode = "MP"
	CountryNO CountryCode = "NO"
	CountryOM CountryCode = "OM"
	CountryPK CountryCode = "PK"
	CountryPW CountryCode = "PW"
	CountryPS CountryCode = "PS"
	CountryPA CountryCode = "PA"
	CountryPG CountryCode = "PG"
	CountryPY CountryCode = "PY"
	CountryPE CountryCode = "PE"
	CountryPH CountryCode = "PH"
	CountryPN CountryCode = "PN"
	CountryPL CountryCode = "PL"
	CountryPT CountryCode = "PT"
	CountryPR CountryCode = "PR"
	CountryQA CountryCode = "QA"
	CountryRE CountryCode = "RE"
	CountryRO CountryCode = "RO"
	CountryRU CountryCode = "RU"
	CountryRW CountryCode = "RW"
	CountryBL CountryCode = "BL"
	CountrySH CountryCode = "SH"
	CountryKN CountryCode = "KN"
	CountryLC CountryCode = "LC"
	CountryMF CountryCode = "MF"
	CountryPM CountryCode = "PM"
	CountryVC CountryCode = "VC"
	CountryWS CountryCode = "WS"
	CountrySM CountryCode = "SM"
	CountryST CountryCode = "ST"
	CountrySA CountryCode = "SA"
	CountrySN CountryCode = "SN"
	CountryRS CountryCode = "RS"
	CountrySC CountryCode = "SC"
	CountrySL CountryCode = "SL"
	CountrySG CountryCode = "SG"
	CountrySX CountryCode = "SX"
	CountrySK CountryCode = "SK"
	CountrySI CountryCode = "SI"
	CountrySB CountryCode = "SB"
	CountrySO CountryCode = "SO"
	CountryZA CountryCode = "ZA"
	CountryGS CountryCode = "GS"
	CountryKR CountryCode = "KR"
	CountrySS CountryCode = "SS"
	CountryES CountryCode = "ES"
	CountryLK CountryCode = "LK"
	CountrySD CountryCode = "SD"
	CountrySR CountryCode = "SR"
	CountrySJ CountryCode = "SJ"
	CountrySE CountryCode = "SE"
	CountryCH CountryCode = "CH"
	CountrySY CountryCode = "SY"
	CountryTW CountryCode = "TW"
	CountryTJ CountryCode = "TJ"
	CountryTZ CountryCode = "TZ"
	CountryTH CountryCode = "TH"
	CountryTL CountryCode = "TL"
	CountryTG CountryCode = "TG"
	CountryTK CountryCode = "TK"
	CountryTO CountryCode = "TO"
	CountryTT CountryCode = "TT"
	CountryTN CountryCode = "TN"
	CountryTR CountryCode = "TR"
	CountryTM CountryCode = "TM"
	CountryTC CountryCode = "TC"
	CountryTV CountryCode = "TV"
	CountryUG CountryCode = "UG"
	CountryUA CountryCode = "UA"
	CountryAE CountryCode = "AE"
	CountryGB CountryCode = "GB"
	CountryUM CountryCode = "UM"
	CountryUS CountryCode = "US"
	CountryUY CountryCode = "UY"
	CountryUZ CountryCode = "UZ"
	CountryVU CountryCode = "VU"
	CountryVA CountryCode = "VA"
	CountryVE CountryCode = "VE"
	CountryVN CountryCode = "VN"
	CountryVI CountryCode = "VI"
	CountryWF CountryCode = "WF"
	CountryEH CountryCode = "EH"
	CountryYE CountryCode = "YE"
	CountryZM CountryCode = "ZM"
	CountryZW CountryCode = "ZW"
)

// Country represents a country with all its metadata.
type Country struct {
	ID           string
	Alpha2Code   string
	Alpha3Code   string
	NumericCode  int
	NativeName   string
	Capital      string
	MainLanguage string
	Languages    []string
	TLD          string
	CallingCode  int
	Continent    string
	Currency     string
}

// String returns the alpha2 code.
func (c CountryCode) String() string {
	return string(c)
}

// Country returns the country data for this code.
func (c CountryCode) Country() Country {
	return countries[c]
}

// EmojiFlag returns the emoji flag for this country.
func (c CountryCode) EmojiFlag() string {
	const base = 0x1F1E6 - 65

	code := string(c)
	if len(code) != 2 {
		return ""
	}

	first := rune(code[0]) + base
	second := rune(code[1]) + base

	return string([]rune{first, second})
}

var countries = map[CountryCode]Country{
	CountryAF: {
		ID:           "afghanistan",
		Alpha2Code:   "AF",
		Alpha3Code:   "AFG",
		NumericCode:  4,
		NativeName:   "افغانستان",
		Capital:      "کابل",
		MainLanguage: "pashto",
		Languages:    []string{"pashto", "persian"},
		TLD:          ".af",
		CallingCode:  93,
		Continent:    "asia",
		Currency:     "afn",
	},
	CountryAX: {
		ID:           "aalandIslands",
		Alpha2Code:   "AX",
		Alpha3Code:   "ALA",
		NumericCode:  248,
		NativeName:   "Åland",
		Capital:      "Mariehamn",
		MainLanguage: "swedish",
		Languages:    []string{"swedish"},
		TLD:          ".ax",
		CallingCode:  358,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryAL: {
		ID:           "albania",
		Alpha2Code:   "AL",
		Alpha3Code:   "ALB",
		NumericCode:  8,
		NativeName:   "Shqipëria",
		Capital:      "Tiranë",
		MainLanguage: "albanian",
		Languages:    []string{"albanian"},
		TLD:          ".al",
		CallingCode:  355,
		Continent:    "europe",
		Currency:     "all",
	},
	CountryDZ: {
		ID:           "algeria",
		Alpha2Code:   "DZ",
		Alpha3Code:   "DZA",
		NumericCode:  12,
		NativeName:   "الجزائر",
		Capital:      "الجزائر",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".dz",
		CallingCode:  213,
		Continent:    "africa",
		Currency:     "dzd",
	},
	CountryAS: {
		ID:           "americanSamoa",
		Alpha2Code:   "AS",
		Alpha3Code:   "ASM",
		NumericCode:  16,
		NativeName:   "American Samoa",
		Capital:      "Pago",
		MainLanguage: "english",
		Languages:    []string{"english", "samoan"},
		TLD:          ".as",
		CallingCode:  1,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryAD: {
		ID:           "andorra",
		Alpha2Code:   "AD",
		Alpha3Code:   "AND",
		NumericCode:  20,
		NativeName:   "Andorra",
		Capital:      "Andorra la Vella",
		MainLanguage: "catalan",
		Languages:    []string{"catalan"},
		TLD:          ".ad",
		CallingCode:  376,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryAO: {
		ID:           "angola",
		Alpha2Code:   "AO",
		Alpha3Code:   "AGO",
		NumericCode:  24,
		NativeName:   "Angola",
		Capital:      "Luanda",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".ao",
		CallingCode:  244,
		Continent:    "africa",
		Currency:     "aoa",
	},
	CountryAI: {
		ID:           "anguilla",
		Alpha2Code:   "AI",
		Alpha3Code:   "AIA",
		NumericCode:  660,
		NativeName:   "Anguilla",
		Capital:      "The Valley",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ai",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryAQ: {
		ID:           "antarctica",
		Alpha2Code:   "AQ",
		Alpha3Code:   "ATA",
		NumericCode:  10,
		NativeName:   "Antarctica",
		Capital:      "",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".aq",
		CallingCode:  672,
		Continent:    "antarctica",
		Currency:     "all",
	},
	CountryAG: {
		ID:           "antiguaAndBarbuda",
		Alpha2Code:   "AG",
		Alpha3Code:   "ATG",
		NumericCode:  28,
		NativeName:   "Antigua and Barbuda",
		Capital:      "Saint John's",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ag",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryAR: {
		ID:           "argentina",
		Alpha2Code:   "AR",
		Alpha3Code:   "ARG",
		NumericCode:  32,
		NativeName:   "Argentina",
		Capital:      "Buenos Aires",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".ar",
		CallingCode:  54,
		Continent:    "southAmerica",
		Currency:     "ars",
	},
	CountryAM: {
		ID:           "armenia",
		Alpha2Code:   "AM",
		Alpha3Code:   "ARM",
		NumericCode:  51,
		NativeName:   "Հայաստան",
		Capital:      "Երևան",
		MainLanguage: "armenian",
		Languages:    []string{"armenian"},
		TLD:          ".am",
		CallingCode:  374,
		Continent:    "asia",
		Currency:     "amd",
	},
	CountryAW: {
		ID:           "aruba",
		Alpha2Code:   "AW",
		Alpha3Code:   "ABW",
		NumericCode:  533,
		NativeName:   "Aruba",
		Capital:      "Oranjestad",
		MainLanguage: "dutch",
		Languages:    []string{"dutch"},
		TLD:          ".aw",
		CallingCode:  297,
		Continent:    "northAmerica",
		Currency:     "awg",
	},
	CountryAU: {
		ID:           "australia",
		Alpha2Code:   "AU",
		Alpha3Code:   "AUS",
		NumericCode:  36,
		NativeName:   "Australia",
		Capital:      "Canberra",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".au",
		CallingCode:  61,
		Continent:    "oceania",
		Currency:     "aud",
	},
	CountryAT: {
		ID:           "austria",
		Alpha2Code:   "AT",
		Alpha3Code:   "AUT",
		NumericCode:  40,
		NativeName:   "Österreich",
		Capital:      "Wien",
		MainLanguage: "german",
		Languages:    []string{"german"},
		TLD:          ".at",
		CallingCode:  43,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryAZ: {
		ID:           "azerbaijan",
		Alpha2Code:   "AZ",
		Alpha3Code:   "AZE",
		NumericCode:  31,
		NativeName:   "Azərbaycan",
		Capital:      "Bakı",
		MainLanguage: "azerbaijani",
		Languages:    []string{"azerbaijani"},
		TLD:          ".az",
		CallingCode:  994,
		Continent:    "asia",
		Currency:     "azn",
	},
	CountryBS: {
		ID:           "bahamas",
		Alpha2Code:   "BS",
		Alpha3Code:   "BHS",
		NumericCode:  44,
		NativeName:   "Bahamas",
		Capital:      "Nassau",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".bs",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "bsd",
	},
	CountryBH: {
		ID:           "bahrain",
		Alpha2Code:   "BH",
		Alpha3Code:   "BHR",
		NumericCode:  48,
		NativeName:   "البحرين",
		Capital:      "المنامة",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".bh",
		CallingCode:  973,
		Continent:    "asia",
		Currency:     "bhd",
	},
	CountryBD: {
		ID:           "bangladesh",
		Alpha2Code:   "BD",
		Alpha3Code:   "BGD",
		NumericCode:  50,
		NativeName:   "বাংলাদেশ",
		Capital:      "ঢাকা",
		MainLanguage: "bengali",
		Languages:    []string{"bengali"},
		TLD:          ".bd",
		CallingCode:  880,
		Continent:    "asia",
		Currency:     "bdt",
	},
	CountryBB: {
		ID:           "barbados",
		Alpha2Code:   "BB",
		Alpha3Code:   "BRB",
		NumericCode:  52,
		NativeName:   "Barbados",
		Capital:      "Bridgetown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".bb",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "bbd",
	},
	CountryBY: {
		ID:           "belarus",
		Alpha2Code:   "BY",
		Alpha3Code:   "BLR",
		NumericCode:  112,
		NativeName:   "Беларусь",
		Capital:      "Мінск",
		MainLanguage: "belarusian",
		Languages:    []string{"belarusian", "russian"},
		TLD:          ".by",
		CallingCode:  375,
		Continent:    "europe",
		Currency:     "byn",
	},
	CountryBE: {
		ID:           "belgium",
		Alpha2Code:   "BE",
		Alpha3Code:   "BEL",
		NumericCode:  56,
		NativeName:   "België",
		Capital:      "Brussel",
		MainLanguage: "dutch",
		Languages:    []string{"dutch", "french", "german"},
		TLD:          ".be",
		CallingCode:  32,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryBZ: {
		ID:           "belize",
		Alpha2Code:   "BZ",
		Alpha3Code:   "BLZ",
		NumericCode:  84,
		NativeName:   "Belize",
		Capital:      "Belmopan",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".bz",
		CallingCode:  501,
		Continent:    "northAmerica",
		Currency:     "bzd",
	},
	CountryBJ: {
		ID:           "benin",
		Alpha2Code:   "BJ",
		Alpha3Code:   "BEN",
		NumericCode:  204,
		NativeName:   "Bénin",
		Capital:      "Porto-Novo",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".bj",
		CallingCode:  229,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryBM: {
		ID:           "bermuda",
		Alpha2Code:   "BM",
		Alpha3Code:   "BMU",
		NumericCode:  60,
		NativeName:   "Bermuda",
		Capital:      "Hamilton",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".bm",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "bmd",
	},
	CountryBT: {
		ID:           "bhutan",
		Alpha2Code:   "BT",
		Alpha3Code:   "BTN",
		NumericCode:  64,
		NativeName:   "འབྲུག",
		Capital:      "ཐིམ་ཕུ",
		MainLanguage: "dzongkha",
		Languages:    []string{"dzongkha"},
		TLD:          ".bt",
		CallingCode:  975,
		Continent:    "asia",
		Currency:     "inr",
	},
	CountryBO: {
		ID:           "bolivia",
		Alpha2Code:   "BO",
		Alpha3Code:   "BOL",
		NumericCode:  68,
		NativeName:   "Bolivia",
		Capital:      "Sucre",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".bo",
		CallingCode:  591,
		Continent:    "southAmerica",
		Currency:     "bob",
	},
	CountryBQ: {
		ID:           "bonaireSintEustatiusAndSaba",
		Alpha2Code:   "BQ",
		Alpha3Code:   "BES",
		NumericCode:  535,
		NativeName:   "Bonaire, Sint Eustatius and Saba",
		Capital:      "Kralendijk",
		MainLanguage: "dutch",
		Languages:    []string{"dutch"},
		TLD:          ".bq",
		CallingCode:  599,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryBA: {
		ID:           "bosniaAndHerzegovina",
		Alpha2Code:   "BA",
		Alpha3Code:   "BIH",
		NumericCode:  70,
		NativeName:   "Bosna i Hercegovina",
		Capital:      "Sarajevo",
		MainLanguage: "bosnian",
		Languages:    []string{"bosnian", "croatian", "serbian"},
		TLD:          ".ba",
		CallingCode:  387,
		Continent:    "europe",
		Currency:     "bam",
	},
	CountryBW: {
		ID:           "botswana",
		Alpha2Code:   "BW",
		Alpha3Code:   "BWA",
		NumericCode:  72,
		NativeName:   "Botswana",
		Capital:      "Gaborone",
		MainLanguage: "english",
		Languages:    []string{"english", "tswana"},
		TLD:          ".bw",
		CallingCode:  267,
		Continent:    "africa",
		Currency:     "bwp",
	},
	CountryBV: {
		ID:           "bouvetIsland",
		Alpha2Code:   "BV",
		Alpha3Code:   "BVT",
		NumericCode:  74,
		NativeName:   "Bouvet Island",
		Capital:      "",
		MainLanguage: "norwegian",
		Languages:    []string{"norwegian"},
		TLD:          ".bv",
		CallingCode:  47,
		Continent:    "antarctica",
		Currency:     "nok",
	},
	CountryBR: {
		ID:           "brazil",
		Alpha2Code:   "BR",
		Alpha3Code:   "BRA",
		NumericCode:  76,
		NativeName:   "Brasil",
		Capital:      "Brasília",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".br",
		CallingCode:  55,
		Continent:    "southAmerica",
		Currency:     "brl",
	},
	CountryIO: {
		ID:           "britishIndianOceanTerritory",
		Alpha2Code:   "IO",
		Alpha3Code:   "IOT",
		NumericCode:  86,
		NativeName:   "British Indian Ocean Territory",
		Capital:      "Diego Garcia",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".io",
		CallingCode:  246,
		Continent:    "asia",
		Currency:     "usd",
	},
	CountryVG: {
		ID:           "britishVirginIslands",
		Alpha2Code:   "VG",
		Alpha3Code:   "VGB",
		NumericCode:  92,
		NativeName:   "British Virgin Islands",
		Capital:      "Road Town",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".vg",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryBN: {
		ID:           "brunei",
		Alpha2Code:   "BN",
		Alpha3Code:   "BRN",
		NumericCode:  96,
		NativeName:   "Brunei",
		Capital:      "Bandar Seri Begawan",
		MainLanguage: "malay",
		Languages:    []string{"malay"},
		TLD:          ".bn",
		CallingCode:  673,
		Continent:    "asia",
		Currency:     "bnd",
	},
	CountryBG: {
		ID:           "bulgaria",
		Alpha2Code:   "BG",
		Alpha3Code:   "BGR",
		NumericCode:  100,
		NativeName:   "България",
		Capital:      "София",
		MainLanguage: "bulgarian",
		Languages:    []string{"bulgarian"},
		TLD:          ".bg",
		CallingCode:  359,
		Continent:    "europe",
		Currency:     "bgn",
	},
	CountryBF: {
		ID:           "burkinaFaso",
		Alpha2Code:   "BF",
		Alpha3Code:   "BFA",
		NumericCode:  854,
		NativeName:   "Burkina Faso",
		Capital:      "Ouagadougou",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".bf",
		CallingCode:  226,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryBI: {
		ID:           "burundi",
		Alpha2Code:   "BI",
		Alpha3Code:   "BDI",
		NumericCode:  108,
		NativeName:   "Burundi",
		Capital:      "Gitega",
		MainLanguage: "rundi",
		Languages:    []string{"rundi", "french"},
		TLD:          ".bi",
		CallingCode:  257,
		Continent:    "africa",
		Currency:     "bif",
	},
	CountryCV: {
		ID:           "caboVerde",
		Alpha2Code:   "CV",
		Alpha3Code:   "CPV",
		NumericCode:  132,
		NativeName:   "Cabo Verde",
		Capital:      "Praia",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".cv",
		CallingCode:  238,
		Continent:    "africa",
		Currency:     "cve",
	},
	CountryKH: {
		ID:           "cambodia",
		Alpha2Code:   "KH",
		Alpha3Code:   "KHM",
		NumericCode:  116,
		NativeName:   "កម្ពុជា",
		Capital:      "ភ្នំពេញ",
		MainLanguage: "khmer",
		Languages:    []string{"khmer"},
		TLD:          ".kh",
		CallingCode:  855,
		Continent:    "asia",
		Currency:     "khr",
	},
	CountryCM: {
		ID:           "cameroon",
		Alpha2Code:   "CM",
		Alpha3Code:   "CMR",
		NumericCode:  120,
		NativeName:   "Cameroun",
		Capital:      "Yaoundé",
		MainLanguage: "french",
		Languages:    []string{"french", "english"},
		TLD:          ".cm",
		CallingCode:  237,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryCA: {
		ID:           "canada",
		Alpha2Code:   "CA",
		Alpha3Code:   "CAN",
		NumericCode:  124,
		NativeName:   "Canada",
		Capital:      "Ottawa",
		MainLanguage: "english",
		Languages:    []string{"english", "french"},
		TLD:          ".ca",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "cad",
	},
	CountryKY: {
		ID:           "caymanIslands",
		Alpha2Code:   "KY",
		Alpha3Code:   "CYM",
		NumericCode:  136,
		NativeName:   "Cayman Islands",
		Capital:      "George Town",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ky",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "kyd",
	},
	CountryCF: {
		ID:           "centralAfricanRepublic",
		Alpha2Code:   "CF",
		Alpha3Code:   "CAF",
		NumericCode:  140,
		NativeName:   "République centrafricaine",
		Capital:      "Bangui",
		MainLanguage: "french",
		Languages:    []string{"french", "sango"},
		TLD:          ".cf",
		CallingCode:  236,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryTD: {
		ID:           "chad",
		Alpha2Code:   "TD",
		Alpha3Code:   "TCD",
		NumericCode:  148,
		NativeName:   "Tchad",
		Capital:      "N'Djamena",
		MainLanguage: "french",
		Languages:    []string{"french", "arabic"},
		TLD:          ".td",
		CallingCode:  235,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryCL: {
		ID:           "chile",
		Alpha2Code:   "CL",
		Alpha3Code:   "CHL",
		NumericCode:  152,
		NativeName:   "Chile",
		Capital:      "Santiago",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".cl",
		CallingCode:  56,
		Continent:    "southAmerica",
		Currency:     "clp",
	},
	CountryCN: {
		ID:           "china",
		Alpha2Code:   "CN",
		Alpha3Code:   "CHN",
		NumericCode:  156,
		NativeName:   "中国",
		Capital:      "北京",
		MainLanguage: "chinese",
		Languages:    []string{"chinese"},
		TLD:          ".cn",
		CallingCode:  86,
		Continent:    "asia",
		Currency:     "cny",
	},
	CountryCX: {
		ID:           "christmasIsland",
		Alpha2Code:   "CX",
		Alpha3Code:   "CXR",
		NumericCode:  162,
		NativeName:   "Christmas Island",
		Capital:      "Flying Fish Cove",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".cx",
		CallingCode:  61,
		Continent:    "asia",
		Currency:     "aud",
	},
	CountryCC: {
		ID:           "cocosKeelingIslands",
		Alpha2Code:   "CC",
		Alpha3Code:   "CCK",
		NumericCode:  166,
		NativeName:   "Cocos (Keeling) Islands",
		Capital:      "West Island",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".cc",
		CallingCode:  61,
		Continent:    "asia",
		Currency:     "aud",
	},
	CountryCO: {
		ID:           "colombia",
		Alpha2Code:   "CO",
		Alpha3Code:   "COL",
		NumericCode:  170,
		NativeName:   "Colombia",
		Capital:      "Bogotá",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".co",
		CallingCode:  57,
		Continent:    "southAmerica",
		Currency:     "cop",
	},
	CountryKM: {
		ID:           "comoros",
		Alpha2Code:   "KM",
		Alpha3Code:   "COM",
		NumericCode:  174,
		NativeName:   "Comores",
		Capital:      "Moroni",
		MainLanguage: "french",
		Languages:    []string{"french", "arabic"},
		TLD:          ".km",
		CallingCode:  269,
		Continent:    "africa",
		Currency:     "kmf",
	},
	CountryCG: {
		ID:           "congo",
		Alpha2Code:   "CG",
		Alpha3Code:   "COG",
		NumericCode:  178,
		NativeName:   "Congo",
		Capital:      "Brazzaville",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".cg",
		CallingCode:  242,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryCD: {
		ID:           "congoDemocraticRepublic",
		Alpha2Code:   "CD",
		Alpha3Code:   "COD",
		NumericCode:  180,
		NativeName:   "Congo, Democratic Republic",
		Capital:      "Kinshasa",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".cd",
		CallingCode:  243,
		Continent:    "africa",
		Currency:     "cdf",
	},
	CountryCK: {
		ID:           "cookIslands",
		Alpha2Code:   "CK",
		Alpha3Code:   "COK",
		NumericCode:  184,
		NativeName:   "Cook Islands",
		Capital:      "Avarua",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ck",
		CallingCode:  682,
		Continent:    "oceania",
		Currency:     "nzd",
	},
	CountryCR: {
		ID:           "costaRica",
		Alpha2Code:   "CR",
		Alpha3Code:   "CRI",
		NumericCode:  188,
		NativeName:   "Costa Rica",
		Capital:      "San José",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".cr",
		CallingCode:  506,
		Continent:    "northAmerica",
		Currency:     "crc",
	},
	CountryCI: {
		ID:           "coteDIvoire",
		Alpha2Code:   "CI",
		Alpha3Code:   "CIV",
		NumericCode:  384,
		NativeName:   "Côte d'Ivoire",
		Capital:      "Yamoussoukro",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".ci",
		CallingCode:  225,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryHR: {
		ID:           "croatia",
		Alpha2Code:   "HR",
		Alpha3Code:   "HRV",
		NumericCode:  191,
		NativeName:   "Hrvatska",
		Capital:      "Zagreb",
		MainLanguage: "croatian",
		Languages:    []string{"croatian"},
		TLD:          ".hr",
		CallingCode:  385,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryCU: {
		ID:           "cuba",
		Alpha2Code:   "CU",
		Alpha3Code:   "CUB",
		NumericCode:  192,
		NativeName:   "Cuba",
		Capital:      "La Habana",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".cu",
		CallingCode:  53,
		Continent:    "northAmerica",
		Currency:     "cup",
	},
	CountryCW: {
		ID:           "curacao",
		Alpha2Code:   "CW",
		Alpha3Code:   "CUW",
		NumericCode:  531,
		NativeName:   "Curaçao",
		Capital:      "Willemstad",
		MainLanguage: "dutch",
		Languages:    []string{"dutch"},
		TLD:          ".cw",
		CallingCode:  599,
		Continent:    "northAmerica",
		Currency:     "ang",
	},
	CountryCY: {
		ID:           "cyprus",
		Alpha2Code:   "CY",
		Alpha3Code:   "CYP",
		NumericCode:  196,
		NativeName:   "Κύπρος",
		Capital:      "Λευκωσία",
		MainLanguage: "greek",
		Languages:    []string{"greek", "turkish"},
		TLD:          ".cy",
		CallingCode:  357,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryCZ: {
		ID:           "czechia",
		Alpha2Code:   "CZ",
		Alpha3Code:   "CZE",
		NumericCode:  203,
		NativeName:   "Česko",
		Capital:      "Praha",
		MainLanguage: "czech",
		Languages:    []string{"czech"},
		TLD:          ".cz",
		CallingCode:  420,
		Continent:    "europe",
		Currency:     "czk",
	},
	CountryDK: {
		ID:           "denmark",
		Alpha2Code:   "DK",
		Alpha3Code:   "DNK",
		NumericCode:  208,
		NativeName:   "Danmark",
		Capital:      "København",
		MainLanguage: "danish",
		Languages:    []string{"danish"},
		TLD:          ".dk",
		CallingCode:  45,
		Continent:    "europe",
		Currency:     "dkk",
	},
	CountryDJ: {
		ID:           "djibouti",
		Alpha2Code:   "DJ",
		Alpha3Code:   "DJI",
		NumericCode:  262,
		NativeName:   "Djibouti",
		Capital:      "Djibouti",
		MainLanguage: "french",
		Languages:    []string{"french", "arabic"},
		TLD:          ".dj",
		CallingCode:  253,
		Continent:    "africa",
		Currency:     "djf",
	},
	CountryDM: {
		ID:           "dominica",
		Alpha2Code:   "DM",
		Alpha3Code:   "DMA",
		NumericCode:  212,
		NativeName:   "Dominica",
		Capital:      "Roseau",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".dm",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryDO: {
		ID:           "dominicanRepublic",
		Alpha2Code:   "DO",
		Alpha3Code:   "DOM",
		NumericCode:  214,
		NativeName:   "República Dominicana",
		Capital:      "Santo Domingo",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".do",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "dop",
	},
	CountryEC: {
		ID:           "ecuador",
		Alpha2Code:   "EC",
		Alpha3Code:   "ECU",
		NumericCode:  218,
		NativeName:   "Ecuador",
		Capital:      "Quito",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".ec",
		CallingCode:  593,
		Continent:    "southAmerica",
		Currency:     "usd",
	},
	CountryEG: {
		ID:           "egypt",
		Alpha2Code:   "EG",
		Alpha3Code:   "EGY",
		NumericCode:  818,
		NativeName:   "مصر",
		Capital:      "القاهرة",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".eg",
		CallingCode:  20,
		Continent:    "africa",
		Currency:     "egp",
	},
	CountrySV: {
		ID:           "elSalvador",
		Alpha2Code:   "SV",
		Alpha3Code:   "SLV",
		NumericCode:  222,
		NativeName:   "El Salvador",
		Capital:      "San Salvador",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".sv",
		CallingCode:  503,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryGQ: {
		ID:           "equatorialGuinea",
		Alpha2Code:   "GQ",
		Alpha3Code:   "GNQ",
		NumericCode:  226,
		NativeName:   "Guinea Ecuatorial",
		Capital:      "Malabo",
		MainLanguage: "spanish",
		Languages:    []string{"spanish", "french", "portuguese"},
		TLD:          ".gq",
		CallingCode:  240,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryER: {
		ID:           "eritrea",
		Alpha2Code:   "ER",
		Alpha3Code:   "ERI",
		NumericCode:  232,
		NativeName:   "ኤርትራ",
		Capital:      "ኣስመራ",
		MainLanguage: "tigrinya",
		Languages:    []string{"tigrinya", "arabic", "english"},
		TLD:          ".er",
		CallingCode:  291,
		Continent:    "africa",
		Currency:     "ern",
	},
	CountryEE: {
		ID:           "estonia",
		Alpha2Code:   "EE",
		Alpha3Code:   "EST",
		NumericCode:  233,
		NativeName:   "Eesti",
		Capital:      "Tallinn",
		MainLanguage: "estonian",
		Languages:    []string{"estonian"},
		TLD:          ".ee",
		CallingCode:  372,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountrySZ: {
		ID:           "eswatini",
		Alpha2Code:   "SZ",
		Alpha3Code:   "SWZ",
		NumericCode:  748,
		NativeName:   "Eswatini",
		Capital:      "Mbabane",
		MainLanguage: "swati",
		Languages:    []string{"swati", "english"},
		TLD:          ".sz",
		CallingCode:  268,
		Continent:    "africa",
		Currency:     "szl",
	},
	CountryET: {
		ID:           "ethiopia",
		Alpha2Code:   "ET",
		Alpha3Code:   "ETH",
		NumericCode:  231,
		NativeName:   "ኢትዮጵያ",
		Capital:      "አዲስ አበባ",
		MainLanguage: "amharic",
		Languages:    []string{"amharic"},
		TLD:          ".et",
		CallingCode:  251,
		Continent:    "africa",
		Currency:     "etb",
	},
	CountryFK: {
		ID:           "falklandIslands",
		Alpha2Code:   "FK",
		Alpha3Code:   "FLK",
		NumericCode:  238,
		NativeName:   "Falkland Islands",
		Capital:      "Stanley",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".fk",
		CallingCode:  500,
		Continent:    "southAmerica",
		Currency:     "fkp",
	},
	CountryFO: {
		ID:           "faroeIslands",
		Alpha2Code:   "FO",
		Alpha3Code:   "FRO",
		NumericCode:  234,
		NativeName:   "Føroyar",
		Capital:      "Tórshavn",
		MainLanguage: "faroese",
		Languages:    []string{"faroese", "danish"},
		TLD:          ".fo",
		CallingCode:  298,
		Continent:    "europe",
		Currency:     "dkk",
	},
	CountryFJ: {
		ID:           "fiji",
		Alpha2Code:   "FJ",
		Alpha3Code:   "FJI",
		NumericCode:  242,
		NativeName:   "Fiji",
		Capital:      "Suva",
		MainLanguage: "english",
		Languages:    []string{"english", "fijian", "hindi"},
		TLD:          ".fj",
		CallingCode:  679,
		Continent:    "oceania",
		Currency:     "fjd",
	},
	CountryFI: {
		ID:           "finland",
		Alpha2Code:   "FI",
		Alpha3Code:   "FIN",
		NumericCode:  246,
		NativeName:   "Suomi",
		Capital:      "Helsinki",
		MainLanguage: "finnish",
		Languages:    []string{"finnish", "swedish"},
		TLD:          ".fi",
		CallingCode:  358,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryFR: {
		ID:           "france",
		Alpha2Code:   "FR",
		Alpha3Code:   "FRA",
		NumericCode:  250,
		NativeName:   "France",
		Capital:      "Paris",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".fr",
		CallingCode:  33,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryGF: {
		ID:           "frenchGuiana",
		Alpha2Code:   "GF",
		Alpha3Code:   "GUF",
		NumericCode:  254,
		NativeName:   "Guyane française",
		Capital:      "Cayenne",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".gf",
		CallingCode:  594,
		Continent:    "southAmerica",
		Currency:     "eur",
	},
	CountryPF: {
		ID:           "frenchPolynesia",
		Alpha2Code:   "PF",
		Alpha3Code:   "PYF",
		NumericCode:  258,
		NativeName:   "Polynésie française",
		Capital:      "Papeete",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".pf",
		CallingCode:  689,
		Continent:    "oceania",
		Currency:     "xpf",
	},
	CountryTF: {
		ID:           "frenchSouthernTerritories",
		Alpha2Code:   "TF",
		Alpha3Code:   "ATF",
		NumericCode:  260,
		NativeName:   "French Southern Territories",
		Capital:      "Port-aux-Français",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".tf",
		CallingCode:  262,
		Continent:    "antarctica",
		Currency:     "eur",
	},
	CountryGA: {
		ID:           "gabon",
		Alpha2Code:   "GA",
		Alpha3Code:   "GAB",
		NumericCode:  266,
		NativeName:   "Gabon",
		Capital:      "Libreville",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".ga",
		CallingCode:  241,
		Continent:    "africa",
		Currency:     "xaf",
	},
	CountryGM: {
		ID:           "gambia",
		Alpha2Code:   "GM",
		Alpha3Code:   "GMB",
		NumericCode:  270,
		NativeName:   "Gambia",
		Capital:      "Banjul",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gm",
		CallingCode:  220,
		Continent:    "africa",
		Currency:     "gmd",
	},
	CountryGE: {
		ID:           "georgia",
		Alpha2Code:   "GE",
		Alpha3Code:   "GEO",
		NumericCode:  268,
		NativeName:   "საქართველო",
		Capital:      "თბილისი",
		MainLanguage: "georgian",
		Languages:    []string{"georgian"},
		TLD:          ".ge",
		CallingCode:  995,
		Continent:    "asia",
		Currency:     "gel",
	},
	CountryDE: {
		ID:           "germany",
		Alpha2Code:   "DE",
		Alpha3Code:   "DEU",
		NumericCode:  276,
		NativeName:   "Deutschland",
		Capital:      "Berlin",
		MainLanguage: "german",
		Languages:    []string{"german"},
		TLD:          ".de",
		CallingCode:  49,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryGH: {
		ID:           "ghana",
		Alpha2Code:   "GH",
		Alpha3Code:   "GHA",
		NumericCode:  288,
		NativeName:   "Ghana",
		Capital:      "Accra",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gh",
		CallingCode:  233,
		Continent:    "africa",
		Currency:     "ghs",
	},
	CountryGI: {
		ID:           "gibraltar",
		Alpha2Code:   "GI",
		Alpha3Code:   "GIB",
		NumericCode:  292,
		NativeName:   "Gibraltar",
		Capital:      "Gibraltar",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gi",
		CallingCode:  350,
		Continent:    "europe",
		Currency:     "gip",
	},
	CountryGR: {
		ID:           "greece",
		Alpha2Code:   "GR",
		Alpha3Code:   "GRC",
		NumericCode:  300,
		NativeName:   "Ελλάδα",
		Capital:      "Αθήνα",
		MainLanguage: "greek",
		Languages:    []string{"greek"},
		TLD:          ".gr",
		CallingCode:  30,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryGD: {
		ID:           "grenada",
		Alpha2Code:   "GD",
		Alpha3Code:   "GRD",
		NumericCode:  308,
		NativeName:   "Grenada",
		Capital:      "St. George's",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gd",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryGP: {
		ID:           "guadeloupe",
		Alpha2Code:   "GP",
		Alpha3Code:   "GLP",
		NumericCode:  312,
		NativeName:   "Guadeloupe",
		Capital:      "Basse-Terre",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".gp",
		CallingCode:  590,
		Continent:    "northAmerica",
		Currency:     "eur",
	},
	CountryGU: {
		ID:           "guam",
		Alpha2Code:   "GU",
		Alpha3Code:   "GUM",
		NumericCode:  316,
		NativeName:   "Guam",
		Capital:      "Hagåtña",
		MainLanguage: "english",
		Languages:    []string{"english", "chamorro"},
		TLD:          ".gu",
		CallingCode:  1,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryGT: {
		ID:           "guatemala",
		Alpha2Code:   "GT",
		Alpha3Code:   "GTM",
		NumericCode:  320,
		NativeName:   "Guatemala",
		Capital:      "Ciudad de Guatemala",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".gt",
		CallingCode:  502,
		Continent:    "northAmerica",
		Currency:     "gtq",
	},
	CountryGG: {
		ID:           "guernsey",
		Alpha2Code:   "GG",
		Alpha3Code:   "GGY",
		NumericCode:  831,
		NativeName:   "Guernsey",
		Capital:      "St Peter Port",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gg",
		CallingCode:  44,
		Continent:    "europe",
		Currency:     "gbp",
	},
	CountryGN: {
		ID:           "guinea",
		Alpha2Code:   "GN",
		Alpha3Code:   "GIN",
		NumericCode:  324,
		NativeName:   "Guinée",
		Capital:      "Conakry",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".gn",
		CallingCode:  224,
		Continent:    "africa",
		Currency:     "gnf",
	},
	CountryGW: {
		ID:           "guineaBissau",
		Alpha2Code:   "GW",
		Alpha3Code:   "GNB",
		NumericCode:  624,
		NativeName:   "Guiné-Bissau",
		Capital:      "Bissau",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".gw",
		CallingCode:  245,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryGY: {
		ID:           "guyana",
		Alpha2Code:   "GY",
		Alpha3Code:   "GUY",
		NumericCode:  328,
		NativeName:   "Guyana",
		Capital:      "Georgetown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gy",
		CallingCode:  592,
		Continent:    "southAmerica",
		Currency:     "gyd",
	},
	CountryHT: {
		ID:           "haiti",
		Alpha2Code:   "HT",
		Alpha3Code:   "HTI",
		NumericCode:  332,
		NativeName:   "Haïti",
		Capital:      "Port-au-Prince",
		MainLanguage: "french",
		Languages:    []string{"french", "haitian"},
		TLD:          ".ht",
		CallingCode:  509,
		Continent:    "northAmerica",
		Currency:     "htg",
	},
	CountryHM: {
		ID:           "heardIslandAndMcDonaldIslands",
		Alpha2Code:   "HM",
		Alpha3Code:   "HMD",
		NumericCode:  334,
		NativeName:   "Heard Island and McDonald Islands",
		Capital:      "",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".hm",
		CallingCode:  672,
		Continent:    "antarctica",
		Currency:     "usd",
	},
	CountryHN: {
		ID:           "honduras",
		Alpha2Code:   "HN",
		Alpha3Code:   "HND",
		NumericCode:  340,
		NativeName:   "Honduras",
		Capital:      "Tegucigalpa",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".hn",
		CallingCode:  504,
		Continent:    "northAmerica",
		Currency:     "hnl",
	},
	CountryHK: {
		ID:           "hongKong",
		Alpha2Code:   "HK",
		Alpha3Code:   "HKG",
		NumericCode:  344,
		NativeName:   "香港",
		Capital:      "香港",
		MainLanguage: "chinese",
		Languages:    []string{"chinese", "english"},
		TLD:          ".hk",
		CallingCode:  852,
		Continent:    "asia",
		Currency:     "hkd",
	},
	CountryHU: {
		ID:           "hungary",
		Alpha2Code:   "HU",
		Alpha3Code:   "HUN",
		NumericCode:  348,
		NativeName:   "Magyarország",
		Capital:      "Budapest",
		MainLanguage: "hungarian",
		Languages:    []string{"hungarian"},
		TLD:          ".hu",
		CallingCode:  36,
		Continent:    "europe",
		Currency:     "huf",
	},
	CountryIS: {
		ID:           "iceland",
		Alpha2Code:   "IS",
		Alpha3Code:   "ISL",
		NumericCode:  352,
		NativeName:   "Ísland",
		Capital:      "Reykjavík",
		MainLanguage: "icelandic",
		Languages:    []string{"icelandic"},
		TLD:          ".is",
		CallingCode:  354,
		Continent:    "europe",
		Currency:     "isk",
	},
	CountryIN: {
		ID:           "india",
		Alpha2Code:   "IN",
		Alpha3Code:   "IND",
		NumericCode:  356,
		NativeName:   "भारत",
		Capital:      "नई दिल्ली",
		MainLanguage: "hindi",
		Languages:    []string{"hindi", "english"},
		TLD:          ".in",
		CallingCode:  91,
		Continent:    "asia",
		Currency:     "inr",
	},
	CountryID: {
		ID:           "indonesia",
		Alpha2Code:   "ID",
		Alpha3Code:   "IDN",
		NumericCode:  360,
		NativeName:   "Indonesia",
		Capital:      "Jakarta",
		MainLanguage: "indonesian",
		Languages:    []string{"indonesian"},
		TLD:          ".id",
		CallingCode:  62,
		Continent:    "asia",
		Currency:     "idr",
	},
	CountryIR: {
		ID:           "iran",
		Alpha2Code:   "IR",
		Alpha3Code:   "IRN",
		NumericCode:  364,
		NativeName:   "ایران",
		Capital:      "تهران",
		MainLanguage: "persian",
		Languages:    []string{"persian"},
		TLD:          ".ir",
		CallingCode:  98,
		Continent:    "asia",
		Currency:     "irr",
	},
	CountryIQ: {
		ID:           "iraq",
		Alpha2Code:   "IQ",
		Alpha3Code:   "IRQ",
		NumericCode:  368,
		NativeName:   "العراق",
		Capital:      "بغداد",
		MainLanguage: "arabic",
		Languages:    []string{"arabic", "kurdish"},
		TLD:          ".iq",
		CallingCode:  964,
		Continent:    "asia",
		Currency:     "iqd",
	},
	CountryIE: {
		ID:           "ireland",
		Alpha2Code:   "IE",
		Alpha3Code:   "IRL",
		NumericCode:  372,
		NativeName:   "Éire",
		Capital:      "Baile Átha Cliath",
		MainLanguage: "english",
		Languages:    []string{"english", "irish"},
		TLD:          ".ie",
		CallingCode:  353,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryIM: {
		ID:           "isleOfMan",
		Alpha2Code:   "IM",
		Alpha3Code:   "IMN",
		NumericCode:  833,
		NativeName:   "Isle of Man",
		Capital:      "Douglas",
		MainLanguage: "english",
		Languages:    []string{"english", "manx"},
		TLD:          ".im",
		CallingCode:  44,
		Continent:    "europe",
		Currency:     "gbp",
	},
	CountryIL: {
		ID:           "israel",
		Alpha2Code:   "IL",
		Alpha3Code:   "ISR",
		NumericCode:  376,
		NativeName:   "ישראל",
		Capital:      "ירושלים",
		MainLanguage: "hebrew",
		Languages:    []string{"hebrew", "arabic"},
		TLD:          ".il",
		CallingCode:  972,
		Continent:    "asia",
		Currency:     "ils",
	},
	CountryIT: {
		ID:           "italy",
		Alpha2Code:   "IT",
		Alpha3Code:   "ITA",
		NumericCode:  380,
		NativeName:   "Italia",
		Capital:      "Roma",
		MainLanguage: "italian",
		Languages:    []string{"italian"},
		TLD:          ".it",
		CallingCode:  39,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryJM: {
		ID:           "jamaica",
		Alpha2Code:   "JM",
		Alpha3Code:   "JAM",
		NumericCode:  388,
		NativeName:   "Jamaica",
		Capital:      "Kingston",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".jm",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "jmd",
	},
	CountryJP: {
		ID:           "japan",
		Alpha2Code:   "JP",
		Alpha3Code:   "JPN",
		NumericCode:  392,
		NativeName:   "日本",
		Capital:      "東京",
		MainLanguage: "japanese",
		Languages:    []string{"japanese"},
		TLD:          ".jp",
		CallingCode:  81,
		Continent:    "asia",
		Currency:     "jpy",
	},
	CountryJE: {
		ID:           "jersey",
		Alpha2Code:   "JE",
		Alpha3Code:   "JEY",
		NumericCode:  832,
		NativeName:   "Jersey",
		Capital:      "Saint Helier",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".je",
		CallingCode:  44,
		Continent:    "europe",
		Currency:     "gbp",
	},
	CountryJO: {
		ID:           "jordan",
		Alpha2Code:   "JO",
		Alpha3Code:   "JOR",
		NumericCode:  400,
		NativeName:   "الأردن",
		Capital:      "عمّان",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".jo",
		CallingCode:  962,
		Continent:    "asia",
		Currency:     "jod",
	},
	CountryKZ: {
		ID:           "kazakhstan",
		Alpha2Code:   "KZ",
		Alpha3Code:   "KAZ",
		NumericCode:  398,
		NativeName:   "Қазақстан",
		Capital:      "Астана",
		MainLanguage: "kazakh",
		Languages:    []string{"kazakh", "russian"},
		TLD:          ".kz",
		CallingCode:  7,
		Continent:    "asia",
		Currency:     "kzt",
	},
	CountryKE: {
		ID:           "kenya",
		Alpha2Code:   "KE",
		Alpha3Code:   "KEN",
		NumericCode:  404,
		NativeName:   "Kenya",
		Capital:      "Nairobi",
		MainLanguage: "swahili",
		Languages:    []string{"swahili", "english"},
		TLD:          ".ke",
		CallingCode:  254,
		Continent:    "africa",
		Currency:     "kes",
	},
	CountryKI: {
		ID:           "kiribati",
		Alpha2Code:   "KI",
		Alpha3Code:   "KIR",
		NumericCode:  296,
		NativeName:   "Kiribati",
		Capital:      "Tarawa",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ki",
		CallingCode:  686,
		Continent:    "oceania",
		Currency:     "aud",
	},
	CountryKW: {
		ID:           "kuwait",
		Alpha2Code:   "KW",
		Alpha3Code:   "KWT",
		NumericCode:  414,
		NativeName:   "الكويت",
		Capital:      "مدينة الكويت",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".kw",
		CallingCode:  965,
		Continent:    "asia",
		Currency:     "kwd",
	},
	CountryKG: {
		ID:           "kyrgyzstan",
		Alpha2Code:   "KG",
		Alpha3Code:   "KGZ",
		NumericCode:  417,
		NativeName:   "Кыргызстан",
		Capital:      "Бишкек",
		MainLanguage: "kirghiz",
		Languages:    []string{"kirghiz", "russian"},
		TLD:          ".kg",
		CallingCode:  996,
		Continent:    "asia",
		Currency:     "kgs",
	},
	CountryLA: {
		ID:           "laos",
		Alpha2Code:   "LA",
		Alpha3Code:   "LAO",
		NumericCode:  418,
		NativeName:   "ສປປລາວ",
		Capital:      "ວຽງຈັນ",
		MainLanguage: "lao",
		Languages:    []string{"lao"},
		TLD:          ".la",
		CallingCode:  856,
		Continent:    "asia",
		Currency:     "lak",
	},
	CountryLV: {
		ID:           "latvia",
		Alpha2Code:   "LV",
		Alpha3Code:   "LVA",
		NumericCode:  428,
		NativeName:   "Latvija",
		Capital:      "Rīga",
		MainLanguage: "latvian",
		Languages:    []string{"latvian"},
		TLD:          ".lv",
		CallingCode:  371,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryLB: {
		ID:           "lebanon",
		Alpha2Code:   "LB",
		Alpha3Code:   "LBN",
		NumericCode:  422,
		NativeName:   "لبنان",
		Capital:      "بيروت",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".lb",
		CallingCode:  961,
		Continent:    "asia",
		Currency:     "lbp",
	},
	CountryLS: {
		ID:           "lesotho",
		Alpha2Code:   "LS",
		Alpha3Code:   "LSO",
		NumericCode:  426,
		NativeName:   "Lesotho",
		Capital:      "Maseru",
		MainLanguage: "english",
		Languages:    []string{"english", "southernSotho"},
		TLD:          ".ls",
		CallingCode:  266,
		Continent:    "africa",
		Currency:     "lsl",
	},
	CountryLR: {
		ID:           "liberia",
		Alpha2Code:   "LR",
		Alpha3Code:   "LBR",
		NumericCode:  430,
		NativeName:   "Liberia",
		Capital:      "Monrovia",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".lr",
		CallingCode:  231,
		Continent:    "africa",
		Currency:     "lrd",
	},
	CountryLY: {
		ID:           "libya",
		Alpha2Code:   "LY",
		Alpha3Code:   "LBY",
		NumericCode:  434,
		NativeName:   "ليبيا",
		Capital:      "طرابلس",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".ly",
		CallingCode:  218,
		Continent:    "africa",
		Currency:     "lyd",
	},
	CountryLI: {
		ID:           "liechtenstein",
		Alpha2Code:   "LI",
		Alpha3Code:   "LIE",
		NumericCode:  438,
		NativeName:   "Liechtenstein",
		Capital:      "Vaduz",
		MainLanguage: "german",
		Languages:    []string{"german"},
		TLD:          ".li",
		CallingCode:  423,
		Continent:    "europe",
		Currency:     "chf",
	},
	CountryLT: {
		ID:           "lithuania",
		Alpha2Code:   "LT",
		Alpha3Code:   "LTU",
		NumericCode:  440,
		NativeName:   "Lietuva",
		Capital:      "Vilnius",
		MainLanguage: "lithuanian",
		Languages:    []string{"lithuanian"},
		TLD:          ".lt",
		CallingCode:  370,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryLU: {
		ID:           "luxembourg",
		Alpha2Code:   "LU",
		Alpha3Code:   "LUX",
		NumericCode:  442,
		NativeName:   "Luxembourg",
		Capital:      "Luxembourg",
		MainLanguage: "luxembourgish",
		Languages:    []string{"luxembourgish", "french", "german"},
		TLD:          ".lu",
		CallingCode:  352,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryMO: {
		ID:           "macao",
		Alpha2Code:   "MO",
		Alpha3Code:   "MAC",
		NumericCode:  446,
		NativeName:   "澳門",
		Capital:      "澳門",
		MainLanguage: "chinese",
		Languages:    []string{"chinese", "portuguese"},
		TLD:          ".mo",
		CallingCode:  853,
		Continent:    "asia",
		Currency:     "mop",
	},
	CountryMG: {
		ID:           "madagascar",
		Alpha2Code:   "MG",
		Alpha3Code:   "MDG",
		NumericCode:  450,
		NativeName:   "Madagasikara",
		Capital:      "Antananarivo",
		MainLanguage: "malagasy",
		Languages:    []string{"malagasy", "french"},
		TLD:          ".mg",
		CallingCode:  261,
		Continent:    "africa",
		Currency:     "mga",
	},
	CountryMW: {
		ID:           "malawi",
		Alpha2Code:   "MW",
		Alpha3Code:   "MWI",
		NumericCode:  454,
		NativeName:   "Malawi",
		Capital:      "Lilongwe",
		MainLanguage: "english",
		Languages:    []string{"english", "chichewa"},
		TLD:          ".mw",
		CallingCode:  265,
		Continent:    "africa",
		Currency:     "mwk",
	},
	CountryMY: {
		ID:           "malaysia",
		Alpha2Code:   "MY",
		Alpha3Code:   "MYS",
		NumericCode:  458,
		NativeName:   "Malaysia",
		Capital:      "Kuala Lumpur",
		MainLanguage: "malay",
		Languages:    []string{"malay"},
		TLD:          ".my",
		CallingCode:  60,
		Continent:    "asia",
		Currency:     "myr",
	},
	CountryMV: {
		ID:           "maldives",
		Alpha2Code:   "MV",
		Alpha3Code:   "MDV",
		NumericCode:  462,
		NativeName:   "ދިވެހިރާއްޖެ",
		Capital:      "މާލެ",
		MainLanguage: "divehi",
		Languages:    []string{"divehi"},
		TLD:          ".mv",
		CallingCode:  960,
		Continent:    "asia",
		Currency:     "mvr",
	},
	CountryML: {
		ID:           "mali",
		Alpha2Code:   "ML",
		Alpha3Code:   "MLI",
		NumericCode:  466,
		NativeName:   "Mali",
		Capital:      "Bamako",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".ml",
		CallingCode:  223,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryMT: {
		ID:           "malta",
		Alpha2Code:   "MT",
		Alpha3Code:   "MLT",
		NumericCode:  470,
		NativeName:   "Malta",
		Capital:      "Il-Belt Valletta",
		MainLanguage: "maltese",
		Languages:    []string{"maltese", "english"},
		TLD:          ".mt",
		CallingCode:  356,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryMH: {
		ID:           "marshallIslands",
		Alpha2Code:   "MH",
		Alpha3Code:   "MHL",
		NumericCode:  584,
		NativeName:   "Marshall Islands",
		Capital:      "Majuro",
		MainLanguage: "english",
		Languages:    []string{"english", "marshallese"},
		TLD:          ".mh",
		CallingCode:  692,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryMQ: {
		ID:           "martinique",
		Alpha2Code:   "MQ",
		Alpha3Code:   "MTQ",
		NumericCode:  474,
		NativeName:   "Martinique",
		Capital:      "Fort-de-France",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".mq",
		CallingCode:  596,
		Continent:    "northAmerica",
		Currency:     "eur",
	},
	CountryMR: {
		ID:           "mauritania",
		Alpha2Code:   "MR",
		Alpha3Code:   "MRT",
		NumericCode:  478,
		NativeName:   "موريتانيا",
		Capital:      "نواكشوط",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".mr",
		CallingCode:  222,
		Continent:    "africa",
		Currency:     "mru",
	},
	CountryMU: {
		ID:           "mauritius",
		Alpha2Code:   "MU",
		Alpha3Code:   "MUS",
		NumericCode:  480,
		NativeName:   "Maurice",
		Capital:      "Port Louis",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".mu",
		CallingCode:  230,
		Continent:    "africa",
		Currency:     "mur",
	},
	CountryYT: {
		ID:           "mayotte",
		Alpha2Code:   "YT",
		Alpha3Code:   "MYT",
		NumericCode:  175,
		NativeName:   "Mayotte",
		Capital:      "Mamoudzou",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".yt",
		CallingCode:  262,
		Continent:    "africa",
		Currency:     "eur",
	},
	CountryMX: {
		ID:           "mexico",
		Alpha2Code:   "MX",
		Alpha3Code:   "MEX",
		NumericCode:  484,
		NativeName:   "México",
		Capital:      "Ciudad de México",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".mx",
		CallingCode:  52,
		Continent:    "northAmerica",
		Currency:     "mxn",
	},
	CountryFM: {
		ID:           "micronesia",
		Alpha2Code:   "FM",
		Alpha3Code:   "FSM",
		NumericCode:  583,
		NativeName:   "Micronesia",
		Capital:      "Palikir",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".fm",
		CallingCode:  691,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryMD: {
		ID:           "moldova",
		Alpha2Code:   "MD",
		Alpha3Code:   "MDA",
		NumericCode:  498,
		NativeName:   "Moldova",
		Capital:      "Chișinău",
		MainLanguage: "romanian",
		Languages:    []string{"romanian"},
		TLD:          ".md",
		CallingCode:  373,
		Continent:    "europe",
		Currency:     "mdl",
	},
	CountryMC: {
		ID:           "monaco",
		Alpha2Code:   "MC",
		Alpha3Code:   "MCO",
		NumericCode:  492,
		NativeName:   "Monaco",
		Capital:      "Monaco",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".mc",
		CallingCode:  377,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryMN: {
		ID:           "mongolia",
		Alpha2Code:   "MN",
		Alpha3Code:   "MNG",
		NumericCode:  496,
		NativeName:   "Монгол улс",
		Capital:      "Улаанбаатар",
		MainLanguage: "mongolian",
		Languages:    []string{"mongolian"},
		TLD:          ".mn",
		CallingCode:  976,
		Continent:    "asia",
		Currency:     "mnt",
	},
	CountryME: {
		ID:           "montenegro",
		Alpha2Code:   "ME",
		Alpha3Code:   "MNE",
		NumericCode:  499,
		NativeName:   "Црна Гора",
		Capital:      "Podgorica",
		MainLanguage: "serbian",
		Languages:    []string{"serbian"},
		TLD:          ".me",
		CallingCode:  382,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryMS: {
		ID:           "montserrat",
		Alpha2Code:   "MS",
		Alpha3Code:   "MSR",
		NumericCode:  500,
		NativeName:   "Montserrat",
		Capital:      "Plymouth",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ms",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryMA: {
		ID:           "morocco",
		Alpha2Code:   "MA",
		Alpha3Code:   "MAR",
		NumericCode:  504,
		NativeName:   "المغرب",
		Capital:      "الرباط",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".ma",
		CallingCode:  212,
		Continent:    "africa",
		Currency:     "mad",
	},
	CountryMZ: {
		ID:           "mozambique",
		Alpha2Code:   "MZ",
		Alpha3Code:   "MOZ",
		NumericCode:  508,
		NativeName:   "Moçambique",
		Capital:      "Maputo",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".mz",
		CallingCode:  258,
		Continent:    "africa",
		Currency:     "mzn",
	},
	CountryMM: {
		ID:           "myanmar",
		Alpha2Code:   "MM",
		Alpha3Code:   "MMR",
		NumericCode:  104,
		NativeName:   "မြန်မာ",
		Capital:      "နေပြည်တော်",
		MainLanguage: "burmese",
		Languages:    []string{"burmese"},
		TLD:          ".mm",
		CallingCode:  95,
		Continent:    "asia",
		Currency:     "mmk",
	},
	CountryNA: {
		ID:           "namibia",
		Alpha2Code:   "NA",
		Alpha3Code:   "NAM",
		NumericCode:  516,
		NativeName:   "Namibia",
		Capital:      "Windhoek",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".na",
		CallingCode:  264,
		Continent:    "africa",
		Currency:     "nad",
	},
	CountryNR: {
		ID:           "nauru",
		Alpha2Code:   "NR",
		Alpha3Code:   "NRU",
		NumericCode:  520,
		NativeName:   "Nauru",
		Capital:      "Yaren",
		MainLanguage: "nauru",
		Languages:    []string{"nauru", "english"},
		TLD:          ".nr",
		CallingCode:  674,
		Continent:    "oceania",
		Currency:     "aud",
	},
	CountryNP: {
		ID:           "nepal",
		Alpha2Code:   "NP",
		Alpha3Code:   "NPL",
		NumericCode:  524,
		NativeName:   "नेपाल",
		Capital:      "काठमाडौं",
		MainLanguage: "nepali",
		Languages:    []string{"nepali"},
		TLD:          ".np",
		CallingCode:  977,
		Continent:    "asia",
		Currency:     "npr",
	},
	CountryNL: {
		ID:           "netherlands",
		Alpha2Code:   "NL",
		Alpha3Code:   "NLD",
		NumericCode:  528,
		NativeName:   "Nederland",
		Capital:      "Amsterdam",
		MainLanguage: "dutch",
		Languages:    []string{"dutch"},
		TLD:          ".nl",
		CallingCode:  31,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryNC: {
		ID:           "newCaledonia",
		Alpha2Code:   "NC",
		Alpha3Code:   "NCL",
		NumericCode:  540,
		NativeName:   "Nouvelle-Calédonie",
		Capital:      "Nouméa",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".nc",
		CallingCode:  687,
		Continent:    "oceania",
		Currency:     "xpf",
	},
	CountryNZ: {
		ID:           "newZealand",
		Alpha2Code:   "NZ",
		Alpha3Code:   "NZL",
		NumericCode:  554,
		NativeName:   "New Zealand",
		Capital:      "Wellington",
		MainLanguage: "english",
		Languages:    []string{"english", "maori"},
		TLD:          ".nz",
		CallingCode:  64,
		Continent:    "oceania",
		Currency:     "nzd",
	},
	CountryNI: {
		ID:           "nicaragua",
		Alpha2Code:   "NI",
		Alpha3Code:   "NIC",
		NumericCode:  558,
		NativeName:   "Nicaragua",
		Capital:      "Managua",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".ni",
		CallingCode:  505,
		Continent:    "northAmerica",
		Currency:     "nio",
	},
	CountryNE: {
		ID:           "niger",
		Alpha2Code:   "NE",
		Alpha3Code:   "NER",
		NumericCode:  562,
		NativeName:   "Niger",
		Capital:      "Niamey",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".ne",
		CallingCode:  227,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryNG: {
		ID:           "nigeria",
		Alpha2Code:   "NG",
		Alpha3Code:   "NGA",
		NumericCode:  566,
		NativeName:   "Nigeria",
		Capital:      "Abuja",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ng",
		CallingCode:  234,
		Continent:    "africa",
		Currency:     "ngn",
	},
	CountryNU: {
		ID:           "niue",
		Alpha2Code:   "NU",
		Alpha3Code:   "NIU",
		NumericCode:  570,
		NativeName:   "Niue",
		Capital:      "Alofi",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".nu",
		CallingCode:  683,
		Continent:    "oceania",
		Currency:     "nzd",
	},
	CountryNF: {
		ID:           "norfolkIsland",
		Alpha2Code:   "NF",
		Alpha3Code:   "NFK",
		NumericCode:  574,
		NativeName:   "Norfolk Island",
		Capital:      "Kingston",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".nf",
		CallingCode:  672,
		Continent:    "oceania",
		Currency:     "aud",
	},
	CountryKP: {
		ID:           "northKorea",
		Alpha2Code:   "KP",
		Alpha3Code:   "PRK",
		NumericCode:  408,
		NativeName:   "조선민주주의인민공화국",
		Capital:      "평양",
		MainLanguage: "korean",
		Languages:    []string{"korean"},
		TLD:          ".kp",
		CallingCode:  850,
		Continent:    "asia",
		Currency:     "kpw",
	},
	CountryMK: {
		ID:           "northMacedonia",
		Alpha2Code:   "MK",
		Alpha3Code:   "MKD",
		NumericCode:  807,
		NativeName:   "Северна Македонија",
		Capital:      "Скопје",
		MainLanguage: "macedonian",
		Languages:    []string{"macedonian"},
		TLD:          ".mk",
		CallingCode:  389,
		Continent:    "europe",
		Currency:     "mkd",
	},
	CountryMP: {
		ID:           "northernMarianaIslands",
		Alpha2Code:   "MP",
		Alpha3Code:   "MNP",
		NumericCode:  580,
		NativeName:   "Northern Mariana Islands",
		Capital:      "Saipan",
		MainLanguage: "english",
		Languages:    []string{"english", "chamorro"},
		TLD:          ".mp",
		CallingCode:  1,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryNO: {
		ID:           "norway",
		Alpha2Code:   "NO",
		Alpha3Code:   "NOR",
		NumericCode:  578,
		NativeName:   "Norge",
		Capital:      "Oslo",
		MainLanguage: "norwegian",
		Languages:    []string{"norwegian"},
		TLD:          ".no",
		CallingCode:  47,
		Continent:    "europe",
		Currency:     "nok",
	},
	CountryOM: {
		ID:           "oman",
		Alpha2Code:   "OM",
		Alpha3Code:   "OMN",
		NumericCode:  512,
		NativeName:   "عمان",
		Capital:      "مسقط",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".om",
		CallingCode:  968,
		Continent:    "asia",
		Currency:     "omr",
	},
	CountryPK: {
		ID:           "pakistan",
		Alpha2Code:   "PK",
		Alpha3Code:   "PAK",
		NumericCode:  586,
		NativeName:   "پاکستان",
		Capital:      "اسلام آباد",
		MainLanguage: "urdu",
		Languages:    []string{"urdu", "english"},
		TLD:          ".pk",
		CallingCode:  92,
		Continent:    "asia",
		Currency:     "pkr",
	},
	CountryPW: {
		ID:           "palau",
		Alpha2Code:   "PW",
		Alpha3Code:   "PLW",
		NumericCode:  585,
		NativeName:   "Palau",
		Capital:      "Ngerulmud",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".pw",
		CallingCode:  680,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryPS: {
		ID:           "palestine",
		Alpha2Code:   "PS",
		Alpha3Code:   "PSE",
		NumericCode:  275,
		NativeName:   "فلسطين",
		Capital:      "رام الله",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".ps",
		CallingCode:  970,
		Continent:    "asia",
		Currency:     "ils",
	},
	CountryPA: {
		ID:           "panama",
		Alpha2Code:   "PA",
		Alpha3Code:   "PAN",
		NumericCode:  591,
		NativeName:   "Panamá",
		Capital:      "Ciudad de Panamá",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".pa",
		CallingCode:  507,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryPG: {
		ID:           "papuaNewGuinea",
		Alpha2Code:   "PG",
		Alpha3Code:   "PNG",
		NumericCode:  598,
		NativeName:   "Papua New Guinea",
		Capital:      "Port Moresby",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".pg",
		CallingCode:  675,
		Continent:    "oceania",
		Currency:     "pgk",
	},
	CountryPY: {
		ID:           "paraguay",
		Alpha2Code:   "PY",
		Alpha3Code:   "PRY",
		NumericCode:  600,
		NativeName:   "Paraguay",
		Capital:      "Asunción",
		MainLanguage: "spanish",
		Languages:    []string{"spanish", "guarani"},
		TLD:          ".py",
		CallingCode:  595,
		Continent:    "southAmerica",
		Currency:     "pyg",
	},
	CountryPE: {
		ID:           "peru",
		Alpha2Code:   "PE",
		Alpha3Code:   "PER",
		NumericCode:  604,
		NativeName:   "Perú",
		Capital:      "Lima",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".pe",
		CallingCode:  51,
		Continent:    "southAmerica",
		Currency:     "pen",
	},
	CountryPH: {
		ID:           "philippines",
		Alpha2Code:   "PH",
		Alpha3Code:   "PHL",
		NumericCode:  608,
		NativeName:   "Pilipinas",
		Capital:      "Manila",
		MainLanguage: "tagalog",
		Languages:    []string{"tagalog", "english"},
		TLD:          ".ph",
		CallingCode:  63,
		Continent:    "asia",
		Currency:     "php",
	},
	CountryPN: {
		ID:           "pitcairn",
		Alpha2Code:   "PN",
		Alpha3Code:   "PCN",
		NumericCode:  612,
		NativeName:   "Pitcairn Islands",
		Capital:      "Adamstown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".pn",
		CallingCode:  64,
		Continent:    "oceania",
		Currency:     "nzd",
	},
	CountryPL: {
		ID:           "poland",
		Alpha2Code:   "PL",
		Alpha3Code:   "POL",
		NumericCode:  616,
		NativeName:   "Polska",
		Capital:      "Warszawa",
		MainLanguage: "polish",
		Languages:    []string{"polish"},
		TLD:          ".pl",
		CallingCode:  48,
		Continent:    "europe",
		Currency:     "pln",
	},
	CountryPT: {
		ID:           "portugal",
		Alpha2Code:   "PT",
		Alpha3Code:   "PRT",
		NumericCode:  620,
		NativeName:   "Portugal",
		Capital:      "Lisboa",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".pt",
		CallingCode:  351,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryPR: {
		ID:           "puertoRico",
		Alpha2Code:   "PR",
		Alpha3Code:   "PRI",
		NumericCode:  630,
		NativeName:   "Puerto Rico",
		Capital:      "San Juan",
		MainLanguage: "spanish",
		Languages:    []string{"spanish", "english"},
		TLD:          ".pr",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryQA: {
		ID:           "qatar",
		Alpha2Code:   "QA",
		Alpha3Code:   "QAT",
		NumericCode:  634,
		NativeName:   "قطر",
		Capital:      "الدوحة",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".qa",
		CallingCode:  974,
		Continent:    "asia",
		Currency:     "qar",
	},
	CountryRE: {
		ID:           "reunion",
		Alpha2Code:   "RE",
		Alpha3Code:   "REU",
		NumericCode:  638,
		NativeName:   "Réunion",
		Capital:      "Saint-Denis",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".re",
		CallingCode:  262,
		Continent:    "africa",
		Currency:     "eur",
	},
	CountryRO: {
		ID:           "romania",
		Alpha2Code:   "RO",
		Alpha3Code:   "ROU",
		NumericCode:  642,
		NativeName:   "România",
		Capital:      "București",
		MainLanguage: "romanian",
		Languages:    []string{"romanian"},
		TLD:          ".ro",
		CallingCode:  40,
		Continent:    "europe",
		Currency:     "ron",
	},
	CountryRU: {
		ID:           "russia",
		Alpha2Code:   "RU",
		Alpha3Code:   "RUS",
		NumericCode:  643,
		NativeName:   "Россия",
		Capital:      "Москва",
		MainLanguage: "russian",
		Languages:    []string{"russian"},
		TLD:          ".ru",
		CallingCode:  7,
		Continent:    "europe",
		Currency:     "rub",
	},
	CountryRW: {
		ID:           "rwanda",
		Alpha2Code:   "RW",
		Alpha3Code:   "RWA",
		NumericCode:  646,
		NativeName:   "Rwanda",
		Capital:      "Kigali",
		MainLanguage: "kinyarwanda",
		Languages:    []string{"kinyarwanda", "french", "english"},
		TLD:          ".rw",
		CallingCode:  250,
		Continent:    "africa",
		Currency:     "rwf",
	},
	CountryBL: {
		ID:           "saintBarthelemy",
		Alpha2Code:   "BL",
		Alpha3Code:   "BLM",
		NumericCode:  652,
		NativeName:   "Saint-Barthélemy",
		Capital:      "Gustavia",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".bl",
		CallingCode:  590,
		Continent:    "northAmerica",
		Currency:     "eur",
	},
	CountrySH: {
		ID:           "saintHelena",
		Alpha2Code:   "SH",
		Alpha3Code:   "SHN",
		NumericCode:  654,
		NativeName:   "Saint Helena",
		Capital:      "Jamestown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".sh",
		CallingCode:  290,
		Continent:    "africa",
		Currency:     "svc",
	},
	CountryKN: {
		ID:           "saintKittsAndNevis",
		Alpha2Code:   "KN",
		Alpha3Code:   "KNA",
		NumericCode:  659,
		NativeName:   "Saint Kitts and Nevis",
		Capital:      "Basseterre",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".kn",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryLC: {
		ID:           "saintLucia",
		Alpha2Code:   "LC",
		Alpha3Code:   "LCA",
		NumericCode:  662,
		NativeName:   "Saint Lucia",
		Capital:      "Castries",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".lc",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryMF: {
		ID:           "saintMartin",
		Alpha2Code:   "MF",
		Alpha3Code:   "MAF",
		NumericCode:  663,
		NativeName:   "Saint-Martin",
		Capital:      "Marigot",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".mf",
		CallingCode:  590,
		Continent:    "northAmerica",
		Currency:     "eur",
	},
	CountryPM: {
		ID:           "saintPierreAndMiquelon",
		Alpha2Code:   "PM",
		Alpha3Code:   "SPM",
		NumericCode:  666,
		NativeName:   "Saint-Pierre-et-Miquelon",
		Capital:      "Saint-Pierre",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".pm",
		CallingCode:  508,
		Continent:    "northAmerica",
		Currency:     "eur",
	},
	CountryVC: {
		ID:           "saintVincentAndTheGrenadines",
		Alpha2Code:   "VC",
		Alpha3Code:   "VCT",
		NumericCode:  670,
		NativeName:   "Saint Vincent and the Grenadines",
		Capital:      "Kingstown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".vc",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "xcd",
	},
	CountryWS: {
		ID:           "samoa",
		Alpha2Code:   "WS",
		Alpha3Code:   "WSM",
		NumericCode:  882,
		NativeName:   "Samoa",
		Capital:      "Apia",
		MainLanguage: "samoan",
		Languages:    []string{"samoan", "english"},
		TLD:          ".ws",
		CallingCode:  685,
		Continent:    "oceania",
		Currency:     "wst",
	},
	CountrySM: {
		ID:           "sanMarino",
		Alpha2Code:   "SM",
		Alpha3Code:   "SMR",
		NumericCode:  674,
		NativeName:   "San Marino",
		Capital:      "San Marino",
		MainLanguage: "italian",
		Languages:    []string{"italian"},
		TLD:          ".sm",
		CallingCode:  378,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryST: {
		ID:           "saoTomeAndPrincipe",
		Alpha2Code:   "ST",
		Alpha3Code:   "STP",
		NumericCode:  678,
		NativeName:   "São Tomé e Príncipe",
		Capital:      "São Tomé",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".st",
		CallingCode:  239,
		Continent:    "africa",
		Currency:     "stn",
	},
	CountrySA: {
		ID:           "saudiArabia",
		Alpha2Code:   "SA",
		Alpha3Code:   "SAU",
		NumericCode:  682,
		NativeName:   "العربية السعودية",
		Capital:      "الرياض",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".sa",
		CallingCode:  966,
		Continent:    "asia",
		Currency:     "sar",
	},
	CountrySN: {
		ID:           "senegal",
		Alpha2Code:   "SN",
		Alpha3Code:   "SEN",
		NumericCode:  686,
		NativeName:   "Sénégal",
		Capital:      "Dakar",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".sn",
		CallingCode:  221,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryRS: {
		ID:           "serbia",
		Alpha2Code:   "RS",
		Alpha3Code:   "SRB",
		NumericCode:  688,
		NativeName:   "Србија",
		Capital:      "Београд",
		MainLanguage: "serbian",
		Languages:    []string{"serbian"},
		TLD:          ".rs",
		CallingCode:  381,
		Continent:    "europe",
		Currency:     "rsd",
	},
	CountrySC: {
		ID:           "seychelles",
		Alpha2Code:   "SC",
		Alpha3Code:   "SYC",
		NumericCode:  690,
		NativeName:   "Seychelles",
		Capital:      "Victoria",
		MainLanguage: "french",
		Languages:    []string{"french", "english"},
		TLD:          ".sc",
		CallingCode:  248,
		Continent:    "africa",
		Currency:     "scr",
	},
	CountrySL: {
		ID:           "sierraLeone",
		Alpha2Code:   "SL",
		Alpha3Code:   "SLE",
		NumericCode:  694,
		NativeName:   "Sierra Leone",
		Capital:      "Freetown",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".sl",
		CallingCode:  232,
		Continent:    "africa",
		Currency:     "sle",
	},
	CountrySG: {
		ID:           "singapore",
		Alpha2Code:   "SG",
		Alpha3Code:   "SGP",
		NumericCode:  702,
		NativeName:   "Singapore",
		Capital:      "Singapore",
		MainLanguage: "english",
		Languages:    []string{"english", "malay", "tamil", "chinese"},
		TLD:          ".sg",
		CallingCode:  65,
		Continent:    "asia",
		Currency:     "sgd",
	},
	CountrySX: {
		ID:           "sintMaarten",
		Alpha2Code:   "SX",
		Alpha3Code:   "SXM",
		NumericCode:  534,
		NativeName:   "Sint Maarten",
		Capital:      "Philipsburg",
		MainLanguage: "dutch",
		Languages:    []string{"dutch", "english"},
		TLD:          ".sx",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "ang",
	},
	CountrySK: {
		ID:           "slovakia",
		Alpha2Code:   "SK",
		Alpha3Code:   "SVK",
		NumericCode:  703,
		NativeName:   "Slovensko",
		Capital:      "Bratislava",
		MainLanguage: "slovak",
		Languages:    []string{"slovak"},
		TLD:          ".sk",
		CallingCode:  421,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountrySI: {
		ID:           "slovenia",
		Alpha2Code:   "SI",
		Alpha3Code:   "SVN",
		NumericCode:  705,
		NativeName:   "Slovenija",
		Capital:      "Ljubljana",
		MainLanguage: "slovenian",
		Languages:    []string{"slovenian"},
		TLD:          ".si",
		CallingCode:  386,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountrySB: {
		ID:           "solomonIslands",
		Alpha2Code:   "SB",
		Alpha3Code:   "SLB",
		NumericCode:  90,
		NativeName:   "Solomon Islands",
		Capital:      "Honiara",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".sb",
		CallingCode:  677,
		Continent:    "oceania",
		Currency:     "sbd",
	},
	CountrySO: {
		ID:           "somalia",
		Alpha2Code:   "SO",
		Alpha3Code:   "SOM",
		NumericCode:  706,
		NativeName:   "Soomaaliya",
		Capital:      "Muqdisho",
		MainLanguage: "somali",
		Languages:    []string{"somali", "arabic"},
		TLD:          ".so",
		CallingCode:  252,
		Continent:    "africa",
		Currency:     "sos",
	},
	CountryZA: {
		ID:           "southAfrica",
		Alpha2Code:   "ZA",
		Alpha3Code:   "ZAF",
		NumericCode:  710,
		NativeName:   "South Africa",
		Capital:      "Pretoria",
		MainLanguage: "english",
		Languages:    []string{"english", "afrikaans", "southNdebele", "southernSotho", "swati", "tsonga", "tswana", "venda", "xhosa", "zulu"},
		TLD:          ".za",
		CallingCode:  27,
		Continent:    "africa",
		Currency:     "zar",
	},
	CountryGS: {
		ID:           "southGeorgiaAndTheSouthSandwichIslands",
		Alpha2Code:   "GS",
		Alpha3Code:   "SGS",
		NumericCode:  239,
		NativeName:   "South Georgia and the South Sandwich Islands",
		Capital:      "King Edward Point",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".gs",
		CallingCode:  500,
		Continent:    "antarctica",
		Currency:     "gbp",
	},
	CountryKR: {
		ID:           "southKorea",
		Alpha2Code:   "KR",
		Alpha3Code:   "KOR",
		NumericCode:  410,
		NativeName:   "대한민국",
		Capital:      "서울",
		MainLanguage: "korean",
		Languages:    []string{"korean"},
		TLD:          ".kr",
		CallingCode:  82,
		Continent:    "asia",
		Currency:     "krw",
	},
	CountrySS: {
		ID:           "southSudan",
		Alpha2Code:   "SS",
		Alpha3Code:   "SSD",
		NumericCode:  728,
		NativeName:   "South Sudan",
		Capital:      "Juba",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ss",
		CallingCode:  211,
		Continent:    "africa",
		Currency:     "ssp",
	},
	CountryES: {
		ID:           "spain",
		Alpha2Code:   "ES",
		Alpha3Code:   "ESP",
		NumericCode:  724,
		NativeName:   "España",
		Capital:      "Madrid",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".es",
		CallingCode:  34,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryLK: {
		ID:           "sriLanka",
		Alpha2Code:   "LK",
		Alpha3Code:   "LKA",
		NumericCode:  144,
		NativeName:   "ශ්‍රී ලංකාව",
		Capital:      "ශ්‍රී ජයවර්ධනපුර කෝට්ටේ",
		MainLanguage: "sinhala",
		Languages:    []string{"sinhala", "tamil"},
		TLD:          ".lk",
		CallingCode:  94,
		Continent:    "asia",
		Currency:     "lkr",
	},
	CountrySD: {
		ID:           "sudan",
		Alpha2Code:   "SD",
		Alpha3Code:   "SDN",
		NumericCode:  729,
		NativeName:   "السودان",
		Capital:      "الخرطوم",
		MainLanguage: "arabic",
		Languages:    []string{"arabic", "english"},
		TLD:          ".sd",
		CallingCode:  249,
		Continent:    "africa",
		Currency:     "sdg",
	},
	CountrySR: {
		ID:           "suriname",
		Alpha2Code:   "SR",
		Alpha3Code:   "SUR",
		NumericCode:  740,
		NativeName:   "Suriname",
		Capital:      "Paramaribo",
		MainLanguage: "dutch",
		Languages:    []string{"dutch"},
		TLD:          ".sr",
		CallingCode:  597,
		Continent:    "southAmerica",
		Currency:     "srd",
	},
	CountrySJ: {
		ID:           "svalbardAndJanMayen",
		Alpha2Code:   "SJ",
		Alpha3Code:   "SJM",
		NumericCode:  744,
		NativeName:   "Svalbard og Jan Mayen",
		Capital:      "Longyearbyen",
		MainLanguage: "norwegian",
		Languages:    []string{"norwegian"},
		TLD:          ".sj",
		CallingCode:  47,
		Continent:    "europe",
		Currency:     "nok",
	},
	CountrySE: {
		ID:           "sweden",
		Alpha2Code:   "SE",
		Alpha3Code:   "SWE",
		NumericCode:  752,
		NativeName:   "Sverige",
		Capital:      "Stockholm",
		MainLanguage: "swedish",
		Languages:    []string{"swedish"},
		TLD:          ".se",
		CallingCode:  46,
		Continent:    "europe",
		Currency:     "sek",
	},
	CountryCH: {
		ID:           "switzerland",
		Alpha2Code:   "CH",
		Alpha3Code:   "CHE",
		NumericCode:  756,
		NativeName:   "Schweiz",
		Capital:      "Bern",
		MainLanguage: "german",
		Languages:    []string{"german", "french", "italian"},
		TLD:          ".ch",
		CallingCode:  41,
		Continent:    "europe",
		Currency:     "chf",
	},
	CountrySY: {
		ID:           "syria",
		Alpha2Code:   "SY",
		Alpha3Code:   "SYR",
		NumericCode:  760,
		NativeName:   "سوريا",
		Capital:      "دمشق",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".sy",
		CallingCode:  963,
		Continent:    "asia",
		Currency:     "syp",
	},
	CountryTW: {
		ID:           "taiwan",
		Alpha2Code:   "TW",
		Alpha3Code:   "TWN",
		NumericCode:  158,
		NativeName:   "臺灣",
		Capital:      "臺北",
		MainLanguage: "chinese",
		Languages:    []string{"chinese"},
		TLD:          ".tw",
		CallingCode:  886,
		Continent:    "asia",
		Currency:     "twd",
	},
	CountryTJ: {
		ID:           "tajikistan",
		Alpha2Code:   "TJ",
		Alpha3Code:   "TJK",
		NumericCode:  762,
		NativeName:   "Тоҷикистон",
		Capital:      "Душанбе",
		MainLanguage: "tajik",
		Languages:    []string{"tajik", "russian"},
		TLD:          ".tj",
		CallingCode:  992,
		Continent:    "asia",
		Currency:     "tjs",
	},
	CountryTZ: {
		ID:           "tanzania",
		Alpha2Code:   "TZ",
		Alpha3Code:   "TZA",
		NumericCode:  834,
		NativeName:   "Tanzania",
		Capital:      "Dodoma",
		MainLanguage: "swahili",
		Languages:    []string{"swahili", "english"},
		TLD:          ".tz",
		CallingCode:  255,
		Continent:    "africa",
		Currency:     "tzs",
	},
	CountryTH: {
		ID:           "thailand",
		Alpha2Code:   "TH",
		Alpha3Code:   "THA",
		NumericCode:  764,
		NativeName:   "ประเทศไทย",
		Capital:      "กรุงเทพมหานคร",
		MainLanguage: "thai",
		Languages:    []string{"thai"},
		TLD:          ".th",
		CallingCode:  66,
		Continent:    "asia",
		Currency:     "thb",
	},
	CountryTL: {
		ID:           "timorLeste",
		Alpha2Code:   "TL",
		Alpha3Code:   "TLS",
		NumericCode:  626,
		NativeName:   "Timor-Leste",
		Capital:      "Dili",
		MainLanguage: "portuguese",
		Languages:    []string{"portuguese"},
		TLD:          ".tl",
		CallingCode:  670,
		Continent:    "asia",
		Currency:     "usd",
	},
	CountryTG: {
		ID:           "togo",
		Alpha2Code:   "TG",
		Alpha3Code:   "TGO",
		NumericCode:  768,
		NativeName:   "Togo",
		Capital:      "Lomé",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".tg",
		CallingCode:  228,
		Continent:    "africa",
		Currency:     "xof",
	},
	CountryTK: {
		ID:           "tokelau",
		Alpha2Code:   "TK",
		Alpha3Code:   "TKL",
		NumericCode:  772,
		NativeName:   "Tokelau",
		Capital:      "Fakaofo",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".tk",
		CallingCode:  690,
		Continent:    "oceania",
		Currency:     "nzd",
	},
	CountryTO: {
		ID:           "tonga",
		Alpha2Code:   "TO",
		Alpha3Code:   "TON",
		NumericCode:  776,
		NativeName:   "Tonga",
		Capital:      "Nukuʻalofa",
		MainLanguage: "tonga",
		Languages:    []string{"tonga", "english"},
		TLD:          ".to",
		CallingCode:  676,
		Continent:    "oceania",
		Currency:     "top",
	},
	CountryTT: {
		ID:           "trinidadAndTobago",
		Alpha2Code:   "TT",
		Alpha3Code:   "TTO",
		NumericCode:  780,
		NativeName:   "Trinidad and Tobago",
		Capital:      "Port of Spain",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".tt",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "ttd",
	},
	CountryTN: {
		ID:           "tunisia",
		Alpha2Code:   "TN",
		Alpha3Code:   "TUN",
		NumericCode:  788,
		NativeName:   "تونس",
		Capital:      "Tunis",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".tn",
		CallingCode:  216,
		Continent:    "africa",
		Currency:     "tnd",
	},
	CountryTR: {
		ID:           "turkey",
		Alpha2Code:   "TR",
		Alpha3Code:   "TUR",
		NumericCode:  792,
		NativeName:   "Türkiye",
		Capital:      "Ankara",
		MainLanguage: "turkish",
		Languages:    []string{"turkish"},
		TLD:          ".tr",
		CallingCode:  90,
		Continent:    "europe",
		Currency:     "turkishLira",
	},
	CountryTM: {
		ID:           "turkmenistan",
		Alpha2Code:   "TM",
		Alpha3Code:   "TKM",
		NumericCode:  795,
		NativeName:   "Türkmenistan",
		Capital:      "Aşgabat",
		MainLanguage: "turkmen",
		Languages:    []string{"turkmen", "russian"},
		TLD:          ".tm",
		CallingCode:  993,
		Continent:    "asia",
		Currency:     "tmt",
	},
	CountryTC: {
		ID:           "turksAndCaicosIslands",
		Alpha2Code:   "TC",
		Alpha3Code:   "TCA",
		NumericCode:  796,
		NativeName:   "Turks and Caicos Islands",
		Capital:      "Cockburn Town",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".tc",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryTV: {
		ID:           "tuvalu",
		Alpha2Code:   "TV",
		Alpha3Code:   "TUV",
		NumericCode:  798,
		NativeName:   "Tuvalu",
		Capital:      "Funafuti",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".tv",
		CallingCode:  688,
		Continent:    "oceania",
		Currency:     "aud",
	},
	CountryUG: {
		ID:           "uganda",
		Alpha2Code:   "UG",
		Alpha3Code:   "UGA",
		NumericCode:  800,
		NativeName:   "Uganda",
		Capital:      "Kampala",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".ug",
		CallingCode:  256,
		Continent:    "africa",
		Currency:     "ugx",
	},
	CountryUA: {
		ID:           "ukraine",
		Alpha2Code:   "UA",
		Alpha3Code:   "UKR",
		NumericCode:  804,
		NativeName:   "Україна",
		Capital:      "Київ",
		MainLanguage: "ukrainian",
		Languages:    []string{"ukrainian"},
		TLD:          ".ua",
		CallingCode:  380,
		Continent:    "europe",
		Currency:     "uah",
	},
	CountryAE: {
		ID:           "unitedArabEmirates",
		Alpha2Code:   "AE",
		Alpha3Code:   "ARE",
		NumericCode:  784,
		NativeName:   "الإمارات العربية المتحدة",
		Capital:      "أبو ظبي",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".ae",
		CallingCode:  971,
		Continent:    "asia",
		Currency:     "aed",
	},
	CountryGB: {
		ID:           "unitedKingdom",
		Alpha2Code:   "GB",
		Alpha3Code:   "GBR",
		NumericCode:  826,
		NativeName:   "United Kingdom",
		Capital:      "London",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".uk",
		CallingCode:  44,
		Continent:    "europe",
		Currency:     "gbp",
	},
	CountryUM: {
		ID:           "unitedStatesMinorOutlyingIslands",
		Alpha2Code:   "UM",
		Alpha3Code:   "UMI",
		NumericCode:  581,
		NativeName:   "United States Minor Outlying Islands",
		Capital:      "",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".us",
		CallingCode:  1,
		Continent:    "oceania",
		Currency:     "usd",
	},
	CountryUS: {
		ID:           "unitedStates",
		Alpha2Code:   "US",
		Alpha3Code:   "USA",
		NumericCode:  840,
		NativeName:   "United States",
		Capital:      "Washington, D.C.",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".us",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryUY: {
		ID:           "uruguay",
		Alpha2Code:   "UY",
		Alpha3Code:   "URY",
		NumericCode:  858,
		NativeName:   "Uruguay",
		Capital:      "Montevideo",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".uy",
		CallingCode:  598,
		Continent:    "southAmerica",
		Currency:     "uyu",
	},
	CountryUZ: {
		ID:           "uzbekistan",
		Alpha2Code:   "UZ",
		Alpha3Code:   "UZB",
		NumericCode:  860,
		NativeName:   "Oʻzbekiston",
		Capital:      "Toshkent",
		MainLanguage: "uzbek",
		Languages:    []string{"uzbek", "russian"},
		TLD:          ".uz",
		CallingCode:  998,
		Continent:    "asia",
		Currency:     "uzs",
	},
	CountryVU: {
		ID:           "vanuatu",
		Alpha2Code:   "VU",
		Alpha3Code:   "VUT",
		NumericCode:  548,
		NativeName:   "Vanuatu",
		Capital:      "Port Vila",
		MainLanguage: "bislama",
		Languages:    []string{"bislama", "english", "french"},
		TLD:          ".vu",
		CallingCode:  678,
		Continent:    "oceania",
		Currency:     "vuv",
	},
	CountryVA: {
		ID:           "vaticanCity",
		Alpha2Code:   "VA",
		Alpha3Code:   "VAT",
		NumericCode:  336,
		NativeName:   "Vaticano",
		Capital:      "Vatican City",
		MainLanguage: "italian",
		Languages:    []string{"italian"},
		TLD:          ".va",
		CallingCode:  379,
		Continent:    "europe",
		Currency:     "eur",
	},
	CountryVE: {
		ID:           "venezuela",
		Alpha2Code:   "VE",
		Alpha3Code:   "VEN",
		NumericCode:  862,
		NativeName:   "Venezuela",
		Capital:      "Caracas",
		MainLanguage: "spanish",
		Languages:    []string{"spanish"},
		TLD:          ".ve",
		CallingCode:  58,
		Continent:    "southAmerica",
		Currency:     "ves",
	},
	CountryVN: {
		ID:           "vietnam",
		Alpha2Code:   "VN",
		Alpha3Code:   "VNM",
		NumericCode:  704,
		NativeName:   "Việt Nam",
		Capital:      "Hà Nội",
		MainLanguage: "vietnamese",
		Languages:    []string{"vietnamese"},
		TLD:          ".vn",
		CallingCode:  84,
		Continent:    "asia",
		Currency:     "vnd",
	},
	CountryVI: {
		ID:           "virginIslandsUS",
		Alpha2Code:   "VI",
		Alpha3Code:   "VIR",
		NumericCode:  850,
		NativeName:   "United States Virgin Islands",
		Capital:      "Charlotte Amalie",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".vi",
		CallingCode:  1,
		Continent:    "northAmerica",
		Currency:     "usd",
	},
	CountryWF: {
		ID:           "wallisAndFutuna",
		Alpha2Code:   "WF",
		Alpha3Code:   "WLF",
		NumericCode:  876,
		NativeName:   "Wallis et Futuna",
		Capital:      "Mata-Utu",
		MainLanguage: "french",
		Languages:    []string{"french"},
		TLD:          ".wf",
		CallingCode:  681,
		Continent:    "oceania",
		Currency:     "xpf",
	},
	CountryEH: {
		ID:           "westernSahara",
		Alpha2Code:   "EH",
		Alpha3Code:   "ESH",
		NumericCode:  732,
		NativeName:   "الصحراء الغربية",
		Capital:      "العيون",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".eh",
		CallingCode:  212,
		Continent:    "africa",
		Currency:     "mad",
	},
	CountryYE: {
		ID:           "yemen",
		Alpha2Code:   "YE",
		Alpha3Code:   "YEM",
		NumericCode:  887,
		NativeName:   "اليمن",
		Capital:      "صنعاء",
		MainLanguage: "arabic",
		Languages:    []string{"arabic"},
		TLD:          ".ye",
		CallingCode:  967,
		Continent:    "asia",
		Currency:     "yer",
	},
	CountryZM: {
		ID:           "zambia",
		Alpha2Code:   "ZM",
		Alpha3Code:   "ZMB",
		NumericCode:  894,
		NativeName:   "Zambia",
		Capital:      "Lusaka",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".zm",
		CallingCode:  260,
		Continent:    "africa",
		Currency:     "zmw",
	},
	CountryZW: {
		ID:           "zimbabwe",
		Alpha2Code:   "ZW",
		Alpha3Code:   "ZWE",
		NumericCode:  716,
		NativeName:   "Zimbabwe",
		Capital:      "Harare",
		MainLanguage: "english",
		Languages:    []string{"english"},
		TLD:          ".zw",
		CallingCode:  263,
		Continent:    "africa",
		Currency:     "zwl",
	},
}

var countriesByAlpha3 = map[string]Country{}

func init() {
	for _, c := range countries {
		countriesByAlpha3[c.Alpha3Code] = c
	}
}

// CountryByAlpha2 returns a country by its alpha-2 code.
func CountryByAlpha2(code string) (Country, bool) {
	c, ok := countries[CountryCode(strings.ToUpper(code))]

	return c, ok
}

// CountryByAlpha3 returns a country by its alpha-3 code.
func CountryByAlpha3(code string) (Country, bool) {
	c, ok := countriesByAlpha3[strings.ToUpper(code)]

	return c, ok
}

// AllCountries returns all countries.
func AllCountries() []Country {
	result := make([]Country, 0, len(countries))
	for _, c := range countries {
		result = append(result, c)
	}

	return result
}

// CountriesByContinent returns all countries in a continent.
func CountriesByContinent(continentID string) []Country {
	var result []Country

	for _, c := range countries {
		if c.Continent == continentID {
			result = append(result, c)
		}
	}

	return result
}
