<?php

// GENERATED CODE - DO NOT MODIFY BY HAND

declare(strict_types=1);

namespace Infobits\Intl;

enum Currency: string
{
    case Aed = 'AED';
    case Afn = 'AFN';
    case All = 'ALL';
    case Amd = 'AMD';
    case Ang = 'ANG';
    case Aoa = 'AOA';
    case Ars = 'ARS';
    case Aud = 'AUD';
    case Awg = 'AWG';
    case Azn = 'AZN';
    case Bam = 'BAM';
    case Bbd = 'BBD';
    case Bdt = 'BDT';
    case Bgn = 'BGN';
    case Bhd = 'BHD';
    case Bif = 'BIF';
    case Bmd = 'BMD';
    case Bnd = 'BND';
    case Bob = 'BOB';
    case Bov = 'BOV';
    case Brl = 'BRL';
    case Bsd = 'BSD';
    case Btn = 'BTN';
    case Bwp = 'BWP';
    case Byn = 'BYN';
    case Bzd = 'BZD';
    case Cad = 'CAD';
    case Cdf = 'CDF';
    case Che = 'CHE';
    case Chf = 'CHF';
    case Chw = 'CHW';
    case Clf = 'CLF';
    case Clp = 'CLP';
    case Cny = 'CNY';
    case Cop = 'COP';
    case Cou = 'COU';
    case Crc = 'CRC';
    case Cup = 'CUP';
    case Cve = 'CVE';
    case Czk = 'CZK';
    case Djf = 'DJF';
    case Dkk = 'DKK';
    case Dop = 'DOP';
    case Dzd = 'DZD';
    case Egp = 'EGP';
    case Ern = 'ERN';
    case Etb = 'ETB';
    case Eur = 'EUR';
    case Fjd = 'FJD';
    case Fkp = 'FKP';
    case Gbp = 'GBP';
    case Gel = 'GEL';
    case Ghs = 'GHS';
    case Gip = 'GIP';
    case Gmd = 'GMD';
    case Gnf = 'GNF';
    case Gtq = 'GTQ';
    case Gyd = 'GYD';
    case Hkd = 'HKD';
    case Hnl = 'HNL';
    case Htg = 'HTG';
    case Huf = 'HUF';
    case Idr = 'IDR';
    case Ils = 'ILS';
    case Inr = 'INR';
    case Iqd = 'IQD';
    case Irr = 'IRR';
    case Isk = 'ISK';
    case Jmd = 'JMD';
    case Jod = 'JOD';
    case Jpy = 'JPY';
    case Kes = 'KES';
    case Kgs = 'KGS';
    case Khr = 'KHR';
    case Kmf = 'KMF';
    case Kpw = 'KPW';
    case Krw = 'KRW';
    case Kwd = 'KWD';
    case Kyd = 'KYD';
    case Kzt = 'KZT';
    case Lak = 'LAK';
    case Lbp = 'LBP';
    case Lkr = 'LKR';
    case Lrd = 'LRD';
    case Lsl = 'LSL';
    case Lyd = 'LYD';
    case Mad = 'MAD';
    case Mdl = 'MDL';
    case Mga = 'MGA';
    case Mkd = 'MKD';
    case Mmk = 'MMK';
    case Mnt = 'MNT';
    case Mop = 'MOP';
    case Mru = 'MRU';
    case Mur = 'MUR';
    case Mvr = 'MVR';
    case Mwk = 'MWK';
    case Mxn = 'MXN';
    case Mxv = 'MXV';
    case Myr = 'MYR';
    case Mzn = 'MZN';
    case Nad = 'NAD';
    case Ngn = 'NGN';
    case Nio = 'NIO';
    case Nok = 'NOK';
    case Npr = 'NPR';
    case Nzd = 'NZD';
    case Omr = 'OMR';
    case Pab = 'PAB';
    case Pen = 'PEN';
    case Pgk = 'PGK';
    case Php = 'PHP';
    case Pkr = 'PKR';
    case Pln = 'PLN';
    case Pyg = 'PYG';
    case Qar = 'QAR';
    case Ron = 'RON';
    case Rsd = 'RSD';
    case Rub = 'RUB';
    case Rwf = 'RWF';
    case Sar = 'SAR';
    case Sbd = 'SBD';
    case Scr = 'SCR';
    case Sdg = 'SDG';
    case Sek = 'SEK';
    case Sgd = 'SGD';
    case Shp = 'SHP';
    case Sle = 'SLE';
    case Sos = 'SOS';
    case Srd = 'SRD';
    case Ssp = 'SSP';
    case Stn = 'STN';
    case Svc = 'SVC';
    case Syp = 'SYP';
    case Szl = 'SZL';
    case Thb = 'THB';
    case Tjs = 'TJS';
    case Tmt = 'TMT';
    case Tnd = 'TND';
    case Top = 'TOP';
    case TurkishLira = 'TRY';
    case Ttd = 'TTD';
    case Twd = 'TWD';
    case Tzs = 'TZS';
    case Uah = 'UAH';
    case Ugx = 'UGX';
    case Usd = 'USD';
    case Usn = 'USN';
    case Uyi = 'UYI';
    case Uyu = 'UYU';
    case Uyw = 'UYW';
    case Uzs = 'UZS';
    case Ved = 'VED';
    case Ves = 'VES';
    case Vnd = 'VND';
    case Vuv = 'VUV';
    case Wst = 'WST';
    case Xaf = 'XAF';
    case Xag = 'XAG';
    case Xau = 'XAU';
    case Xba = 'XBA';
    case Xbb = 'XBB';
    case Xbc = 'XBC';
    case Xbd = 'XBD';
    case Xcd = 'XCD';
    case Xdr = 'XDR';
    case Xof = 'XOF';
    case Xpd = 'XPD';
    case Xpf = 'XPF';
    case Xpt = 'XPT';
    case Xsu = 'XSU';
    case Xts = 'XTS';
    case Xua = 'XUA';
    case Xxx = 'XXX';
    case Yer = 'YER';
    case Zar = 'ZAR';
    case Zmw = 'ZMW';
    case Zmg = 'ZMG';
    case Zwl = 'ZWL';

    public function code(): string
    {
        return $this->value;
    }

    public function nativeName(): string
    {
        return match ($this) {
            self::Aed => 'United Arab Emirates Dirham',
            self::Afn => 'Afghan Afghani',
            self::All => 'Albanian Lek',
            self::Amd => 'Armenian Dram',
            self::Ang => 'Netherlands Antillean Guilder',
            self::Aoa => 'Angolan Kwanza',
            self::Ars => 'Argentine Peso',
            self::Aud => 'Australian Dollar',
            self::Awg => 'Aruban Florin',
            self::Azn => 'Azerbaijani Manat',
            self::Bam => 'Bosnia-Herzegovina Convertible Mark',
            self::Bbd => 'Barbadian Dollar',
            self::Bdt => 'Bangladeshi Taka',
            self::Bgn => 'Bulgarian Lev',
            self::Bhd => 'Bahraini Dinar',
            self::Bif => 'Burundian Franc',
            self::Bmd => 'Bermudian Dollar',
            self::Bnd => 'Brunei Dollar',
            self::Bob => 'Bolivian Boliviano',
            self::Bov => 'Bolivian Mvdol',
            self::Brl => 'Brazilian Real',
            self::Bsd => 'Bahamian Dollar',
            self::Btn => 'Bhutanese Ngultrum',
            self::Bwp => 'Botswana Pula',
            self::Byn => 'Belarusian Ruble',
            self::Bzd => 'Belize Dollar',
            self::Cad => 'Canadian Dollar',
            self::Cdf => 'Congolese Franc',
            self::Che => 'WIR Euro',
            self::Chf => 'Swiss Franc',
            self::Chw => 'WIR Franc',
            self::Clf => 'Chilean Unit of Account (UF)',
            self::Clp => 'Chilean Peso',
            self::Cny => 'Chinese Yuan',
            self::Cop => 'Colombian Peso',
            self::Cou => 'Unidad de Valor Real',
            self::Crc => 'Costa Rican Colón',
            self::Cup => 'Cuban Peso',
            self::Cve => 'Cape Verdean Escudo',
            self::Czk => 'Czech Koruna',
            self::Djf => 'Djiboutian Franc',
            self::Dkk => 'Danske Kroner',
            self::Dop => 'Dominican Peso',
            self::Dzd => 'Algerian Dinar',
            self::Egp => 'Egyptian Pound',
            self::Ern => 'Eritrean Nakfa',
            self::Etb => 'Ethiopian Birr',
            self::Eur => 'Euro',
            self::Fjd => 'Fijian Dollar',
            self::Fkp => 'Falkland Islands Pound',
            self::Gbp => 'British Pound',
            self::Gel => 'Georgian Lari',
            self::Ghs => 'Ghanaian Cedi',
            self::Gip => 'Gibraltar Pound',
            self::Gmd => 'Gambian Dalasi',
            self::Gnf => 'Guinean Franc',
            self::Gtq => 'Guatemalan Quetzal',
            self::Gyd => 'Guyanese Dollar',
            self::Hkd => 'Hong Kong Dollar',
            self::Hnl => 'Honduran Lempira',
            self::Htg => 'Haitian Gourde',
            self::Huf => 'Hungarian Forint',
            self::Idr => 'Indonesian Rupiah',
            self::Ils => 'Israeli New Shekel',
            self::Inr => 'Indian Rupee',
            self::Iqd => 'Iraqi Dinar',
            self::Irr => 'Iranian Rial',
            self::Isk => 'Icelandic Króna',
            self::Jmd => 'Jamaican Dollar',
            self::Jod => 'Jordanian Dinar',
            self::Jpy => 'Japanese Yen',
            self::Kes => 'Kenyan Shilling',
            self::Kgs => 'Kyrgyzstani Som',
            self::Khr => 'Cambodian Riel',
            self::Kmf => 'Comorian Franc',
            self::Kpw => 'North Korean Won',
            self::Krw => 'South Korean Won',
            self::Kwd => 'Kuwaiti Dinar',
            self::Kyd => 'Cayman Islands Dollar',
            self::Kzt => 'Kazakhstani Tenge',
            self::Lak => 'Lao Kip',
            self::Lbp => 'Lebanese Pound',
            self::Lkr => 'Sri Lankan Rupee',
            self::Lrd => 'Liberian Dollar',
            self::Lsl => 'Lesotho Loti',
            self::Lyd => 'Libyan Dinar',
            self::Mad => 'Moroccan Dirham',
            self::Mdl => 'Moldovan Leu',
            self::Mga => 'Malagasy Ariary',
            self::Mkd => 'Macedonian Denar',
            self::Mmk => 'Myanmar Kyat',
            self::Mnt => 'Mongolian Tugrik',
            self::Mop => 'Macanese Pataca',
            self::Mru => 'Mauritanian Ouguiya',
            self::Mur => 'Mauritian Rupee',
            self::Mvr => 'Maldivian Rufiyaa',
            self::Mwk => 'Malawian Kwacha',
            self::Mxn => 'Mexican Peso',
            self::Mxv => 'Mexican Unidad de Inversion (UDI)',
            self::Myr => 'Malaysian Ringgit',
            self::Mzn => 'Mozambican Metical',
            self::Nad => 'Namibian Dollar',
            self::Ngn => 'Nigerian Naira',
            self::Nio => 'Nicaraguan Córdoba',
            self::Nok => 'Norwegian Krone',
            self::Npr => 'Nepalese Rupee',
            self::Nzd => 'New Zealand Dollar',
            self::Omr => 'Omani Rial',
            self::Pab => 'Panamanian Balboa',
            self::Pen => 'Peruvian Nuevo Sol',
            self::Pgk => 'Papua New Guinean Kina',
            self::Php => 'Philippine Peso',
            self::Pkr => 'Pakistani Rupee',
            self::Pln => 'Polish Złoty',
            self::Pyg => 'Paraguayan Guaraní',
            self::Qar => 'Qatari Rial',
            self::Ron => 'Romanian Leu',
            self::Rsd => 'Serbian Dinar',
            self::Rub => 'Russian Ruble',
            self::Rwf => 'Rwandan Franc',
            self::Sar => 'Saudi Riyal',
            self::Sbd => 'Solomon Islands Dollar',
            self::Scr => 'Seychellois Rupee',
            self::Sdg => 'Sudanese Pound',
            self::Sek => 'Swedish Krona',
            self::Sgd => 'Singapore Dollar',
            self::Shp => 'Saint Helena Pound',
            self::Sle => 'Sierra Leonean Leone',
            self::Sos => 'Somali Shilling',
            self::Srd => 'Surinamese Dollar',
            self::Ssp => 'South Sudanese Pound',
            self::Stn => 'São Tomé and Príncipe Dobra',
            self::Svc => 'Salvadoran Colón',
            self::Syp => 'Syrian Pound',
            self::Szl => 'Swazi Lilangeni',
            self::Thb => 'Thai Baht',
            self::Tjs => 'Tajikistani Somoni',
            self::Tmt => 'Turkmenistani Manat',
            self::Tnd => 'Tunisian Dinar',
            self::Top => 'Tongan Pa\'anga',
            self::TurkishLira => 'Turkish Lira',
            self::Ttd => 'Trinidad and Tobago Dollar',
            self::Twd => 'New Taiwan Dollar',
            self::Tzs => 'Tanzanian Shilling',
            self::Uah => 'Ukrainian Hryvnia',
            self::Ugx => 'Ugandan Shilling',
            self::Usd => 'United States Dollar',
            self::Usn => 'United States Dollar (Next day)',
            self::Uyi => 'Uruguayan Peso en Unidades Indexadas',
            self::Uyu => 'Uruguayan Peso',
            self::Uyw => 'Unidad Previsional',
            self::Uzs => 'Uzbekistan Som',
            self::Ved => 'Venezuelan Bolívar Soberano',
            self::Ves => 'Venezuelan Bolívar',
            self::Vnd => 'Vietnamese Dong',
            self::Vuv => 'Vanuatu Vatu',
            self::Wst => 'Samoan Tala',
            self::Xaf => 'Central African CFA Franc',
            self::Xag => 'Silver (one troy ounce)',
            self::Xau => 'Gold (one troy ounce)',
            self::Xba => 'European Composite Unit',
            self::Xbb => 'European Monetary Unit',
            self::Xbc => 'European Unit of Account 9',
            self::Xbd => 'European Unit of Account 17',
            self::Xcd => 'East Caribbean Dollar',
            self::Xdr => 'Special Drawing Rights',
            self::Xof => 'West African CFA Franc',
            self::Xpd => 'Palladium (one troy ounce)',
            self::Xpf => 'CFP Franc',
            self::Xpt => 'Platinum (one troy ounce)',
            self::Xsu => 'SUCRE',
            self::Xts => 'Codes specifically reserved for testing purposes',
            self::Xua => 'ADB Unit of Account',
            self::Xxx => 'No currency',
            self::Yer => 'Yemeni Rial',
            self::Zar => 'South African Rand',
            self::Zmw => 'Zambian Kwacha',
            self::Zmg => 'Zambian Kwacha (pre-2013)',
            self::Zwl => 'Zimbabwean Dollar',
        };
    }

    public function nativeNamePlural(): string
    {
        return match ($this) {
            self::Aed => 'United Arab Emirates Dirhams',
            self::Afn => 'Afghan Afghanis',
            self::All => 'Albanian Leke',
            self::Amd => 'Armenian Drams',
            self::Ang => 'Netherlands Antillean Guilders',
            self::Aoa => 'Angolan Kwanza',
            self::Ars => 'Argentine Pesos',
            self::Aud => 'Australian Dollars',
            self::Awg => 'Aruban Florin',
            self::Azn => 'Azerbaijani Manat',
            self::Bam => 'Bosnia-Herzegovina Convertible Marks',
            self::Bbd => 'Barbadian Dollars',
            self::Bdt => 'Bangladeshi Takas',
            self::Bgn => 'Bulgarian Leva',
            self::Bhd => 'Bahraini Dinars',
            self::Bif => 'Burundian Francs',
            self::Bmd => 'Bermudian Dollars',
            self::Bnd => 'Brunei Dollars',
            self::Bob => 'Bolivian Bolivianos',
            self::Bov => 'Bolivian Mvdols',
            self::Brl => 'Brazilian Reals',
            self::Bsd => 'Bahamian Dollars',
            self::Btn => 'Bhutanese Ngultrums',
            self::Bwp => 'Botswana Pulas',
            self::Byn => 'Belarusian Rubles',
            self::Bzd => 'Belize Dollars',
            self::Cad => 'Canadian Dollars',
            self::Cdf => 'Congolese Francs',
            self::Che => 'WIR Euros',
            self::Chf => 'Swiss Francs',
            self::Chw => 'WIR Francs',
            self::Clf => 'Chilean Units of Account (UF)',
            self::Clp => 'Chilean Pesos',
            self::Cny => 'Chinese Yuan',
            self::Cop => 'Colombian Pesos',
            self::Cou => 'Unidad de Valor Reals',
            self::Crc => 'Costa Rican Colóns',
            self::Cup => 'Cuban Pesos',
            self::Cve => 'Cape Verdean Escudos',
            self::Czk => 'Czech Korunas',
            self::Djf => 'Djiboutian Francs',
            self::Dkk => 'Danske Kroner',
            self::Dop => 'Dominican Pesos',
            self::Dzd => 'Algerian Dinars',
            self::Egp => 'Egyptian Pounds',
            self::Ern => 'Eritrean Nakfas',
            self::Etb => 'Ethiopian Birrs',
            self::Eur => 'Euros',
            self::Fjd => 'Fijian Dollars',
            self::Fkp => 'Falkland Islands Pounds',
            self::Gbp => 'British Pounds',
            self::Gel => 'Georgian Laris',
            self::Ghs => 'Ghanaian Cedis',
            self::Gip => 'Gibraltar Pounds',
            self::Gmd => 'Gambian Dalasis',
            self::Gnf => 'Guinean Francs',
            self::Gtq => 'Guatemalan Quetzals',
            self::Gyd => 'Guyanese Dollars',
            self::Hkd => 'Hong Kong Dollars',
            self::Hnl => 'Honduran Lempiras',
            self::Htg => 'Haitian Gourdes',
            self::Huf => 'Hungarian Forints',
            self::Idr => 'Indonesian Rupiahs',
            self::Ils => 'Israeli New Shekels',
            self::Inr => 'Indian Rupees',
            self::Iqd => 'Iraqi Dinars',
            self::Irr => 'Iranian Rials',
            self::Isk => 'Icelandic Krónur',
            self::Jmd => 'Jamaican Dollars',
            self::Jod => 'Jordanian Dinars',
            self::Jpy => 'Japanese Yen',
            self::Kes => 'Kenyan Shillings',
            self::Kgs => 'Kyrgyzstani Soms',
            self::Khr => 'Cambodian Riels',
            self::Kmf => 'Comorian Francs',
            self::Kpw => 'North Korean Won',
            self::Krw => 'South Korean Won',
            self::Kwd => 'Kuwaiti Dinars',
            self::Kyd => 'Cayman Islands Dollars',
            self::Kzt => 'Kazakhstani Tenges',
            self::Lak => 'Lao Kips',
            self::Lbp => 'Lebanese Pounds',
            self::Lkr => 'Sri Lankan Rupees',
            self::Lrd => 'Liberian Dollars',
            self::Lsl => 'Lesotho Lotis',
            self::Lyd => 'Libyan Dinars',
            self::Mad => 'Moroccan Dirhams',
            self::Mdl => 'Moldovan Lei',
            self::Mga => 'Malagasy Ariaries',
            self::Mkd => 'Macedonian Denari',
            self::Mmk => 'Myanmar Kyats',
            self::Mnt => 'Mongolian Tugriks',
            self::Mop => 'Macanese Patacas',
            self::Mru => 'Mauritanian Ouguiyas',
            self::Mur => 'Mauritian Rupees',
            self::Mvr => 'Maldivian Rufiyaas',
            self::Mwk => 'Malawian Kwachas',
            self::Mxn => 'Mexican Pesos',
            self::Mxv => 'Mexican Unidad de Inversions (UDI)',
            self::Myr => 'Malaysian Ringgits',
            self::Mzn => 'Mozambican Meticals',
            self::Nad => 'Namibian Dollars',
            self::Ngn => 'Nigerian Nairas',
            self::Nio => 'Nicaraguan Córdobas',
            self::Nok => 'Norwegian Kroner',
            self::Npr => 'Nepalese Rupees',
            self::Nzd => 'New Zealand Dollars',
            self::Omr => 'Omani Rials',
            self::Pab => 'Panamanian Balboas',
            self::Pen => 'Peruvian Nuevo Sols',
            self::Pgk => 'Papua New Guinean Kina',
            self::Php => 'Philippine Pesos',
            self::Pkr => 'Pakistani Rupees',
            self::Pln => 'Polish Złotys',
            self::Pyg => 'Paraguayan Guaranís',
            self::Qar => 'Qatari Rials',
            self::Ron => 'Romanian Lei',
            self::Rsd => 'Serbian Dinars',
            self::Rub => 'Russian Rubles',
            self::Rwf => 'Rwandan Francs',
            self::Sar => 'Saudi Riyals',
            self::Sbd => 'Solomon Islands Dollars',
            self::Scr => 'Seychellois Rupees',
            self::Sdg => 'Sudanese Pounds',
            self::Sek => 'Swedish Kronor',
            self::Sgd => 'Singapore Dollars',
            self::Shp => 'Saint Helena Pounds',
            self::Sle => 'Sierra Leonean Leones',
            self::Sos => 'Somali Shillings',
            self::Srd => 'Surinamese Dollars',
            self::Ssp => 'South Sudanese Pounds',
            self::Stn => 'São Tomé and Príncipe Dobras',
            self::Svc => 'Salvadoran Colóns',
            self::Syp => 'Syrian Pounds',
            self::Szl => 'Swazi Emalangeni',
            self::Thb => 'Thai Baht',
            self::Tjs => 'Tajikistani Somonis',
            self::Tmt => 'Turkmenistani Manats',
            self::Tnd => 'Tunisian Dinars',
            self::Top => 'Tongan Pa\'anga',
            self::TurkishLira => 'Turkish Lira',
            self::Ttd => 'Trinidad and Tobago Dollars',
            self::Twd => 'New Taiwan Dollars',
            self::Tzs => 'Tanzanian Shillings',
            self::Uah => 'Ukrainian Hryvnias',
            self::Ugx => 'Ugandan Shillings',
            self::Usd => 'United States Dollars',
            self::Usn => 'United States Dollars (Next day)',
            self::Uyi => 'Uruguayan Pesos en Unidades Indexadas',
            self::Uyu => 'Uruguayan Pesos',
            self::Uyw => 'Unidad Previsionals',
            self::Uzs => 'Uzbekistan Soms',
            self::Ved => 'Venezuelan Bolívar Soberanos',
            self::Ves => 'Venezuelan Bolívars',
            self::Vnd => 'Vietnamese Dong',
            self::Vuv => 'Vanuatu Vatus',
            self::Wst => 'Samoan Tala',
            self::Xaf => 'Central African CFA Francs',
            self::Xag => 'Silver (one troy ounce)',
            self::Xau => 'Gold (one troy ounce)',
            self::Xba => 'European Composite Units',
            self::Xbb => 'European Monetary Units',
            self::Xbc => 'European Unit of Account 9',
            self::Xbd => 'European Unit of Account 17',
            self::Xcd => 'East Caribbean Dollars',
            self::Xdr => 'Special Drawing Rights',
            self::Xof => 'West African CFA Francs',
            self::Xpd => 'Palladium (one troy ounce)',
            self::Xpf => 'CFP Francs',
            self::Xpt => 'Platinum (one troy ounce)',
            self::Xsu => 'SUCRE',
            self::Xts => 'Codes specifically reserved for testing purposes',
            self::Xua => 'ADB Unit of Accounts',
            self::Xxx => 'No currency',
            self::Yer => 'Yemeni Rials',
            self::Zar => 'South African Rand',
            self::Zmw => 'Zambian Kwachas',
            self::Zmg => 'Zambian Kwachas (pre-2013)',
            self::Zwl => 'Zimbabwean Dollars',
        };
    }

    public function symbol(): string
    {
        return match ($this) {
            self::Aed => 'د.إ',
            self::Afn => '؋',
            self::All => 'L',
            self::Amd => '֏',
            self::Ang => 'ƒ',
            self::Aoa => 'Kz',
            self::Ars => '\\$',
            self::Aud => '\\$',
            self::Awg => 'ƒ',
            self::Azn => '₼',
            self::Bam => 'KM',
            self::Bbd => '\\$',
            self::Bdt => '৳',
            self::Bgn => 'лв',
            self::Bhd => 'ب.د',
            self::Bif => 'FBu',
            self::Bmd => '\\$',
            self::Bnd => '\\$',
            self::Bob => 'Bs.',
            self::Bov => 'BOV',
            self::Brl => 'R\\$',
            self::Bsd => '\\$',
            self::Btn => 'Nu.',
            self::Bwp => 'P',
            self::Byn => 'Br',
            self::Bzd => 'BZ\\$',
            self::Cad => '\\$',
            self::Cdf => 'FC',
            self::Che => 'CHE',
            self::Chf => 'CHF',
            self::Chw => 'CHW',
            self::Clf => 'CLF',
            self::Clp => '\\$',
            self::Cny => '¥',
            self::Cop => '\\$',
            self::Cou => 'COU',
            self::Crc => '₡',
            self::Cup => '\\$',
            self::Cve => 'Esc',
            self::Czk => 'Kč',
            self::Djf => 'Fdj',
            self::Dkk => 'kr',
            self::Dop => 'RD\\$',
            self::Dzd => 'د.ج',
            self::Egp => 'E£',
            self::Ern => 'Nfk',
            self::Etb => 'Br',
            self::Eur => '€',
            self::Fjd => '\\$',
            self::Fkp => '£',
            self::Gbp => '£',
            self::Gel => '₾',
            self::Ghs => '₵',
            self::Gip => '£',
            self::Gmd => 'D',
            self::Gnf => 'FG',
            self::Gtq => 'Q',
            self::Gyd => '\\$',
            self::Hkd => '\\$',
            self::Hnl => 'L',
            self::Htg => 'G',
            self::Huf => 'Ft',
            self::Idr => 'Rp',
            self::Ils => '₪',
            self::Inr => '₹',
            self::Iqd => 'ع.د',
            self::Irr => '﷼',
            self::Isk => 'kr',
            self::Jmd => 'J\\$',
            self::Jod => 'د.ا',
            self::Jpy => '¥',
            self::Kes => 'KSh',
            self::Kgs => 'с',
            self::Khr => '៛',
            self::Kmf => 'CF',
            self::Kpw => '₩',
            self::Krw => '₩',
            self::Kwd => 'د.ك',
            self::Kyd => '\\$',
            self::Kzt => '₸',
            self::Lak => '₭',
            self::Lbp => 'ل.ل',
            self::Lkr => 'Rs',
            self::Lrd => '\\$',
            self::Lsl => 'L',
            self::Lyd => 'ل.د',
            self::Mad => 'د.م.',
            self::Mdl => 'L',
            self::Mga => 'Ar',
            self::Mkd => 'ден',
            self::Mmk => 'K',
            self::Mnt => '₮',
            self::Mop => 'MOP\\$',
            self::Mru => 'UM',
            self::Mur => '₨',
            self::Mvr => 'Rf',
            self::Mwk => 'MK',
            self::Mxn => '\\$',
            self::Mxv => 'MXV',
            self::Myr => 'RM',
            self::Mzn => 'MT',
            self::Nad => '\\$',
            self::Ngn => '₦',
            self::Nio => 'C\\$',
            self::Nok => 'kr',
            self::Npr => 'रू',
            self::Nzd => '\\$',
            self::Omr => 'ر.ع.',
            self::Pab => 'B/.',
            self::Pen => 'S/.',
            self::Pgk => 'K',
            self::Php => '₱',
            self::Pkr => '₨',
            self::Pln => 'zł',
            self::Pyg => '₲',
            self::Qar => 'ر.ق',
            self::Ron => 'lei',
            self::Rsd => 'дин',
            self::Rub => '₽',
            self::Rwf => 'FRw',
            self::Sar => 'ر.س',
            self::Sbd => '\\$',
            self::Scr => '₨',
            self::Sdg => 'ج.س.',
            self::Sek => 'kr',
            self::Sgd => '\\$',
            self::Shp => '£',
            self::Sle => 'Le',
            self::Sos => 'Sh.So.',
            self::Srd => '\\$',
            self::Ssp => '£',
            self::Stn => 'Db',
            self::Svc => '₡',
            self::Syp => 'ل.س',
            self::Szl => 'L',
            self::Thb => '฿',
            self::Tjs => 'ЅМ',
            self::Tmt => 'T',
            self::Tnd => 'د.ت',
            self::Top => 'T\\$',
            self::TurkishLira => '₺',
            self::Ttd => 'TT\\$',
            self::Twd => 'NT\\$',
            self::Tzs => 'TSh',
            self::Uah => '₴',
            self::Ugx => 'USh',
            self::Usd => '\\$',
            self::Usn => 'USN',
            self::Uyi => 'UYI',
            self::Uyu => '\\$U',
            self::Uyw => 'UYW',
            self::Uzs => 'лв',
            self::Ved => 'VES',
            self::Ves => 'Bs.',
            self::Vnd => '₫',
            self::Vuv => 'VT',
            self::Wst => 'WS\\$',
            self::Xaf => 'FCFA',
            self::Xag => 'XAG',
            self::Xau => 'XAU',
            self::Xba => 'XBA',
            self::Xbb => 'XBB',
            self::Xbc => 'XBC',
            self::Xbd => 'XBD',
            self::Xcd => '\\$',
            self::Xdr => 'XDR',
            self::Xof => 'CFA',
            self::Xpd => 'XPD',
            self::Xpf => 'CFPF',
            self::Xpt => 'XPT',
            self::Xsu => 'XSU',
            self::Xts => 'XTS',
            self::Xua => 'XUA',
            self::Xxx => 'XXX',
            self::Yer => '﷼',
            self::Zar => 'R',
            self::Zmw => 'ZK',
            self::Zmg => 'ZMG',
            self::Zwl => 'ZWL',
        };
    }

    public static function fromCode(string $code): ?self
    {
        return self::tryFrom(strtoupper($code));
    }
}
