<?php

// GENERATED CODE - DO NOT MODIFY BY HAND

declare(strict_types=1);

namespace Infobits\Intl;

enum Language: string
{
    case Danish = 'da';
    case English = 'en';
    case Azerbaijani = 'az';
    case German = 'de';
    case Abkhazian = 'ab';
    case Afar = 'aa';
    case Afrikaans = 'af';
    case Akan = 'ak';
    case Albanian = 'sq';
    case Amharic = 'am';
    case Arabic = 'ar';
    case Aragonese = 'an';
    case Armenian = 'hy';
    case Assamese = 'as';
    case Avaric = 'av';
    case Avestan = 'ae';
    case Aymara = 'ay';
    case Bambara = 'bm';
    case Bashkir = 'ba';
    case Basque = 'eu';
    case Belarusian = 'be';
    case Bengali = 'bn';
    case Bihari = 'bh';
    case Bislama = 'bi';
    case Bosnian = 'bs';
    case Breton = 'br';
    case Bulgarian = 'bg';
    case Burmese = 'my';
    case Catalan = 'ca';
    case Chamorro = 'ch';
    case Chechen = 'ce';
    case ChurchSlavic = 'cu';
    case Chichewa = 'ny';
    case Chinese = 'zh';
    case Chuvash = 'cv';
    case Cornish = 'kw';
    case Corsican = 'co';
    case Cree = 'cr';
    case Croatian = 'hr';
    case Czech = 'cs';
    case Divehi = 'dv';
    case Dutch = 'nl';
    case Dzongkha = 'dz';
    case Esperanto = 'eo';
    case Estonian = 'et';
    case Ewe = 'ee';
    case Faroese = 'fo';
    case Fijian = 'fj';
    case Finnish = 'fi';
    case French = 'fr';
    case WesternFrisian = 'fy';
    case Fulah = 'ff';
    case Gaelic = 'gd';
    case Galician = 'gl';
    case Ganda = 'lg';
    case Georgian = 'ka';
    case Greek = 'el';
    case Greenlandic = 'kl';
    case Guarani = 'gn';
    case Gujarati = 'gu';
    case Haitian = 'ht';
    case Hausa = 'ha';
    case Hebrew = 'he';
    case Herero = 'hz';
    case Hindi = 'hi';
    case HiriMotu = 'ho';
    case Hungarian = 'hu';
    case Icelandic = 'is';
    case Ido = 'io';
    case Igbo = 'ig';
    case Indonesian = 'id';
    case Interlingua = 'ia';
    case Interlingue = 'ie';
    case SichuanYi = 'ii';
    case Inuktitut = 'iu';
    case Inupiaq = 'ik';
    case Irish = 'ga';
    case Italian = 'it';
    case Japanese = 'ja';
    case Javanese = 'jv';
    case Kannada = 'kn';
    case Kanuri = 'kr';
    case Kashmiri = 'ks';
    case Kazakh = 'kk';
    case Khmer = 'km';
    case Kikuyu = 'ki';
    case Kinyarwanda = 'rw';
    case Kirghiz = 'ky';
    case Komi = 'kv';
    case Kongo = 'kg';
    case Korean = 'ko';
    case Kuanyama = 'kj';
    case Kurdish = 'ku';
    case Lao = 'lo';
    case Latin = 'la';
    case Latvian = 'lv';
    case Limburgish = 'li';
    case Lingala = 'ln';
    case Lithuanian = 'lt';
    case LubaKatanga = 'lu';
    case Luxembourgish = 'lb';
    case Macedonian = 'mk';
    case Malagasy = 'mg';
    case Malay = 'ms';
    case Malayalam = 'ml';
    case Maltese = 'mt';
    case Manx = 'gv';
    case Maori = 'mi';
    case Marathi = 'mr';
    case Marshallese = 'mh';
    case Mongolian = 'mn';
    case Nauru = 'na';
    case Navajo = 'nv';
    case NorthNdebele = 'nd';
    case SouthNdebele = 'nr';
    case Ndonga = 'ng';
    case Nepali = 'ne';
    case Norwegian = 'no';
    case NorwegianBokmal = 'nb';
    case NorwegianNynorsk = 'nn';
    case Occitan = 'oc';
    case Ojibwa = 'oj';
    case Oriya = 'or';
    case Oromo = 'om';
    case Ossetian = 'os';
    case Pali = 'pi';
    case Pashto = 'ps';
    case Persian = 'fa';
    case Polish = 'pl';
    case Portuguese = 'pt';
    case Punjabi = 'pa';
    case Quechua = 'qu';
    case Romanian = 'ro';
    case Romansh = 'rm';
    case Rundi = 'rn';
    case Russian = 'ru';
    case NorthernSami = 'se';
    case Samoan = 'sm';
    case Sango = 'sg';
    case Sanskrit = 'sa';
    case Sardinian = 'sc';
    case Serbian = 'sr';
    case Sindhi = 'sd';
    case Sinhala = 'si';
    case Slovak = 'sk';
    case Slovenian = 'sl';
    case Somali = 'so';
    case SouthernSotho = 'st';
    case Shona = 'sn';
    case Spanish = 'es';
    case Sundanese = 'su';
    case Swahili = 'sw';
    case Swati = 'ss';
    case Swedish = 'sv';
    case Tagalog = 'tl';
    case Tahitian = 'ty';
    case Tajik = 'tg';
    case Tamil = 'ta';
    case Tatar = 'tt';
    case Telugu = 'te';
    case Thai = 'th';
    case Tibetan = 'bo';
    case Tigrinya = 'ti';
    case Tonga = 'to';
    case Tsonga = 'ts';
    case Tswana = 'tn';
    case Turkish = 'tr';
    case Turkmen = 'tk';
    case Twi = 'tw';
    case Uighur = 'ug';
    case Ukrainian = 'uk';
    case Urdu = 'ur';
    case Uzbek = 'uz';
    case Venda = 've';
    case Vietnamese = 'vi';
    case Volapuk = 'vo';
    case Walloon = 'wa';
    case Welsh = 'cy';
    case Wolof = 'wo';
    case Xhosa = 'xh';
    case Yiddish = 'yi';
    case Yoruba = 'yo';
    case Zhuang = 'za';
    case Zulu = 'zu';

    public function code(): string
    {
        return $this->value;
    }

    public function nativeName(): string
    {
        return match ($this) {
            self::Danish => 'dansk',
            self::English => 'english',
            self::Azerbaijani => 'azərbaycan dili',
            self::German => 'Deutsch',
            self::Abkhazian => 'аҧсуа',
            self::Afar => 'Afaraf',
            self::Afrikaans => 'Afrikaans',
            self::Akan => 'Akan',
            self::Albanian => 'Shqip',
            self::Amharic => 'አማርኛ',
            self::Arabic => 'العربية',
            self::Aragonese => 'aragonés',
            self::Armenian => 'Հայերեն',
            self::Assamese => 'অসমীয়া',
            self::Avaric => 'авар мацӀ',
            self::Avestan => 'avesta',
            self::Aymara => 'aymar aru',
            self::Bambara => 'bamanankan',
            self::Bashkir => 'башҡорт теле',
            self::Basque => 'euskara',
            self::Belarusian => 'беларуская мова',
            self::Bengali => 'বাংলা',
            self::Bihari => 'भोजपुरी',
            self::Bislama => 'Bislama',
            self::Bosnian => 'bosanski jezik',
            self::Breton => 'brezhoneg',
            self::Bulgarian => 'български език',
            self::Burmese => 'ဗမာစာ',
            self::Catalan => 'català',
            self::Chamorro => 'Chamoru',
            self::Chechen => 'нохчийн мотт',
            self::ChurchSlavic => 'ѩзыкъ словѣньскъ',
            self::Chichewa => 'chiCheŵa',
            self::Chinese => '中文',
            self::Chuvash => 'чӑваш чӗлхи',
            self::Cornish => 'Kernewek',
            self::Corsican => 'corsu',
            self::Cree => 'ᓀᐦᐃᔭᐍᐏᐣ',
            self::Croatian => 'hrvatski jezik',
            self::Czech => 'čeština',
            self::Divehi => 'ދިވެހި',
            self::Dutch => 'Nederlands',
            self::Dzongkha => 'རྫོང་ཁ',
            self::Esperanto => 'Esperanto',
            self::Estonian => 'eesti',
            self::Ewe => 'Eʋegbe',
            self::Faroese => 'føroyskt',
            self::Fijian => 'vosa Vakaviti',
            self::Finnish => 'suomi',
            self::French => 'français',
            self::WesternFrisian => 'Frysk',
            self::Fulah => 'Fulfulde',
            self::Gaelic => 'Gàidhlig',
            self::Galician => 'galego',
            self::Ganda => 'Luganda',
            self::Georgian => 'ქართული',
            self::Greek => 'Ελληνικά',
            self::Greenlandic => 'kalaallisut',
            self::Guarani => 'Avañe\'ẽ',
            self::Gujarati => 'ગુજરાતી',
            self::Haitian => 'Kreyòl ayisyen',
            self::Hausa => 'هَوُسَ',
            self::Hebrew => 'עברית',
            self::Herero => 'Otjiherero',
            self::Hindi => 'हिन्दी',
            self::HiriMotu => 'Hiri Motu',
            self::Hungarian => 'magyar',
            self::Icelandic => 'Íslenska',
            self::Ido => 'Ido',
            self::Igbo => 'Asụsụ Igbo',
            self::Indonesian => 'Bahasa Indonesia',
            self::Interlingua => 'Interlingua',
            self::Interlingue => 'Interlingue',
            self::SichuanYi => 'ꆈꌠ꒿ Nuosuhxop',
            self::Inuktitut => 'ᐃᓄᒃᑎᑐᑦ',
            self::Inupiaq => 'Iñupiaq',
            self::Irish => 'Gaeilge',
            self::Italian => 'italiano',
            self::Japanese => '日本語',
            self::Javanese => 'basa Jawa',
            self::Kannada => 'ಕನ್ನಡ',
            self::Kanuri => 'Kanuri',
            self::Kashmiri => 'कश्मीरी',
            self::Kazakh => 'қазақ тілі',
            self::Khmer => 'ភាសាខ្មែរ',
            self::Kikuyu => 'Gĩkũyũ',
            self::Kinyarwanda => 'Ikinyarwanda',
            self::Kirghiz => 'Кыргызча',
            self::Komi => 'коми кыв',
            self::Kongo => 'Kikongo',
            self::Korean => '한국어',
            self::Kuanyama => 'Kuanyama',
            self::Kurdish => 'Kurdî',
            self::Lao => 'ພາສາລາວ',
            self::Latin => 'latine',
            self::Latvian => 'latviešu valoda',
            self::Limburgish => 'Limburgs',
            self::Lingala => 'Lingála',
            self::Lithuanian => 'lietuvių kalba',
            self::LubaKatanga => 'Tshiluba',
            self::Luxembourgish => 'Lëtzebuergesch',
            self::Macedonian => 'македонски јазик',
            self::Malagasy => 'fiteny malagasy',
            self::Malay => 'Bahasa Melayu',
            self::Malayalam => 'മലയാളം',
            self::Maltese => 'Malti',
            self::Manx => 'Gaelg',
            self::Maori => 'te reo Māori',
            self::Marathi => 'मराठी',
            self::Marshallese => 'Kajin M̧ajeļ',
            self::Mongolian => 'Монгол хэл',
            self::Nauru => 'Ekakairũ Naoero',
            self::Navajo => 'Diné bizaad',
            self::NorthNdebele => 'isiNdebele',
            self::SouthNdebele => 'isiNdebele',
            self::Ndonga => 'Owambo',
            self::Nepali => 'नेपाली',
            self::Norwegian => 'Norsk',
            self::NorwegianBokmal => 'Norsk bokmål',
            self::NorwegianNynorsk => 'Norsk nynorsk',
            self::Occitan => 'occitan',
            self::Ojibwa => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
            self::Oriya => 'ଓଡ଼ିଆ',
            self::Oromo => 'Afaan Oromoo',
            self::Ossetian => 'ирон æвзаг',
            self::Pali => 'पाऴि',
            self::Pashto => 'پښتو',
            self::Persian => 'فارسی',
            self::Polish => 'język polski',
            self::Portuguese => 'português',
            self::Punjabi => 'ਪੰਜਾਬੀ',
            self::Quechua => 'Runa Simi',
            self::Romanian => 'limba română',
            self::Romansh => 'rumantsch grischun',
            self::Rundi => 'Ikirundi',
            self::Russian => 'русский язык',
            self::NorthernSami => 'Davvisámegiella',
            self::Samoan => 'gagana fa\'a Samoa',
            self::Sango => 'yângâ tî sängö',
            self::Sanskrit => 'संस्कृतम्',
            self::Sardinian => 'sardu',
            self::Serbian => 'српски језик',
            self::Sindhi => 'सिन्धी',
            self::Sinhala => 'සිංහල',
            self::Slovak => 'slovenčina',
            self::Slovenian => 'slovenščina',
            self::Somali => 'Soomaaliga',
            self::SouthernSotho => 'Sesotho',
            self::Shona => 'chiShona',
            self::Spanish => 'español',
            self::Sundanese => 'Basa Sunda',
            self::Swahili => 'Kiswahili',
            self::Swati => 'SiSwati',
            self::Swedish => 'svenska',
            self::Tagalog => 'Wikang Tagalog',
            self::Tahitian => 'Reo Tahiti',
            self::Tajik => 'тоҷикӣ',
            self::Tamil => 'தமிழ்',
            self::Tatar => 'татар теле',
            self::Telugu => 'తెలుగు',
            self::Thai => 'ไทย',
            self::Tibetan => 'བོད་ཡིག',
            self::Tigrinya => 'ትግርኛ',
            self::Tonga => 'faka Tonga',
            self::Tsonga => 'Xitsonga',
            self::Tswana => 'Setswana',
            self::Turkish => 'Türkçe',
            self::Turkmen => 'Türkmen',
            self::Twi => 'Twi',
            self::Uighur => 'ئۇيغۇرچە‎',
            self::Ukrainian => 'українська мова',
            self::Urdu => 'اردو',
            self::Uzbek => 'Oʻzbek',
            self::Venda => 'Tshivenḓa',
            self::Vietnamese => 'Tiếng Việt',
            self::Volapuk => 'Volapük',
            self::Walloon => 'walon',
            self::Welsh => 'Cymraeg',
            self::Wolof => 'Wollof',
            self::Xhosa => 'isiXhosa',
            self::Yiddish => 'ייִדיש',
            self::Yoruba => 'Yorùbá',
            self::Zhuang => 'Saɯ cueŋƅ',
            self::Zulu => 'isiZulu',
        };
    }

    public function defaultFlagCode(): ?string
    {
        return match ($this) {
            self::Danish => 'dk',
            self::English => 'gb',
            self::Azerbaijani => 'az',
            self::German => 'de',
            self::Abkhazian => 'ge',
            self::Afar => 'et',
            self::Afrikaans => 'za',
            self::Akan => 'gh',
            self::Albanian => 'al',
            self::Amharic => 'et',
            self::Arabic => 'sa',
            self::Aragonese => 'es',
            self::Armenian => 'am',
            self::Assamese => 'in',
            self::Avaric => 'ru',
            self::Aymara => 'bo',
            self::Bambara => 'ml',
            self::Bashkir => 'ru',
            self::Basque => 'es',
            self::Belarusian => 'by',
            self::Bengali => 'bd',
            self::Bihari => 'in',
            self::Bislama => 'vu',
            self::Bosnian => 'ba',
            self::Breton => 'fr',
            self::Bulgarian => 'bg',
            self::Burmese => 'mm',
            self::Catalan => 'es',
            self::Chamorro => 'gu',
            self::Chechen => 'ru',
            self::Chichewa => 'mw',
            self::Chinese => 'cn',
            self::Chuvash => 'ru',
            self::Cornish => 'gb',
            self::Corsican => 'fr',
            self::Cree => 'ca',
            self::Croatian => 'hr',
            self::Czech => 'cz',
            self::Divehi => 'mv',
            self::Dutch => 'nl',
            self::Dzongkha => 'bt',
            self::Estonian => 'ee',
            self::Ewe => 'gh',
            self::Faroese => 'fo',
            self::Fijian => 'fj',
            self::Finnish => 'fi',
            self::French => 'fr',
            self::WesternFrisian => 'nl',
            self::Fulah => 'gn',
            self::Gaelic => 'gb',
            self::Galician => 'es',
            self::Ganda => 'ug',
            self::Georgian => 'ge',
            self::Greek => 'gr',
            self::Greenlandic => 'gl',
            self::Guarani => 'py',
            self::Gujarati => 'in',
            self::Haitian => 'ht',
            self::Hausa => 'ng',
            self::Hebrew => 'il',
            self::Herero => 'na',
            self::Hindi => 'in',
            self::HiriMotu => 'pg',
            self::Hungarian => 'hu',
            self::Icelandic => 'is',
            self::Igbo => 'ng',
            self::Indonesian => 'id',
            self::SichuanYi => 'cn',
            self::Inuktitut => 'ca',
            self::Inupiaq => 'us',
            self::Irish => 'ie',
            self::Italian => 'it',
            self::Japanese => 'jp',
            self::Javanese => 'id',
            self::Kannada => 'in',
            self::Kanuri => 'ng',
            self::Kashmiri => 'in',
            self::Kazakh => 'kz',
            self::Khmer => 'kh',
            self::Kikuyu => 'ke',
            self::Kinyarwanda => 'rw',
            self::Kirghiz => 'kg',
            self::Komi => 'ru',
            self::Kongo => 'cd',
            self::Korean => 'kr',
            self::Kuanyama => 'na',
            self::Kurdish => 'iq',
            self::Lao => 'la',
            self::Latin => 'va',
            self::Latvian => 'lv',
            self::Limburgish => 'nl',
            self::Lingala => 'cd',
            self::Lithuanian => 'lt',
            self::LubaKatanga => 'cd',
            self::Luxembourgish => 'lu',
            self::Macedonian => 'mk',
            self::Malagasy => 'mg',
            self::Malay => 'my',
            self::Malayalam => 'in',
            self::Maltese => 'mt',
            self::Manx => 'im',
            self::Maori => 'nz',
            self::Marathi => 'in',
            self::Marshallese => 'mh',
            self::Mongolian => 'mn',
            self::Nauru => 'nr',
            self::Navajo => 'us',
            self::NorthNdebele => 'zw',
            self::SouthNdebele => 'za',
            self::Ndonga => 'na',
            self::Nepali => 'np',
            self::Norwegian => 'no',
            self::NorwegianBokmal => 'no',
            self::NorwegianNynorsk => 'no',
            self::Occitan => 'fr',
            self::Ojibwa => 'ca',
            self::Oriya => 'in',
            self::Oromo => 'et',
            self::Ossetian => 'ge',
            self::Pali => 'in',
            self::Pashto => 'af',
            self::Persian => 'ir',
            self::Polish => 'pl',
            self::Portuguese => 'pt',
            self::Punjabi => 'in',
            self::Quechua => 'pe',
            self::Romanian => 'ro',
            self::Romansh => 'ch',
            self::Rundi => 'bi',
            self::Russian => 'ru',
            self::NorthernSami => 'no',
            self::Samoan => 'ws',
            self::Sango => 'cf',
            self::Sanskrit => 'in',
            self::Sardinian => 'it',
            self::Serbian => 'rs',
            self::Sindhi => 'pk',
            self::Sinhala => 'lk',
            self::Slovak => 'sk',
            self::Slovenian => 'si',
            self::Somali => 'so',
            self::SouthernSotho => 'za',
            self::Shona => 'zw',
            self::Spanish => 'es',
            self::Sundanese => 'id',
            self::Swahili => 'tz',
            self::Swati => 'sz',
            self::Swedish => 'se',
            self::Tagalog => 'ph',
            self::Tahitian => 'pf',
            self::Tajik => 'tj',
            self::Tamil => 'in',
            self::Tatar => 'ru',
            self::Telugu => 'in',
            self::Thai => 'th',
            self::Tibetan => 'cn',
            self::Tigrinya => 'er',
            self::Tonga => 'to',
            self::Tsonga => 'za',
            self::Tswana => 'bw',
            self::Turkish => 'tr',
            self::Turkmen => 'tm',
            self::Twi => 'gh',
            self::Uighur => 'cn',
            self::Ukrainian => 'ua',
            self::Urdu => 'pk',
            self::Uzbek => 'uz',
            self::Venda => 'za',
            self::Vietnamese => 'vn',
            self::Walloon => 'be',
            self::Welsh => 'gb',
            self::Wolof => 'sn',
            self::Xhosa => 'za',
            self::Yiddish => 'il',
            self::Yoruba => 'ng',
            self::Zhuang => 'cn',
            self::Zulu => 'za',
            default => null,
        };
    }

    public static function fromCode(string $code): ?self
    {
        return self::tryFrom(strtolower($code));
    }
}
