// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'currencies.g.dart';
import 'languages.g.dart';
import 'continents.g.dart';
import 'flags.g.dart';
import 'i18n/countries.g.dart';
import 'i18n/capitals.g.dart';

/// Shape options for country flags
enum FlagShape {
  rectangle,
  square,
  circle,
}

/// A list of countries with their respective information
enum Country {
  afghanistan(
    alpha2Code: "AF",
    alpha3Code: "AFG",
    numericCode: 4,
    nativeName: "افغانستان",
    capital: "کابل",
    mainLanguage: Language.pashto,
    languages: [Language.pashto, Language.persian],
    tld: ".af",
    callingCode: 93,
    continent: Continent.asia,
    currency: Currency.afn,
  ),
  aalandIslands(
    alpha2Code: "AX",
    alpha3Code: "ALA",
    numericCode: 248,
    nativeName: "Åland",
    capital: "Mariehamn",
    mainLanguage: Language.swedish,
    languages: [Language.swedish],
    tld: ".ax",
    callingCode: 358,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  albania(
    alpha2Code: "AL",
    alpha3Code: "ALB",
    numericCode: 8,
    nativeName: "Shqipëria",
    capital: "Tiranë",
    mainLanguage: Language.albanian,
    languages: [Language.albanian],
    tld: ".al",
    callingCode: 355,
    continent: Continent.europe,
    currency: Currency.all,
  ),
  algeria(
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    numericCode: 12,
    nativeName: "الجزائر",
    capital: "الجزائر",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".dz",
    callingCode: 213,
    continent: Continent.africa,
    currency: Currency.dzd,
  ),
  americanSamoa(
    alpha2Code: "AS",
    alpha3Code: "ASM",
    numericCode: 16,
    nativeName: "American Samoa",
    capital: "Pago Pago",
    mainLanguage: Language.english,
    languages: [Language.english, Language.samoan],
    tld: ".as",
    callingCode: 1,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  andorra(
    alpha2Code: "AD",
    alpha3Code: "AND",
    numericCode: 20,
    nativeName: "Andorra",
    capital: "Andorra la Vella",
    mainLanguage: Language.catalan,
    languages: [Language.catalan],
    tld: ".ad",
    callingCode: 376,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  angola(
    alpha2Code: "AO",
    alpha3Code: "AGO",
    numericCode: 24,
    nativeName: "Angola",
    capital: "Luanda",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".ao",
    callingCode: 244,
    continent: Continent.africa,
    currency: Currency.aoa,
  ),
  anguilla(
    alpha2Code: "AI",
    alpha3Code: "AIA",
    numericCode: 660,
    nativeName: "Anguilla",
    capital: "The Valley",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ai",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  antarctica(
    alpha2Code: "AQ",
    alpha3Code: "ATA",
    numericCode: 10,
    nativeName: "Antarctica",
    capital: "",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".aq",
    callingCode: 672,
    continent: Continent.antarctica,
    currency: Currency.all,
  ),
  antiguaAndBarbuda(
    alpha2Code: "AG",
    alpha3Code: "ATG",
    numericCode: 28,
    nativeName: "Antigua and Barbuda",
    capital: "Saint John's",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ag",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  argentina(
    alpha2Code: "AR",
    alpha3Code: "ARG",
    numericCode: 32,
    nativeName: "Argentina",
    capital: "Buenos Aires",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".ar",
    callingCode: 54,
    continent: Continent.southAmerica,
    currency: Currency.ars,
  ),
  armenia(
    alpha2Code: "AM",
    alpha3Code: "ARM",
    numericCode: 51,
    nativeName: "Հայաստան",
    capital: "Երևան",
    mainLanguage: Language.armenian,
    languages: [Language.armenian],
    tld: ".am",
    callingCode: 374,
    continent: Continent.asia,
    currency: Currency.amd,
  ),
  aruba(
    alpha2Code: "AW",
    alpha3Code: "ABW",
    numericCode: 533,
    nativeName: "Aruba",
    capital: "Oranjestad",
    mainLanguage: Language.dutch,
    languages: [Language.dutch],
    tld: ".aw",
    callingCode: 297,
    continent: Continent.northAmerica,
    currency: Currency.awg,
  ),
  australia(
    alpha2Code: "AU",
    alpha3Code: "AUS",
    numericCode: 36,
    nativeName: "Australia",
    capital: "Canberra",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".au",
    callingCode: 61,
    continent: Continent.oceania,
    currency: Currency.aud,
  ),
  austria(
    alpha2Code: "AT",
    alpha3Code: "AUT",
    numericCode: 40,
    nativeName: "Österreich",
    capital: "Wien",
    mainLanguage: Language.german,
    languages: [Language.german],
    tld: ".at",
    callingCode: 43,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  azerbaijan(
    alpha2Code: "AZ",
    alpha3Code: "AZE",
    numericCode: 31,
    nativeName: "Azərbaycan",
    capital: "Bakı",
    mainLanguage: Language.azerbaijani,
    languages: [Language.azerbaijani],
    tld: ".az",
    callingCode: 994,
    continent: Continent.asia,
    currency: Currency.azn,
  ),
  bahamas(
    alpha2Code: "BS",
    alpha3Code: "BHS",
    numericCode: 44,
    nativeName: "Bahamas",
    capital: "Nassau",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".bs",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.bsd,
  ),
  bahrain(
    alpha2Code: "BH",
    alpha3Code: "BHR",
    numericCode: 48,
    nativeName: "البحرين",
    capital: "المنامة",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".bh",
    callingCode: 973,
    continent: Continent.asia,
    currency: Currency.bhd,
  ),
  bangladesh(
    alpha2Code: "BD",
    alpha3Code: "BGD",
    numericCode: 50,
    nativeName: "বাংলাদেশ",
    capital: "ঢাকা",
    mainLanguage: Language.bengali,
    languages: [Language.bengali],
    tld: ".bd",
    callingCode: 880,
    continent: Continent.asia,
    currency: Currency.bdt,
  ),
  barbados(
    alpha2Code: "BB",
    alpha3Code: "BRB",
    numericCode: 52,
    nativeName: "Barbados",
    capital: "Bridgetown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".bb",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.bbd,
  ),
  belarus(
    alpha2Code: "BY",
    alpha3Code: "BLR",
    numericCode: 112,
    nativeName: "Беларусь",
    capital: "Мінск",
    mainLanguage: Language.belarusian,
    languages: [Language.belarusian, Language.russian],
    tld: ".by",
    callingCode: 375,
    continent: Continent.europe,
    currency: Currency.byn,
  ),
  belgium(
    alpha2Code: "BE",
    alpha3Code: "BEL",
    numericCode: 56,
    nativeName: "België",
    capital: "Brussel",
    mainLanguage: Language.dutch,
    languages: [Language.dutch, Language.french, Language.german],
    tld: ".be",
    callingCode: 32,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  belize(
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
    numericCode: 84,
    nativeName: "Belize",
    capital: "Belmopan",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".bz",
    callingCode: 501,
    continent: Continent.northAmerica,
    currency: Currency.bzd,
  ),
  benin(
    alpha2Code: "BJ",
    alpha3Code: "BEN",
    numericCode: 204,
    nativeName: "Bénin",
    capital: "Porto-Novo",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".bj",
    callingCode: 229,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  bermuda(
    alpha2Code: "BM",
    alpha3Code: "BMU",
    numericCode: 60,
    nativeName: "Bermuda",
    capital: "Hamilton",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".bm",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.bmd,
  ),
  bhutan(
    alpha2Code: "BT",
    alpha3Code: "BTN",
    numericCode: 64,
    nativeName: "འབྲུག",
    capital: "ཐིམ་ཕུ",
    mainLanguage: Language.dzongkha,
    languages: [Language.dzongkha],
    tld: ".bt",
    callingCode: 975,
    continent: Continent.asia,
    currency: Currency.inr,
  ),
  bolivia(
    alpha2Code: "BO",
    alpha3Code: "BOL",
    numericCode: 68,
    nativeName: "Bolivia",
    capital: "Sucre",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".bo",
    callingCode: 591,
    continent: Continent.southAmerica,
    currency: Currency.bob,
  ),
  bonaireSintEustatiusAndSaba(
    alpha2Code: "BQ",
    alpha3Code: "BES",
    numericCode: 535,
    nativeName: "Bonaire, Sint Eustatius and Saba",
    capital: "Kralendijk",
    mainLanguage: Language.dutch,
    languages: [Language.dutch],
    tld: ".bq",
    callingCode: 599,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  bosniaAndHerzegovina(
    alpha2Code: "BA",
    alpha3Code: "BIH",
    numericCode: 70,
    nativeName: "Bosna i Hercegovina",
    capital: "Sarajevo",
    mainLanguage: Language.bosnian,
    languages: [Language.bosnian, Language.croatian, Language.serbian],
    tld: ".ba",
    callingCode: 387,
    continent: Continent.europe,
    currency: Currency.bam,
  ),
  botswana(
    alpha2Code: "BW",
    alpha3Code: "BWA",
    numericCode: 72,
    nativeName: "Botswana",
    capital: "Gaborone",
    mainLanguage: Language.english,
    languages: [Language.english, Language.tswana],
    tld: ".bw",
    callingCode: 267,
    continent: Continent.africa,
    currency: Currency.bwp,
  ),
  bouvetIsland(
    alpha2Code: "BV",
    alpha3Code: "BVT",
    numericCode: 74,
    nativeName: "Bouvet Island",
    capital: "",
    mainLanguage: Language.norwegian,
    languages: [Language.norwegian],
    tld: ".bv",
    callingCode: 47,
    continent: Continent.antarctica,
    currency: Currency.nok,
  ),
  brazil(
    alpha2Code: "BR",
    alpha3Code: "BRA",
    numericCode: 76,
    nativeName: "Brasil",
    capital: "Brasília",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".br",
    callingCode: 55,
    continent: Continent.southAmerica,
    currency: Currency.brl,
  ),
  britishIndianOceanTerritory(
    alpha2Code: "IO",
    alpha3Code: "IOT",
    numericCode: 86,
    nativeName: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".io",
    callingCode: 246,
    continent: Continent.asia,
    currency: Currency.usd,
  ),
  britishVirginIslands(
    alpha2Code: "VG",
    alpha3Code: "VGB",
    numericCode: 92,
    nativeName: "British Virgin Islands",
    capital: "Road Town",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".vg",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  brunei(
    alpha2Code: "BN",
    alpha3Code: "BRN",
    numericCode: 96,
    nativeName: "Brunei",
    capital: "Bandar Seri Begawan",
    mainLanguage: Language.malay,
    languages: [Language.malay],
    tld: ".bn",
    callingCode: 673,
    continent: Continent.asia,
    currency: Currency.bnd,
  ),
  bulgaria(
    alpha2Code: "BG",
    alpha3Code: "BGR",
    numericCode: 100,
    nativeName: "България",
    capital: "София",
    mainLanguage: Language.bulgarian,
    languages: [Language.bulgarian],
    tld: ".bg",
    callingCode: 359,
    continent: Continent.europe,
    currency: Currency.bgn,
  ),
  burkinaFaso(
    alpha2Code: "BF",
    alpha3Code: "BFA",
    numericCode: 854,
    nativeName: "Burkina Faso",
    capital: "Ouagadougou",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".bf",
    callingCode: 226,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  burundi(
    alpha2Code: "BI",
    alpha3Code: "BDI",
    numericCode: 108,
    nativeName: "Burundi",
    capital: "Gitega",
    mainLanguage: Language.rundi,
    languages: [Language.rundi, Language.french],
    tld: ".bi",
    callingCode: 257,
    continent: Continent.africa,
    currency: Currency.bif,
  ),
  caboVerde(
    alpha2Code: "CV",
    alpha3Code: "CPV",
    numericCode: 132,
    nativeName: "Cabo Verde",
    capital: "Praia",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".cv",
    callingCode: 238,
    continent: Continent.africa,
    currency: Currency.cve,
  ),
  cambodia(
    alpha2Code: "KH",
    alpha3Code: "KHM",
    numericCode: 116,
    nativeName: "កម្ពុជា",
    capital: "ភ្នំពេញ",
    mainLanguage: Language.khmer,
    languages: [Language.khmer],
    tld: ".kh",
    callingCode: 855,
    continent: Continent.asia,
    currency: Currency.khr,
  ),
  cameroon(
    alpha2Code: "CM",
    alpha3Code: "CMR",
    numericCode: 120,
    nativeName: "Cameroun",
    capital: "Yaoundé",
    mainLanguage: Language.french,
    languages: [Language.french, Language.english],
    tld: ".cm",
    callingCode: 237,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  canada(
    alpha2Code: "CA",
    alpha3Code: "CAN",
    numericCode: 124,
    nativeName: "Canada",
    capital: "Ottawa",
    mainLanguage: Language.english,
    languages: [Language.english, Language.french],
    tld: ".ca",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.cad,
  ),
  caymanIslands(
    alpha2Code: "KY",
    alpha3Code: "CYM",
    numericCode: 136,
    nativeName: "Cayman Islands",
    capital: "George Town",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ky",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.kyd,
  ),
  centralAfricanRepublic(
    alpha2Code: "CF",
    alpha3Code: "CAF",
    numericCode: 140,
    nativeName: "République centrafricaine",
    capital: "Bangui",
    mainLanguage: Language.french,
    languages: [Language.french, Language.sango],
    tld: ".cf",
    callingCode: 236,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  chad(
    alpha2Code: "TD",
    alpha3Code: "TCD",
    numericCode: 148,
    nativeName: "Tchad",
    capital: "N'Djamena",
    mainLanguage: Language.french,
    languages: [Language.french, Language.arabic],
    tld: ".td",
    callingCode: 235,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  chile(
    alpha2Code: "CL",
    alpha3Code: "CHL",
    numericCode: 152,
    nativeName: "Chile",
    capital: "Santiago",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".cl",
    callingCode: 56,
    continent: Continent.southAmerica,
    currency: Currency.clp,
  ),
  china(
    alpha2Code: "CN",
    alpha3Code: "CHN",
    numericCode: 156,
    nativeName: "中国",
    capital: "北京",
    mainLanguage: Language.chinese,
    languages: [Language.chinese],
    tld: ".cn",
    callingCode: 86,
    continent: Continent.asia,
    currency: Currency.cny,
  ),
  christmasIsland(
    alpha2Code: "CX",
    alpha3Code: "CXR",
    numericCode: 162,
    nativeName: "Christmas Island",
    capital: "Flying Fish Cove",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".cx",
    callingCode: 61,
    continent: Continent.asia,
    currency: Currency.aud,
  ),
  cocosKeelingIslands(
    alpha2Code: "CC",
    alpha3Code: "CCK",
    numericCode: 166,
    nativeName: "Cocos (Keeling) Islands",
    capital: "West Island",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".cc",
    callingCode: 61,
    continent: Continent.asia,
    currency: Currency.aud,
  ),
  colombia(
    alpha2Code: "CO",
    alpha3Code: "COL",
    numericCode: 170,
    nativeName: "Colombia",
    capital: "Bogotá",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".co",
    callingCode: 57,
    continent: Continent.southAmerica,
    currency: Currency.cop,
  ),
  comoros(
    alpha2Code: "KM",
    alpha3Code: "COM",
    numericCode: 174,
    nativeName: "Comores",
    capital: "Moroni",
    mainLanguage: Language.french,
    languages: [Language.french, Language.arabic],
    tld: ".km",
    callingCode: 269,
    continent: Continent.africa,
    currency: Currency.kmf,
  ),
  congo(
    alpha2Code: "CG",
    alpha3Code: "COG",
    numericCode: 178,
    nativeName: "Congo",
    capital: "Brazzaville",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".cg",
    callingCode: 242,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  congoDemocraticRepublic(
    alpha2Code: "CD",
    alpha3Code: "COD",
    numericCode: 180,
    nativeName: "Congo, Democratic Republic",
    capital: "Kinshasa",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".cd",
    callingCode: 243,
    continent: Continent.africa,
    currency: Currency.cdf,
  ),
  cookIslands(
    alpha2Code: "CK",
    alpha3Code: "COK",
    numericCode: 184,
    nativeName: "Cook Islands",
    capital: "Avarua",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ck",
    callingCode: 682,
    continent: Continent.oceania,
    currency: Currency.nzd,
  ),
  costaRica(
    alpha2Code: "CR",
    alpha3Code: "CRI",
    numericCode: 188,
    nativeName: "Costa Rica",
    capital: "San José",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".cr",
    callingCode: 506,
    continent: Continent.northAmerica,
    currency: Currency.crc,
  ),
  coteDIvoire(
    alpha2Code: "CI",
    alpha3Code: "CIV",
    numericCode: 384,
    nativeName: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".ci",
    callingCode: 225,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  croatia(
    alpha2Code: "HR",
    alpha3Code: "HRV",
    numericCode: 191,
    nativeName: "Hrvatska",
    capital: "Zagreb",
    mainLanguage: Language.croatian,
    languages: [Language.croatian],
    tld: ".hr",
    callingCode: 385,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  cuba(
    alpha2Code: "CU",
    alpha3Code: "CUB",
    numericCode: 192,
    nativeName: "Cuba",
    capital: "La Habana",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".cu",
    callingCode: 53,
    continent: Continent.northAmerica,
    currency: Currency.cup,
  ),
  curacao(
    alpha2Code: "CW",
    alpha3Code: "CUW",
    numericCode: 531,
    nativeName: "Curaçao",
    capital: "Willemstad",
    mainLanguage: Language.dutch,
    languages: [Language.dutch],
    tld: ".cw",
    callingCode: 599,
    continent: Continent.northAmerica,
    currency: Currency.ang,
  ),
  cyprus(
    alpha2Code: "CY",
    alpha3Code: "CYP",
    numericCode: 196,
    nativeName: "Κύπρος",
    capital: "Λευκωσία",
    mainLanguage: Language.greek,
    languages: [Language.greek, Language.turkish],
    tld: ".cy",
    callingCode: 357,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  czechia(
    alpha2Code: "CZ",
    alpha3Code: "CZE",
    numericCode: 203,
    nativeName: "Česko",
    capital: "Praha",
    mainLanguage: Language.czech,
    languages: [Language.czech],
    tld: ".cz",
    callingCode: 420,
    continent: Continent.europe,
    currency: Currency.czk,
  ),
  denmark(
    alpha2Code: "DK",
    alpha3Code: "DNK",
    numericCode: 208,
    nativeName: "Danmark",
    capital: "København",
    mainLanguage: Language.danish,
    languages: [Language.danish],
    tld: ".dk",
    callingCode: 45,
    continent: Continent.europe,
    currency: Currency.dkk,
  ),
  djibouti(
    alpha2Code: "DJ",
    alpha3Code: "DJI",
    numericCode: 262,
    nativeName: "Djibouti",
    capital: "Djibouti",
    mainLanguage: Language.french,
    languages: [Language.french, Language.arabic],
    tld: ".dj",
    callingCode: 253,
    continent: Continent.africa,
    currency: Currency.djf,
  ),
  dominica(
    alpha2Code: "DM",
    alpha3Code: "DMA",
    numericCode: 212,
    nativeName: "Dominica",
    capital: "Roseau",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".dm",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  dominicanRepublic(
    alpha2Code: "DO",
    alpha3Code: "DOM",
    numericCode: 214,
    nativeName: "República Dominicana",
    capital: "Santo Domingo",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".do",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.dop,
  ),
  ecuador(
    alpha2Code: "EC",
    alpha3Code: "ECU",
    numericCode: 218,
    nativeName: "Ecuador",
    capital: "Quito",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".ec",
    callingCode: 593,
    continent: Continent.southAmerica,
    currency: Currency.usd,
  ),
  egypt(
    alpha2Code: "EG",
    alpha3Code: "EGY",
    numericCode: 818,
    nativeName: "مصر",
    capital: "القاهرة",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".eg",
    callingCode: 20,
    continent: Continent.africa,
    currency: Currency.egp,
  ),
  elSalvador(
    alpha2Code: "SV",
    alpha3Code: "SLV",
    numericCode: 222,
    nativeName: "El Salvador",
    capital: "San Salvador",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".sv",
    callingCode: 503,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  equatorialGuinea(
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    numericCode: 226,
    nativeName: "Guinea Ecuatorial",
    capital: "Malabo",
    mainLanguage: Language.spanish,
    languages: [Language.spanish, Language.french, Language.portuguese],
    tld: ".gq",
    callingCode: 240,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  eritrea(
    alpha2Code: "ER",
    alpha3Code: "ERI",
    numericCode: 232,
    nativeName: "ኤርትራ",
    capital: "ኣስመራ",
    mainLanguage: Language.tigrinya,
    languages: [Language.tigrinya, Language.arabic, Language.english],
    tld: ".er",
    callingCode: 291,
    continent: Continent.africa,
    currency: Currency.ern,
  ),
  estonia(
    alpha2Code: "EE",
    alpha3Code: "EST",
    numericCode: 233,
    nativeName: "Eesti",
    capital: "Tallinn",
    mainLanguage: Language.estonian,
    languages: [Language.estonian],
    tld: ".ee",
    callingCode: 372,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  eswatini(
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
    numericCode: 748,
    nativeName: "Eswatini",
    capital: "Mbabane",
    mainLanguage: Language.swati,
    languages: [Language.swati, Language.english],
    tld: ".sz",
    callingCode: 268,
    continent: Continent.africa,
    currency: Currency.szl,
  ),
  ethiopia(
    alpha2Code: "ET",
    alpha3Code: "ETH",
    numericCode: 231,
    nativeName: "ኢትዮጵያ",
    capital: "አዲስ አበባ",
    mainLanguage: Language.amharic,
    languages: [Language.amharic],
    tld: ".et",
    callingCode: 251,
    continent: Continent.africa,
    currency: Currency.etb,
  ),
  falklandIslands(
    alpha2Code: "FK",
    alpha3Code: "FLK",
    numericCode: 238,
    nativeName: "Falkland Islands",
    capital: "Stanley",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".fk",
    callingCode: 500,
    continent: Continent.southAmerica,
    currency: Currency.fkp,
  ),
  faroeIslands(
    alpha2Code: "FO",
    alpha3Code: "FRO",
    numericCode: 234,
    nativeName: "Føroyar",
    capital: "Tórshavn",
    mainLanguage: Language.faroese,
    languages: [Language.faroese, Language.danish],
    tld: ".fo",
    callingCode: 298,
    continent: Continent.europe,
    currency: Currency.dkk,
  ),
  fiji(
    alpha2Code: "FJ",
    alpha3Code: "FJI",
    numericCode: 242,
    nativeName: "Fiji",
    capital: "Suva",
    mainLanguage: Language.english,
    languages: [Language.english, Language.fijian, Language.hindi],
    tld: ".fj",
    callingCode: 679,
    continent: Continent.oceania,
    currency: Currency.fjd,
  ),
  finland(
    alpha2Code: "FI",
    alpha3Code: "FIN",
    numericCode: 246,
    nativeName: "Suomi",
    capital: "Helsinki",
    mainLanguage: Language.finnish,
    languages: [Language.finnish, Language.swedish],
    tld: ".fi",
    callingCode: 358,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  france(
    alpha2Code: "FR",
    alpha3Code: "FRA",
    numericCode: 250,
    nativeName: "France",
    capital: "Paris",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".fr",
    callingCode: 33,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  frenchGuiana(
    alpha2Code: "GF",
    alpha3Code: "GUF",
    numericCode: 254,
    nativeName: "Guyane française",
    capital: "Cayenne",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".gf",
    callingCode: 594,
    continent: Continent.southAmerica,
    currency: Currency.eur,
  ),
  frenchPolynesia(
    alpha2Code: "PF",
    alpha3Code: "PYF",
    numericCode: 258,
    nativeName: "Polynésie française",
    capital: "Papeete",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".pf",
    callingCode: 689,
    continent: Continent.oceania,
    currency: Currency.xpf,
  ),
  frenchSouthernTerritories(
    alpha2Code: "TF",
    alpha3Code: "ATF",
    numericCode: 260,
    nativeName: "French Southern Territories",
    capital: "Port-aux-Français",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".tf",
    callingCode: 262,
    continent: Continent.antarctica,
    currency: Currency.eur,
  ),
  gabon(
    alpha2Code: "GA",
    alpha3Code: "GAB",
    numericCode: 266,
    nativeName: "Gabon",
    capital: "Libreville",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".ga",
    callingCode: 241,
    continent: Continent.africa,
    currency: Currency.xaf,
  ),
  gambia(
    alpha2Code: "GM",
    alpha3Code: "GMB",
    numericCode: 270,
    nativeName: "Gambia",
    capital: "Banjul",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gm",
    callingCode: 220,
    continent: Continent.africa,
    currency: Currency.gmd,
  ),
  georgia(
    alpha2Code: "GE",
    alpha3Code: "GEO",
    numericCode: 268,
    nativeName: "საქართველო",
    capital: "თბილისი",
    mainLanguage: Language.georgian,
    languages: [Language.georgian],
    tld: ".ge",
    callingCode: 995,
    continent: Continent.asia,
    currency: Currency.gel,
  ),
  germany(
    alpha2Code: "DE",
    alpha3Code: "DEU",
    numericCode: 276,
    nativeName: "Deutschland",
    capital: "Berlin",
    mainLanguage: Language.german,
    languages: [Language.german],
    tld: ".de",
    callingCode: 49,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  ghana(
    alpha2Code: "GH",
    alpha3Code: "GHA",
    numericCode: 288,
    nativeName: "Ghana",
    capital: "Accra",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gh",
    callingCode: 233,
    continent: Continent.africa,
    currency: Currency.ghs,
  ),
  gibraltar(
    alpha2Code: "GI",
    alpha3Code: "GIB",
    numericCode: 292,
    nativeName: "Gibraltar",
    capital: "Gibraltar",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gi",
    callingCode: 350,
    continent: Continent.europe,
    currency: Currency.gip,
  ),
  greece(
    alpha2Code: "GR",
    alpha3Code: "GRC",
    numericCode: 300,
    nativeName: "Ελλάδα",
    capital: "Αθήνα",
    mainLanguage: Language.greek,
    languages: [Language.greek],
    tld: ".gr",
    callingCode: 30,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  grenada(
    alpha2Code: "GD",
    alpha3Code: "GRD",
    numericCode: 308,
    nativeName: "Grenada",
    capital: "St. George's",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gd",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  guadeloupe(
    alpha2Code: "GP",
    alpha3Code: "GLP",
    numericCode: 312,
    nativeName: "Guadeloupe",
    capital: "Basse-Terre",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".gp",
    callingCode: 590,
    continent: Continent.northAmerica,
    currency: Currency.eur,
  ),
  guam(
    alpha2Code: "GU",
    alpha3Code: "GUM",
    numericCode: 316,
    nativeName: "Guam",
    capital: "Hagåtña",
    mainLanguage: Language.english,
    languages: [Language.english, Language.chamorro],
    tld: ".gu",
    callingCode: 1,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  guatemala(
    alpha2Code: "GT",
    alpha3Code: "GTM",
    numericCode: 320,
    nativeName: "Guatemala",
    capital: "Ciudad de Guatemala",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".gt",
    callingCode: 502,
    continent: Continent.northAmerica,
    currency: Currency.gtq,
  ),
  guernsey(
    alpha2Code: "GG",
    alpha3Code: "GGY",
    numericCode: 831,
    nativeName: "Guernsey",
    capital: "St Peter Port",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gg",
    callingCode: 44,
    continent: Continent.europe,
    currency: Currency.gbp,
  ),
  guinea(
    alpha2Code: "GN",
    alpha3Code: "GIN",
    numericCode: 324,
    nativeName: "Guinée",
    capital: "Conakry",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".gn",
    callingCode: 224,
    continent: Continent.africa,
    currency: Currency.gnf,
  ),
  guineaBissau(
    alpha2Code: "GW",
    alpha3Code: "GNB",
    numericCode: 624,
    nativeName: "Guiné-Bissau",
    capital: "Bissau",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".gw",
    callingCode: 245,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  guyana(
    alpha2Code: "GY",
    alpha3Code: "GUY",
    numericCode: 328,
    nativeName: "Guyana",
    capital: "Georgetown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gy",
    callingCode: 592,
    continent: Continent.southAmerica,
    currency: Currency.gyd,
  ),
  haiti(
    alpha2Code: "HT",
    alpha3Code: "HTI",
    numericCode: 332,
    nativeName: "Haïti",
    capital: "Port-au-Prince",
    mainLanguage: Language.french,
    languages: [Language.french, Language.haitian],
    tld: ".ht",
    callingCode: 509,
    continent: Continent.northAmerica,
    currency: Currency.htg,
  ),
  heardIslandAndMcDonaldIslands(
    alpha2Code: "HM",
    alpha3Code: "HMD",
    numericCode: 334,
    nativeName: "Heard Island and McDonald Islands",
    capital: "",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".hm",
    callingCode: 672,
    continent: Continent.antarctica,
    currency: Currency.usd,
  ),
  honduras(
    alpha2Code: "HN",
    alpha3Code: "HND",
    numericCode: 340,
    nativeName: "Honduras",
    capital: "Tegucigalpa",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".hn",
    callingCode: 504,
    continent: Continent.northAmerica,
    currency: Currency.hnl,
  ),
  hongKong(
    alpha2Code: "HK",
    alpha3Code: "HKG",
    numericCode: 344,
    nativeName: "香港",
    capital: "香港",
    mainLanguage: Language.chinese,
    languages: [Language.chinese, Language.english],
    tld: ".hk",
    callingCode: 852,
    continent: Continent.asia,
    currency: Currency.hkd,
  ),
  hungary(
    alpha2Code: "HU",
    alpha3Code: "HUN",
    numericCode: 348,
    nativeName: "Magyarország",
    capital: "Budapest",
    mainLanguage: Language.hungarian,
    languages: [Language.hungarian],
    tld: ".hu",
    callingCode: 36,
    continent: Continent.europe,
    currency: Currency.huf,
  ),
  iceland(
    alpha2Code: "IS",
    alpha3Code: "ISL",
    numericCode: 352,
    nativeName: "Ísland",
    capital: "Reykjavík",
    mainLanguage: Language.icelandic,
    languages: [Language.icelandic],
    tld: ".is",
    callingCode: 354,
    continent: Continent.europe,
    currency: Currency.isk,
  ),
  india(
    alpha2Code: "IN",
    alpha3Code: "IND",
    numericCode: 356,
    nativeName: "भारत",
    capital: "नई दिल्ली",
    mainLanguage: Language.hindi,
    languages: [Language.hindi, Language.english],
    tld: ".in",
    callingCode: 91,
    continent: Continent.asia,
    currency: Currency.inr,
  ),
  indonesia(
    alpha2Code: "ID",
    alpha3Code: "IDN",
    numericCode: 360,
    nativeName: "Indonesia",
    capital: "Jakarta",
    mainLanguage: Language.indonesian,
    languages: [Language.indonesian],
    tld: ".id",
    callingCode: 62,
    continent: Continent.asia,
    currency: Currency.idr,
  ),
  iran(
    alpha2Code: "IR",
    alpha3Code: "IRN",
    numericCode: 364,
    nativeName: "ایران",
    capital: "تهران",
    mainLanguage: Language.persian,
    languages: [Language.persian],
    tld: ".ir",
    callingCode: 98,
    continent: Continent.asia,
    currency: Currency.irr,
  ),
  iraq(
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
    numericCode: 368,
    nativeName: "العراق",
    capital: "بغداد",
    mainLanguage: Language.arabic,
    languages: [Language.arabic, Language.kurdish],
    tld: ".iq",
    callingCode: 964,
    continent: Continent.asia,
    currency: Currency.iqd,
  ),
  ireland(
    alpha2Code: "IE",
    alpha3Code: "IRL",
    numericCode: 372,
    nativeName: "Éire",
    capital: "Baile Átha Cliath",
    mainLanguage: Language.english,
    languages: [Language.english, Language.irish],
    tld: ".ie",
    callingCode: 353,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  isleOfMan(
    alpha2Code: "IM",
    alpha3Code: "IMN",
    numericCode: 833,
    nativeName: "Isle of Man",
    capital: "Douglas",
    mainLanguage: Language.english,
    languages: [Language.english, Language.manx],
    tld: ".im",
    callingCode: 44,
    continent: Continent.europe,
    currency: Currency.gbp,
  ),
  israel(
    alpha2Code: "IL",
    alpha3Code: "ISR",
    numericCode: 376,
    nativeName: "ישראל",
    capital: "ירושלים",
    mainLanguage: Language.hebrew,
    languages: [Language.hebrew, Language.arabic],
    tld: ".il",
    callingCode: 972,
    continent: Continent.asia,
    currency: Currency.ils,
  ),
  italy(
    alpha2Code: "IT",
    alpha3Code: "ITA",
    numericCode: 380,
    nativeName: "Italia",
    capital: "Roma",
    mainLanguage: Language.italian,
    languages: [Language.italian],
    tld: ".it",
    callingCode: 39,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  jamaica(
    alpha2Code: "JM",
    alpha3Code: "JAM",
    numericCode: 388,
    nativeName: "Jamaica",
    capital: "Kingston",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".jm",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.jmd,
  ),
  japan(
    alpha2Code: "JP",
    alpha3Code: "JPN",
    numericCode: 392,
    nativeName: "日本",
    capital: "東京",
    mainLanguage: Language.japanese,
    languages: [Language.japanese],
    tld: ".jp",
    callingCode: 81,
    continent: Continent.asia,
    currency: Currency.jpy,
  ),
  jersey(
    alpha2Code: "JE",
    alpha3Code: "JEY",
    numericCode: 832,
    nativeName: "Jersey",
    capital: "Saint Helier",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".je",
    callingCode: 44,
    continent: Continent.europe,
    currency: Currency.gbp,
  ),
  jordan(
    alpha2Code: "JO",
    alpha3Code: "JOR",
    numericCode: 400,
    nativeName: "الأردن",
    capital: "عمّان",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".jo",
    callingCode: 962,
    continent: Continent.asia,
    currency: Currency.jod,
  ),
  kazakhstan(
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
    numericCode: 398,
    nativeName: "Қазақстан",
    capital: "Астана",
    mainLanguage: Language.kazakh,
    languages: [Language.kazakh, Language.russian],
    tld: ".kz",
    callingCode: 7,
    continent: Continent.asia,
    currency: Currency.kzt,
  ),
  kenya(
    alpha2Code: "KE",
    alpha3Code: "KEN",
    numericCode: 404,
    nativeName: "Kenya",
    capital: "Nairobi",
    mainLanguage: Language.swahili,
    languages: [Language.swahili, Language.english],
    tld: ".ke",
    callingCode: 254,
    continent: Continent.africa,
    currency: Currency.kes,
  ),
  kiribati(
    alpha2Code: "KI",
    alpha3Code: "KIR",
    numericCode: 296,
    nativeName: "Kiribati",
    capital: "Tarawa",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ki",
    callingCode: 686,
    continent: Continent.oceania,
    currency: Currency.aud,
  ),
  kuwait(
    alpha2Code: "KW",
    alpha3Code: "KWT",
    numericCode: 414,
    nativeName: "الكويت",
    capital: "مدينة الكويت",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".kw",
    callingCode: 965,
    continent: Continent.asia,
    currency: Currency.kwd,
  ),
  kyrgyzstan(
    alpha2Code: "KG",
    alpha3Code: "KGZ",
    numericCode: 417,
    nativeName: "Кыргызстан",
    capital: "Бишкек",
    mainLanguage: Language.kirghiz,
    languages: [Language.kirghiz, Language.russian],
    tld: ".kg",
    callingCode: 996,
    continent: Continent.asia,
    currency: Currency.kgs,
  ),
  laos(
    alpha2Code: "LA",
    alpha3Code: "LAO",
    numericCode: 418,
    nativeName: "ສປປລາວ",
    capital: "ວຽງຈັນ",
    mainLanguage: Language.lao,
    languages: [Language.lao],
    tld: ".la",
    callingCode: 856,
    continent: Continent.asia,
    currency: Currency.lak,
  ),
  latvia(
    alpha2Code: "LV",
    alpha3Code: "LVA",
    numericCode: 428,
    nativeName: "Latvija",
    capital: "Rīga",
    mainLanguage: Language.latvian,
    languages: [Language.latvian],
    tld: ".lv",
    callingCode: 371,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  lebanon(
    alpha2Code: "LB",
    alpha3Code: "LBN",
    numericCode: 422,
    nativeName: "لبنان",
    capital: "بيروت",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".lb",
    callingCode: 961,
    continent: Continent.asia,
    currency: Currency.lbp,
  ),
  lesotho(
    alpha2Code: "LS",
    alpha3Code: "LSO",
    numericCode: 426,
    nativeName: "Lesotho",
    capital: "Maseru",
    mainLanguage: Language.english,
    languages: [Language.english, Language.southernSotho],
    tld: ".ls",
    callingCode: 266,
    continent: Continent.africa,
    currency: Currency.lsl,
  ),
  liberia(
    alpha2Code: "LR",
    alpha3Code: "LBR",
    numericCode: 430,
    nativeName: "Liberia",
    capital: "Monrovia",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".lr",
    callingCode: 231,
    continent: Continent.africa,
    currency: Currency.lrd,
  ),
  libya(
    alpha2Code: "LY",
    alpha3Code: "LBY",
    numericCode: 434,
    nativeName: "ليبيا",
    capital: "طرابلس",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".ly",
    callingCode: 218,
    continent: Continent.africa,
    currency: Currency.lyd,
  ),
  liechtenstein(
    alpha2Code: "LI",
    alpha3Code: "LIE",
    numericCode: 438,
    nativeName: "Liechtenstein",
    capital: "Vaduz",
    mainLanguage: Language.german,
    languages: [Language.german],
    tld: ".li",
    callingCode: 423,
    continent: Continent.europe,
    currency: Currency.chf,
  ),
  lithuania(
    alpha2Code: "LT",
    alpha3Code: "LTU",
    numericCode: 440,
    nativeName: "Lietuva",
    capital: "Vilnius",
    mainLanguage: Language.lithuanian,
    languages: [Language.lithuanian],
    tld: ".lt",
    callingCode: 370,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  luxembourg(
    alpha2Code: "LU",
    alpha3Code: "LUX",
    numericCode: 442,
    nativeName: "Luxembourg",
    capital: "Luxembourg",
    mainLanguage: Language.luxembourgish,
    languages: [Language.luxembourgish, Language.french, Language.german],
    tld: ".lu",
    callingCode: 352,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  macao(
    alpha2Code: "MO",
    alpha3Code: "MAC",
    numericCode: 446,
    nativeName: "澳門",
    capital: "澳門",
    mainLanguage: Language.chinese,
    languages: [Language.chinese, Language.portuguese],
    tld: ".mo",
    callingCode: 853,
    continent: Continent.asia,
    currency: Currency.mop,
  ),
  madagascar(
    alpha2Code: "MG",
    alpha3Code: "MDG",
    numericCode: 450,
    nativeName: "Madagasikara",
    capital: "Antananarivo",
    mainLanguage: Language.malagasy,
    languages: [Language.malagasy, Language.french],
    tld: ".mg",
    callingCode: 261,
    continent: Continent.africa,
    currency: Currency.mga,
  ),
  malawi(
    alpha2Code: "MW",
    alpha3Code: "MWI",
    numericCode: 454,
    nativeName: "Malawi",
    capital: "Lilongwe",
    mainLanguage: Language.english,
    languages: [Language.english, Language.chichewa],
    tld: ".mw",
    callingCode: 265,
    continent: Continent.africa,
    currency: Currency.mwk,
  ),
  malaysia(
    alpha2Code: "MY",
    alpha3Code: "MYS",
    numericCode: 458,
    nativeName: "Malaysia",
    capital: "Kuala Lumpur",
    mainLanguage: Language.malay,
    languages: [Language.malay],
    tld: ".my",
    callingCode: 60,
    continent: Continent.asia,
    currency: Currency.myr,
  ),
  maldives(
    alpha2Code: "MV",
    alpha3Code: "MDV",
    numericCode: 462,
    nativeName: "ދިވެހިރާއްޖެ",
    capital: "މާލެ",
    mainLanguage: Language.divehi,
    languages: [Language.divehi],
    tld: ".mv",
    callingCode: 960,
    continent: Continent.asia,
    currency: Currency.mvr,
  ),
  mali(
    alpha2Code: "ML",
    alpha3Code: "MLI",
    numericCode: 466,
    nativeName: "Mali",
    capital: "Bamako",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".ml",
    callingCode: 223,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  malta(
    alpha2Code: "MT",
    alpha3Code: "MLT",
    numericCode: 470,
    nativeName: "Malta",
    capital: "Il-Belt Valletta",
    mainLanguage: Language.maltese,
    languages: [Language.maltese, Language.english],
    tld: ".mt",
    callingCode: 356,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  marshallIslands(
    alpha2Code: "MH",
    alpha3Code: "MHL",
    numericCode: 584,
    nativeName: "Marshall Islands",
    capital: "Majuro",
    mainLanguage: Language.english,
    languages: [Language.english, Language.marshallese],
    tld: ".mh",
    callingCode: 692,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  martinique(
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
    numericCode: 474,
    nativeName: "Martinique",
    capital: "Fort-de-France",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".mq",
    callingCode: 596,
    continent: Continent.northAmerica,
    currency: Currency.eur,
  ),
  mauritania(
    alpha2Code: "MR",
    alpha3Code: "MRT",
    numericCode: 478,
    nativeName: "موريتانيا",
    capital: "نواكشوط",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".mr",
    callingCode: 222,
    continent: Continent.africa,
    currency: Currency.mru,
  ),
  mauritius(
    alpha2Code: "MU",
    alpha3Code: "MUS",
    numericCode: 480,
    nativeName: "Maurice",
    capital: "Port Louis",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".mu",
    callingCode: 230,
    continent: Continent.africa,
    currency: Currency.mur,
  ),
  mayotte(
    alpha2Code: "YT",
    alpha3Code: "MYT",
    numericCode: 175,
    nativeName: "Mayotte",
    capital: "Mamoudzou",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".yt",
    callingCode: 262,
    continent: Continent.africa,
    currency: Currency.eur,
  ),
  mexico(
    alpha2Code: "MX",
    alpha3Code: "MEX",
    numericCode: 484,
    nativeName: "México",
    capital: "Ciudad de México",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".mx",
    callingCode: 52,
    continent: Continent.northAmerica,
    currency: Currency.mxn,
  ),
  micronesia(
    alpha2Code: "FM",
    alpha3Code: "FSM",
    numericCode: 583,
    nativeName: "Micronesia",
    capital: "Palikir",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".fm",
    callingCode: 691,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  moldova(
    alpha2Code: "MD",
    alpha3Code: "MDA",
    numericCode: 498,
    nativeName: "Moldova",
    capital: "Chișinău",
    mainLanguage: Language.romanian,
    languages: [Language.romanian],
    tld: ".md",
    callingCode: 373,
    continent: Continent.europe,
    currency: Currency.mdl,
  ),
  monaco(
    alpha2Code: "MC",
    alpha3Code: "MCO",
    numericCode: 492,
    nativeName: "Monaco",
    capital: "Monaco",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".mc",
    callingCode: 377,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  mongolia(
    alpha2Code: "MN",
    alpha3Code: "MNG",
    numericCode: 496,
    nativeName: "Монгол улс",
    capital: "Улаанбаатар",
    mainLanguage: Language.mongolian,
    languages: [Language.mongolian],
    tld: ".mn",
    callingCode: 976,
    continent: Continent.asia,
    currency: Currency.mnt,
  ),
  montenegro(
    alpha2Code: "ME",
    alpha3Code: "MNE",
    numericCode: 499,
    nativeName: "Црна Гора",
    capital: "Podgorica",
    mainLanguage: Language.serbian,
    languages: [Language.serbian],
    tld: ".me",
    callingCode: 382,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  montserrat(
    alpha2Code: "MS",
    alpha3Code: "MSR",
    numericCode: 500,
    nativeName: "Montserrat",
    capital: "Plymouth",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ms",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  morocco(
    alpha2Code: "MA",
    alpha3Code: "MAR",
    numericCode: 504,
    nativeName: "المغرب",
    capital: "الرباط",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".ma",
    callingCode: 212,
    continent: Continent.africa,
    currency: Currency.mad,
  ),
  mozambique(
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
    numericCode: 508,
    nativeName: "Moçambique",
    capital: "Maputo",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".mz",
    callingCode: 258,
    continent: Continent.africa,
    currency: Currency.mzn,
  ),
  myanmar(
    alpha2Code: "MM",
    alpha3Code: "MMR",
    numericCode: 104,
    nativeName: "မြန်မာ",
    capital: "နေပြည်တော်",
    mainLanguage: Language.burmese,
    languages: [Language.burmese],
    tld: ".mm",
    callingCode: 95,
    continent: Continent.asia,
    currency: Currency.mmk,
  ),
  namibia(
    alpha2Code: "NA",
    alpha3Code: "NAM",
    numericCode: 516,
    nativeName: "Namibia",
    capital: "Windhoek",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".na",
    callingCode: 264,
    continent: Continent.africa,
    currency: Currency.nad,
  ),
  nauru(
    alpha2Code: "NR",
    alpha3Code: "NRU",
    numericCode: 520,
    nativeName: "Nauru",
    capital: "Yaren",
    mainLanguage: Language.nauru,
    languages: [Language.nauru, Language.english],
    tld: ".nr",
    callingCode: 674,
    continent: Continent.oceania,
    currency: Currency.aud,
  ),
  nepal(
    alpha2Code: "NP",
    alpha3Code: "NPL",
    numericCode: 524,
    nativeName: "नेपाल",
    capital: "काठमाडौं",
    mainLanguage: Language.nepali,
    languages: [Language.nepali],
    tld: ".np",
    callingCode: 977,
    continent: Continent.asia,
    currency: Currency.npr,
  ),
  netherlands(
    alpha2Code: "NL",
    alpha3Code: "NLD",
    numericCode: 528,
    nativeName: "Nederland",
    capital: "Amsterdam",
    mainLanguage: Language.dutch,
    languages: [Language.dutch],
    tld: ".nl",
    callingCode: 31,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  newCaledonia(
    alpha2Code: "NC",
    alpha3Code: "NCL",
    numericCode: 540,
    nativeName: "Nouvelle-Calédonie",
    capital: "Nouméa",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".nc",
    callingCode: 687,
    continent: Continent.oceania,
    currency: Currency.xpf,
  ),
  newZealand(
    alpha2Code: "NZ",
    alpha3Code: "NZL",
    numericCode: 554,
    nativeName: "New Zealand",
    capital: "Wellington",
    mainLanguage: Language.english,
    languages: [Language.english, Language.maori],
    tld: ".nz",
    callingCode: 64,
    continent: Continent.oceania,
    currency: Currency.nzd,
  ),
  nicaragua(
    alpha2Code: "NI",
    alpha3Code: "NIC",
    numericCode: 558,
    nativeName: "Nicaragua",
    capital: "Managua",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".ni",
    callingCode: 505,
    continent: Continent.northAmerica,
    currency: Currency.nio,
  ),
  niger(
    alpha2Code: "NE",
    alpha3Code: "NER",
    numericCode: 562,
    nativeName: "Niger",
    capital: "Niamey",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".ne",
    callingCode: 227,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  nigeria(
    alpha2Code: "NG",
    alpha3Code: "NGA",
    numericCode: 566,
    nativeName: "Nigeria",
    capital: "Abuja",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ng",
    callingCode: 234,
    continent: Continent.africa,
    currency: Currency.ngn,
  ),
  niue(
    alpha2Code: "NU",
    alpha3Code: "NIU",
    numericCode: 570,
    nativeName: "Niue",
    capital: "Alofi",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".nu",
    callingCode: 683,
    continent: Continent.oceania,
    currency: Currency.nzd,
  ),
  norfolkIsland(
    alpha2Code: "NF",
    alpha3Code: "NFK",
    numericCode: 574,
    nativeName: "Norfolk Island",
    capital: "Kingston",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".nf",
    callingCode: 672,
    continent: Continent.oceania,
    currency: Currency.aud,
  ),
  northKorea(
    alpha2Code: "KP",
    alpha3Code: "PRK",
    numericCode: 408,
    nativeName: "조선민주주의인민공화국",
    capital: "평양",
    mainLanguage: Language.korean,
    languages: [Language.korean],
    tld: ".kp",
    callingCode: 850,
    continent: Continent.asia,
    currency: Currency.kpw,
  ),
  northMacedonia(
    alpha2Code: "MK",
    alpha3Code: "MKD",
    numericCode: 807,
    nativeName: "Северна Македонија",
    capital: "Скопје",
    mainLanguage: Language.macedonian,
    languages: [Language.macedonian],
    tld: ".mk",
    callingCode: 389,
    continent: Continent.europe,
    currency: Currency.mkd,
  ),
  northernMarianaIslands(
    alpha2Code: "MP",
    alpha3Code: "MNP",
    numericCode: 580,
    nativeName: "Northern Mariana Islands",
    capital: "Saipan",
    mainLanguage: Language.english,
    languages: [Language.english, Language.chamorro],
    tld: ".mp",
    callingCode: 1,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  norway(
    alpha2Code: "NO",
    alpha3Code: "NOR",
    numericCode: 578,
    nativeName: "Norge",
    capital: "Oslo",
    mainLanguage: Language.norwegian,
    languages: [Language.norwegian],
    tld: ".no",
    callingCode: 47,
    continent: Continent.europe,
    currency: Currency.nok,
  ),
  oman(
    alpha2Code: "OM",
    alpha3Code: "OMN",
    numericCode: 512,
    nativeName: "عمان",
    capital: "مسقط",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".om",
    callingCode: 968,
    continent: Continent.asia,
    currency: Currency.omr,
  ),
  pakistan(
    alpha2Code: "PK",
    alpha3Code: "PAK",
    numericCode: 586,
    nativeName: "پاکستان",
    capital: "اسلام آباد",
    mainLanguage: Language.urdu,
    languages: [Language.urdu, Language.english],
    tld: ".pk",
    callingCode: 92,
    continent: Continent.asia,
    currency: Currency.pkr,
  ),
  palau(
    alpha2Code: "PW",
    alpha3Code: "PLW",
    numericCode: 585,
    nativeName: "Palau",
    capital: "Ngerulmud",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".pw",
    callingCode: 680,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  palestine(
    alpha2Code: "PS",
    alpha3Code: "PSE",
    numericCode: 275,
    nativeName: "فلسطين",
    capital: "رام الله",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".ps",
    callingCode: 970,
    continent: Continent.asia,
    currency: Currency.ils,
  ),
  panama(
    alpha2Code: "PA",
    alpha3Code: "PAN",
    numericCode: 591,
    nativeName: "Panamá",
    capital: "Ciudad de Panamá",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".pa",
    callingCode: 507,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  papuaNewGuinea(
    alpha2Code: "PG",
    alpha3Code: "PNG",
    numericCode: 598,
    nativeName: "Papua New Guinea",
    capital: "Port Moresby",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".pg",
    callingCode: 675,
    continent: Continent.oceania,
    currency: Currency.pgk,
  ),
  paraguay(
    alpha2Code: "PY",
    alpha3Code: "PRY",
    numericCode: 600,
    nativeName: "Paraguay",
    capital: "Asunción",
    mainLanguage: Language.spanish,
    languages: [Language.spanish, Language.guarani],
    tld: ".py",
    callingCode: 595,
    continent: Continent.southAmerica,
    currency: Currency.pyg,
  ),
  peru(
    alpha2Code: "PE",
    alpha3Code: "PER",
    numericCode: 604,
    nativeName: "Perú",
    capital: "Lima",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".pe",
    callingCode: 51,
    continent: Continent.southAmerica,
    currency: Currency.pen,
  ),
  philippines(
    alpha2Code: "PH",
    alpha3Code: "PHL",
    numericCode: 608,
    nativeName: "Pilipinas",
    capital: "Manila",
    mainLanguage: Language.tagalog,
    languages: [Language.tagalog, Language.english],
    tld: ".ph",
    callingCode: 63,
    continent: Continent.asia,
    currency: Currency.php,
  ),
  pitcairn(
    alpha2Code: "PN",
    alpha3Code: "PCN",
    numericCode: 612,
    nativeName: "Pitcairn Islands",
    capital: "Adamstown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".pn",
    callingCode: 64,
    continent: Continent.oceania,
    currency: Currency.nzd,
  ),
  poland(
    alpha2Code: "PL",
    alpha3Code: "POL",
    numericCode: 616,
    nativeName: "Polska",
    capital: "Warszawa",
    mainLanguage: Language.polish,
    languages: [Language.polish],
    tld: ".pl",
    callingCode: 48,
    continent: Continent.europe,
    currency: Currency.pln,
  ),
  portugal(
    alpha2Code: "PT",
    alpha3Code: "PRT",
    numericCode: 620,
    nativeName: "Portugal",
    capital: "Lisboa",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".pt",
    callingCode: 351,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  puertoRico(
    alpha2Code: "PR",
    alpha3Code: "PRI",
    numericCode: 630,
    nativeName: "Puerto Rico",
    capital: "San Juan",
    mainLanguage: Language.spanish,
    languages: [Language.spanish, Language.english],
    tld: ".pr",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  qatar(
    alpha2Code: "QA",
    alpha3Code: "QAT",
    numericCode: 634,
    nativeName: "قطر",
    capital: "الدوحة",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".qa",
    callingCode: 974,
    continent: Continent.asia,
    currency: Currency.qar,
  ),
  reunion(
    alpha2Code: "RE",
    alpha3Code: "REU",
    numericCode: 638,
    nativeName: "Réunion",
    capital: "Saint-Denis",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".re",
    callingCode: 262,
    continent: Continent.africa,
    currency: Currency.eur,
  ),
  romania(
    alpha2Code: "RO",
    alpha3Code: "ROU",
    numericCode: 642,
    nativeName: "România",
    capital: "București",
    mainLanguage: Language.romanian,
    languages: [Language.romanian],
    tld: ".ro",
    callingCode: 40,
    continent: Continent.europe,
    currency: Currency.ron,
  ),
  russia(
    alpha2Code: "RU",
    alpha3Code: "RUS",
    numericCode: 643,
    nativeName: "Россия",
    capital: "Москва",
    mainLanguage: Language.russian,
    languages: [Language.russian],
    tld: ".ru",
    callingCode: 7,
    continent: Continent.europe,
    currency: Currency.rub,
  ),
  rwanda(
    alpha2Code: "RW",
    alpha3Code: "RWA",
    numericCode: 646,
    nativeName: "Rwanda",
    capital: "Kigali",
    mainLanguage: Language.kinyarwanda,
    languages: [Language.kinyarwanda, Language.french, Language.english],
    tld: ".rw",
    callingCode: 250,
    continent: Continent.africa,
    currency: Currency.rwf,
  ),
  saintBarthelemy(
    alpha2Code: "BL",
    alpha3Code: "BLM",
    numericCode: 652,
    nativeName: "Saint-Barthélemy",
    capital: "Gustavia",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".bl",
    callingCode: 590,
    continent: Continent.northAmerica,
    currency: Currency.eur,
  ),
  saintHelena(
    alpha2Code: "SH",
    alpha3Code: "SHN",
    numericCode: 654,
    nativeName: "Saint Helena",
    capital: "Jamestown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".sh",
    callingCode: 290,
    continent: Continent.africa,
    currency: Currency.svc,
  ),
  saintKittsAndNevis(
    alpha2Code: "KN",
    alpha3Code: "KNA",
    numericCode: 659,
    nativeName: "Saint Kitts and Nevis",
    capital: "Basseterre",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".kn",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  saintLucia(
    alpha2Code: "LC",
    alpha3Code: "LCA",
    numericCode: 662,
    nativeName: "Saint Lucia",
    capital: "Castries",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".lc",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  saintMartin(
    alpha2Code: "MF",
    alpha3Code: "MAF",
    numericCode: 663,
    nativeName: "Saint-Martin",
    capital: "Marigot",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".mf",
    callingCode: 590,
    continent: Continent.northAmerica,
    currency: Currency.eur,
  ),
  saintPierreAndMiquelon(
    alpha2Code: "PM",
    alpha3Code: "SPM",
    numericCode: 666,
    nativeName: "Saint-Pierre-et-Miquelon",
    capital: "Saint-Pierre",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".pm",
    callingCode: 508,
    continent: Continent.northAmerica,
    currency: Currency.eur,
  ),
  saintVincentAndTheGrenadines(
    alpha2Code: "VC",
    alpha3Code: "VCT",
    numericCode: 670,
    nativeName: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".vc",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.xcd,
  ),
  samoa(
    alpha2Code: "WS",
    alpha3Code: "WSM",
    numericCode: 882,
    nativeName: "Samoa",
    capital: "Apia",
    mainLanguage: Language.samoan,
    languages: [Language.samoan, Language.english],
    tld: ".ws",
    callingCode: 685,
    continent: Continent.oceania,
    currency: Currency.wst,
  ),
  sanMarino(
    alpha2Code: "SM",
    alpha3Code: "SMR",
    numericCode: 674,
    nativeName: "San Marino",
    capital: "San Marino",
    mainLanguage: Language.italian,
    languages: [Language.italian],
    tld: ".sm",
    callingCode: 378,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  saoTomeAndPrincipe(
    alpha2Code: "ST",
    alpha3Code: "STP",
    numericCode: 678,
    nativeName: "São Tomé e Príncipe",
    capital: "São Tomé",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".st",
    callingCode: 239,
    continent: Continent.africa,
    currency: Currency.stn,
  ),
  saudiArabia(
    alpha2Code: "SA",
    alpha3Code: "SAU",
    numericCode: 682,
    nativeName: "العربية السعودية",
    capital: "الرياض",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".sa",
    callingCode: 966,
    continent: Continent.asia,
    currency: Currency.sar,
  ),
  senegal(
    alpha2Code: "SN",
    alpha3Code: "SEN",
    numericCode: 686,
    nativeName: "Sénégal",
    capital: "Dakar",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".sn",
    callingCode: 221,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  serbia(
    alpha2Code: "RS",
    alpha3Code: "SRB",
    numericCode: 688,
    nativeName: "Србија",
    capital: "Београд",
    mainLanguage: Language.serbian,
    languages: [Language.serbian],
    tld: ".rs",
    callingCode: 381,
    continent: Continent.europe,
    currency: Currency.rsd,
  ),
  seychelles(
    alpha2Code: "SC",
    alpha3Code: "SYC",
    numericCode: 690,
    nativeName: "Seychelles",
    capital: "Victoria",
    mainLanguage: Language.french,
    languages: [Language.french, Language.english],
    tld: ".sc",
    callingCode: 248,
    continent: Continent.africa,
    currency: Currency.scr,
  ),
  sierraLeone(
    alpha2Code: "SL",
    alpha3Code: "SLE",
    numericCode: 694,
    nativeName: "Sierra Leone",
    capital: "Freetown",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".sl",
    callingCode: 232,
    continent: Continent.africa,
    currency: Currency.sle,
  ),
  singapore(
    alpha2Code: "SG",
    alpha3Code: "SGP",
    numericCode: 702,
    nativeName: "Singapore",
    capital: "Singapore",
    mainLanguage: Language.english,
    languages: [Language.english, Language.malay, Language.tamil, Language.chinese],
    tld: ".sg",
    callingCode: 65,
    continent: Continent.asia,
    currency: Currency.sgd,
  ),
  sintMaarten(
    alpha2Code: "SX",
    alpha3Code: "SXM",
    numericCode: 534,
    nativeName: "Sint Maarten",
    capital: "Philipsburg",
    mainLanguage: Language.dutch,
    languages: [Language.dutch, Language.english],
    tld: ".sx",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.ang,
  ),
  slovakia(
    alpha2Code: "SK",
    alpha3Code: "SVK",
    numericCode: 703,
    nativeName: "Slovensko",
    capital: "Bratislava",
    mainLanguage: Language.slovak,
    languages: [Language.slovak],
    tld: ".sk",
    callingCode: 421,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  slovenia(
    alpha2Code: "SI",
    alpha3Code: "SVN",
    numericCode: 705,
    nativeName: "Slovenija",
    capital: "Ljubljana",
    mainLanguage: Language.slovenian,
    languages: [Language.slovenian],
    tld: ".si",
    callingCode: 386,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  solomonIslands(
    alpha2Code: "SB",
    alpha3Code: "SLB",
    numericCode: 90,
    nativeName: "Solomon Islands",
    capital: "Honiara",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".sb",
    callingCode: 677,
    continent: Continent.oceania,
    currency: Currency.sbd,
  ),
  somalia(
    alpha2Code: "SO",
    alpha3Code: "SOM",
    numericCode: 706,
    nativeName: "Soomaaliya",
    capital: "Muqdisho",
    mainLanguage: Language.somali,
    languages: [Language.somali, Language.arabic],
    tld: ".so",
    callingCode: 252,
    continent: Continent.africa,
    currency: Currency.sos,
  ),
  southAfrica(
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    numericCode: 710,
    nativeName: "South Africa",
    capital: "Pretoria",
    mainLanguage: Language.english,
    languages: [Language.english, Language.afrikaans, Language.southNdebele, Language.southernSotho, Language.swati, Language.tsonga, Language.tswana, Language.venda, Language.xhosa, Language.zulu],
    tld: ".za",
    callingCode: 27,
    continent: Continent.africa,
    currency: Currency.zar,
  ),
  southGeorgiaAndTheSouthSandwichIslands(
    alpha2Code: "GS",
    alpha3Code: "SGS",
    numericCode: 239,
    nativeName: "South Georgia and the South Sandwich Islands",
    capital: "King Edward Point",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".gs",
    callingCode: 500,
    continent: Continent.antarctica,
    currency: Currency.gbp,
  ),
  southKorea(
    alpha2Code: "KR",
    alpha3Code: "KOR",
    numericCode: 410,
    nativeName: "대한민국",
    capital: "서울",
    mainLanguage: Language.korean,
    languages: [Language.korean],
    tld: ".kr",
    callingCode: 82,
    continent: Continent.asia,
    currency: Currency.krw,
  ),
  southSudan(
    alpha2Code: "SS",
    alpha3Code: "SSD",
    numericCode: 728,
    nativeName: "South Sudan",
    capital: "Juba",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ss",
    callingCode: 211,
    continent: Continent.africa,
    currency: Currency.ssp,
  ),
  spain(
    alpha2Code: "ES",
    alpha3Code: "ESP",
    numericCode: 724,
    nativeName: "España",
    capital: "Madrid",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".es",
    callingCode: 34,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  sriLanka(
    alpha2Code: "LK",
    alpha3Code: "LKA",
    numericCode: 144,
    nativeName: "ශ්‍රී ලංකාව",
    capital: "ශ්‍රී ජයවර්ධනපුර කෝට්ටේ",
    mainLanguage: Language.sinhala,
    languages: [Language.sinhala, Language.tamil],
    tld: ".lk",
    callingCode: 94,
    continent: Continent.asia,
    currency: Currency.lkr,
  ),
  sudan(
    alpha2Code: "SD",
    alpha3Code: "SDN",
    numericCode: 729,
    nativeName: "السودان",
    capital: "الخرطوم",
    mainLanguage: Language.arabic,
    languages: [Language.arabic, Language.english],
    tld: ".sd",
    callingCode: 249,
    continent: Continent.africa,
    currency: Currency.sdg,
  ),
  suriname(
    alpha2Code: "SR",
    alpha3Code: "SUR",
    numericCode: 740,
    nativeName: "Suriname",
    capital: "Paramaribo",
    mainLanguage: Language.dutch,
    languages: [Language.dutch],
    tld: ".sr",
    callingCode: 597,
    continent: Continent.southAmerica,
    currency: Currency.srd,
  ),
  svalbardAndJanMayen(
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    numericCode: 744,
    nativeName: "Svalbard og Jan Mayen",
    capital: "Longyearbyen",
    mainLanguage: Language.norwegian,
    languages: [Language.norwegian],
    tld: ".sj",
    callingCode: 47,
    continent: Continent.europe,
    currency: Currency.nok,
  ),
  sweden(
    alpha2Code: "SE",
    alpha3Code: "SWE",
    numericCode: 752,
    nativeName: "Sverige",
    capital: "Stockholm",
    mainLanguage: Language.swedish,
    languages: [Language.swedish],
    tld: ".se",
    callingCode: 46,
    continent: Continent.europe,
    currency: Currency.sek,
  ),
  switzerland(
    alpha2Code: "CH",
    alpha3Code: "CHE",
    numericCode: 756,
    nativeName: "Schweiz",
    capital: "Bern",
    mainLanguage: Language.german,
    languages: [Language.german, Language.french, Language.italian],
    tld: ".ch",
    callingCode: 41,
    continent: Continent.europe,
    currency: Currency.chf,
  ),
  syria(
    alpha2Code: "SY",
    alpha3Code: "SYR",
    numericCode: 760,
    nativeName: "سوريا",
    capital: "دمشق",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".sy",
    callingCode: 963,
    continent: Continent.asia,
    currency: Currency.syp,
  ),
  taiwan(
    alpha2Code: "TW",
    alpha3Code: "TWN",
    numericCode: 158,
    nativeName: "臺灣",
    capital: "臺北",
    mainLanguage: Language.chinese,
    languages: [Language.chinese],
    tld: ".tw",
    callingCode: 886,
    continent: Continent.asia,
    currency: Currency.twd,
  ),
  tajikistan(
    alpha2Code: "TJ",
    alpha3Code: "TJK",
    numericCode: 762,
    nativeName: "Тоҷикистон",
    capital: "Душанбе",
    mainLanguage: Language.tajik,
    languages: [Language.tajik, Language.russian],
    tld: ".tj",
    callingCode: 992,
    continent: Continent.asia,
    currency: Currency.tjs,
  ),
  tanzania(
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    numericCode: 834,
    nativeName: "Tanzania",
    capital: "Dodoma",
    mainLanguage: Language.swahili,
    languages: [Language.swahili, Language.english],
    tld: ".tz",
    callingCode: 255,
    continent: Continent.africa,
    currency: Currency.tzs,
  ),
  thailand(
    alpha2Code: "TH",
    alpha3Code: "THA",
    numericCode: 764,
    nativeName: "ประเทศไทย",
    capital: "กรุงเทพมหานคร",
    mainLanguage: Language.thai,
    languages: [Language.thai],
    tld: ".th",
    callingCode: 66,
    continent: Continent.asia,
    currency: Currency.thb,
  ),
  timorLeste(
    alpha2Code: "TL",
    alpha3Code: "TLS",
    numericCode: 626,
    nativeName: "Timor-Leste",
    capital: "Dili",
    mainLanguage: Language.portuguese,
    languages: [Language.portuguese],
    tld: ".tl",
    callingCode: 670,
    continent: Continent.asia,
    currency: Currency.usd,
  ),
  togo(
    alpha2Code: "TG",
    alpha3Code: "TGO",
    numericCode: 768,
    nativeName: "Togo",
    capital: "Lomé",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".tg",
    callingCode: 228,
    continent: Continent.africa,
    currency: Currency.xof,
  ),
  tokelau(
    alpha2Code: "TK",
    alpha3Code: "TKL",
    numericCode: 772,
    nativeName: "Tokelau",
    capital: "Fakaofo",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".tk",
    callingCode: 690,
    continent: Continent.oceania,
    currency: Currency.nzd,
  ),
  tonga(
    alpha2Code: "TO",
    alpha3Code: "TON",
    numericCode: 776,
    nativeName: "Tonga",
    capital: "Nukuʻalofa",
    mainLanguage: Language.tonga,
    languages: [Language.tonga, Language.english],
    tld: ".to",
    callingCode: 676,
    continent: Continent.oceania,
    currency: Currency.top,
  ),
  trinidadAndTobago(
    alpha2Code: "TT",
    alpha3Code: "TTO",
    numericCode: 780,
    nativeName: "Trinidad and Tobago",
    capital: "Port of Spain",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".tt",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.ttd,
  ),
  tunisia(
    alpha2Code: "TN",
    alpha3Code: "TUN",
    numericCode: 788,
    nativeName: "تونس",
    capital: "Tunis",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".tn",
    callingCode: 216,
    continent: Continent.africa,
    currency: Currency.tnd,
  ),
  turkey(
    alpha2Code: "TR",
    alpha3Code: "TUR",
    numericCode: 792,
    nativeName: "Türkiye",
    capital: "Ankara",
    mainLanguage: Language.turkish,
    languages: [Language.turkish],
    tld: ".tr",
    callingCode: 90,
    continent: Continent.europe,
    currency: Currency.turkishLira,
  ),
  turkmenistan(
    alpha2Code: "TM",
    alpha3Code: "TKM",
    numericCode: 795,
    nativeName: "Türkmenistan",
    capital: "Aşgabat",
    mainLanguage: Language.turkmen,
    languages: [Language.turkmen, Language.russian],
    tld: ".tm",
    callingCode: 993,
    continent: Continent.asia,
    currency: Currency.tmt,
  ),
  turksAndCaicosIslands(
    alpha2Code: "TC",
    alpha3Code: "TCA",
    numericCode: 796,
    nativeName: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".tc",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  tuvalu(
    alpha2Code: "TV",
    alpha3Code: "TUV",
    numericCode: 798,
    nativeName: "Tuvalu",
    capital: "Funafuti",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".tv",
    callingCode: 688,
    continent: Continent.oceania,
    currency: Currency.aud,
  ),
  uganda(
    alpha2Code: "UG",
    alpha3Code: "UGA",
    numericCode: 800,
    nativeName: "Uganda",
    capital: "Kampala",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".ug",
    callingCode: 256,
    continent: Continent.africa,
    currency: Currency.ugx,
  ),
  ukraine(
    alpha2Code: "UA",
    alpha3Code: "UKR",
    numericCode: 804,
    nativeName: "Україна",
    capital: "Київ",
    mainLanguage: Language.ukrainian,
    languages: [Language.ukrainian],
    tld: ".ua",
    callingCode: 380,
    continent: Continent.europe,
    currency: Currency.uah,
  ),
  unitedArabEmirates(
    alpha2Code: "AE",
    alpha3Code: "ARE",
    numericCode: 784,
    nativeName: "الإمارات العربية المتحدة",
    capital: "أبو ظبي",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".ae",
    callingCode: 971,
    continent: Continent.asia,
    currency: Currency.aed,
  ),
  unitedKingdom(
    alpha2Code: "GB",
    alpha3Code: "GBR",
    numericCode: 826,
    nativeName: "United Kingdom",
    capital: "London",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".uk",
    callingCode: 44,
    continent: Continent.europe,
    currency: Currency.gbp,
  ),
  unitedStatesMinorOutlyingIslands(
    alpha2Code: "UM",
    alpha3Code: "UMI",
    numericCode: 581,
    nativeName: "United States Minor Outlying Islands",
    capital: "",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".us",
    callingCode: 1,
    continent: Continent.oceania,
    currency: Currency.usd,
  ),
  unitedStates(
    alpha2Code: "US",
    alpha3Code: "USA",
    numericCode: 840,
    nativeName: "United States",
    capital: "Washington, D.C.",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".us",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  uruguay(
    alpha2Code: "UY",
    alpha3Code: "URY",
    numericCode: 858,
    nativeName: "Uruguay",
    capital: "Montevideo",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".uy",
    callingCode: 598,
    continent: Continent.southAmerica,
    currency: Currency.uyu,
  ),
  uzbekistan(
    alpha2Code: "UZ",
    alpha3Code: "UZB",
    numericCode: 860,
    nativeName: "Oʻzbekiston",
    capital: "Toshkent",
    mainLanguage: Language.uzbek,
    languages: [Language.uzbek, Language.russian],
    tld: ".uz",
    callingCode: 998,
    continent: Continent.asia,
    currency: Currency.uzs,
  ),
  vanuatu(
    alpha2Code: "VU",
    alpha3Code: "VUT",
    numericCode: 548,
    nativeName: "Vanuatu",
    capital: "Port Vila",
    mainLanguage: Language.bislama,
    languages: [Language.bislama, Language.english, Language.french],
    tld: ".vu",
    callingCode: 678,
    continent: Continent.oceania,
    currency: Currency.vuv,
  ),
  vaticanCity(
    alpha2Code: "VA",
    alpha3Code: "VAT",
    numericCode: 336,
    nativeName: "Vaticano",
    capital: "Vatican City",
    mainLanguage: Language.italian,
    languages: [Language.italian],
    tld: ".va",
    callingCode: 379,
    continent: Continent.europe,
    currency: Currency.eur,
  ),
  venezuela(
    alpha2Code: "VE",
    alpha3Code: "VEN",
    numericCode: 862,
    nativeName: "Venezuela",
    capital: "Caracas",
    mainLanguage: Language.spanish,
    languages: [Language.spanish],
    tld: ".ve",
    callingCode: 58,
    continent: Continent.southAmerica,
    currency: Currency.ves,
  ),
  vietnam(
    alpha2Code: "VN",
    alpha3Code: "VNM",
    numericCode: 704,
    nativeName: "Việt Nam",
    capital: "Hà Nội",
    mainLanguage: Language.vietnamese,
    languages: [Language.vietnamese],
    tld: ".vn",
    callingCode: 84,
    continent: Continent.asia,
    currency: Currency.vnd,
  ),
  virginIslandsUS(
    alpha2Code: "VI",
    alpha3Code: "VIR",
    numericCode: 850,
    nativeName: "United States Virgin Islands",
    capital: "Charlotte Amalie",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".vi",
    callingCode: 1,
    continent: Continent.northAmerica,
    currency: Currency.usd,
  ),
  wallisAndFutuna(
    alpha2Code: "WF",
    alpha3Code: "WLF",
    numericCode: 876,
    nativeName: "Wallis et Futuna",
    capital: "Mata-Utu",
    mainLanguage: Language.french,
    languages: [Language.french],
    tld: ".wf",
    callingCode: 681,
    continent: Continent.oceania,
    currency: Currency.xpf,
  ),
  westernSahara(
    alpha2Code: "EH",
    alpha3Code: "ESH",
    numericCode: 732,
    nativeName: "الصحراء الغربية",
    capital: "العيون",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".eh",
    callingCode: 212,
    continent: Continent.africa,
    currency: Currency.mad,
  ),
  yemen(
    alpha2Code: "YE",
    alpha3Code: "YEM",
    numericCode: 887,
    nativeName: "اليمن",
    capital: "صنعاء",
    mainLanguage: Language.arabic,
    languages: [Language.arabic],
    tld: ".ye",
    callingCode: 967,
    continent: Continent.asia,
    currency: Currency.yer,
  ),
  zambia(
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
    numericCode: 894,
    nativeName: "Zambia",
    capital: "Lusaka",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".zm",
    callingCode: 260,
    continent: Continent.africa,
    currency: Currency.zmw,
  ),
  zimbabwe(
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
    numericCode: 716,
    nativeName: "Zimbabwe",
    capital: "Harare",
    mainLanguage: Language.english,
    languages: [Language.english],
    tld: ".zw",
    callingCode: 263,
    continent: Continent.africa,
    currency: Currency.zwl,
  ),
  ;

  const Country({
    required this.alpha2Code,
    required this.alpha3Code,
    required this.numericCode,
    required this.nativeName,
    required this.capital,
    required this.mainLanguage,
    required this.languages,
    required this.tld,
    required this.callingCode,
    required this.continent,
    required this.currency,
  });

  final String alpha2Code;
  final String alpha3Code;
  final int numericCode;
  final String nativeName;
  final String capital;
  final Language mainLanguage;
  final List<Language> languages;
  final String tld;
  final int callingCode;
  final Continent continent;
  final Currency currency;

  /// Alias for alpha2Code
  String get code => alpha2Code;

  /// Alias for nativeName (backwards compatibility)
  String get name => nativeName;

  /// Returns the numeric code as a zero-padded string
  String get numericCodeString => numericCode.toString().padLeft(3, '0');

  /// Returns the calling code as a string with + prefix
  String get callingCodeString => '+$callingCode';

  /// Returns the country's flag SVG as a string
  String get flagSvg => countryFlags[alpha2Code] ?? '';

  /// Returns the country's emoji flag
  String get emojiFlag {
    final int base = 0x1F1E6 - 65;
    final int first = alpha2Code.codeUnitAt(0) + base;
    final int second = alpha2Code.codeUnitAt(1) + base;
    return String.fromCharCodes([first, second]);
  }

  /// Returns the display name based on the locale
  String displayName(BuildContext context) =>
      displayNameFromLocale(Localizations.localeOf(context));

  /// Returns the display name based on the given locale
  String displayNameFromLocale(Locale locale) =>
      CountriesTranslationsDelegate.getNameFromCodeAndLocale(alpha2Code, locale) ??
      nativeName;

  /// Returns the capital display name based on the locale
  String displayCapital(BuildContext context) =>
      displayCapitalFromLocale(Localizations.localeOf(context));

  /// Returns the capital display name based on the given locale
  String displayCapitalFromLocale(Locale locale) =>
      CapitalsTranslationsDelegate.getNameFromCodeAndLocale(alpha2Code, locale) ??
      capital;

  /// Returns a country from its alpha2 code
  static Country? fromAlpha2Code(String code) {
    final upperCode = code.toUpperCase();
    for (var country in Country.values) {
      if (country.alpha2Code == upperCode) {
        return country;
      }
    }
    return null;
  }

  /// Returns a country from its alpha3 code
  static Country? fromAlpha3Code(String code) {
    final upperCode = code.toUpperCase();
    for (var country in Country.values) {
      if (country.alpha3Code == upperCode) {
        return country;
      }
    }
    return null;
  }

  /// Returns a country from its numeric code
  static Country? fromNumericCode(int code) {
    for (var country in Country.values) {
      if (country.numericCode == code) {
        return country;
      }
    }
    return null;
  }

  /// Alias for fromAlpha2Code
  static Country? fromCode(String code) => fromAlpha2Code(code);

  /// Returns a flag widget with the specified shape and size
  Widget flag({
    FlagShape shape = FlagShape.rectangle,
    double? width,
    double? height,
    double? size,
  }) {
    final svg = flagSvg;
    final w = size ?? width;
    final h = size ?? height;
    if (svg.isEmpty) {
      return SizedBox(width: w, height: h);
    }

    Widget flagWidget = SvgPicture.string(
      svg,
      width: w,
      height: h,
    );

    if (shape == FlagShape.circle) {
      return ClipOval(child: flagWidget);
    } else if (shape == FlagShape.square) {
      return ClipRect(child: flagWidget);
    }

    return flagWidget;
  }

  @override
  String toString() => nativeName;
}
