// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/widgets.dart';

import 'i18n/currencies.g.dart';

/// A list of currencies
enum Currency {
  aed(
    code: "AED",
    nativeName: "United Arab Emirates Dirham",
    nativeNamePlural: "United Arab Emirates Dirhams",
    symbol: "د.إ",
  ),
  afn(
    code: "AFN",
    nativeName: "Afghan Afghani",
    nativeNamePlural: "Afghan Afghanis",
    symbol: "؋",
  ),
  all(
    code: "ALL",
    nativeName: "Albanian Lek",
    nativeNamePlural: "Albanian Leke",
    symbol: "L",
  ),
  amd(
    code: "AMD",
    nativeName: "Armenian Dram",
    nativeNamePlural: "Armenian Drams",
    symbol: "֏",
  ),
  ang(
    code: "ANG",
    nativeName: "Netherlands Antillean Guilder",
    nativeNamePlural: "Netherlands Antillean Guilders",
    symbol: "ƒ",
  ),
  aoa(
    code: "AOA",
    nativeName: "Angolan Kwanza",
    nativeNamePlural: "Angolan Kwanza",
    symbol: "Kz",
  ),
  ars(
    code: "ARS",
    nativeName: "Argentine Peso",
    nativeNamePlural: "Argentine Pesos",
    symbol: "\\\$",
  ),
  aud(
    code: "AUD",
    nativeName: "Australian Dollar",
    nativeNamePlural: "Australian Dollars",
    symbol: "\\\$",
  ),
  awg(
    code: "AWG",
    nativeName: "Aruban Florin",
    nativeNamePlural: "Aruban Florin",
    symbol: "ƒ",
  ),
  azn(
    code: "AZN",
    nativeName: "Azerbaijani Manat",
    nativeNamePlural: "Azerbaijani Manat",
    symbol: "₼",
  ),
  bam(
    code: "BAM",
    nativeName: "Bosnia-Herzegovina Convertible Mark",
    nativeNamePlural: "Bosnia-Herzegovina Convertible Marks",
    symbol: "KM",
  ),
  bbd(
    code: "BBD",
    nativeName: "Barbadian Dollar",
    nativeNamePlural: "Barbadian Dollars",
    symbol: "\\\$",
  ),
  bdt(
    code: "BDT",
    nativeName: "Bangladeshi Taka",
    nativeNamePlural: "Bangladeshi Takas",
    symbol: "৳",
  ),
  bgn(
    code: "BGN",
    nativeName: "Bulgarian Lev",
    nativeNamePlural: "Bulgarian Leva",
    symbol: "лв",
  ),
  bhd(
    code: "BHD",
    nativeName: "Bahraini Dinar",
    nativeNamePlural: "Bahraini Dinars",
    symbol: "ب.د",
  ),
  bif(
    code: "BIF",
    nativeName: "Burundian Franc",
    nativeNamePlural: "Burundian Francs",
    symbol: "FBu",
  ),
  bmd(
    code: "BMD",
    nativeName: "Bermudian Dollar",
    nativeNamePlural: "Bermudian Dollars",
    symbol: "\\\$",
  ),
  bnd(
    code: "BND",
    nativeName: "Brunei Dollar",
    nativeNamePlural: "Brunei Dollars",
    symbol: "\\\$",
  ),
  bob(
    code: "BOB",
    nativeName: "Bolivian Boliviano",
    nativeNamePlural: "Bolivian Bolivianos",
    symbol: "Bs.",
  ),
  bov(
    code: "BOV",
    nativeName: "Bolivian Mvdol",
    nativeNamePlural: "Bolivian Mvdols",
    symbol: "BOV",
  ),
  brl(
    code: "BRL",
    nativeName: "Brazilian Real",
    nativeNamePlural: "Brazilian Reals",
    symbol: "R\\\$",
  ),
  bsd(
    code: "BSD",
    nativeName: "Bahamian Dollar",
    nativeNamePlural: "Bahamian Dollars",
    symbol: "\\\$",
  ),
  btn(
    code: "BTN",
    nativeName: "Bhutanese Ngultrum",
    nativeNamePlural: "Bhutanese Ngultrums",
    symbol: "Nu.",
  ),
  bwp(
    code: "BWP",
    nativeName: "Botswana Pula",
    nativeNamePlural: "Botswana Pulas",
    symbol: "P",
  ),
  byn(
    code: "BYN",
    nativeName: "Belarusian Ruble",
    nativeNamePlural: "Belarusian Rubles",
    symbol: "Br",
  ),
  bzd(
    code: "BZD",
    nativeName: "Belize Dollar",
    nativeNamePlural: "Belize Dollars",
    symbol: "BZ\\\$",
  ),
  cad(
    code: "CAD",
    nativeName: "Canadian Dollar",
    nativeNamePlural: "Canadian Dollars",
    symbol: "\\\$",
  ),
  cdf(
    code: "CDF",
    nativeName: "Congolese Franc",
    nativeNamePlural: "Congolese Francs",
    symbol: "FC",
  ),
  che(
    code: "CHE",
    nativeName: "WIR Euro",
    nativeNamePlural: "WIR Euros",
    symbol: "CHE",
  ),
  chf(
    code: "CHF",
    nativeName: "Swiss Franc",
    nativeNamePlural: "Swiss Francs",
    symbol: "CHF",
  ),
  chw(
    code: "CHW",
    nativeName: "WIR Franc",
    nativeNamePlural: "WIR Francs",
    symbol: "CHW",
  ),
  clf(
    code: "CLF",
    nativeName: "Chilean Unit of Account (UF)",
    nativeNamePlural: "Chilean Units of Account (UF)",
    symbol: "CLF",
  ),
  clp(
    code: "CLP",
    nativeName: "Chilean Peso",
    nativeNamePlural: "Chilean Pesos",
    symbol: "\\\$",
  ),
  cny(
    code: "CNY",
    nativeName: "Chinese Yuan",
    nativeNamePlural: "Chinese Yuan",
    symbol: "¥",
  ),
  cop(
    code: "COP",
    nativeName: "Colombian Peso",
    nativeNamePlural: "Colombian Pesos",
    symbol: "\\\$",
  ),
  cou(
    code: "COU",
    nativeName: "Unidad de Valor Real",
    nativeNamePlural: "Unidad de Valor Reals",
    symbol: "COU",
  ),
  crc(
    code: "CRC",
    nativeName: "Costa Rican Colón",
    nativeNamePlural: "Costa Rican Colóns",
    symbol: "₡",
  ),
  cup(
    code: "CUP",
    nativeName: "Cuban Peso",
    nativeNamePlural: "Cuban Pesos",
    symbol: "\\\$",
  ),
  cve(
    code: "CVE",
    nativeName: "Cape Verdean Escudo",
    nativeNamePlural: "Cape Verdean Escudos",
    symbol: "Esc",
  ),
  czk(
    code: "CZK",
    nativeName: "Czech Koruna",
    nativeNamePlural: "Czech Korunas",
    symbol: "Kč",
  ),
  djf(
    code: "DJF",
    nativeName: "Djiboutian Franc",
    nativeNamePlural: "Djiboutian Francs",
    symbol: "Fdj",
  ),
  dkk(
    code: "DKK",
    nativeName: "Danske Kroner",
    nativeNamePlural: "Danske Kroner",
    symbol: "kr",
  ),
  dop(
    code: "DOP",
    nativeName: "Dominican Peso",
    nativeNamePlural: "Dominican Pesos",
    symbol: "RD\\\$",
  ),
  dzd(
    code: "DZD",
    nativeName: "Algerian Dinar",
    nativeNamePlural: "Algerian Dinars",
    symbol: "د.ج",
  ),
  egp(
    code: "EGP",
    nativeName: "Egyptian Pound",
    nativeNamePlural: "Egyptian Pounds",
    symbol: "E£",
  ),
  ern(
    code: "ERN",
    nativeName: "Eritrean Nakfa",
    nativeNamePlural: "Eritrean Nakfas",
    symbol: "Nfk",
  ),
  etb(
    code: "ETB",
    nativeName: "Ethiopian Birr",
    nativeNamePlural: "Ethiopian Birrs",
    symbol: "Br",
  ),
  eur(
    code: "EUR",
    nativeName: "Euro",
    nativeNamePlural: "Euros",
    symbol: "€",
  ),
  fjd(
    code: "FJD",
    nativeName: "Fijian Dollar",
    nativeNamePlural: "Fijian Dollars",
    symbol: "\\\$",
  ),
  fkp(
    code: "FKP",
    nativeName: "Falkland Islands Pound",
    nativeNamePlural: "Falkland Islands Pounds",
    symbol: "£",
  ),
  gbp(
    code: "GBP",
    nativeName: "British Pound",
    nativeNamePlural: "British Pounds",
    symbol: "£",
  ),
  gel(
    code: "GEL",
    nativeName: "Georgian Lari",
    nativeNamePlural: "Georgian Laris",
    symbol: "₾",
  ),
  ghs(
    code: "GHS",
    nativeName: "Ghanaian Cedi",
    nativeNamePlural: "Ghanaian Cedis",
    symbol: "₵",
  ),
  gip(
    code: "GIP",
    nativeName: "Gibraltar Pound",
    nativeNamePlural: "Gibraltar Pounds",
    symbol: "£",
  ),
  gmd(
    code: "GMD",
    nativeName: "Gambian Dalasi",
    nativeNamePlural: "Gambian Dalasis",
    symbol: "D",
  ),
  gnf(
    code: "GNF",
    nativeName: "Guinean Franc",
    nativeNamePlural: "Guinean Francs",
    symbol: "FG",
  ),
  gtq(
    code: "GTQ",
    nativeName: "Guatemalan Quetzal",
    nativeNamePlural: "Guatemalan Quetzals",
    symbol: "Q",
  ),
  gyd(
    code: "GYD",
    nativeName: "Guyanese Dollar",
    nativeNamePlural: "Guyanese Dollars",
    symbol: "\\\$",
  ),
  hkd(
    code: "HKD",
    nativeName: "Hong Kong Dollar",
    nativeNamePlural: "Hong Kong Dollars",
    symbol: "\\\$",
  ),
  hnl(
    code: "HNL",
    nativeName: "Honduran Lempira",
    nativeNamePlural: "Honduran Lempiras",
    symbol: "L",
  ),
  htg(
    code: "HTG",
    nativeName: "Haitian Gourde",
    nativeNamePlural: "Haitian Gourdes",
    symbol: "G",
  ),
  huf(
    code: "HUF",
    nativeName: "Hungarian Forint",
    nativeNamePlural: "Hungarian Forints",
    symbol: "Ft",
  ),
  idr(
    code: "IDR",
    nativeName: "Indonesian Rupiah",
    nativeNamePlural: "Indonesian Rupiahs",
    symbol: "Rp",
  ),
  ils(
    code: "ILS",
    nativeName: "Israeli New Shekel",
    nativeNamePlural: "Israeli New Shekels",
    symbol: "₪",
  ),
  inr(
    code: "INR",
    nativeName: "Indian Rupee",
    nativeNamePlural: "Indian Rupees",
    symbol: "₹",
  ),
  iqd(
    code: "IQD",
    nativeName: "Iraqi Dinar",
    nativeNamePlural: "Iraqi Dinars",
    symbol: "ع.د",
  ),
  irr(
    code: "IRR",
    nativeName: "Iranian Rial",
    nativeNamePlural: "Iranian Rials",
    symbol: "﷼",
  ),
  isk(
    code: "ISK",
    nativeName: "Icelandic Króna",
    nativeNamePlural: "Icelandic Krónur",
    symbol: "kr",
  ),
  jmd(
    code: "JMD",
    nativeName: "Jamaican Dollar",
    nativeNamePlural: "Jamaican Dollars",
    symbol: "J\\\$",
  ),
  jod(
    code: "JOD",
    nativeName: "Jordanian Dinar",
    nativeNamePlural: "Jordanian Dinars",
    symbol: "د.ا",
  ),
  jpy(
    code: "JPY",
    nativeName: "Japanese Yen",
    nativeNamePlural: "Japanese Yen",
    symbol: "¥",
  ),
  kes(
    code: "KES",
    nativeName: "Kenyan Shilling",
    nativeNamePlural: "Kenyan Shillings",
    symbol: "KSh",
  ),
  kgs(
    code: "KGS",
    nativeName: "Kyrgyzstani Som",
    nativeNamePlural: "Kyrgyzstani Soms",
    symbol: "с",
  ),
  khr(
    code: "KHR",
    nativeName: "Cambodian Riel",
    nativeNamePlural: "Cambodian Riels",
    symbol: "៛",
  ),
  kmf(
    code: "KMF",
    nativeName: "Comorian Franc",
    nativeNamePlural: "Comorian Francs",
    symbol: "CF",
  ),
  kpw(
    code: "KPW",
    nativeName: "North Korean Won",
    nativeNamePlural: "North Korean Won",
    symbol: "₩",
  ),
  krw(
    code: "KRW",
    nativeName: "South Korean Won",
    nativeNamePlural: "South Korean Won",
    symbol: "₩",
  ),
  kwd(
    code: "KWD",
    nativeName: "Kuwaiti Dinar",
    nativeNamePlural: "Kuwaiti Dinars",
    symbol: "د.ك",
  ),
  kyd(
    code: "KYD",
    nativeName: "Cayman Islands Dollar",
    nativeNamePlural: "Cayman Islands Dollars",
    symbol: "\\\$",
  ),
  kzt(
    code: "KZT",
    nativeName: "Kazakhstani Tenge",
    nativeNamePlural: "Kazakhstani Tenges",
    symbol: "₸",
  ),
  lak(
    code: "LAK",
    nativeName: "Lao Kip",
    nativeNamePlural: "Lao Kips",
    symbol: "₭",
  ),
  lbp(
    code: "LBP",
    nativeName: "Lebanese Pound",
    nativeNamePlural: "Lebanese Pounds",
    symbol: "ل.ل",
  ),
  lkr(
    code: "LKR",
    nativeName: "Sri Lankan Rupee",
    nativeNamePlural: "Sri Lankan Rupees",
    symbol: "Rs",
  ),
  lrd(
    code: "LRD",
    nativeName: "Liberian Dollar",
    nativeNamePlural: "Liberian Dollars",
    symbol: "\\\$",
  ),
  lsl(
    code: "LSL",
    nativeName: "Lesotho Loti",
    nativeNamePlural: "Lesotho Lotis",
    symbol: "L",
  ),
  lyd(
    code: "LYD",
    nativeName: "Libyan Dinar",
    nativeNamePlural: "Libyan Dinars",
    symbol: "ل.د",
  ),
  mad(
    code: "MAD",
    nativeName: "Moroccan Dirham",
    nativeNamePlural: "Moroccan Dirhams",
    symbol: "د.م.",
  ),
  mdl(
    code: "MDL",
    nativeName: "Moldovan Leu",
    nativeNamePlural: "Moldovan Lei",
    symbol: "L",
  ),
  mga(
    code: "MGA",
    nativeName: "Malagasy Ariary",
    nativeNamePlural: "Malagasy Ariaries",
    symbol: "Ar",
  ),
  mkd(
    code: "MKD",
    nativeName: "Macedonian Denar",
    nativeNamePlural: "Macedonian Denari",
    symbol: "ден",
  ),
  mmk(
    code: "MMK",
    nativeName: "Myanmar Kyat",
    nativeNamePlural: "Myanmar Kyats",
    symbol: "K",
  ),
  mnt(
    code: "MNT",
    nativeName: "Mongolian Tugrik",
    nativeNamePlural: "Mongolian Tugriks",
    symbol: "₮",
  ),
  mop(
    code: "MOP",
    nativeName: "Macanese Pataca",
    nativeNamePlural: "Macanese Patacas",
    symbol: "MOP\\\$",
  ),
  mru(
    code: "MRU",
    nativeName: "Mauritanian Ouguiya",
    nativeNamePlural: "Mauritanian Ouguiyas",
    symbol: "UM",
  ),
  mur(
    code: "MUR",
    nativeName: "Mauritian Rupee",
    nativeNamePlural: "Mauritian Rupees",
    symbol: "₨",
  ),
  mvr(
    code: "MVR",
    nativeName: "Maldivian Rufiyaa",
    nativeNamePlural: "Maldivian Rufiyaas",
    symbol: "Rf",
  ),
  mwk(
    code: "MWK",
    nativeName: "Malawian Kwacha",
    nativeNamePlural: "Malawian Kwachas",
    symbol: "MK",
  ),
  mxn(
    code: "MXN",
    nativeName: "Mexican Peso",
    nativeNamePlural: "Mexican Pesos",
    symbol: "\\\$",
  ),
  mxv(
    code: "MXV",
    nativeName: "Mexican Unidad de Inversion (UDI)",
    nativeNamePlural: "Mexican Unidad de Inversions (UDI)",
    symbol: "MXV",
  ),
  myr(
    code: "MYR",
    nativeName: "Malaysian Ringgit",
    nativeNamePlural: "Malaysian Ringgits",
    symbol: "RM",
  ),
  mzn(
    code: "MZN",
    nativeName: "Mozambican Metical",
    nativeNamePlural: "Mozambican Meticals",
    symbol: "MT",
  ),
  nad(
    code: "NAD",
    nativeName: "Namibian Dollar",
    nativeNamePlural: "Namibian Dollars",
    symbol: "\\\$",
  ),
  ngn(
    code: "NGN",
    nativeName: "Nigerian Naira",
    nativeNamePlural: "Nigerian Nairas",
    symbol: "₦",
  ),
  nio(
    code: "NIO",
    nativeName: "Nicaraguan Córdoba",
    nativeNamePlural: "Nicaraguan Córdobas",
    symbol: "C\\\$",
  ),
  nok(
    code: "NOK",
    nativeName: "Norwegian Krone",
    nativeNamePlural: "Norwegian Kroner",
    symbol: "kr",
  ),
  npr(
    code: "NPR",
    nativeName: "Nepalese Rupee",
    nativeNamePlural: "Nepalese Rupees",
    symbol: "रू",
  ),
  nzd(
    code: "NZD",
    nativeName: "New Zealand Dollar",
    nativeNamePlural: "New Zealand Dollars",
    symbol: "\\\$",
  ),
  omr(
    code: "OMR",
    nativeName: "Omani Rial",
    nativeNamePlural: "Omani Rials",
    symbol: "ر.ع.",
  ),
  pab(
    code: "PAB",
    nativeName: "Panamanian Balboa",
    nativeNamePlural: "Panamanian Balboas",
    symbol: "B/.",
  ),
  pen(
    code: "PEN",
    nativeName: "Peruvian Nuevo Sol",
    nativeNamePlural: "Peruvian Nuevo Sols",
    symbol: "S/.",
  ),
  pgk(
    code: "PGK",
    nativeName: "Papua New Guinean Kina",
    nativeNamePlural: "Papua New Guinean Kina",
    symbol: "K",
  ),
  php(
    code: "PHP",
    nativeName: "Philippine Peso",
    nativeNamePlural: "Philippine Pesos",
    symbol: "₱",
  ),
  pkr(
    code: "PKR",
    nativeName: "Pakistani Rupee",
    nativeNamePlural: "Pakistani Rupees",
    symbol: "₨",
  ),
  pln(
    code: "PLN",
    nativeName: "Polish Złoty",
    nativeNamePlural: "Polish Złotys",
    symbol: "zł",
  ),
  pyg(
    code: "PYG",
    nativeName: "Paraguayan Guaraní",
    nativeNamePlural: "Paraguayan Guaranís",
    symbol: "₲",
  ),
  qar(
    code: "QAR",
    nativeName: "Qatari Rial",
    nativeNamePlural: "Qatari Rials",
    symbol: "ر.ق",
  ),
  ron(
    code: "RON",
    nativeName: "Romanian Leu",
    nativeNamePlural: "Romanian Lei",
    symbol: "lei",
  ),
  rsd(
    code: "RSD",
    nativeName: "Serbian Dinar",
    nativeNamePlural: "Serbian Dinars",
    symbol: "дин",
  ),
  rub(
    code: "RUB",
    nativeName: "Russian Ruble",
    nativeNamePlural: "Russian Rubles",
    symbol: "₽",
  ),
  rwf(
    code: "RWF",
    nativeName: "Rwandan Franc",
    nativeNamePlural: "Rwandan Francs",
    symbol: "FRw",
  ),
  sar(
    code: "SAR",
    nativeName: "Saudi Riyal",
    nativeNamePlural: "Saudi Riyals",
    symbol: "ر.س",
  ),
  sbd(
    code: "SBD",
    nativeName: "Solomon Islands Dollar",
    nativeNamePlural: "Solomon Islands Dollars",
    symbol: "\\\$",
  ),
  scr(
    code: "SCR",
    nativeName: "Seychellois Rupee",
    nativeNamePlural: "Seychellois Rupees",
    symbol: "₨",
  ),
  sdg(
    code: "SDG",
    nativeName: "Sudanese Pound",
    nativeNamePlural: "Sudanese Pounds",
    symbol: "ج.س.",
  ),
  sek(
    code: "SEK",
    nativeName: "Swedish Krona",
    nativeNamePlural: "Swedish Kronor",
    symbol: "kr",
  ),
  sgd(
    code: "SGD",
    nativeName: "Singapore Dollar",
    nativeNamePlural: "Singapore Dollars",
    symbol: "\\\$",
  ),
  shp(
    code: "SHP",
    nativeName: "Saint Helena Pound",
    nativeNamePlural: "Saint Helena Pounds",
    symbol: "£",
  ),
  sle(
    code: "SLE",
    nativeName: "Sierra Leonean Leone",
    nativeNamePlural: "Sierra Leonean Leones",
    symbol: "Le",
  ),
  sos(
    code: "SOS",
    nativeName: "Somali Shilling",
    nativeNamePlural: "Somali Shillings",
    symbol: "Sh.So.",
  ),
  srd(
    code: "SRD",
    nativeName: "Surinamese Dollar",
    nativeNamePlural: "Surinamese Dollars",
    symbol: "\\\$",
  ),
  ssp(
    code: "SSP",
    nativeName: "South Sudanese Pound",
    nativeNamePlural: "South Sudanese Pounds",
    symbol: "£",
  ),
  stn(
    code: "STN",
    nativeName: "São Tomé and Príncipe Dobra",
    nativeNamePlural: "São Tomé and Príncipe Dobras",
    symbol: "Db",
  ),
  svc(
    code: "SVC",
    nativeName: "Salvadoran Colón",
    nativeNamePlural: "Salvadoran Colóns",
    symbol: "₡",
  ),
  syp(
    code: "SYP",
    nativeName: "Syrian Pound",
    nativeNamePlural: "Syrian Pounds",
    symbol: "ل.س",
  ),
  szl(
    code: "SZL",
    nativeName: "Swazi Lilangeni",
    nativeNamePlural: "Swazi Emalangeni",
    symbol: "L",
  ),
  thb(
    code: "THB",
    nativeName: "Thai Baht",
    nativeNamePlural: "Thai Baht",
    symbol: "฿",
  ),
  tjs(
    code: "TJS",
    nativeName: "Tajikistani Somoni",
    nativeNamePlural: "Tajikistani Somonis",
    symbol: "ЅМ",
  ),
  tmt(
    code: "TMT",
    nativeName: "Turkmenistani Manat",
    nativeNamePlural: "Turkmenistani Manats",
    symbol: "T",
  ),
  tnd(
    code: "TND",
    nativeName: "Tunisian Dinar",
    nativeNamePlural: "Tunisian Dinars",
    symbol: "د.ت",
  ),
  top(
    code: "TOP",
    nativeName: "Tongan Pa'anga",
    nativeNamePlural: "Tongan Pa'anga",
    symbol: "T\\\$",
  ),
  turkishLira(
    code: "TRY",
    nativeName: "Turkish Lira",
    nativeNamePlural: "Turkish Lira",
    symbol: "₺",
  ),
  ttd(
    code: "TTD",
    nativeName: "Trinidad and Tobago Dollar",
    nativeNamePlural: "Trinidad and Tobago Dollars",
    symbol: "TT\\\$",
  ),
  twd(
    code: "TWD",
    nativeName: "New Taiwan Dollar",
    nativeNamePlural: "New Taiwan Dollars",
    symbol: "NT\\\$",
  ),
  tzs(
    code: "TZS",
    nativeName: "Tanzanian Shilling",
    nativeNamePlural: "Tanzanian Shillings",
    symbol: "TSh",
  ),
  uah(
    code: "UAH",
    nativeName: "Ukrainian Hryvnia",
    nativeNamePlural: "Ukrainian Hryvnias",
    symbol: "₴",
  ),
  ugx(
    code: "UGX",
    nativeName: "Ugandan Shilling",
    nativeNamePlural: "Ugandan Shillings",
    symbol: "USh",
  ),
  usd(
    code: "USD",
    nativeName: "United States Dollar",
    nativeNamePlural: "United States Dollars",
    symbol: "\\\$",
  ),
  usn(
    code: "USN",
    nativeName: "United States Dollar (Next day)",
    nativeNamePlural: "United States Dollars (Next day)",
    symbol: "USN",
  ),
  uyi(
    code: "UYI",
    nativeName: "Uruguayan Peso en Unidades Indexadas",
    nativeNamePlural: "Uruguayan Pesos en Unidades Indexadas",
    symbol: "UYI",
  ),
  uyu(
    code: "UYU",
    nativeName: "Uruguayan Peso",
    nativeNamePlural: "Uruguayan Pesos",
    symbol: "\\\$U",
  ),
  uyw(
    code: "UYW",
    nativeName: "Unidad Previsional",
    nativeNamePlural: "Unidad Previsionals",
    symbol: "UYW",
  ),
  uzs(
    code: "UZS",
    nativeName: "Uzbekistan Som",
    nativeNamePlural: "Uzbekistan Soms",
    symbol: "лв",
  ),
  ved(
    code: "VED",
    nativeName: "Venezuelan Bolívar Soberano",
    nativeNamePlural: "Venezuelan Bolívar Soberanos",
    symbol: "VES",
  ),
  ves(
    code: "VES",
    nativeName: "Venezuelan Bolívar",
    nativeNamePlural: "Venezuelan Bolívars",
    symbol: "Bs.",
  ),
  vnd(
    code: "VND",
    nativeName: "Vietnamese Dong",
    nativeNamePlural: "Vietnamese Dong",
    symbol: "₫",
  ),
  vuv(
    code: "VUV",
    nativeName: "Vanuatu Vatu",
    nativeNamePlural: "Vanuatu Vatus",
    symbol: "VT",
  ),
  wst(
    code: "WST",
    nativeName: "Samoan Tala",
    nativeNamePlural: "Samoan Tala",
    symbol: "WS\\\$",
  ),
  xaf(
    code: "XAF",
    nativeName: "Central African CFA Franc",
    nativeNamePlural: "Central African CFA Francs",
    symbol: "FCFA",
  ),
  xag(
    code: "XAG",
    nativeName: "Silver (one troy ounce)",
    nativeNamePlural: "Silver (one troy ounce)",
    symbol: "XAG",
  ),
  xau(
    code: "XAU",
    nativeName: "Gold (one troy ounce)",
    nativeNamePlural: "Gold (one troy ounce)",
    symbol: "XAU",
  ),
  xba(
    code: "XBA",
    nativeName: "European Composite Unit",
    nativeNamePlural: "European Composite Units",
    symbol: "XBA",
  ),
  xbb(
    code: "XBB",
    nativeName: "European Monetary Unit",
    nativeNamePlural: "European Monetary Units",
    symbol: "XBB",
  ),
  xbc(
    code: "XBC",
    nativeName: "European Unit of Account 9",
    nativeNamePlural: "European Unit of Account 9",
    symbol: "XBC",
  ),
  xbd(
    code: "XBD",
    nativeName: "European Unit of Account 17",
    nativeNamePlural: "European Unit of Account 17",
    symbol: "XBD",
  ),
  xcd(
    code: "XCD",
    nativeName: "East Caribbean Dollar",
    nativeNamePlural: "East Caribbean Dollars",
    symbol: "\\\$",
  ),
  xdr(
    code: "XDR",
    nativeName: "Special Drawing Rights",
    nativeNamePlural: "Special Drawing Rights",
    symbol: "XDR",
  ),
  xof(
    code: "XOF",
    nativeName: "West African CFA Franc",
    nativeNamePlural: "West African CFA Francs",
    symbol: "CFA",
  ),
  xpd(
    code: "XPD",
    nativeName: "Palladium (one troy ounce)",
    nativeNamePlural: "Palladium (one troy ounce)",
    symbol: "XPD",
  ),
  xpf(
    code: "XPF",
    nativeName: "CFP Franc",
    nativeNamePlural: "CFP Francs",
    symbol: "CFPF",
  ),
  xpt(
    code: "XPT",
    nativeName: "Platinum (one troy ounce)",
    nativeNamePlural: "Platinum (one troy ounce)",
    symbol: "XPT",
  ),
  xsu(
    code: "XSU",
    nativeName: "SUCRE",
    nativeNamePlural: "SUCRE",
    symbol: "XSU",
  ),
  xts(
    code: "XTS",
    nativeName: "Codes specifically reserved for testing purposes",
    nativeNamePlural: "Codes specifically reserved for testing purposes",
    symbol: "XTS",
  ),
  xua(
    code: "XUA",
    nativeName: "ADB Unit of Account",
    nativeNamePlural: "ADB Unit of Accounts",
    symbol: "XUA",
  ),
  xxx(
    code: "XXX",
    nativeName: "No currency",
    nativeNamePlural: "No currency",
    symbol: "XXX",
  ),
  yer(
    code: "YER",
    nativeName: "Yemeni Rial",
    nativeNamePlural: "Yemeni Rials",
    symbol: "﷼",
  ),
  zar(
    code: "ZAR",
    nativeName: "South African Rand",
    nativeNamePlural: "South African Rand",
    symbol: "R",
  ),
  zmw(
    code: "ZMW",
    nativeName: "Zambian Kwacha",
    nativeNamePlural: "Zambian Kwachas",
    symbol: "ZK",
  ),
  zmg(
    code: "ZMG",
    nativeName: "Zambian Kwacha (pre-2013)",
    nativeNamePlural: "Zambian Kwachas (pre-2013)",
    symbol: "ZMG",
  ),
  zwl(
    code: "ZWL",
    nativeName: "Zimbabwean Dollar",
    nativeNamePlural: "Zimbabwean Dollars",
    symbol: "ZWL",
  ),
  ;

  const Currency({
    required this.code,
    required this.nativeName,
    required this.nativeNamePlural,
    required this.symbol,
  });

  final String code;
  final String nativeName;
  final String nativeNamePlural;
  final String symbol;

  /// Returns the display name based on the locale
  String displayName(BuildContext context) =>
      displayNameFromLocale(Localizations.localeOf(context));

  /// Returns the display name based on the given locale
  String displayNameFromLocale(Locale locale) =>
      CurrenciesTranslationsDelegate.getNameFromCodeAndLocale(code, locale) ??
      nativeName;

  /// Returns a currency from its code
  static Currency? fromCode(String code) {
    final upperCode = code.toUpperCase();
    for (var currency in Currency.values) {
      if (currency.code == upperCode) {
        return currency;
      }
    }
    return null;
  }

  @override
  String toString() => code;
}
