// GENERATED CODE - DO NOT MODIFY BY HAND

import type { Country } from './types';

export enum CountryCode {
  AF = "AF",
  AX = "AX",
  AL = "AL",
  DZ = "DZ",
  AS = "AS",
  AD = "AD",
  AO = "AO",
  AI = "AI",
  AQ = "AQ",
  AG = "AG",
  AR = "AR",
  AM = "AM",
  AW = "AW",
  AU = "AU",
  AT = "AT",
  AZ = "AZ",
  BS = "BS",
  BH = "BH",
  BD = "BD",
  BB = "BB",
  BY = "BY",
  BE = "BE",
  BZ = "BZ",
  BJ = "BJ",
  BM = "BM",
  BT = "BT",
  BO = "BO",
  BQ = "BQ",
  BA = "BA",
  BW = "BW",
  BV = "BV",
  BR = "BR",
  IO = "IO",
  VG = "VG",
  BN = "BN",
  BG = "BG",
  BF = "BF",
  BI = "BI",
  CV = "CV",
  KH = "KH",
  CM = "CM",
  CA = "CA",
  KY = "KY",
  CF = "CF",
  TD = "TD",
  CL = "CL",
  CN = "CN",
  CX = "CX",
  CC = "CC",
  CO = "CO",
  KM = "KM",
  CG = "CG",
  CD = "CD",
  CK = "CK",
  CR = "CR",
  CI = "CI",
  HR = "HR",
  CU = "CU",
  CW = "CW",
  CY = "CY",
  CZ = "CZ",
  DK = "DK",
  DJ = "DJ",
  DM = "DM",
  DO = "DO",
  EC = "EC",
  EG = "EG",
  SV = "SV",
  GQ = "GQ",
  ER = "ER",
  EE = "EE",
  SZ = "SZ",
  ET = "ET",
  FK = "FK",
  FO = "FO",
  FJ = "FJ",
  FI = "FI",
  FR = "FR",
  GF = "GF",
  PF = "PF",
  TF = "TF",
  GA = "GA",
  GM = "GM",
  GE = "GE",
  DE = "DE",
  GH = "GH",
  GI = "GI",
  GR = "GR",
  GD = "GD",
  GP = "GP",
  GU = "GU",
  GT = "GT",
  GG = "GG",
  GN = "GN",
  GW = "GW",
  GY = "GY",
  HT = "HT",
  HM = "HM",
  HN = "HN",
  HK = "HK",
  HU = "HU",
  IS = "IS",
  IN = "IN",
  ID = "ID",
  IR = "IR",
  IQ = "IQ",
  IE = "IE",
  IM = "IM",
  IL = "IL",
  IT = "IT",
  JM = "JM",
  JP = "JP",
  JE = "JE",
  JO = "JO",
  KZ = "KZ",
  KE = "KE",
  KI = "KI",
  KW = "KW",
  KG = "KG",
  LA = "LA",
  LV = "LV",
  LB = "LB",
  LS = "LS",
  LR = "LR",
  LY = "LY",
  LI = "LI",
  LT = "LT",
  LU = "LU",
  MO = "MO",
  MG = "MG",
  MW = "MW",
  MY = "MY",
  MV = "MV",
  ML = "ML",
  MT = "MT",
  MH = "MH",
  MQ = "MQ",
  MR = "MR",
  MU = "MU",
  YT = "YT",
  MX = "MX",
  FM = "FM",
  MD = "MD",
  MC = "MC",
  MN = "MN",
  ME = "ME",
  MS = "MS",
  MA = "MA",
  MZ = "MZ",
  MM = "MM",
  NA = "NA",
  NR = "NR",
  NP = "NP",
  NL = "NL",
  NC = "NC",
  NZ = "NZ",
  NI = "NI",
  NE = "NE",
  NG = "NG",
  NU = "NU",
  NF = "NF",
  KP = "KP",
  MK = "MK",
  MP = "MP",
  NO = "NO",
  OM = "OM",
  PK = "PK",
  PW = "PW",
  PS = "PS",
  PA = "PA",
  PG = "PG",
  PY = "PY",
  PE = "PE",
  PH = "PH",
  PN = "PN",
  PL = "PL",
  PT = "PT",
  PR = "PR",
  QA = "QA",
  RE = "RE",
  RO = "RO",
  RU = "RU",
  RW = "RW",
  BL = "BL",
  SH = "SH",
  KN = "KN",
  LC = "LC",
  MF = "MF",
  PM = "PM",
  VC = "VC",
  WS = "WS",
  SM = "SM",
  ST = "ST",
  SA = "SA",
  SN = "SN",
  RS = "RS",
  SC = "SC",
  SL = "SL",
  SG = "SG",
  SX = "SX",
  SK = "SK",
  SI = "SI",
  SB = "SB",
  SO = "SO",
  ZA = "ZA",
  GS = "GS",
  KR = "KR",
  SS = "SS",
  ES = "ES",
  LK = "LK",
  SD = "SD",
  SR = "SR",
  SJ = "SJ",
  SE = "SE",
  CH = "CH",
  SY = "SY",
  TW = "TW",
  TJ = "TJ",
  TZ = "TZ",
  TH = "TH",
  TL = "TL",
  TG = "TG",
  TK = "TK",
  TO = "TO",
  TT = "TT",
  TN = "TN",
  TR = "TR",
  TM = "TM",
  TC = "TC",
  TV = "TV",
  UG = "UG",
  UA = "UA",
  AE = "AE",
  GB = "GB",
  UM = "UM",
  US = "US",
  UY = "UY",
  UZ = "UZ",
  VU = "VU",
  VA = "VA",
  VE = "VE",
  VN = "VN",
  VI = "VI",
  WF = "WF",
  EH = "EH",
  YE = "YE",
  ZM = "ZM",
  ZW = "ZW",
}

export const countries: Record<CountryCode, Country> = {
  [CountryCode.AF]: {
    id: "afghanistan",
    alpha2Code: "AF",
    alpha3Code: "AFG",
    numericCode: 4,
    nativeName: "افغانستان",
    capital: "کابل",
    mainLanguage: "pashto",
    languages: ["pashto", "persian"] as const,
    tld: ".af",
    callingCode: 93,
    continent: "asia",
    currency: "afn",
  },
  [CountryCode.AX]: {
    id: "aalandIslands",
    alpha2Code: "AX",
    alpha3Code: "ALA",
    numericCode: 248,
    nativeName: "Åland",
    capital: "Mariehamn",
    mainLanguage: "swedish",
    languages: ["swedish"] as const,
    tld: ".ax",
    callingCode: 358,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.AL]: {
    id: "albania",
    alpha2Code: "AL",
    alpha3Code: "ALB",
    numericCode: 8,
    nativeName: "Shqipëria",
    capital: "Tiranë",
    mainLanguage: "albanian",
    languages: ["albanian"] as const,
    tld: ".al",
    callingCode: 355,
    continent: "europe",
    currency: "all",
  },
  [CountryCode.DZ]: {
    id: "algeria",
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    numericCode: 12,
    nativeName: "الجزائر",
    capital: "الجزائر",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".dz",
    callingCode: 213,
    continent: "africa",
    currency: "dzd",
  },
  [CountryCode.AS]: {
    id: "americanSamoa",
    alpha2Code: "AS",
    alpha3Code: "ASM",
    numericCode: 16,
    nativeName: "American Samoa",
    capital: "Pago Pago",
    mainLanguage: "english",
    languages: ["english", "samoan"] as const,
    tld: ".as",
    callingCode: 1,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.AD]: {
    id: "andorra",
    alpha2Code: "AD",
    alpha3Code: "AND",
    numericCode: 20,
    nativeName: "Andorra",
    capital: "Andorra la Vella",
    mainLanguage: "catalan",
    languages: ["catalan"] as const,
    tld: ".ad",
    callingCode: 376,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.AO]: {
    id: "angola",
    alpha2Code: "AO",
    alpha3Code: "AGO",
    numericCode: 24,
    nativeName: "Angola",
    capital: "Luanda",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".ao",
    callingCode: 244,
    continent: "africa",
    currency: "aoa",
  },
  [CountryCode.AI]: {
    id: "anguilla",
    alpha2Code: "AI",
    alpha3Code: "AIA",
    numericCode: 660,
    nativeName: "Anguilla",
    capital: "The Valley",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ai",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.AQ]: {
    id: "antarctica",
    alpha2Code: "AQ",
    alpha3Code: "ATA",
    numericCode: 10,
    nativeName: "Antarctica",
    capital: "",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".aq",
    callingCode: 672,
    continent: "antarctica",
    currency: "all",
  },
  [CountryCode.AG]: {
    id: "antiguaAndBarbuda",
    alpha2Code: "AG",
    alpha3Code: "ATG",
    numericCode: 28,
    nativeName: "Antigua and Barbuda",
    capital: "Saint John's",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ag",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.AR]: {
    id: "argentina",
    alpha2Code: "AR",
    alpha3Code: "ARG",
    numericCode: 32,
    nativeName: "Argentina",
    capital: "Buenos Aires",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".ar",
    callingCode: 54,
    continent: "southAmerica",
    currency: "ars",
  },
  [CountryCode.AM]: {
    id: "armenia",
    alpha2Code: "AM",
    alpha3Code: "ARM",
    numericCode: 51,
    nativeName: "Հայաստան",
    capital: "Երևան",
    mainLanguage: "armenian",
    languages: ["armenian"] as const,
    tld: ".am",
    callingCode: 374,
    continent: "asia",
    currency: "amd",
  },
  [CountryCode.AW]: {
    id: "aruba",
    alpha2Code: "AW",
    alpha3Code: "ABW",
    numericCode: 533,
    nativeName: "Aruba",
    capital: "Oranjestad",
    mainLanguage: "dutch",
    languages: ["dutch"] as const,
    tld: ".aw",
    callingCode: 297,
    continent: "northAmerica",
    currency: "awg",
  },
  [CountryCode.AU]: {
    id: "australia",
    alpha2Code: "AU",
    alpha3Code: "AUS",
    numericCode: 36,
    nativeName: "Australia",
    capital: "Canberra",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".au",
    callingCode: 61,
    continent: "oceania",
    currency: "aud",
  },
  [CountryCode.AT]: {
    id: "austria",
    alpha2Code: "AT",
    alpha3Code: "AUT",
    numericCode: 40,
    nativeName: "Österreich",
    capital: "Wien",
    mainLanguage: "german",
    languages: ["german"] as const,
    tld: ".at",
    callingCode: 43,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.AZ]: {
    id: "azerbaijan",
    alpha2Code: "AZ",
    alpha3Code: "AZE",
    numericCode: 31,
    nativeName: "Azərbaycan",
    capital: "Bakı",
    mainLanguage: "azerbaijani",
    languages: ["azerbaijani"] as const,
    tld: ".az",
    callingCode: 994,
    continent: "asia",
    currency: "azn",
  },
  [CountryCode.BS]: {
    id: "bahamas",
    alpha2Code: "BS",
    alpha3Code: "BHS",
    numericCode: 44,
    nativeName: "Bahamas",
    capital: "Nassau",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".bs",
    callingCode: 1,
    continent: "northAmerica",
    currency: "bsd",
  },
  [CountryCode.BH]: {
    id: "bahrain",
    alpha2Code: "BH",
    alpha3Code: "BHR",
    numericCode: 48,
    nativeName: "البحرين",
    capital: "المنامة",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".bh",
    callingCode: 973,
    continent: "asia",
    currency: "bhd",
  },
  [CountryCode.BD]: {
    id: "bangladesh",
    alpha2Code: "BD",
    alpha3Code: "BGD",
    numericCode: 50,
    nativeName: "বাংলাদেশ",
    capital: "ঢাকা",
    mainLanguage: "bengali",
    languages: ["bengali"] as const,
    tld: ".bd",
    callingCode: 880,
    continent: "asia",
    currency: "bdt",
  },
  [CountryCode.BB]: {
    id: "barbados",
    alpha2Code: "BB",
    alpha3Code: "BRB",
    numericCode: 52,
    nativeName: "Barbados",
    capital: "Bridgetown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".bb",
    callingCode: 1,
    continent: "northAmerica",
    currency: "bbd",
  },
  [CountryCode.BY]: {
    id: "belarus",
    alpha2Code: "BY",
    alpha3Code: "BLR",
    numericCode: 112,
    nativeName: "Беларусь",
    capital: "Мінск",
    mainLanguage: "belarusian",
    languages: ["belarusian", "russian"] as const,
    tld: ".by",
    callingCode: 375,
    continent: "europe",
    currency: "byn",
  },
  [CountryCode.BE]: {
    id: "belgium",
    alpha2Code: "BE",
    alpha3Code: "BEL",
    numericCode: 56,
    nativeName: "België",
    capital: "Brussel",
    mainLanguage: "dutch",
    languages: ["dutch", "french", "german"] as const,
    tld: ".be",
    callingCode: 32,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.BZ]: {
    id: "belize",
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
    numericCode: 84,
    nativeName: "Belize",
    capital: "Belmopan",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".bz",
    callingCode: 501,
    continent: "northAmerica",
    currency: "bzd",
  },
  [CountryCode.BJ]: {
    id: "benin",
    alpha2Code: "BJ",
    alpha3Code: "BEN",
    numericCode: 204,
    nativeName: "Bénin",
    capital: "Porto-Novo",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".bj",
    callingCode: 229,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.BM]: {
    id: "bermuda",
    alpha2Code: "BM",
    alpha3Code: "BMU",
    numericCode: 60,
    nativeName: "Bermuda",
    capital: "Hamilton",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".bm",
    callingCode: 1,
    continent: "northAmerica",
    currency: "bmd",
  },
  [CountryCode.BT]: {
    id: "bhutan",
    alpha2Code: "BT",
    alpha3Code: "BTN",
    numericCode: 64,
    nativeName: "འབྲུག",
    capital: "ཐིམ་ཕུ",
    mainLanguage: "dzongkha",
    languages: ["dzongkha"] as const,
    tld: ".bt",
    callingCode: 975,
    continent: "asia",
    currency: "inr",
  },
  [CountryCode.BO]: {
    id: "bolivia",
    alpha2Code: "BO",
    alpha3Code: "BOL",
    numericCode: 68,
    nativeName: "Bolivia",
    capital: "Sucre",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".bo",
    callingCode: 591,
    continent: "southAmerica",
    currency: "bob",
  },
  [CountryCode.BQ]: {
    id: "bonaireSintEustatiusAndSaba",
    alpha2Code: "BQ",
    alpha3Code: "BES",
    numericCode: 535,
    nativeName: "Bonaire, Sint Eustatius and Saba",
    capital: "Kralendijk",
    mainLanguage: "dutch",
    languages: ["dutch"] as const,
    tld: ".bq",
    callingCode: 599,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.BA]: {
    id: "bosniaAndHerzegovina",
    alpha2Code: "BA",
    alpha3Code: "BIH",
    numericCode: 70,
    nativeName: "Bosna i Hercegovina",
    capital: "Sarajevo",
    mainLanguage: "bosnian",
    languages: ["bosnian", "croatian", "serbian"] as const,
    tld: ".ba",
    callingCode: 387,
    continent: "europe",
    currency: "bam",
  },
  [CountryCode.BW]: {
    id: "botswana",
    alpha2Code: "BW",
    alpha3Code: "BWA",
    numericCode: 72,
    nativeName: "Botswana",
    capital: "Gaborone",
    mainLanguage: "english",
    languages: ["english", "tswana"] as const,
    tld: ".bw",
    callingCode: 267,
    continent: "africa",
    currency: "bwp",
  },
  [CountryCode.BV]: {
    id: "bouvetIsland",
    alpha2Code: "BV",
    alpha3Code: "BVT",
    numericCode: 74,
    nativeName: "Bouvet Island",
    capital: "",
    mainLanguage: "norwegian",
    languages: ["norwegian"] as const,
    tld: ".bv",
    callingCode: 47,
    continent: "antarctica",
    currency: "nok",
  },
  [CountryCode.BR]: {
    id: "brazil",
    alpha2Code: "BR",
    alpha3Code: "BRA",
    numericCode: 76,
    nativeName: "Brasil",
    capital: "Brasília",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".br",
    callingCode: 55,
    continent: "southAmerica",
    currency: "brl",
  },
  [CountryCode.IO]: {
    id: "britishIndianOceanTerritory",
    alpha2Code: "IO",
    alpha3Code: "IOT",
    numericCode: 86,
    nativeName: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".io",
    callingCode: 246,
    continent: "asia",
    currency: "usd",
  },
  [CountryCode.VG]: {
    id: "britishVirginIslands",
    alpha2Code: "VG",
    alpha3Code: "VGB",
    numericCode: 92,
    nativeName: "British Virgin Islands",
    capital: "Road Town",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".vg",
    callingCode: 1,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.BN]: {
    id: "brunei",
    alpha2Code: "BN",
    alpha3Code: "BRN",
    numericCode: 96,
    nativeName: "Brunei",
    capital: "Bandar Seri Begawan",
    mainLanguage: "malay",
    languages: ["malay"] as const,
    tld: ".bn",
    callingCode: 673,
    continent: "asia",
    currency: "bnd",
  },
  [CountryCode.BG]: {
    id: "bulgaria",
    alpha2Code: "BG",
    alpha3Code: "BGR",
    numericCode: 100,
    nativeName: "България",
    capital: "София",
    mainLanguage: "bulgarian",
    languages: ["bulgarian"] as const,
    tld: ".bg",
    callingCode: 359,
    continent: "europe",
    currency: "bgn",
  },
  [CountryCode.BF]: {
    id: "burkinaFaso",
    alpha2Code: "BF",
    alpha3Code: "BFA",
    numericCode: 854,
    nativeName: "Burkina Faso",
    capital: "Ouagadougou",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".bf",
    callingCode: 226,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.BI]: {
    id: "burundi",
    alpha2Code: "BI",
    alpha3Code: "BDI",
    numericCode: 108,
    nativeName: "Burundi",
    capital: "Gitega",
    mainLanguage: "rundi",
    languages: ["rundi", "french"] as const,
    tld: ".bi",
    callingCode: 257,
    continent: "africa",
    currency: "bif",
  },
  [CountryCode.CV]: {
    id: "caboVerde",
    alpha2Code: "CV",
    alpha3Code: "CPV",
    numericCode: 132,
    nativeName: "Cabo Verde",
    capital: "Praia",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".cv",
    callingCode: 238,
    continent: "africa",
    currency: "cve",
  },
  [CountryCode.KH]: {
    id: "cambodia",
    alpha2Code: "KH",
    alpha3Code: "KHM",
    numericCode: 116,
    nativeName: "កម្ពុជា",
    capital: "ភ្នំពេញ",
    mainLanguage: "khmer",
    languages: ["khmer"] as const,
    tld: ".kh",
    callingCode: 855,
    continent: "asia",
    currency: "khr",
  },
  [CountryCode.CM]: {
    id: "cameroon",
    alpha2Code: "CM",
    alpha3Code: "CMR",
    numericCode: 120,
    nativeName: "Cameroun",
    capital: "Yaoundé",
    mainLanguage: "french",
    languages: ["french", "english"] as const,
    tld: ".cm",
    callingCode: 237,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.CA]: {
    id: "canada",
    alpha2Code: "CA",
    alpha3Code: "CAN",
    numericCode: 124,
    nativeName: "Canada",
    capital: "Ottawa",
    mainLanguage: "english",
    languages: ["english", "french"] as const,
    tld: ".ca",
    callingCode: 1,
    continent: "northAmerica",
    currency: "cad",
  },
  [CountryCode.KY]: {
    id: "caymanIslands",
    alpha2Code: "KY",
    alpha3Code: "CYM",
    numericCode: 136,
    nativeName: "Cayman Islands",
    capital: "George Town",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ky",
    callingCode: 1,
    continent: "northAmerica",
    currency: "kyd",
  },
  [CountryCode.CF]: {
    id: "centralAfricanRepublic",
    alpha2Code: "CF",
    alpha3Code: "CAF",
    numericCode: 140,
    nativeName: "République centrafricaine",
    capital: "Bangui",
    mainLanguage: "french",
    languages: ["french", "sango"] as const,
    tld: ".cf",
    callingCode: 236,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.TD]: {
    id: "chad",
    alpha2Code: "TD",
    alpha3Code: "TCD",
    numericCode: 148,
    nativeName: "Tchad",
    capital: "N'Djamena",
    mainLanguage: "french",
    languages: ["french", "arabic"] as const,
    tld: ".td",
    callingCode: 235,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.CL]: {
    id: "chile",
    alpha2Code: "CL",
    alpha3Code: "CHL",
    numericCode: 152,
    nativeName: "Chile",
    capital: "Santiago",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".cl",
    callingCode: 56,
    continent: "southAmerica",
    currency: "clp",
  },
  [CountryCode.CN]: {
    id: "china",
    alpha2Code: "CN",
    alpha3Code: "CHN",
    numericCode: 156,
    nativeName: "中国",
    capital: "北京",
    mainLanguage: "chinese",
    languages: ["chinese"] as const,
    tld: ".cn",
    callingCode: 86,
    continent: "asia",
    currency: "cny",
  },
  [CountryCode.CX]: {
    id: "christmasIsland",
    alpha2Code: "CX",
    alpha3Code: "CXR",
    numericCode: 162,
    nativeName: "Christmas Island",
    capital: "Flying Fish Cove",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".cx",
    callingCode: 61,
    continent: "asia",
    currency: "aud",
  },
  [CountryCode.CC]: {
    id: "cocosKeelingIslands",
    alpha2Code: "CC",
    alpha3Code: "CCK",
    numericCode: 166,
    nativeName: "Cocos (Keeling) Islands",
    capital: "West Island",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".cc",
    callingCode: 61,
    continent: "asia",
    currency: "aud",
  },
  [CountryCode.CO]: {
    id: "colombia",
    alpha2Code: "CO",
    alpha3Code: "COL",
    numericCode: 170,
    nativeName: "Colombia",
    capital: "Bogotá",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".co",
    callingCode: 57,
    continent: "southAmerica",
    currency: "cop",
  },
  [CountryCode.KM]: {
    id: "comoros",
    alpha2Code: "KM",
    alpha3Code: "COM",
    numericCode: 174,
    nativeName: "Comores",
    capital: "Moroni",
    mainLanguage: "french",
    languages: ["french", "arabic"] as const,
    tld: ".km",
    callingCode: 269,
    continent: "africa",
    currency: "kmf",
  },
  [CountryCode.CG]: {
    id: "congo",
    alpha2Code: "CG",
    alpha3Code: "COG",
    numericCode: 178,
    nativeName: "Congo",
    capital: "Brazzaville",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".cg",
    callingCode: 242,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.CD]: {
    id: "congoDemocraticRepublic",
    alpha2Code: "CD",
    alpha3Code: "COD",
    numericCode: 180,
    nativeName: "Congo, Democratic Republic",
    capital: "Kinshasa",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".cd",
    callingCode: 243,
    continent: "africa",
    currency: "cdf",
  },
  [CountryCode.CK]: {
    id: "cookIslands",
    alpha2Code: "CK",
    alpha3Code: "COK",
    numericCode: 184,
    nativeName: "Cook Islands",
    capital: "Avarua",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ck",
    callingCode: 682,
    continent: "oceania",
    currency: "nzd",
  },
  [CountryCode.CR]: {
    id: "costaRica",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    numericCode: 188,
    nativeName: "Costa Rica",
    capital: "San José",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".cr",
    callingCode: 506,
    continent: "northAmerica",
    currency: "crc",
  },
  [CountryCode.CI]: {
    id: "coteDIvoire",
    alpha2Code: "CI",
    alpha3Code: "CIV",
    numericCode: 384,
    nativeName: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".ci",
    callingCode: 225,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.HR]: {
    id: "croatia",
    alpha2Code: "HR",
    alpha3Code: "HRV",
    numericCode: 191,
    nativeName: "Hrvatska",
    capital: "Zagreb",
    mainLanguage: "croatian",
    languages: ["croatian"] as const,
    tld: ".hr",
    callingCode: 385,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.CU]: {
    id: "cuba",
    alpha2Code: "CU",
    alpha3Code: "CUB",
    numericCode: 192,
    nativeName: "Cuba",
    capital: "La Habana",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".cu",
    callingCode: 53,
    continent: "northAmerica",
    currency: "cup",
  },
  [CountryCode.CW]: {
    id: "curacao",
    alpha2Code: "CW",
    alpha3Code: "CUW",
    numericCode: 531,
    nativeName: "Curaçao",
    capital: "Willemstad",
    mainLanguage: "dutch",
    languages: ["dutch"] as const,
    tld: ".cw",
    callingCode: 599,
    continent: "northAmerica",
    currency: "ang",
  },
  [CountryCode.CY]: {
    id: "cyprus",
    alpha2Code: "CY",
    alpha3Code: "CYP",
    numericCode: 196,
    nativeName: "Κύπρος",
    capital: "Λευκωσία",
    mainLanguage: "greek",
    languages: ["greek", "turkish"] as const,
    tld: ".cy",
    callingCode: 357,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.CZ]: {
    id: "czechia",
    alpha2Code: "CZ",
    alpha3Code: "CZE",
    numericCode: 203,
    nativeName: "Česko",
    capital: "Praha",
    mainLanguage: "czech",
    languages: ["czech"] as const,
    tld: ".cz",
    callingCode: 420,
    continent: "europe",
    currency: "czk",
  },
  [CountryCode.DK]: {
    id: "denmark",
    alpha2Code: "DK",
    alpha3Code: "DNK",
    numericCode: 208,
    nativeName: "Danmark",
    capital: "København",
    mainLanguage: "danish",
    languages: ["danish"] as const,
    tld: ".dk",
    callingCode: 45,
    continent: "europe",
    currency: "dkk",
  },
  [CountryCode.DJ]: {
    id: "djibouti",
    alpha2Code: "DJ",
    alpha3Code: "DJI",
    numericCode: 262,
    nativeName: "Djibouti",
    capital: "Djibouti",
    mainLanguage: "french",
    languages: ["french", "arabic"] as const,
    tld: ".dj",
    callingCode: 253,
    continent: "africa",
    currency: "djf",
  },
  [CountryCode.DM]: {
    id: "dominica",
    alpha2Code: "DM",
    alpha3Code: "DMA",
    numericCode: 212,
    nativeName: "Dominica",
    capital: "Roseau",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".dm",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.DO]: {
    id: "dominicanRepublic",
    alpha2Code: "DO",
    alpha3Code: "DOM",
    numericCode: 214,
    nativeName: "República Dominicana",
    capital: "Santo Domingo",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".do",
    callingCode: 1,
    continent: "northAmerica",
    currency: "dop",
  },
  [CountryCode.EC]: {
    id: "ecuador",
    alpha2Code: "EC",
    alpha3Code: "ECU",
    numericCode: 218,
    nativeName: "Ecuador",
    capital: "Quito",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".ec",
    callingCode: 593,
    continent: "southAmerica",
    currency: "usd",
  },
  [CountryCode.EG]: {
    id: "egypt",
    alpha2Code: "EG",
    alpha3Code: "EGY",
    numericCode: 818,
    nativeName: "مصر",
    capital: "القاهرة",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".eg",
    callingCode: 20,
    continent: "africa",
    currency: "egp",
  },
  [CountryCode.SV]: {
    id: "elSalvador",
    alpha2Code: "SV",
    alpha3Code: "SLV",
    numericCode: 222,
    nativeName: "El Salvador",
    capital: "San Salvador",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".sv",
    callingCode: 503,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.GQ]: {
    id: "equatorialGuinea",
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    numericCode: 226,
    nativeName: "Guinea Ecuatorial",
    capital: "Malabo",
    mainLanguage: "spanish",
    languages: ["spanish", "french", "portuguese"] as const,
    tld: ".gq",
    callingCode: 240,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.ER]: {
    id: "eritrea",
    alpha2Code: "ER",
    alpha3Code: "ERI",
    numericCode: 232,
    nativeName: "ኤርትራ",
    capital: "ኣስመራ",
    mainLanguage: "tigrinya",
    languages: ["tigrinya", "arabic", "english"] as const,
    tld: ".er",
    callingCode: 291,
    continent: "africa",
    currency: "ern",
  },
  [CountryCode.EE]: {
    id: "estonia",
    alpha2Code: "EE",
    alpha3Code: "EST",
    numericCode: 233,
    nativeName: "Eesti",
    capital: "Tallinn",
    mainLanguage: "estonian",
    languages: ["estonian"] as const,
    tld: ".ee",
    callingCode: 372,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.SZ]: {
    id: "eswatini",
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
    numericCode: 748,
    nativeName: "Eswatini",
    capital: "Mbabane",
    mainLanguage: "swati",
    languages: ["swati", "english"] as const,
    tld: ".sz",
    callingCode: 268,
    continent: "africa",
    currency: "szl",
  },
  [CountryCode.ET]: {
    id: "ethiopia",
    alpha2Code: "ET",
    alpha3Code: "ETH",
    numericCode: 231,
    nativeName: "ኢትዮጵያ",
    capital: "አዲስ አበባ",
    mainLanguage: "amharic",
    languages: ["amharic"] as const,
    tld: ".et",
    callingCode: 251,
    continent: "africa",
    currency: "etb",
  },
  [CountryCode.FK]: {
    id: "falklandIslands",
    alpha2Code: "FK",
    alpha3Code: "FLK",
    numericCode: 238,
    nativeName: "Falkland Islands",
    capital: "Stanley",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".fk",
    callingCode: 500,
    continent: "southAmerica",
    currency: "fkp",
  },
  [CountryCode.FO]: {
    id: "faroeIslands",
    alpha2Code: "FO",
    alpha3Code: "FRO",
    numericCode: 234,
    nativeName: "Føroyar",
    capital: "Tórshavn",
    mainLanguage: "faroese",
    languages: ["faroese", "danish"] as const,
    tld: ".fo",
    callingCode: 298,
    continent: "europe",
    currency: "dkk",
  },
  [CountryCode.FJ]: {
    id: "fiji",
    alpha2Code: "FJ",
    alpha3Code: "FJI",
    numericCode: 242,
    nativeName: "Fiji",
    capital: "Suva",
    mainLanguage: "english",
    languages: ["english", "fijian", "hindi"] as const,
    tld: ".fj",
    callingCode: 679,
    continent: "oceania",
    currency: "fjd",
  },
  [CountryCode.FI]: {
    id: "finland",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    numericCode: 246,
    nativeName: "Suomi",
    capital: "Helsinki",
    mainLanguage: "finnish",
    languages: ["finnish", "swedish"] as const,
    tld: ".fi",
    callingCode: 358,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.FR]: {
    id: "france",
    alpha2Code: "FR",
    alpha3Code: "FRA",
    numericCode: 250,
    nativeName: "France",
    capital: "Paris",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".fr",
    callingCode: 33,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.GF]: {
    id: "frenchGuiana",
    alpha2Code: "GF",
    alpha3Code: "GUF",
    numericCode: 254,
    nativeName: "Guyane française",
    capital: "Cayenne",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".gf",
    callingCode: 594,
    continent: "southAmerica",
    currency: "eur",
  },
  [CountryCode.PF]: {
    id: "frenchPolynesia",
    alpha2Code: "PF",
    alpha3Code: "PYF",
    numericCode: 258,
    nativeName: "Polynésie française",
    capital: "Papeete",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".pf",
    callingCode: 689,
    continent: "oceania",
    currency: "xpf",
  },
  [CountryCode.TF]: {
    id: "frenchSouthernTerritories",
    alpha2Code: "TF",
    alpha3Code: "ATF",
    numericCode: 260,
    nativeName: "French Southern Territories",
    capital: "Port-aux-Français",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".tf",
    callingCode: 262,
    continent: "antarctica",
    currency: "eur",
  },
  [CountryCode.GA]: {
    id: "gabon",
    alpha2Code: "GA",
    alpha3Code: "GAB",
    numericCode: 266,
    nativeName: "Gabon",
    capital: "Libreville",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".ga",
    callingCode: 241,
    continent: "africa",
    currency: "xaf",
  },
  [CountryCode.GM]: {
    id: "gambia",
    alpha2Code: "GM",
    alpha3Code: "GMB",
    numericCode: 270,
    nativeName: "Gambia",
    capital: "Banjul",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gm",
    callingCode: 220,
    continent: "africa",
    currency: "gmd",
  },
  [CountryCode.GE]: {
    id: "georgia",
    alpha2Code: "GE",
    alpha3Code: "GEO",
    numericCode: 268,
    nativeName: "საქართველო",
    capital: "თბილისი",
    mainLanguage: "georgian",
    languages: ["georgian"] as const,
    tld: ".ge",
    callingCode: 995,
    continent: "asia",
    currency: "gel",
  },
  [CountryCode.DE]: {
    id: "germany",
    alpha2Code: "DE",
    alpha3Code: "DEU",
    numericCode: 276,
    nativeName: "Deutschland",
    capital: "Berlin",
    mainLanguage: "german",
    languages: ["german"] as const,
    tld: ".de",
    callingCode: 49,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.GH]: {
    id: "ghana",
    alpha2Code: "GH",
    alpha3Code: "GHA",
    numericCode: 288,
    nativeName: "Ghana",
    capital: "Accra",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gh",
    callingCode: 233,
    continent: "africa",
    currency: "ghs",
  },
  [CountryCode.GI]: {
    id: "gibraltar",
    alpha2Code: "GI",
    alpha3Code: "GIB",
    numericCode: 292,
    nativeName: "Gibraltar",
    capital: "Gibraltar",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gi",
    callingCode: 350,
    continent: "europe",
    currency: "gip",
  },
  [CountryCode.GR]: {
    id: "greece",
    alpha2Code: "GR",
    alpha3Code: "GRC",
    numericCode: 300,
    nativeName: "Ελλάδα",
    capital: "Αθήνα",
    mainLanguage: "greek",
    languages: ["greek"] as const,
    tld: ".gr",
    callingCode: 30,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.GD]: {
    id: "grenada",
    alpha2Code: "GD",
    alpha3Code: "GRD",
    numericCode: 308,
    nativeName: "Grenada",
    capital: "St. George's",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gd",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.GP]: {
    id: "guadeloupe",
    alpha2Code: "GP",
    alpha3Code: "GLP",
    numericCode: 312,
    nativeName: "Guadeloupe",
    capital: "Basse-Terre",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".gp",
    callingCode: 590,
    continent: "northAmerica",
    currency: "eur",
  },
  [CountryCode.GU]: {
    id: "guam",
    alpha2Code: "GU",
    alpha3Code: "GUM",
    numericCode: 316,
    nativeName: "Guam",
    capital: "Hagåtña",
    mainLanguage: "english",
    languages: ["english", "chamorro"] as const,
    tld: ".gu",
    callingCode: 1,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.GT]: {
    id: "guatemala",
    alpha2Code: "GT",
    alpha3Code: "GTM",
    numericCode: 320,
    nativeName: "Guatemala",
    capital: "Ciudad de Guatemala",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".gt",
    callingCode: 502,
    continent: "northAmerica",
    currency: "gtq",
  },
  [CountryCode.GG]: {
    id: "guernsey",
    alpha2Code: "GG",
    alpha3Code: "GGY",
    numericCode: 831,
    nativeName: "Guernsey",
    capital: "St Peter Port",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gg",
    callingCode: 44,
    continent: "europe",
    currency: "gbp",
  },
  [CountryCode.GN]: {
    id: "guinea",
    alpha2Code: "GN",
    alpha3Code: "GIN",
    numericCode: 324,
    nativeName: "Guinée",
    capital: "Conakry",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".gn",
    callingCode: 224,
    continent: "africa",
    currency: "gnf",
  },
  [CountryCode.GW]: {
    id: "guineaBissau",
    alpha2Code: "GW",
    alpha3Code: "GNB",
    numericCode: 624,
    nativeName: "Guiné-Bissau",
    capital: "Bissau",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".gw",
    callingCode: 245,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.GY]: {
    id: "guyana",
    alpha2Code: "GY",
    alpha3Code: "GUY",
    numericCode: 328,
    nativeName: "Guyana",
    capital: "Georgetown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gy",
    callingCode: 592,
    continent: "southAmerica",
    currency: "gyd",
  },
  [CountryCode.HT]: {
    id: "haiti",
    alpha2Code: "HT",
    alpha3Code: "HTI",
    numericCode: 332,
    nativeName: "Haïti",
    capital: "Port-au-Prince",
    mainLanguage: "french",
    languages: ["french", "haitian"] as const,
    tld: ".ht",
    callingCode: 509,
    continent: "northAmerica",
    currency: "htg",
  },
  [CountryCode.HM]: {
    id: "heardIslandAndMcDonaldIslands",
    alpha2Code: "HM",
    alpha3Code: "HMD",
    numericCode: 334,
    nativeName: "Heard Island and McDonald Islands",
    capital: "",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".hm",
    callingCode: 672,
    continent: "antarctica",
    currency: "usd",
  },
  [CountryCode.HN]: {
    id: "honduras",
    alpha2Code: "HN",
    alpha3Code: "HND",
    numericCode: 340,
    nativeName: "Honduras",
    capital: "Tegucigalpa",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".hn",
    callingCode: 504,
    continent: "northAmerica",
    currency: "hnl",
  },
  [CountryCode.HK]: {
    id: "hongKong",
    alpha2Code: "HK",
    alpha3Code: "HKG",
    numericCode: 344,
    nativeName: "香港",
    capital: "香港",
    mainLanguage: "chinese",
    languages: ["chinese", "english"] as const,
    tld: ".hk",
    callingCode: 852,
    continent: "asia",
    currency: "hkd",
  },
  [CountryCode.HU]: {
    id: "hungary",
    alpha2Code: "HU",
    alpha3Code: "HUN",
    numericCode: 348,
    nativeName: "Magyarország",
    capital: "Budapest",
    mainLanguage: "hungarian",
    languages: ["hungarian"] as const,
    tld: ".hu",
    callingCode: 36,
    continent: "europe",
    currency: "huf",
  },
  [CountryCode.IS]: {
    id: "iceland",
    alpha2Code: "IS",
    alpha3Code: "ISL",
    numericCode: 352,
    nativeName: "Ísland",
    capital: "Reykjavík",
    mainLanguage: "icelandic",
    languages: ["icelandic"] as const,
    tld: ".is",
    callingCode: 354,
    continent: "europe",
    currency: "isk",
  },
  [CountryCode.IN]: {
    id: "india",
    alpha2Code: "IN",
    alpha3Code: "IND",
    numericCode: 356,
    nativeName: "भारत",
    capital: "नई दिल्ली",
    mainLanguage: "hindi",
    languages: ["hindi", "english"] as const,
    tld: ".in",
    callingCode: 91,
    continent: "asia",
    currency: "inr",
  },
  [CountryCode.ID]: {
    id: "indonesia",
    alpha2Code: "ID",
    alpha3Code: "IDN",
    numericCode: 360,
    nativeName: "Indonesia",
    capital: "Jakarta",
    mainLanguage: "indonesian",
    languages: ["indonesian"] as const,
    tld: ".id",
    callingCode: 62,
    continent: "asia",
    currency: "idr",
  },
  [CountryCode.IR]: {
    id: "iran",
    alpha2Code: "IR",
    alpha3Code: "IRN",
    numericCode: 364,
    nativeName: "ایران",
    capital: "تهران",
    mainLanguage: "persian",
    languages: ["persian"] as const,
    tld: ".ir",
    callingCode: 98,
    continent: "asia",
    currency: "irr",
  },
  [CountryCode.IQ]: {
    id: "iraq",
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
    numericCode: 368,
    nativeName: "العراق",
    capital: "بغداد",
    mainLanguage: "arabic",
    languages: ["arabic", "kurdish"] as const,
    tld: ".iq",
    callingCode: 964,
    continent: "asia",
    currency: "iqd",
  },
  [CountryCode.IE]: {
    id: "ireland",
    alpha2Code: "IE",
    alpha3Code: "IRL",
    numericCode: 372,
    nativeName: "Éire",
    capital: "Baile Átha Cliath",
    mainLanguage: "english",
    languages: ["english", "irish"] as const,
    tld: ".ie",
    callingCode: 353,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.IM]: {
    id: "isleOfMan",
    alpha2Code: "IM",
    alpha3Code: "IMN",
    numericCode: 833,
    nativeName: "Isle of Man",
    capital: "Douglas",
    mainLanguage: "english",
    languages: ["english", "manx"] as const,
    tld: ".im",
    callingCode: 44,
    continent: "europe",
    currency: "gbp",
  },
  [CountryCode.IL]: {
    id: "israel",
    alpha2Code: "IL",
    alpha3Code: "ISR",
    numericCode: 376,
    nativeName: "ישראל",
    capital: "ירושלים",
    mainLanguage: "hebrew",
    languages: ["hebrew", "arabic"] as const,
    tld: ".il",
    callingCode: 972,
    continent: "asia",
    currency: "ils",
  },
  [CountryCode.IT]: {
    id: "italy",
    alpha2Code: "IT",
    alpha3Code: "ITA",
    numericCode: 380,
    nativeName: "Italia",
    capital: "Roma",
    mainLanguage: "italian",
    languages: ["italian"] as const,
    tld: ".it",
    callingCode: 39,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.JM]: {
    id: "jamaica",
    alpha2Code: "JM",
    alpha3Code: "JAM",
    numericCode: 388,
    nativeName: "Jamaica",
    capital: "Kingston",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".jm",
    callingCode: 1,
    continent: "northAmerica",
    currency: "jmd",
  },
  [CountryCode.JP]: {
    id: "japan",
    alpha2Code: "JP",
    alpha3Code: "JPN",
    numericCode: 392,
    nativeName: "日本",
    capital: "東京",
    mainLanguage: "japanese",
    languages: ["japanese"] as const,
    tld: ".jp",
    callingCode: 81,
    continent: "asia",
    currency: "jpy",
  },
  [CountryCode.JE]: {
    id: "jersey",
    alpha2Code: "JE",
    alpha3Code: "JEY",
    numericCode: 832,
    nativeName: "Jersey",
    capital: "Saint Helier",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".je",
    callingCode: 44,
    continent: "europe",
    currency: "gbp",
  },
  [CountryCode.JO]: {
    id: "jordan",
    alpha2Code: "JO",
    alpha3Code: "JOR",
    numericCode: 400,
    nativeName: "الأردن",
    capital: "عمّان",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".jo",
    callingCode: 962,
    continent: "asia",
    currency: "jod",
  },
  [CountryCode.KZ]: {
    id: "kazakhstan",
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
    numericCode: 398,
    nativeName: "Қазақстан",
    capital: "Астана",
    mainLanguage: "kazakh",
    languages: ["kazakh", "russian"] as const,
    tld: ".kz",
    callingCode: 7,
    continent: "asia",
    currency: "kzt",
  },
  [CountryCode.KE]: {
    id: "kenya",
    alpha2Code: "KE",
    alpha3Code: "KEN",
    numericCode: 404,
    nativeName: "Kenya",
    capital: "Nairobi",
    mainLanguage: "swahili",
    languages: ["swahili", "english"] as const,
    tld: ".ke",
    callingCode: 254,
    continent: "africa",
    currency: "kes",
  },
  [CountryCode.KI]: {
    id: "kiribati",
    alpha2Code: "KI",
    alpha3Code: "KIR",
    numericCode: 296,
    nativeName: "Kiribati",
    capital: "Tarawa",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ki",
    callingCode: 686,
    continent: "oceania",
    currency: "aud",
  },
  [CountryCode.KW]: {
    id: "kuwait",
    alpha2Code: "KW",
    alpha3Code: "KWT",
    numericCode: 414,
    nativeName: "الكويت",
    capital: "مدينة الكويت",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".kw",
    callingCode: 965,
    continent: "asia",
    currency: "kwd",
  },
  [CountryCode.KG]: {
    id: "kyrgyzstan",
    alpha2Code: "KG",
    alpha3Code: "KGZ",
    numericCode: 417,
    nativeName: "Кыргызстан",
    capital: "Бишкек",
    mainLanguage: "kirghiz",
    languages: ["kirghiz", "russian"] as const,
    tld: ".kg",
    callingCode: 996,
    continent: "asia",
    currency: "kgs",
  },
  [CountryCode.LA]: {
    id: "laos",
    alpha2Code: "LA",
    alpha3Code: "LAO",
    numericCode: 418,
    nativeName: "ສປປລາວ",
    capital: "ວຽງຈັນ",
    mainLanguage: "lao",
    languages: ["lao"] as const,
    tld: ".la",
    callingCode: 856,
    continent: "asia",
    currency: "lak",
  },
  [CountryCode.LV]: {
    id: "latvia",
    alpha2Code: "LV",
    alpha3Code: "LVA",
    numericCode: 428,
    nativeName: "Latvija",
    capital: "Rīga",
    mainLanguage: "latvian",
    languages: ["latvian"] as const,
    tld: ".lv",
    callingCode: 371,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.LB]: {
    id: "lebanon",
    alpha2Code: "LB",
    alpha3Code: "LBN",
    numericCode: 422,
    nativeName: "لبنان",
    capital: "بيروت",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".lb",
    callingCode: 961,
    continent: "asia",
    currency: "lbp",
  },
  [CountryCode.LS]: {
    id: "lesotho",
    alpha2Code: "LS",
    alpha3Code: "LSO",
    numericCode: 426,
    nativeName: "Lesotho",
    capital: "Maseru",
    mainLanguage: "english",
    languages: ["english", "southernSotho"] as const,
    tld: ".ls",
    callingCode: 266,
    continent: "africa",
    currency: "lsl",
  },
  [CountryCode.LR]: {
    id: "liberia",
    alpha2Code: "LR",
    alpha3Code: "LBR",
    numericCode: 430,
    nativeName: "Liberia",
    capital: "Monrovia",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".lr",
    callingCode: 231,
    continent: "africa",
    currency: "lrd",
  },
  [CountryCode.LY]: {
    id: "libya",
    alpha2Code: "LY",
    alpha3Code: "LBY",
    numericCode: 434,
    nativeName: "ليبيا",
    capital: "طرابلس",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".ly",
    callingCode: 218,
    continent: "africa",
    currency: "lyd",
  },
  [CountryCode.LI]: {
    id: "liechtenstein",
    alpha2Code: "LI",
    alpha3Code: "LIE",
    numericCode: 438,
    nativeName: "Liechtenstein",
    capital: "Vaduz",
    mainLanguage: "german",
    languages: ["german"] as const,
    tld: ".li",
    callingCode: 423,
    continent: "europe",
    currency: "chf",
  },
  [CountryCode.LT]: {
    id: "lithuania",
    alpha2Code: "LT",
    alpha3Code: "LTU",
    numericCode: 440,
    nativeName: "Lietuva",
    capital: "Vilnius",
    mainLanguage: "lithuanian",
    languages: ["lithuanian"] as const,
    tld: ".lt",
    callingCode: 370,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.LU]: {
    id: "luxembourg",
    alpha2Code: "LU",
    alpha3Code: "LUX",
    numericCode: 442,
    nativeName: "Luxembourg",
    capital: "Luxembourg",
    mainLanguage: "luxembourgish",
    languages: ["luxembourgish", "french", "german"] as const,
    tld: ".lu",
    callingCode: 352,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.MO]: {
    id: "macao",
    alpha2Code: "MO",
    alpha3Code: "MAC",
    numericCode: 446,
    nativeName: "澳門",
    capital: "澳門",
    mainLanguage: "chinese",
    languages: ["chinese", "portuguese"] as const,
    tld: ".mo",
    callingCode: 853,
    continent: "asia",
    currency: "mop",
  },
  [CountryCode.MG]: {
    id: "madagascar",
    alpha2Code: "MG",
    alpha3Code: "MDG",
    numericCode: 450,
    nativeName: "Madagasikara",
    capital: "Antananarivo",
    mainLanguage: "malagasy",
    languages: ["malagasy", "french"] as const,
    tld: ".mg",
    callingCode: 261,
    continent: "africa",
    currency: "mga",
  },
  [CountryCode.MW]: {
    id: "malawi",
    alpha2Code: "MW",
    alpha3Code: "MWI",
    numericCode: 454,
    nativeName: "Malawi",
    capital: "Lilongwe",
    mainLanguage: "english",
    languages: ["english", "chichewa"] as const,
    tld: ".mw",
    callingCode: 265,
    continent: "africa",
    currency: "mwk",
  },
  [CountryCode.MY]: {
    id: "malaysia",
    alpha2Code: "MY",
    alpha3Code: "MYS",
    numericCode: 458,
    nativeName: "Malaysia",
    capital: "Kuala Lumpur",
    mainLanguage: "malay",
    languages: ["malay"] as const,
    tld: ".my",
    callingCode: 60,
    continent: "asia",
    currency: "myr",
  },
  [CountryCode.MV]: {
    id: "maldives",
    alpha2Code: "MV",
    alpha3Code: "MDV",
    numericCode: 462,
    nativeName: "ދިވެހިރާއްޖެ",
    capital: "މާލެ",
    mainLanguage: "divehi",
    languages: ["divehi"] as const,
    tld: ".mv",
    callingCode: 960,
    continent: "asia",
    currency: "mvr",
  },
  [CountryCode.ML]: {
    id: "mali",
    alpha2Code: "ML",
    alpha3Code: "MLI",
    numericCode: 466,
    nativeName: "Mali",
    capital: "Bamako",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".ml",
    callingCode: 223,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.MT]: {
    id: "malta",
    alpha2Code: "MT",
    alpha3Code: "MLT",
    numericCode: 470,
    nativeName: "Malta",
    capital: "Il-Belt Valletta",
    mainLanguage: "maltese",
    languages: ["maltese", "english"] as const,
    tld: ".mt",
    callingCode: 356,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.MH]: {
    id: "marshallIslands",
    alpha2Code: "MH",
    alpha3Code: "MHL",
    numericCode: 584,
    nativeName: "Marshall Islands",
    capital: "Majuro",
    mainLanguage: "english",
    languages: ["english", "marshallese"] as const,
    tld: ".mh",
    callingCode: 692,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.MQ]: {
    id: "martinique",
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
    numericCode: 474,
    nativeName: "Martinique",
    capital: "Fort-de-France",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".mq",
    callingCode: 596,
    continent: "northAmerica",
    currency: "eur",
  },
  [CountryCode.MR]: {
    id: "mauritania",
    alpha2Code: "MR",
    alpha3Code: "MRT",
    numericCode: 478,
    nativeName: "موريتانيا",
    capital: "نواكشوط",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".mr",
    callingCode: 222,
    continent: "africa",
    currency: "mru",
  },
  [CountryCode.MU]: {
    id: "mauritius",
    alpha2Code: "MU",
    alpha3Code: "MUS",
    numericCode: 480,
    nativeName: "Maurice",
    capital: "Port Louis",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".mu",
    callingCode: 230,
    continent: "africa",
    currency: "mur",
  },
  [CountryCode.YT]: {
    id: "mayotte",
    alpha2Code: "YT",
    alpha3Code: "MYT",
    numericCode: 175,
    nativeName: "Mayotte",
    capital: "Mamoudzou",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".yt",
    callingCode: 262,
    continent: "africa",
    currency: "eur",
  },
  [CountryCode.MX]: {
    id: "mexico",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    numericCode: 484,
    nativeName: "México",
    capital: "Ciudad de México",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".mx",
    callingCode: 52,
    continent: "northAmerica",
    currency: "mxn",
  },
  [CountryCode.FM]: {
    id: "micronesia",
    alpha2Code: "FM",
    alpha3Code: "FSM",
    numericCode: 583,
    nativeName: "Micronesia",
    capital: "Palikir",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".fm",
    callingCode: 691,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.MD]: {
    id: "moldova",
    alpha2Code: "MD",
    alpha3Code: "MDA",
    numericCode: 498,
    nativeName: "Moldova",
    capital: "Chișinău",
    mainLanguage: "romanian",
    languages: ["romanian"] as const,
    tld: ".md",
    callingCode: 373,
    continent: "europe",
    currency: "mdl",
  },
  [CountryCode.MC]: {
    id: "monaco",
    alpha2Code: "MC",
    alpha3Code: "MCO",
    numericCode: 492,
    nativeName: "Monaco",
    capital: "Monaco",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".mc",
    callingCode: 377,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.MN]: {
    id: "mongolia",
    alpha2Code: "MN",
    alpha3Code: "MNG",
    numericCode: 496,
    nativeName: "Монгол улс",
    capital: "Улаанбаатар",
    mainLanguage: "mongolian",
    languages: ["mongolian"] as const,
    tld: ".mn",
    callingCode: 976,
    continent: "asia",
    currency: "mnt",
  },
  [CountryCode.ME]: {
    id: "montenegro",
    alpha2Code: "ME",
    alpha3Code: "MNE",
    numericCode: 499,
    nativeName: "Црна Гора",
    capital: "Podgorica",
    mainLanguage: "serbian",
    languages: ["serbian"] as const,
    tld: ".me",
    callingCode: 382,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.MS]: {
    id: "montserrat",
    alpha2Code: "MS",
    alpha3Code: "MSR",
    numericCode: 500,
    nativeName: "Montserrat",
    capital: "Plymouth",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ms",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.MA]: {
    id: "morocco",
    alpha2Code: "MA",
    alpha3Code: "MAR",
    numericCode: 504,
    nativeName: "المغرب",
    capital: "الرباط",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".ma",
    callingCode: 212,
    continent: "africa",
    currency: "mad",
  },
  [CountryCode.MZ]: {
    id: "mozambique",
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
    numericCode: 508,
    nativeName: "Moçambique",
    capital: "Maputo",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".mz",
    callingCode: 258,
    continent: "africa",
    currency: "mzn",
  },
  [CountryCode.MM]: {
    id: "myanmar",
    alpha2Code: "MM",
    alpha3Code: "MMR",
    numericCode: 104,
    nativeName: "မြန်မာ",
    capital: "နေပြည်တော်",
    mainLanguage: "burmese",
    languages: ["burmese"] as const,
    tld: ".mm",
    callingCode: 95,
    continent: "asia",
    currency: "mmk",
  },
  [CountryCode.NA]: {
    id: "namibia",
    alpha2Code: "NA",
    alpha3Code: "NAM",
    numericCode: 516,
    nativeName: "Namibia",
    capital: "Windhoek",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".na",
    callingCode: 264,
    continent: "africa",
    currency: "nad",
  },
  [CountryCode.NR]: {
    id: "nauru",
    alpha2Code: "NR",
    alpha3Code: "NRU",
    numericCode: 520,
    nativeName: "Nauru",
    capital: "Yaren",
    mainLanguage: "nauru",
    languages: ["nauru", "english"] as const,
    tld: ".nr",
    callingCode: 674,
    continent: "oceania",
    currency: "aud",
  },
  [CountryCode.NP]: {
    id: "nepal",
    alpha2Code: "NP",
    alpha3Code: "NPL",
    numericCode: 524,
    nativeName: "नेपाल",
    capital: "काठमाडौं",
    mainLanguage: "nepali",
    languages: ["nepali"] as const,
    tld: ".np",
    callingCode: 977,
    continent: "asia",
    currency: "npr",
  },
  [CountryCode.NL]: {
    id: "netherlands",
    alpha2Code: "NL",
    alpha3Code: "NLD",
    numericCode: 528,
    nativeName: "Nederland",
    capital: "Amsterdam",
    mainLanguage: "dutch",
    languages: ["dutch"] as const,
    tld: ".nl",
    callingCode: 31,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.NC]: {
    id: "newCaledonia",
    alpha2Code: "NC",
    alpha3Code: "NCL",
    numericCode: 540,
    nativeName: "Nouvelle-Calédonie",
    capital: "Nouméa",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".nc",
    callingCode: 687,
    continent: "oceania",
    currency: "xpf",
  },
  [CountryCode.NZ]: {
    id: "newZealand",
    alpha2Code: "NZ",
    alpha3Code: "NZL",
    numericCode: 554,
    nativeName: "New Zealand",
    capital: "Wellington",
    mainLanguage: "english",
    languages: ["english", "maori"] as const,
    tld: ".nz",
    callingCode: 64,
    continent: "oceania",
    currency: "nzd",
  },
  [CountryCode.NI]: {
    id: "nicaragua",
    alpha2Code: "NI",
    alpha3Code: "NIC",
    numericCode: 558,
    nativeName: "Nicaragua",
    capital: "Managua",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".ni",
    callingCode: 505,
    continent: "northAmerica",
    currency: "nio",
  },
  [CountryCode.NE]: {
    id: "niger",
    alpha2Code: "NE",
    alpha3Code: "NER",
    numericCode: 562,
    nativeName: "Niger",
    capital: "Niamey",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".ne",
    callingCode: 227,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.NG]: {
    id: "nigeria",
    alpha2Code: "NG",
    alpha3Code: "NGA",
    numericCode: 566,
    nativeName: "Nigeria",
    capital: "Abuja",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ng",
    callingCode: 234,
    continent: "africa",
    currency: "ngn",
  },
  [CountryCode.NU]: {
    id: "niue",
    alpha2Code: "NU",
    alpha3Code: "NIU",
    numericCode: 570,
    nativeName: "Niue",
    capital: "Alofi",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".nu",
    callingCode: 683,
    continent: "oceania",
    currency: "nzd",
  },
  [CountryCode.NF]: {
    id: "norfolkIsland",
    alpha2Code: "NF",
    alpha3Code: "NFK",
    numericCode: 574,
    nativeName: "Norfolk Island",
    capital: "Kingston",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".nf",
    callingCode: 672,
    continent: "oceania",
    currency: "aud",
  },
  [CountryCode.KP]: {
    id: "northKorea",
    alpha2Code: "KP",
    alpha3Code: "PRK",
    numericCode: 408,
    nativeName: "조선민주주의인민공화국",
    capital: "평양",
    mainLanguage: "korean",
    languages: ["korean"] as const,
    tld: ".kp",
    callingCode: 850,
    continent: "asia",
    currency: "kpw",
  },
  [CountryCode.MK]: {
    id: "northMacedonia",
    alpha2Code: "MK",
    alpha3Code: "MKD",
    numericCode: 807,
    nativeName: "Северна Македонија",
    capital: "Скопје",
    mainLanguage: "macedonian",
    languages: ["macedonian"] as const,
    tld: ".mk",
    callingCode: 389,
    continent: "europe",
    currency: "mkd",
  },
  [CountryCode.MP]: {
    id: "northernMarianaIslands",
    alpha2Code: "MP",
    alpha3Code: "MNP",
    numericCode: 580,
    nativeName: "Northern Mariana Islands",
    capital: "Saipan",
    mainLanguage: "english",
    languages: ["english", "chamorro"] as const,
    tld: ".mp",
    callingCode: 1,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.NO]: {
    id: "norway",
    alpha2Code: "NO",
    alpha3Code: "NOR",
    numericCode: 578,
    nativeName: "Norge",
    capital: "Oslo",
    mainLanguage: "norwegian",
    languages: ["norwegian"] as const,
    tld: ".no",
    callingCode: 47,
    continent: "europe",
    currency: "nok",
  },
  [CountryCode.OM]: {
    id: "oman",
    alpha2Code: "OM",
    alpha3Code: "OMN",
    numericCode: 512,
    nativeName: "عمان",
    capital: "مسقط",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".om",
    callingCode: 968,
    continent: "asia",
    currency: "omr",
  },
  [CountryCode.PK]: {
    id: "pakistan",
    alpha2Code: "PK",
    alpha3Code: "PAK",
    numericCode: 586,
    nativeName: "پاکستان",
    capital: "اسلام آباد",
    mainLanguage: "urdu",
    languages: ["urdu", "english"] as const,
    tld: ".pk",
    callingCode: 92,
    continent: "asia",
    currency: "pkr",
  },
  [CountryCode.PW]: {
    id: "palau",
    alpha2Code: "PW",
    alpha3Code: "PLW",
    numericCode: 585,
    nativeName: "Palau",
    capital: "Ngerulmud",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".pw",
    callingCode: 680,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.PS]: {
    id: "palestine",
    alpha2Code: "PS",
    alpha3Code: "PSE",
    numericCode: 275,
    nativeName: "فلسطين",
    capital: "رام الله",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".ps",
    callingCode: 970,
    continent: "asia",
    currency: "ils",
  },
  [CountryCode.PA]: {
    id: "panama",
    alpha2Code: "PA",
    alpha3Code: "PAN",
    numericCode: 591,
    nativeName: "Panamá",
    capital: "Ciudad de Panamá",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".pa",
    callingCode: 507,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.PG]: {
    id: "papuaNewGuinea",
    alpha2Code: "PG",
    alpha3Code: "PNG",
    numericCode: 598,
    nativeName: "Papua New Guinea",
    capital: "Port Moresby",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".pg",
    callingCode: 675,
    continent: "oceania",
    currency: "pgk",
  },
  [CountryCode.PY]: {
    id: "paraguay",
    alpha2Code: "PY",
    alpha3Code: "PRY",
    numericCode: 600,
    nativeName: "Paraguay",
    capital: "Asunción",
    mainLanguage: "spanish",
    languages: ["spanish", "guarani"] as const,
    tld: ".py",
    callingCode: 595,
    continent: "southAmerica",
    currency: "pyg",
  },
  [CountryCode.PE]: {
    id: "peru",
    alpha2Code: "PE",
    alpha3Code: "PER",
    numericCode: 604,
    nativeName: "Perú",
    capital: "Lima",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".pe",
    callingCode: 51,
    continent: "southAmerica",
    currency: "pen",
  },
  [CountryCode.PH]: {
    id: "philippines",
    alpha2Code: "PH",
    alpha3Code: "PHL",
    numericCode: 608,
    nativeName: "Pilipinas",
    capital: "Manila",
    mainLanguage: "tagalog",
    languages: ["tagalog", "english"] as const,
    tld: ".ph",
    callingCode: 63,
    continent: "asia",
    currency: "php",
  },
  [CountryCode.PN]: {
    id: "pitcairn",
    alpha2Code: "PN",
    alpha3Code: "PCN",
    numericCode: 612,
    nativeName: "Pitcairn Islands",
    capital: "Adamstown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".pn",
    callingCode: 64,
    continent: "oceania",
    currency: "nzd",
  },
  [CountryCode.PL]: {
    id: "poland",
    alpha2Code: "PL",
    alpha3Code: "POL",
    numericCode: 616,
    nativeName: "Polska",
    capital: "Warszawa",
    mainLanguage: "polish",
    languages: ["polish"] as const,
    tld: ".pl",
    callingCode: 48,
    continent: "europe",
    currency: "pln",
  },
  [CountryCode.PT]: {
    id: "portugal",
    alpha2Code: "PT",
    alpha3Code: "PRT",
    numericCode: 620,
    nativeName: "Portugal",
    capital: "Lisboa",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".pt",
    callingCode: 351,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.PR]: {
    id: "puertoRico",
    alpha2Code: "PR",
    alpha3Code: "PRI",
    numericCode: 630,
    nativeName: "Puerto Rico",
    capital: "San Juan",
    mainLanguage: "spanish",
    languages: ["spanish", "english"] as const,
    tld: ".pr",
    callingCode: 1,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.QA]: {
    id: "qatar",
    alpha2Code: "QA",
    alpha3Code: "QAT",
    numericCode: 634,
    nativeName: "قطر",
    capital: "الدوحة",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".qa",
    callingCode: 974,
    continent: "asia",
    currency: "qar",
  },
  [CountryCode.RE]: {
    id: "reunion",
    alpha2Code: "RE",
    alpha3Code: "REU",
    numericCode: 638,
    nativeName: "Réunion",
    capital: "Saint-Denis",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".re",
    callingCode: 262,
    continent: "africa",
    currency: "eur",
  },
  [CountryCode.RO]: {
    id: "romania",
    alpha2Code: "RO",
    alpha3Code: "ROU",
    numericCode: 642,
    nativeName: "România",
    capital: "București",
    mainLanguage: "romanian",
    languages: ["romanian"] as const,
    tld: ".ro",
    callingCode: 40,
    continent: "europe",
    currency: "ron",
  },
  [CountryCode.RU]: {
    id: "russia",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    numericCode: 643,
    nativeName: "Россия",
    capital: "Москва",
    mainLanguage: "russian",
    languages: ["russian"] as const,
    tld: ".ru",
    callingCode: 7,
    continent: "europe",
    currency: "rub",
  },
  [CountryCode.RW]: {
    id: "rwanda",
    alpha2Code: "RW",
    alpha3Code: "RWA",
    numericCode: 646,
    nativeName: "Rwanda",
    capital: "Kigali",
    mainLanguage: "kinyarwanda",
    languages: ["kinyarwanda", "french", "english"] as const,
    tld: ".rw",
    callingCode: 250,
    continent: "africa",
    currency: "rwf",
  },
  [CountryCode.BL]: {
    id: "saintBarthelemy",
    alpha2Code: "BL",
    alpha3Code: "BLM",
    numericCode: 652,
    nativeName: "Saint-Barthélemy",
    capital: "Gustavia",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".bl",
    callingCode: 590,
    continent: "northAmerica",
    currency: "eur",
  },
  [CountryCode.SH]: {
    id: "saintHelena",
    alpha2Code: "SH",
    alpha3Code: "SHN",
    numericCode: 654,
    nativeName: "Saint Helena",
    capital: "Jamestown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".sh",
    callingCode: 290,
    continent: "africa",
    currency: "svc",
  },
  [CountryCode.KN]: {
    id: "saintKittsAndNevis",
    alpha2Code: "KN",
    alpha3Code: "KNA",
    numericCode: 659,
    nativeName: "Saint Kitts and Nevis",
    capital: "Basseterre",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".kn",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.LC]: {
    id: "saintLucia",
    alpha2Code: "LC",
    alpha3Code: "LCA",
    numericCode: 662,
    nativeName: "Saint Lucia",
    capital: "Castries",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".lc",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.MF]: {
    id: "saintMartin",
    alpha2Code: "MF",
    alpha3Code: "MAF",
    numericCode: 663,
    nativeName: "Saint-Martin",
    capital: "Marigot",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".mf",
    callingCode: 590,
    continent: "northAmerica",
    currency: "eur",
  },
  [CountryCode.PM]: {
    id: "saintPierreAndMiquelon",
    alpha2Code: "PM",
    alpha3Code: "SPM",
    numericCode: 666,
    nativeName: "Saint-Pierre-et-Miquelon",
    capital: "Saint-Pierre",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".pm",
    callingCode: 508,
    continent: "northAmerica",
    currency: "eur",
  },
  [CountryCode.VC]: {
    id: "saintVincentAndTheGrenadines",
    alpha2Code: "VC",
    alpha3Code: "VCT",
    numericCode: 670,
    nativeName: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".vc",
    callingCode: 1,
    continent: "northAmerica",
    currency: "xcd",
  },
  [CountryCode.WS]: {
    id: "samoa",
    alpha2Code: "WS",
    alpha3Code: "WSM",
    numericCode: 882,
    nativeName: "Samoa",
    capital: "Apia",
    mainLanguage: "samoan",
    languages: ["samoan", "english"] as const,
    tld: ".ws",
    callingCode: 685,
    continent: "oceania",
    currency: "wst",
  },
  [CountryCode.SM]: {
    id: "sanMarino",
    alpha2Code: "SM",
    alpha3Code: "SMR",
    numericCode: 674,
    nativeName: "San Marino",
    capital: "San Marino",
    mainLanguage: "italian",
    languages: ["italian"] as const,
    tld: ".sm",
    callingCode: 378,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.ST]: {
    id: "saoTomeAndPrincipe",
    alpha2Code: "ST",
    alpha3Code: "STP",
    numericCode: 678,
    nativeName: "São Tomé e Príncipe",
    capital: "São Tomé",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".st",
    callingCode: 239,
    continent: "africa",
    currency: "stn",
  },
  [CountryCode.SA]: {
    id: "saudiArabia",
    alpha2Code: "SA",
    alpha3Code: "SAU",
    numericCode: 682,
    nativeName: "العربية السعودية",
    capital: "الرياض",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".sa",
    callingCode: 966,
    continent: "asia",
    currency: "sar",
  },
  [CountryCode.SN]: {
    id: "senegal",
    alpha2Code: "SN",
    alpha3Code: "SEN",
    numericCode: 686,
    nativeName: "Sénégal",
    capital: "Dakar",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".sn",
    callingCode: 221,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.RS]: {
    id: "serbia",
    alpha2Code: "RS",
    alpha3Code: "SRB",
    numericCode: 688,
    nativeName: "Србија",
    capital: "Београд",
    mainLanguage: "serbian",
    languages: ["serbian"] as const,
    tld: ".rs",
    callingCode: 381,
    continent: "europe",
    currency: "rsd",
  },
  [CountryCode.SC]: {
    id: "seychelles",
    alpha2Code: "SC",
    alpha3Code: "SYC",
    numericCode: 690,
    nativeName: "Seychelles",
    capital: "Victoria",
    mainLanguage: "french",
    languages: ["french", "english"] as const,
    tld: ".sc",
    callingCode: 248,
    continent: "africa",
    currency: "scr",
  },
  [CountryCode.SL]: {
    id: "sierraLeone",
    alpha2Code: "SL",
    alpha3Code: "SLE",
    numericCode: 694,
    nativeName: "Sierra Leone",
    capital: "Freetown",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".sl",
    callingCode: 232,
    continent: "africa",
    currency: "sle",
  },
  [CountryCode.SG]: {
    id: "singapore",
    alpha2Code: "SG",
    alpha3Code: "SGP",
    numericCode: 702,
    nativeName: "Singapore",
    capital: "Singapore",
    mainLanguage: "english",
    languages: ["english", "malay", "tamil", "chinese"] as const,
    tld: ".sg",
    callingCode: 65,
    continent: "asia",
    currency: "sgd",
  },
  [CountryCode.SX]: {
    id: "sintMaarten",
    alpha2Code: "SX",
    alpha3Code: "SXM",
    numericCode: 534,
    nativeName: "Sint Maarten",
    capital: "Philipsburg",
    mainLanguage: "dutch",
    languages: ["dutch", "english"] as const,
    tld: ".sx",
    callingCode: 1,
    continent: "northAmerica",
    currency: "ang",
  },
  [CountryCode.SK]: {
    id: "slovakia",
    alpha2Code: "SK",
    alpha3Code: "SVK",
    numericCode: 703,
    nativeName: "Slovensko",
    capital: "Bratislava",
    mainLanguage: "slovak",
    languages: ["slovak"] as const,
    tld: ".sk",
    callingCode: 421,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.SI]: {
    id: "slovenia",
    alpha2Code: "SI",
    alpha3Code: "SVN",
    numericCode: 705,
    nativeName: "Slovenija",
    capital: "Ljubljana",
    mainLanguage: "slovenian",
    languages: ["slovenian"] as const,
    tld: ".si",
    callingCode: 386,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.SB]: {
    id: "solomonIslands",
    alpha2Code: "SB",
    alpha3Code: "SLB",
    numericCode: 90,
    nativeName: "Solomon Islands",
    capital: "Honiara",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".sb",
    callingCode: 677,
    continent: "oceania",
    currency: "sbd",
  },
  [CountryCode.SO]: {
    id: "somalia",
    alpha2Code: "SO",
    alpha3Code: "SOM",
    numericCode: 706,
    nativeName: "Soomaaliya",
    capital: "Muqdisho",
    mainLanguage: "somali",
    languages: ["somali", "arabic"] as const,
    tld: ".so",
    callingCode: 252,
    continent: "africa",
    currency: "sos",
  },
  [CountryCode.ZA]: {
    id: "southAfrica",
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    numericCode: 710,
    nativeName: "South Africa",
    capital: "Pretoria",
    mainLanguage: "english",
    languages: ["english", "afrikaans", "southNdebele", "southernSotho", "swati", "tsonga", "tswana", "venda", "xhosa", "zulu"] as const,
    tld: ".za",
    callingCode: 27,
    continent: "africa",
    currency: "zar",
  },
  [CountryCode.GS]: {
    id: "southGeorgiaAndTheSouthSandwichIslands",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    numericCode: 239,
    nativeName: "South Georgia and the South Sandwich Islands",
    capital: "King Edward Point",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".gs",
    callingCode: 500,
    continent: "antarctica",
    currency: "gbp",
  },
  [CountryCode.KR]: {
    id: "southKorea",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    numericCode: 410,
    nativeName: "대한민국",
    capital: "서울",
    mainLanguage: "korean",
    languages: ["korean"] as const,
    tld: ".kr",
    callingCode: 82,
    continent: "asia",
    currency: "krw",
  },
  [CountryCode.SS]: {
    id: "southSudan",
    alpha2Code: "SS",
    alpha3Code: "SSD",
    numericCode: 728,
    nativeName: "South Sudan",
    capital: "Juba",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ss",
    callingCode: 211,
    continent: "africa",
    currency: "ssp",
  },
  [CountryCode.ES]: {
    id: "spain",
    alpha2Code: "ES",
    alpha3Code: "ESP",
    numericCode: 724,
    nativeName: "España",
    capital: "Madrid",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".es",
    callingCode: 34,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.LK]: {
    id: "sriLanka",
    alpha2Code: "LK",
    alpha3Code: "LKA",
    numericCode: 144,
    nativeName: "ශ්‍රී ලංකාව",
    capital: "ශ්‍රී ජයවර්ධනපුර කෝට්ටේ",
    mainLanguage: "sinhala",
    languages: ["sinhala", "tamil"] as const,
    tld: ".lk",
    callingCode: 94,
    continent: "asia",
    currency: "lkr",
  },
  [CountryCode.SD]: {
    id: "sudan",
    alpha2Code: "SD",
    alpha3Code: "SDN",
    numericCode: 729,
    nativeName: "السودان",
    capital: "الخرطوم",
    mainLanguage: "arabic",
    languages: ["arabic", "english"] as const,
    tld: ".sd",
    callingCode: 249,
    continent: "africa",
    currency: "sdg",
  },
  [CountryCode.SR]: {
    id: "suriname",
    alpha2Code: "SR",
    alpha3Code: "SUR",
    numericCode: 740,
    nativeName: "Suriname",
    capital: "Paramaribo",
    mainLanguage: "dutch",
    languages: ["dutch"] as const,
    tld: ".sr",
    callingCode: 597,
    continent: "southAmerica",
    currency: "srd",
  },
  [CountryCode.SJ]: {
    id: "svalbardAndJanMayen",
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    numericCode: 744,
    nativeName: "Svalbard og Jan Mayen",
    capital: "Longyearbyen",
    mainLanguage: "norwegian",
    languages: ["norwegian"] as const,
    tld: ".sj",
    callingCode: 47,
    continent: "europe",
    currency: "nok",
  },
  [CountryCode.SE]: {
    id: "sweden",
    alpha2Code: "SE",
    alpha3Code: "SWE",
    numericCode: 752,
    nativeName: "Sverige",
    capital: "Stockholm",
    mainLanguage: "swedish",
    languages: ["swedish"] as const,
    tld: ".se",
    callingCode: 46,
    continent: "europe",
    currency: "sek",
  },
  [CountryCode.CH]: {
    id: "switzerland",
    alpha2Code: "CH",
    alpha3Code: "CHE",
    numericCode: 756,
    nativeName: "Schweiz",
    capital: "Bern",
    mainLanguage: "german",
    languages: ["german", "french", "italian"] as const,
    tld: ".ch",
    callingCode: 41,
    continent: "europe",
    currency: "chf",
  },
  [CountryCode.SY]: {
    id: "syria",
    alpha2Code: "SY",
    alpha3Code: "SYR",
    numericCode: 760,
    nativeName: "سوريا",
    capital: "دمشق",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".sy",
    callingCode: 963,
    continent: "asia",
    currency: "syp",
  },
  [CountryCode.TW]: {
    id: "taiwan",
    alpha2Code: "TW",
    alpha3Code: "TWN",
    numericCode: 158,
    nativeName: "臺灣",
    capital: "臺北",
    mainLanguage: "chinese",
    languages: ["chinese"] as const,
    tld: ".tw",
    callingCode: 886,
    continent: "asia",
    currency: "twd",
  },
  [CountryCode.TJ]: {
    id: "tajikistan",
    alpha2Code: "TJ",
    alpha3Code: "TJK",
    numericCode: 762,
    nativeName: "Тоҷикистон",
    capital: "Душанбе",
    mainLanguage: "tajik",
    languages: ["tajik", "russian"] as const,
    tld: ".tj",
    callingCode: 992,
    continent: "asia",
    currency: "tjs",
  },
  [CountryCode.TZ]: {
    id: "tanzania",
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    numericCode: 834,
    nativeName: "Tanzania",
    capital: "Dodoma",
    mainLanguage: "swahili",
    languages: ["swahili", "english"] as const,
    tld: ".tz",
    callingCode: 255,
    continent: "africa",
    currency: "tzs",
  },
  [CountryCode.TH]: {
    id: "thailand",
    alpha2Code: "TH",
    alpha3Code: "THA",
    numericCode: 764,
    nativeName: "ประเทศไทย",
    capital: "กรุงเทพมหานคร",
    mainLanguage: "thai",
    languages: ["thai"] as const,
    tld: ".th",
    callingCode: 66,
    continent: "asia",
    currency: "thb",
  },
  [CountryCode.TL]: {
    id: "timorLeste",
    alpha2Code: "TL",
    alpha3Code: "TLS",
    numericCode: 626,
    nativeName: "Timor-Leste",
    capital: "Dili",
    mainLanguage: "portuguese",
    languages: ["portuguese"] as const,
    tld: ".tl",
    callingCode: 670,
    continent: "asia",
    currency: "usd",
  },
  [CountryCode.TG]: {
    id: "togo",
    alpha2Code: "TG",
    alpha3Code: "TGO",
    numericCode: 768,
    nativeName: "Togo",
    capital: "Lomé",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".tg",
    callingCode: 228,
    continent: "africa",
    currency: "xof",
  },
  [CountryCode.TK]: {
    id: "tokelau",
    alpha2Code: "TK",
    alpha3Code: "TKL",
    numericCode: 772,
    nativeName: "Tokelau",
    capital: "Fakaofo",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".tk",
    callingCode: 690,
    continent: "oceania",
    currency: "nzd",
  },
  [CountryCode.TO]: {
    id: "tonga",
    alpha2Code: "TO",
    alpha3Code: "TON",
    numericCode: 776,
    nativeName: "Tonga",
    capital: "Nukuʻalofa",
    mainLanguage: "tonga",
    languages: ["tonga", "english"] as const,
    tld: ".to",
    callingCode: 676,
    continent: "oceania",
    currency: "top",
  },
  [CountryCode.TT]: {
    id: "trinidadAndTobago",
    alpha2Code: "TT",
    alpha3Code: "TTO",
    numericCode: 780,
    nativeName: "Trinidad and Tobago",
    capital: "Port of Spain",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".tt",
    callingCode: 1,
    continent: "northAmerica",
    currency: "ttd",
  },
  [CountryCode.TN]: {
    id: "tunisia",
    alpha2Code: "TN",
    alpha3Code: "TUN",
    numericCode: 788,
    nativeName: "تونس",
    capital: "Tunis",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".tn",
    callingCode: 216,
    continent: "africa",
    currency: "tnd",
  },
  [CountryCode.TR]: {
    id: "turkey",
    alpha2Code: "TR",
    alpha3Code: "TUR",
    numericCode: 792,
    nativeName: "Türkiye",
    capital: "Ankara",
    mainLanguage: "turkish",
    languages: ["turkish"] as const,
    tld: ".tr",
    callingCode: 90,
    continent: "europe",
    currency: "turkishLira",
  },
  [CountryCode.TM]: {
    id: "turkmenistan",
    alpha2Code: "TM",
    alpha3Code: "TKM",
    numericCode: 795,
    nativeName: "Türkmenistan",
    capital: "Aşgabat",
    mainLanguage: "turkmen",
    languages: ["turkmen", "russian"] as const,
    tld: ".tm",
    callingCode: 993,
    continent: "asia",
    currency: "tmt",
  },
  [CountryCode.TC]: {
    id: "turksAndCaicosIslands",
    alpha2Code: "TC",
    alpha3Code: "TCA",
    numericCode: 796,
    nativeName: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".tc",
    callingCode: 1,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.TV]: {
    id: "tuvalu",
    alpha2Code: "TV",
    alpha3Code: "TUV",
    numericCode: 798,
    nativeName: "Tuvalu",
    capital: "Funafuti",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".tv",
    callingCode: 688,
    continent: "oceania",
    currency: "aud",
  },
  [CountryCode.UG]: {
    id: "uganda",
    alpha2Code: "UG",
    alpha3Code: "UGA",
    numericCode: 800,
    nativeName: "Uganda",
    capital: "Kampala",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".ug",
    callingCode: 256,
    continent: "africa",
    currency: "ugx",
  },
  [CountryCode.UA]: {
    id: "ukraine",
    alpha2Code: "UA",
    alpha3Code: "UKR",
    numericCode: 804,
    nativeName: "Україна",
    capital: "Київ",
    mainLanguage: "ukrainian",
    languages: ["ukrainian"] as const,
    tld: ".ua",
    callingCode: 380,
    continent: "europe",
    currency: "uah",
  },
  [CountryCode.AE]: {
    id: "unitedArabEmirates",
    alpha2Code: "AE",
    alpha3Code: "ARE",
    numericCode: 784,
    nativeName: "الإمارات العربية المتحدة",
    capital: "أبو ظبي",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".ae",
    callingCode: 971,
    continent: "asia",
    currency: "aed",
  },
  [CountryCode.GB]: {
    id: "unitedKingdom",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    numericCode: 826,
    nativeName: "United Kingdom",
    capital: "London",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".uk",
    callingCode: 44,
    continent: "europe",
    currency: "gbp",
  },
  [CountryCode.UM]: {
    id: "unitedStatesMinorOutlyingIslands",
    alpha2Code: "UM",
    alpha3Code: "UMI",
    numericCode: 581,
    nativeName: "United States Minor Outlying Islands",
    capital: "",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".us",
    callingCode: 1,
    continent: "oceania",
    currency: "usd",
  },
  [CountryCode.US]: {
    id: "unitedStates",
    alpha2Code: "US",
    alpha3Code: "USA",
    numericCode: 840,
    nativeName: "United States",
    capital: "Washington, D.C.",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".us",
    callingCode: 1,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.UY]: {
    id: "uruguay",
    alpha2Code: "UY",
    alpha3Code: "URY",
    numericCode: 858,
    nativeName: "Uruguay",
    capital: "Montevideo",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".uy",
    callingCode: 598,
    continent: "southAmerica",
    currency: "uyu",
  },
  [CountryCode.UZ]: {
    id: "uzbekistan",
    alpha2Code: "UZ",
    alpha3Code: "UZB",
    numericCode: 860,
    nativeName: "Oʻzbekiston",
    capital: "Toshkent",
    mainLanguage: "uzbek",
    languages: ["uzbek", "russian"] as const,
    tld: ".uz",
    callingCode: 998,
    continent: "asia",
    currency: "uzs",
  },
  [CountryCode.VU]: {
    id: "vanuatu",
    alpha2Code: "VU",
    alpha3Code: "VUT",
    numericCode: 548,
    nativeName: "Vanuatu",
    capital: "Port Vila",
    mainLanguage: "bislama",
    languages: ["bislama", "english", "french"] as const,
    tld: ".vu",
    callingCode: 678,
    continent: "oceania",
    currency: "vuv",
  },
  [CountryCode.VA]: {
    id: "vaticanCity",
    alpha2Code: "VA",
    alpha3Code: "VAT",
    numericCode: 336,
    nativeName: "Vaticano",
    capital: "Vatican City",
    mainLanguage: "italian",
    languages: ["italian"] as const,
    tld: ".va",
    callingCode: 379,
    continent: "europe",
    currency: "eur",
  },
  [CountryCode.VE]: {
    id: "venezuela",
    alpha2Code: "VE",
    alpha3Code: "VEN",
    numericCode: 862,
    nativeName: "Venezuela",
    capital: "Caracas",
    mainLanguage: "spanish",
    languages: ["spanish"] as const,
    tld: ".ve",
    callingCode: 58,
    continent: "southAmerica",
    currency: "ves",
  },
  [CountryCode.VN]: {
    id: "vietnam",
    alpha2Code: "VN",
    alpha3Code: "VNM",
    numericCode: 704,
    nativeName: "Việt Nam",
    capital: "Hà Nội",
    mainLanguage: "vietnamese",
    languages: ["vietnamese"] as const,
    tld: ".vn",
    callingCode: 84,
    continent: "asia",
    currency: "vnd",
  },
  [CountryCode.VI]: {
    id: "virginIslandsUS",
    alpha2Code: "VI",
    alpha3Code: "VIR",
    numericCode: 850,
    nativeName: "United States Virgin Islands",
    capital: "Charlotte Amalie",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".vi",
    callingCode: 1,
    continent: "northAmerica",
    currency: "usd",
  },
  [CountryCode.WF]: {
    id: "wallisAndFutuna",
    alpha2Code: "WF",
    alpha3Code: "WLF",
    numericCode: 876,
    nativeName: "Wallis et Futuna",
    capital: "Mata-Utu",
    mainLanguage: "french",
    languages: ["french"] as const,
    tld: ".wf",
    callingCode: 681,
    continent: "oceania",
    currency: "xpf",
  },
  [CountryCode.EH]: {
    id: "westernSahara",
    alpha2Code: "EH",
    alpha3Code: "ESH",
    numericCode: 732,
    nativeName: "الصحراء الغربية",
    capital: "العيون",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".eh",
    callingCode: 212,
    continent: "africa",
    currency: "mad",
  },
  [CountryCode.YE]: {
    id: "yemen",
    alpha2Code: "YE",
    alpha3Code: "YEM",
    numericCode: 887,
    nativeName: "اليمن",
    capital: "صنعاء",
    mainLanguage: "arabic",
    languages: ["arabic"] as const,
    tld: ".ye",
    callingCode: 967,
    continent: "asia",
    currency: "yer",
  },
  [CountryCode.ZM]: {
    id: "zambia",
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
    numericCode: 894,
    nativeName: "Zambia",
    capital: "Lusaka",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".zm",
    callingCode: 260,
    continent: "africa",
    currency: "zmw",
  },
  [CountryCode.ZW]: {
    id: "zimbabwe",
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
    numericCode: 716,
    nativeName: "Zimbabwe",
    capital: "Harare",
    mainLanguage: "english",
    languages: ["english"] as const,
    tld: ".zw",
    callingCode: 263,
    continent: "africa",
    currency: "zwl",
  },
} as const;

// Tree-shakeable exports
export const Afghanistan: Country = countries[CountryCode.AF];
export const AalandIslands: Country = countries[CountryCode.AX];
export const Albania: Country = countries[CountryCode.AL];
export const Algeria: Country = countries[CountryCode.DZ];
export const AmericanSamoa: Country = countries[CountryCode.AS];
export const Andorra: Country = countries[CountryCode.AD];
export const Angola: Country = countries[CountryCode.AO];
export const Anguilla: Country = countries[CountryCode.AI];
export const Antarctica: Country = countries[CountryCode.AQ];
export const AntiguaAndBarbuda: Country = countries[CountryCode.AG];
export const Argentina: Country = countries[CountryCode.AR];
export const Armenia: Country = countries[CountryCode.AM];
export const Aruba: Country = countries[CountryCode.AW];
export const Australia: Country = countries[CountryCode.AU];
export const Austria: Country = countries[CountryCode.AT];
export const Azerbaijan: Country = countries[CountryCode.AZ];
export const Bahamas: Country = countries[CountryCode.BS];
export const Bahrain: Country = countries[CountryCode.BH];
export const Bangladesh: Country = countries[CountryCode.BD];
export const Barbados: Country = countries[CountryCode.BB];
export const Belarus: Country = countries[CountryCode.BY];
export const Belgium: Country = countries[CountryCode.BE];
export const Belize: Country = countries[CountryCode.BZ];
export const Benin: Country = countries[CountryCode.BJ];
export const Bermuda: Country = countries[CountryCode.BM];
export const Bhutan: Country = countries[CountryCode.BT];
export const Bolivia: Country = countries[CountryCode.BO];
export const BonaireSintEustatiusAndSaba: Country = countries[CountryCode.BQ];
export const BosniaAndHerzegovina: Country = countries[CountryCode.BA];
export const Botswana: Country = countries[CountryCode.BW];
export const BouvetIsland: Country = countries[CountryCode.BV];
export const Brazil: Country = countries[CountryCode.BR];
export const BritishIndianOceanTerritory: Country = countries[CountryCode.IO];
export const BritishVirginIslands: Country = countries[CountryCode.VG];
export const Brunei: Country = countries[CountryCode.BN];
export const Bulgaria: Country = countries[CountryCode.BG];
export const BurkinaFaso: Country = countries[CountryCode.BF];
export const Burundi: Country = countries[CountryCode.BI];
export const CaboVerde: Country = countries[CountryCode.CV];
export const Cambodia: Country = countries[CountryCode.KH];
export const Cameroon: Country = countries[CountryCode.CM];
export const Canada: Country = countries[CountryCode.CA];
export const CaymanIslands: Country = countries[CountryCode.KY];
export const CentralAfricanRepublic: Country = countries[CountryCode.CF];
export const Chad: Country = countries[CountryCode.TD];
export const Chile: Country = countries[CountryCode.CL];
export const China: Country = countries[CountryCode.CN];
export const ChristmasIsland: Country = countries[CountryCode.CX];
export const CocosKeelingIslands: Country = countries[CountryCode.CC];
export const Colombia: Country = countries[CountryCode.CO];
export const Comoros: Country = countries[CountryCode.KM];
export const Congo: Country = countries[CountryCode.CG];
export const CongoDemocraticRepublic: Country = countries[CountryCode.CD];
export const CookIslands: Country = countries[CountryCode.CK];
export const CostaRica: Country = countries[CountryCode.CR];
export const CoteDivoire: Country = countries[CountryCode.CI];
export const Croatia: Country = countries[CountryCode.HR];
export const Cuba: Country = countries[CountryCode.CU];
export const Curacao: Country = countries[CountryCode.CW];
export const Cyprus: Country = countries[CountryCode.CY];
export const Czechia: Country = countries[CountryCode.CZ];
export const Denmark: Country = countries[CountryCode.DK];
export const Djibouti: Country = countries[CountryCode.DJ];
export const Dominica: Country = countries[CountryCode.DM];
export const DominicanRepublic: Country = countries[CountryCode.DO];
export const Ecuador: Country = countries[CountryCode.EC];
export const Egypt: Country = countries[CountryCode.EG];
export const ElSalvador: Country = countries[CountryCode.SV];
export const EquatorialGuinea: Country = countries[CountryCode.GQ];
export const Eritrea: Country = countries[CountryCode.ER];
export const Estonia: Country = countries[CountryCode.EE];
export const Eswatini: Country = countries[CountryCode.SZ];
export const Ethiopia: Country = countries[CountryCode.ET];
export const FalklandIslands: Country = countries[CountryCode.FK];
export const FaroeIslands: Country = countries[CountryCode.FO];
export const Fiji: Country = countries[CountryCode.FJ];
export const Finland: Country = countries[CountryCode.FI];
export const France: Country = countries[CountryCode.FR];
export const FrenchGuiana: Country = countries[CountryCode.GF];
export const FrenchPolynesia: Country = countries[CountryCode.PF];
export const FrenchSouthernTerritories: Country = countries[CountryCode.TF];
export const Gabon: Country = countries[CountryCode.GA];
export const Gambia: Country = countries[CountryCode.GM];
export const Georgia: Country = countries[CountryCode.GE];
export const Germany: Country = countries[CountryCode.DE];
export const Ghana: Country = countries[CountryCode.GH];
export const Gibraltar: Country = countries[CountryCode.GI];
export const Greece: Country = countries[CountryCode.GR];
export const Grenada: Country = countries[CountryCode.GD];
export const Guadeloupe: Country = countries[CountryCode.GP];
export const Guam: Country = countries[CountryCode.GU];
export const Guatemala: Country = countries[CountryCode.GT];
export const Guernsey: Country = countries[CountryCode.GG];
export const Guinea: Country = countries[CountryCode.GN];
export const GuineaBissau: Country = countries[CountryCode.GW];
export const Guyana: Country = countries[CountryCode.GY];
export const Haiti: Country = countries[CountryCode.HT];
export const HeardIslandAndMcDonaldIslands: Country = countries[CountryCode.HM];
export const Honduras: Country = countries[CountryCode.HN];
export const HongKong: Country = countries[CountryCode.HK];
export const Hungary: Country = countries[CountryCode.HU];
export const Iceland: Country = countries[CountryCode.IS];
export const India: Country = countries[CountryCode.IN];
export const Indonesia: Country = countries[CountryCode.ID];
export const Iran: Country = countries[CountryCode.IR];
export const Iraq: Country = countries[CountryCode.IQ];
export const Ireland: Country = countries[CountryCode.IE];
export const IsleOfMan: Country = countries[CountryCode.IM];
export const Israel: Country = countries[CountryCode.IL];
export const Italy: Country = countries[CountryCode.IT];
export const Jamaica: Country = countries[CountryCode.JM];
export const Japan: Country = countries[CountryCode.JP];
export const Jersey: Country = countries[CountryCode.JE];
export const Jordan: Country = countries[CountryCode.JO];
export const Kazakhstan: Country = countries[CountryCode.KZ];
export const Kenya: Country = countries[CountryCode.KE];
export const Kiribati: Country = countries[CountryCode.KI];
export const Kuwait: Country = countries[CountryCode.KW];
export const Kyrgyzstan: Country = countries[CountryCode.KG];
export const Laos: Country = countries[CountryCode.LA];
export const Latvia: Country = countries[CountryCode.LV];
export const Lebanon: Country = countries[CountryCode.LB];
export const Lesotho: Country = countries[CountryCode.LS];
export const Liberia: Country = countries[CountryCode.LR];
export const Libya: Country = countries[CountryCode.LY];
export const Liechtenstein: Country = countries[CountryCode.LI];
export const Lithuania: Country = countries[CountryCode.LT];
export const Luxembourg: Country = countries[CountryCode.LU];
export const Macao: Country = countries[CountryCode.MO];
export const Madagascar: Country = countries[CountryCode.MG];
export const Malawi: Country = countries[CountryCode.MW];
export const Malaysia: Country = countries[CountryCode.MY];
export const Maldives: Country = countries[CountryCode.MV];
export const Mali: Country = countries[CountryCode.ML];
export const Malta: Country = countries[CountryCode.MT];
export const MarshallIslands: Country = countries[CountryCode.MH];
export const Martinique: Country = countries[CountryCode.MQ];
export const Mauritania: Country = countries[CountryCode.MR];
export const Mauritius: Country = countries[CountryCode.MU];
export const Mayotte: Country = countries[CountryCode.YT];
export const Mexico: Country = countries[CountryCode.MX];
export const Micronesia: Country = countries[CountryCode.FM];
export const Moldova: Country = countries[CountryCode.MD];
export const Monaco: Country = countries[CountryCode.MC];
export const Mongolia: Country = countries[CountryCode.MN];
export const Montenegro: Country = countries[CountryCode.ME];
export const Montserrat: Country = countries[CountryCode.MS];
export const Morocco: Country = countries[CountryCode.MA];
export const Mozambique: Country = countries[CountryCode.MZ];
export const Myanmar: Country = countries[CountryCode.MM];
export const Namibia: Country = countries[CountryCode.NA];
export const Nauru: Country = countries[CountryCode.NR];
export const Nepal: Country = countries[CountryCode.NP];
export const Netherlands: Country = countries[CountryCode.NL];
export const NewCaledonia: Country = countries[CountryCode.NC];
export const NewZealand: Country = countries[CountryCode.NZ];
export const Nicaragua: Country = countries[CountryCode.NI];
export const Niger: Country = countries[CountryCode.NE];
export const Nigeria: Country = countries[CountryCode.NG];
export const Niue: Country = countries[CountryCode.NU];
export const NorfolkIsland: Country = countries[CountryCode.NF];
export const NorthKorea: Country = countries[CountryCode.KP];
export const NorthMacedonia: Country = countries[CountryCode.MK];
export const NorthernMarianaIslands: Country = countries[CountryCode.MP];
export const Norway: Country = countries[CountryCode.NO];
export const Oman: Country = countries[CountryCode.OM];
export const Pakistan: Country = countries[CountryCode.PK];
export const Palau: Country = countries[CountryCode.PW];
export const Palestine: Country = countries[CountryCode.PS];
export const Panama: Country = countries[CountryCode.PA];
export const PapuaNewGuinea: Country = countries[CountryCode.PG];
export const Paraguay: Country = countries[CountryCode.PY];
export const Peru: Country = countries[CountryCode.PE];
export const Philippines: Country = countries[CountryCode.PH];
export const Pitcairn: Country = countries[CountryCode.PN];
export const Poland: Country = countries[CountryCode.PL];
export const Portugal: Country = countries[CountryCode.PT];
export const PuertoRico: Country = countries[CountryCode.PR];
export const Qatar: Country = countries[CountryCode.QA];
export const Reunion: Country = countries[CountryCode.RE];
export const Romania: Country = countries[CountryCode.RO];
export const Russia: Country = countries[CountryCode.RU];
export const Rwanda: Country = countries[CountryCode.RW];
export const SaintBarthelemy: Country = countries[CountryCode.BL];
export const SaintHelena: Country = countries[CountryCode.SH];
export const SaintKittsAndNevis: Country = countries[CountryCode.KN];
export const SaintLucia: Country = countries[CountryCode.LC];
export const SaintMartin: Country = countries[CountryCode.MF];
export const SaintPierreAndMiquelon: Country = countries[CountryCode.PM];
export const SaintVincentAndTheGrenadines: Country = countries[CountryCode.VC];
export const Samoa: Country = countries[CountryCode.WS];
export const SanMarino: Country = countries[CountryCode.SM];
export const SaoTomeAndPrincipe: Country = countries[CountryCode.ST];
export const SaudiArabia: Country = countries[CountryCode.SA];
export const Senegal: Country = countries[CountryCode.SN];
export const Serbia: Country = countries[CountryCode.RS];
export const Seychelles: Country = countries[CountryCode.SC];
export const SierraLeone: Country = countries[CountryCode.SL];
export const Singapore: Country = countries[CountryCode.SG];
export const SintMaarten: Country = countries[CountryCode.SX];
export const Slovakia: Country = countries[CountryCode.SK];
export const Slovenia: Country = countries[CountryCode.SI];
export const SolomonIslands: Country = countries[CountryCode.SB];
export const Somalia: Country = countries[CountryCode.SO];
export const SouthAfrica: Country = countries[CountryCode.ZA];
export const SouthGeorgiaAndTheSouthSandwichIslands: Country = countries[CountryCode.GS];
export const SouthKorea: Country = countries[CountryCode.KR];
export const SouthSudan: Country = countries[CountryCode.SS];
export const Spain: Country = countries[CountryCode.ES];
export const SriLanka: Country = countries[CountryCode.LK];
export const Sudan: Country = countries[CountryCode.SD];
export const Suriname: Country = countries[CountryCode.SR];
export const SvalbardAndJanMayen: Country = countries[CountryCode.SJ];
export const Sweden: Country = countries[CountryCode.SE];
export const Switzerland: Country = countries[CountryCode.CH];
export const Syria: Country = countries[CountryCode.SY];
export const Taiwan: Country = countries[CountryCode.TW];
export const Tajikistan: Country = countries[CountryCode.TJ];
export const Tanzania: Country = countries[CountryCode.TZ];
export const Thailand: Country = countries[CountryCode.TH];
export const TimorLeste: Country = countries[CountryCode.TL];
export const Togo: Country = countries[CountryCode.TG];
export const Tokelau: Country = countries[CountryCode.TK];
export const Tonga: Country = countries[CountryCode.TO];
export const TrinidadAndTobago: Country = countries[CountryCode.TT];
export const Tunisia: Country = countries[CountryCode.TN];
export const Turkey: Country = countries[CountryCode.TR];
export const Turkmenistan: Country = countries[CountryCode.TM];
export const TurksAndCaicosIslands: Country = countries[CountryCode.TC];
export const Tuvalu: Country = countries[CountryCode.TV];
export const Uganda: Country = countries[CountryCode.UG];
export const Ukraine: Country = countries[CountryCode.UA];
export const UnitedArabEmirates: Country = countries[CountryCode.AE];
export const UnitedKingdom: Country = countries[CountryCode.GB];
export const UnitedStatesMinorOutlyingIslands: Country = countries[CountryCode.UM];
export const UnitedStates: Country = countries[CountryCode.US];
export const Uruguay: Country = countries[CountryCode.UY];
export const Uzbekistan: Country = countries[CountryCode.UZ];
export const Vanuatu: Country = countries[CountryCode.VU];
export const VaticanCity: Country = countries[CountryCode.VA];
export const Venezuela: Country = countries[CountryCode.VE];
export const Vietnam: Country = countries[CountryCode.VN];
export const VirginIslandsUs: Country = countries[CountryCode.VI];
export const WallisAndFutuna: Country = countries[CountryCode.WF];
export const WesternSahara: Country = countries[CountryCode.EH];
export const Yemen: Country = countries[CountryCode.YE];
export const Zambia: Country = countries[CountryCode.ZM];
export const Zimbabwe: Country = countries[CountryCode.ZW];

// Lookup functions
export function getCountryByAlpha2(code: string): Country | undefined {
  return countries[code.toUpperCase() as CountryCode];
}

export function getCountryByAlpha3(code: string): Country | undefined {
  return Object.values(countries).find(c => c.alpha3Code === code.toUpperCase());
}

export function getCountriesByContinent(continent: string): Country[] {
  return Object.values(countries).filter(c => c.continent === continent);
}

export function getEmojiFlag(alpha2Code: string): string {
  const base = 0x1F1E6 - 65;
  const first = alpha2Code.charCodeAt(0) + base;
  const second = alpha2Code.charCodeAt(1) + base;
  return String.fromCodePoint(first, second);
}
