// GENERATED CODE - DO NOT MODIFY BY HAND

import type { Currency } from './types';

export enum CurrencyCode {
  AED = "AED",
  AFN = "AFN",
  ALL = "ALL",
  AMD = "AMD",
  ANG = "ANG",
  AOA = "AOA",
  ARS = "ARS",
  AUD = "AUD",
  AWG = "AWG",
  AZN = "AZN",
  BAM = "BAM",
  BBD = "BBD",
  BDT = "BDT",
  BGN = "BGN",
  BHD = "BHD",
  BIF = "BIF",
  BMD = "BMD",
  BND = "BND",
  BOB = "BOB",
  BOV = "BOV",
  BRL = "BRL",
  BSD = "BSD",
  BTN = "BTN",
  BWP = "BWP",
  BYN = "BYN",
  BZD = "BZD",
  CAD = "CAD",
  CDF = "CDF",
  CHE = "CHE",
  CHF = "CHF",
  CHW = "CHW",
  CLF = "CLF",
  CLP = "CLP",
  CNY = "CNY",
  COP = "COP",
  COU = "COU",
  CRC = "CRC",
  CUP = "CUP",
  CVE = "CVE",
  CZK = "CZK",
  DJF = "DJF",
  DKK = "DKK",
  DOP = "DOP",
  DZD = "DZD",
  EGP = "EGP",
  ERN = "ERN",
  ETB = "ETB",
  EUR = "EUR",
  FJD = "FJD",
  FKP = "FKP",
  GBP = "GBP",
  GEL = "GEL",
  GHS = "GHS",
  GIP = "GIP",
  GMD = "GMD",
  GNF = "GNF",
  GTQ = "GTQ",
  GYD = "GYD",
  HKD = "HKD",
  HNL = "HNL",
  HTG = "HTG",
  HUF = "HUF",
  IDR = "IDR",
  ILS = "ILS",
  INR = "INR",
  IQD = "IQD",
  IRR = "IRR",
  ISK = "ISK",
  JMD = "JMD",
  JOD = "JOD",
  JPY = "JPY",
  KES = "KES",
  KGS = "KGS",
  KHR = "KHR",
  KMF = "KMF",
  KPW = "KPW",
  KRW = "KRW",
  KWD = "KWD",
  KYD = "KYD",
  KZT = "KZT",
  LAK = "LAK",
  LBP = "LBP",
  LKR = "LKR",
  LRD = "LRD",
  LSL = "LSL",
  LYD = "LYD",
  MAD = "MAD",
  MDL = "MDL",
  MGA = "MGA",
  MKD = "MKD",
  MMK = "MMK",
  MNT = "MNT",
  MOP = "MOP",
  MRU = "MRU",
  MUR = "MUR",
  MVR = "MVR",
  MWK = "MWK",
  MXN = "MXN",
  MXV = "MXV",
  MYR = "MYR",
  MZN = "MZN",
  NAD = "NAD",
  NGN = "NGN",
  NIO = "NIO",
  NOK = "NOK",
  NPR = "NPR",
  NZD = "NZD",
  OMR = "OMR",
  PAB = "PAB",
  PEN = "PEN",
  PGK = "PGK",
  PHP = "PHP",
  PKR = "PKR",
  PLN = "PLN",
  PYG = "PYG",
  QAR = "QAR",
  RON = "RON",
  RSD = "RSD",
  RUB = "RUB",
  RWF = "RWF",
  SAR = "SAR",
  SBD = "SBD",
  SCR = "SCR",
  SDG = "SDG",
  SEK = "SEK",
  SGD = "SGD",
  SHP = "SHP",
  SLE = "SLE",
  SOS = "SOS",
  SRD = "SRD",
  SSP = "SSP",
  STN = "STN",
  SVC = "SVC",
  SYP = "SYP",
  SZL = "SZL",
  THB = "THB",
  TJS = "TJS",
  TMT = "TMT",
  TND = "TND",
  TOP = "TOP",
  TRY = "TRY",
  TTD = "TTD",
  TWD = "TWD",
  TZS = "TZS",
  UAH = "UAH",
  UGX = "UGX",
  USD = "USD",
  USN = "USN",
  UYI = "UYI",
  UYU = "UYU",
  UYW = "UYW",
  UZS = "UZS",
  VED = "VED",
  VES = "VES",
  VND = "VND",
  VUV = "VUV",
  WST = "WST",
  XAF = "XAF",
  XAG = "XAG",
  XAU = "XAU",
  XBA = "XBA",
  XBB = "XBB",
  XBC = "XBC",
  XBD = "XBD",
  XCD = "XCD",
  XDR = "XDR",
  XOF = "XOF",
  XPD = "XPD",
  XPF = "XPF",
  XPT = "XPT",
  XSU = "XSU",
  XTS = "XTS",
  XUA = "XUA",
  XXX = "XXX",
  YER = "YER",
  ZAR = "ZAR",
  ZMW = "ZMW",
  ZMG = "ZMG",
  ZWL = "ZWL",
}

export const currencies: Record<CurrencyCode, Currency> = {
  [CurrencyCode.AED]: {
    id: "aed",
    code: "AED",
    nativeName: "United Arab Emirates Dirham",
    nativeNamePlural: "United Arab Emirates Dirhams",
    symbol: "د.إ",
  },
  [CurrencyCode.AFN]: {
    id: "afn",
    code: "AFN",
    nativeName: "Afghan Afghani",
    nativeNamePlural: "Afghan Afghanis",
    symbol: "؋",
  },
  [CurrencyCode.ALL]: {
    id: "all",
    code: "ALL",
    nativeName: "Albanian Lek",
    nativeNamePlural: "Albanian Leke",
    symbol: "L",
  },
  [CurrencyCode.AMD]: {
    id: "amd",
    code: "AMD",
    nativeName: "Armenian Dram",
    nativeNamePlural: "Armenian Drams",
    symbol: "֏",
  },
  [CurrencyCode.ANG]: {
    id: "ang",
    code: "ANG",
    nativeName: "Netherlands Antillean Guilder",
    nativeNamePlural: "Netherlands Antillean Guilders",
    symbol: "ƒ",
  },
  [CurrencyCode.AOA]: {
    id: "aoa",
    code: "AOA",
    nativeName: "Angolan Kwanza",
    nativeNamePlural: "Angolan Kwanza",
    symbol: "Kz",
  },
  [CurrencyCode.ARS]: {
    id: "ars",
    code: "ARS",
    nativeName: "Argentine Peso",
    nativeNamePlural: "Argentine Pesos",
    symbol: "\\\$",
  },
  [CurrencyCode.AUD]: {
    id: "aud",
    code: "AUD",
    nativeName: "Australian Dollar",
    nativeNamePlural: "Australian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.AWG]: {
    id: "awg",
    code: "AWG",
    nativeName: "Aruban Florin",
    nativeNamePlural: "Aruban Florin",
    symbol: "ƒ",
  },
  [CurrencyCode.AZN]: {
    id: "azn",
    code: "AZN",
    nativeName: "Azerbaijani Manat",
    nativeNamePlural: "Azerbaijani Manat",
    symbol: "₼",
  },
  [CurrencyCode.BAM]: {
    id: "bam",
    code: "BAM",
    nativeName: "Bosnia-Herzegovina Convertible Mark",
    nativeNamePlural: "Bosnia-Herzegovina Convertible Marks",
    symbol: "KM",
  },
  [CurrencyCode.BBD]: {
    id: "bbd",
    code: "BBD",
    nativeName: "Barbadian Dollar",
    nativeNamePlural: "Barbadian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.BDT]: {
    id: "bdt",
    code: "BDT",
    nativeName: "Bangladeshi Taka",
    nativeNamePlural: "Bangladeshi Takas",
    symbol: "৳",
  },
  [CurrencyCode.BGN]: {
    id: "bgn",
    code: "BGN",
    nativeName: "Bulgarian Lev",
    nativeNamePlural: "Bulgarian Leva",
    symbol: "лв",
  },
  [CurrencyCode.BHD]: {
    id: "bhd",
    code: "BHD",
    nativeName: "Bahraini Dinar",
    nativeNamePlural: "Bahraini Dinars",
    symbol: "ب.د",
  },
  [CurrencyCode.BIF]: {
    id: "bif",
    code: "BIF",
    nativeName: "Burundian Franc",
    nativeNamePlural: "Burundian Francs",
    symbol: "FBu",
  },
  [CurrencyCode.BMD]: {
    id: "bmd",
    code: "BMD",
    nativeName: "Bermudian Dollar",
    nativeNamePlural: "Bermudian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.BND]: {
    id: "bnd",
    code: "BND",
    nativeName: "Brunei Dollar",
    nativeNamePlural: "Brunei Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.BOB]: {
    id: "bob",
    code: "BOB",
    nativeName: "Bolivian Boliviano",
    nativeNamePlural: "Bolivian Bolivianos",
    symbol: "Bs.",
  },
  [CurrencyCode.BOV]: {
    id: "bov",
    code: "BOV",
    nativeName: "Bolivian Mvdol",
    nativeNamePlural: "Bolivian Mvdols",
    symbol: "BOV",
  },
  [CurrencyCode.BRL]: {
    id: "brl",
    code: "BRL",
    nativeName: "Brazilian Real",
    nativeNamePlural: "Brazilian Reals",
    symbol: "R\\\$",
  },
  [CurrencyCode.BSD]: {
    id: "bsd",
    code: "BSD",
    nativeName: "Bahamian Dollar",
    nativeNamePlural: "Bahamian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.BTN]: {
    id: "btn",
    code: "BTN",
    nativeName: "Bhutanese Ngultrum",
    nativeNamePlural: "Bhutanese Ngultrums",
    symbol: "Nu.",
  },
  [CurrencyCode.BWP]: {
    id: "bwp",
    code: "BWP",
    nativeName: "Botswana Pula",
    nativeNamePlural: "Botswana Pulas",
    symbol: "P",
  },
  [CurrencyCode.BYN]: {
    id: "byn",
    code: "BYN",
    nativeName: "Belarusian Ruble",
    nativeNamePlural: "Belarusian Rubles",
    symbol: "Br",
  },
  [CurrencyCode.BZD]: {
    id: "bzd",
    code: "BZD",
    nativeName: "Belize Dollar",
    nativeNamePlural: "Belize Dollars",
    symbol: "BZ\\\$",
  },
  [CurrencyCode.CAD]: {
    id: "cad",
    code: "CAD",
    nativeName: "Canadian Dollar",
    nativeNamePlural: "Canadian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.CDF]: {
    id: "cdf",
    code: "CDF",
    nativeName: "Congolese Franc",
    nativeNamePlural: "Congolese Francs",
    symbol: "FC",
  },
  [CurrencyCode.CHE]: {
    id: "che",
    code: "CHE",
    nativeName: "WIR Euro",
    nativeNamePlural: "WIR Euros",
    symbol: "CHE",
  },
  [CurrencyCode.CHF]: {
    id: "chf",
    code: "CHF",
    nativeName: "Swiss Franc",
    nativeNamePlural: "Swiss Francs",
    symbol: "CHF",
  },
  [CurrencyCode.CHW]: {
    id: "chw",
    code: "CHW",
    nativeName: "WIR Franc",
    nativeNamePlural: "WIR Francs",
    symbol: "CHW",
  },
  [CurrencyCode.CLF]: {
    id: "clf",
    code: "CLF",
    nativeName: "Chilean Unit of Account (UF)",
    nativeNamePlural: "Chilean Units of Account (UF)",
    symbol: "CLF",
  },
  [CurrencyCode.CLP]: {
    id: "clp",
    code: "CLP",
    nativeName: "Chilean Peso",
    nativeNamePlural: "Chilean Pesos",
    symbol: "\\\$",
  },
  [CurrencyCode.CNY]: {
    id: "cny",
    code: "CNY",
    nativeName: "Chinese Yuan",
    nativeNamePlural: "Chinese Yuan",
    symbol: "¥",
  },
  [CurrencyCode.COP]: {
    id: "cop",
    code: "COP",
    nativeName: "Colombian Peso",
    nativeNamePlural: "Colombian Pesos",
    symbol: "\\\$",
  },
  [CurrencyCode.COU]: {
    id: "cou",
    code: "COU",
    nativeName: "Unidad de Valor Real",
    nativeNamePlural: "Unidad de Valor Reals",
    symbol: "COU",
  },
  [CurrencyCode.CRC]: {
    id: "crc",
    code: "CRC",
    nativeName: "Costa Rican Colón",
    nativeNamePlural: "Costa Rican Colóns",
    symbol: "₡",
  },
  [CurrencyCode.CUP]: {
    id: "cup",
    code: "CUP",
    nativeName: "Cuban Peso",
    nativeNamePlural: "Cuban Pesos",
    symbol: "\\\$",
  },
  [CurrencyCode.CVE]: {
    id: "cve",
    code: "CVE",
    nativeName: "Cape Verdean Escudo",
    nativeNamePlural: "Cape Verdean Escudos",
    symbol: "Esc",
  },
  [CurrencyCode.CZK]: {
    id: "czk",
    code: "CZK",
    nativeName: "Czech Koruna",
    nativeNamePlural: "Czech Korunas",
    symbol: "Kč",
  },
  [CurrencyCode.DJF]: {
    id: "djf",
    code: "DJF",
    nativeName: "Djiboutian Franc",
    nativeNamePlural: "Djiboutian Francs",
    symbol: "Fdj",
  },
  [CurrencyCode.DKK]: {
    id: "dkk",
    code: "DKK",
    nativeName: "Danske Kroner",
    nativeNamePlural: "Danske Kroner",
    symbol: "kr",
  },
  [CurrencyCode.DOP]: {
    id: "dop",
    code: "DOP",
    nativeName: "Dominican Peso",
    nativeNamePlural: "Dominican Pesos",
    symbol: "RD\\\$",
  },
  [CurrencyCode.DZD]: {
    id: "dzd",
    code: "DZD",
    nativeName: "Algerian Dinar",
    nativeNamePlural: "Algerian Dinars",
    symbol: "د.ج",
  },
  [CurrencyCode.EGP]: {
    id: "egp",
    code: "EGP",
    nativeName: "Egyptian Pound",
    nativeNamePlural: "Egyptian Pounds",
    symbol: "E£",
  },
  [CurrencyCode.ERN]: {
    id: "ern",
    code: "ERN",
    nativeName: "Eritrean Nakfa",
    nativeNamePlural: "Eritrean Nakfas",
    symbol: "Nfk",
  },
  [CurrencyCode.ETB]: {
    id: "etb",
    code: "ETB",
    nativeName: "Ethiopian Birr",
    nativeNamePlural: "Ethiopian Birrs",
    symbol: "Br",
  },
  [CurrencyCode.EUR]: {
    id: "eur",
    code: "EUR",
    nativeName: "Euro",
    nativeNamePlural: "Euros",
    symbol: "€",
  },
  [CurrencyCode.FJD]: {
    id: "fjd",
    code: "FJD",
    nativeName: "Fijian Dollar",
    nativeNamePlural: "Fijian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.FKP]: {
    id: "fkp",
    code: "FKP",
    nativeName: "Falkland Islands Pound",
    nativeNamePlural: "Falkland Islands Pounds",
    symbol: "£",
  },
  [CurrencyCode.GBP]: {
    id: "gbp",
    code: "GBP",
    nativeName: "British Pound",
    nativeNamePlural: "British Pounds",
    symbol: "£",
  },
  [CurrencyCode.GEL]: {
    id: "gel",
    code: "GEL",
    nativeName: "Georgian Lari",
    nativeNamePlural: "Georgian Laris",
    symbol: "₾",
  },
  [CurrencyCode.GHS]: {
    id: "ghs",
    code: "GHS",
    nativeName: "Ghanaian Cedi",
    nativeNamePlural: "Ghanaian Cedis",
    symbol: "₵",
  },
  [CurrencyCode.GIP]: {
    id: "gip",
    code: "GIP",
    nativeName: "Gibraltar Pound",
    nativeNamePlural: "Gibraltar Pounds",
    symbol: "£",
  },
  [CurrencyCode.GMD]: {
    id: "gmd",
    code: "GMD",
    nativeName: "Gambian Dalasi",
    nativeNamePlural: "Gambian Dalasis",
    symbol: "D",
  },
  [CurrencyCode.GNF]: {
    id: "gnf",
    code: "GNF",
    nativeName: "Guinean Franc",
    nativeNamePlural: "Guinean Francs",
    symbol: "FG",
  },
  [CurrencyCode.GTQ]: {
    id: "gtq",
    code: "GTQ",
    nativeName: "Guatemalan Quetzal",
    nativeNamePlural: "Guatemalan Quetzals",
    symbol: "Q",
  },
  [CurrencyCode.GYD]: {
    id: "gyd",
    code: "GYD",
    nativeName: "Guyanese Dollar",
    nativeNamePlural: "Guyanese Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.HKD]: {
    id: "hkd",
    code: "HKD",
    nativeName: "Hong Kong Dollar",
    nativeNamePlural: "Hong Kong Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.HNL]: {
    id: "hnl",
    code: "HNL",
    nativeName: "Honduran Lempira",
    nativeNamePlural: "Honduran Lempiras",
    symbol: "L",
  },
  [CurrencyCode.HTG]: {
    id: "htg",
    code: "HTG",
    nativeName: "Haitian Gourde",
    nativeNamePlural: "Haitian Gourdes",
    symbol: "G",
  },
  [CurrencyCode.HUF]: {
    id: "huf",
    code: "HUF",
    nativeName: "Hungarian Forint",
    nativeNamePlural: "Hungarian Forints",
    symbol: "Ft",
  },
  [CurrencyCode.IDR]: {
    id: "idr",
    code: "IDR",
    nativeName: "Indonesian Rupiah",
    nativeNamePlural: "Indonesian Rupiahs",
    symbol: "Rp",
  },
  [CurrencyCode.ILS]: {
    id: "ils",
    code: "ILS",
    nativeName: "Israeli New Shekel",
    nativeNamePlural: "Israeli New Shekels",
    symbol: "₪",
  },
  [CurrencyCode.INR]: {
    id: "inr",
    code: "INR",
    nativeName: "Indian Rupee",
    nativeNamePlural: "Indian Rupees",
    symbol: "₹",
  },
  [CurrencyCode.IQD]: {
    id: "iqd",
    code: "IQD",
    nativeName: "Iraqi Dinar",
    nativeNamePlural: "Iraqi Dinars",
    symbol: "ع.د",
  },
  [CurrencyCode.IRR]: {
    id: "irr",
    code: "IRR",
    nativeName: "Iranian Rial",
    nativeNamePlural: "Iranian Rials",
    symbol: "﷼",
  },
  [CurrencyCode.ISK]: {
    id: "isk",
    code: "ISK",
    nativeName: "Icelandic Króna",
    nativeNamePlural: "Icelandic Krónur",
    symbol: "kr",
  },
  [CurrencyCode.JMD]: {
    id: "jmd",
    code: "JMD",
    nativeName: "Jamaican Dollar",
    nativeNamePlural: "Jamaican Dollars",
    symbol: "J\\\$",
  },
  [CurrencyCode.JOD]: {
    id: "jod",
    code: "JOD",
    nativeName: "Jordanian Dinar",
    nativeNamePlural: "Jordanian Dinars",
    symbol: "د.ا",
  },
  [CurrencyCode.JPY]: {
    id: "jpy",
    code: "JPY",
    nativeName: "Japanese Yen",
    nativeNamePlural: "Japanese Yen",
    symbol: "¥",
  },
  [CurrencyCode.KES]: {
    id: "kes",
    code: "KES",
    nativeName: "Kenyan Shilling",
    nativeNamePlural: "Kenyan Shillings",
    symbol: "KSh",
  },
  [CurrencyCode.KGS]: {
    id: "kgs",
    code: "KGS",
    nativeName: "Kyrgyzstani Som",
    nativeNamePlural: "Kyrgyzstani Soms",
    symbol: "с",
  },
  [CurrencyCode.KHR]: {
    id: "khr",
    code: "KHR",
    nativeName: "Cambodian Riel",
    nativeNamePlural: "Cambodian Riels",
    symbol: "៛",
  },
  [CurrencyCode.KMF]: {
    id: "kmf",
    code: "KMF",
    nativeName: "Comorian Franc",
    nativeNamePlural: "Comorian Francs",
    symbol: "CF",
  },
  [CurrencyCode.KPW]: {
    id: "kpw",
    code: "KPW",
    nativeName: "North Korean Won",
    nativeNamePlural: "North Korean Won",
    symbol: "₩",
  },
  [CurrencyCode.KRW]: {
    id: "krw",
    code: "KRW",
    nativeName: "South Korean Won",
    nativeNamePlural: "South Korean Won",
    symbol: "₩",
  },
  [CurrencyCode.KWD]: {
    id: "kwd",
    code: "KWD",
    nativeName: "Kuwaiti Dinar",
    nativeNamePlural: "Kuwaiti Dinars",
    symbol: "د.ك",
  },
  [CurrencyCode.KYD]: {
    id: "kyd",
    code: "KYD",
    nativeName: "Cayman Islands Dollar",
    nativeNamePlural: "Cayman Islands Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.KZT]: {
    id: "kzt",
    code: "KZT",
    nativeName: "Kazakhstani Tenge",
    nativeNamePlural: "Kazakhstani Tenges",
    symbol: "₸",
  },
  [CurrencyCode.LAK]: {
    id: "lak",
    code: "LAK",
    nativeName: "Lao Kip",
    nativeNamePlural: "Lao Kips",
    symbol: "₭",
  },
  [CurrencyCode.LBP]: {
    id: "lbp",
    code: "LBP",
    nativeName: "Lebanese Pound",
    nativeNamePlural: "Lebanese Pounds",
    symbol: "ل.ل",
  },
  [CurrencyCode.LKR]: {
    id: "lkr",
    code: "LKR",
    nativeName: "Sri Lankan Rupee",
    nativeNamePlural: "Sri Lankan Rupees",
    symbol: "Rs",
  },
  [CurrencyCode.LRD]: {
    id: "lrd",
    code: "LRD",
    nativeName: "Liberian Dollar",
    nativeNamePlural: "Liberian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.LSL]: {
    id: "lsl",
    code: "LSL",
    nativeName: "Lesotho Loti",
    nativeNamePlural: "Lesotho Lotis",
    symbol: "L",
  },
  [CurrencyCode.LYD]: {
    id: "lyd",
    code: "LYD",
    nativeName: "Libyan Dinar",
    nativeNamePlural: "Libyan Dinars",
    symbol: "ل.د",
  },
  [CurrencyCode.MAD]: {
    id: "mad",
    code: "MAD",
    nativeName: "Moroccan Dirham",
    nativeNamePlural: "Moroccan Dirhams",
    symbol: "د.م.",
  },
  [CurrencyCode.MDL]: {
    id: "mdl",
    code: "MDL",
    nativeName: "Moldovan Leu",
    nativeNamePlural: "Moldovan Lei",
    symbol: "L",
  },
  [CurrencyCode.MGA]: {
    id: "mga",
    code: "MGA",
    nativeName: "Malagasy Ariary",
    nativeNamePlural: "Malagasy Ariaries",
    symbol: "Ar",
  },
  [CurrencyCode.MKD]: {
    id: "mkd",
    code: "MKD",
    nativeName: "Macedonian Denar",
    nativeNamePlural: "Macedonian Denari",
    symbol: "ден",
  },
  [CurrencyCode.MMK]: {
    id: "mmk",
    code: "MMK",
    nativeName: "Myanmar Kyat",
    nativeNamePlural: "Myanmar Kyats",
    symbol: "K",
  },
  [CurrencyCode.MNT]: {
    id: "mnt",
    code: "MNT",
    nativeName: "Mongolian Tugrik",
    nativeNamePlural: "Mongolian Tugriks",
    symbol: "₮",
  },
  [CurrencyCode.MOP]: {
    id: "mop",
    code: "MOP",
    nativeName: "Macanese Pataca",
    nativeNamePlural: "Macanese Patacas",
    symbol: "MOP\\\$",
  },
  [CurrencyCode.MRU]: {
    id: "mru",
    code: "MRU",
    nativeName: "Mauritanian Ouguiya",
    nativeNamePlural: "Mauritanian Ouguiyas",
    symbol: "UM",
  },
  [CurrencyCode.MUR]: {
    id: "mur",
    code: "MUR",
    nativeName: "Mauritian Rupee",
    nativeNamePlural: "Mauritian Rupees",
    symbol: "₨",
  },
  [CurrencyCode.MVR]: {
    id: "mvr",
    code: "MVR",
    nativeName: "Maldivian Rufiyaa",
    nativeNamePlural: "Maldivian Rufiyaas",
    symbol: "Rf",
  },
  [CurrencyCode.MWK]: {
    id: "mwk",
    code: "MWK",
    nativeName: "Malawian Kwacha",
    nativeNamePlural: "Malawian Kwachas",
    symbol: "MK",
  },
  [CurrencyCode.MXN]: {
    id: "mxn",
    code: "MXN",
    nativeName: "Mexican Peso",
    nativeNamePlural: "Mexican Pesos",
    symbol: "\\\$",
  },
  [CurrencyCode.MXV]: {
    id: "mxv",
    code: "MXV",
    nativeName: "Mexican Unidad de Inversion (UDI)",
    nativeNamePlural: "Mexican Unidad de Inversions (UDI)",
    symbol: "MXV",
  },
  [CurrencyCode.MYR]: {
    id: "myr",
    code: "MYR",
    nativeName: "Malaysian Ringgit",
    nativeNamePlural: "Malaysian Ringgits",
    symbol: "RM",
  },
  [CurrencyCode.MZN]: {
    id: "mzn",
    code: "MZN",
    nativeName: "Mozambican Metical",
    nativeNamePlural: "Mozambican Meticals",
    symbol: "MT",
  },
  [CurrencyCode.NAD]: {
    id: "nad",
    code: "NAD",
    nativeName: "Namibian Dollar",
    nativeNamePlural: "Namibian Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.NGN]: {
    id: "ngn",
    code: "NGN",
    nativeName: "Nigerian Naira",
    nativeNamePlural: "Nigerian Nairas",
    symbol: "₦",
  },
  [CurrencyCode.NIO]: {
    id: "nio",
    code: "NIO",
    nativeName: "Nicaraguan Córdoba",
    nativeNamePlural: "Nicaraguan Córdobas",
    symbol: "C\\\$",
  },
  [CurrencyCode.NOK]: {
    id: "nok",
    code: "NOK",
    nativeName: "Norwegian Krone",
    nativeNamePlural: "Norwegian Kroner",
    symbol: "kr",
  },
  [CurrencyCode.NPR]: {
    id: "npr",
    code: "NPR",
    nativeName: "Nepalese Rupee",
    nativeNamePlural: "Nepalese Rupees",
    symbol: "रू",
  },
  [CurrencyCode.NZD]: {
    id: "nzd",
    code: "NZD",
    nativeName: "New Zealand Dollar",
    nativeNamePlural: "New Zealand Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.OMR]: {
    id: "omr",
    code: "OMR",
    nativeName: "Omani Rial",
    nativeNamePlural: "Omani Rials",
    symbol: "ر.ع.",
  },
  [CurrencyCode.PAB]: {
    id: "pab",
    code: "PAB",
    nativeName: "Panamanian Balboa",
    nativeNamePlural: "Panamanian Balboas",
    symbol: "B/.",
  },
  [CurrencyCode.PEN]: {
    id: "pen",
    code: "PEN",
    nativeName: "Peruvian Nuevo Sol",
    nativeNamePlural: "Peruvian Nuevo Sols",
    symbol: "S/.",
  },
  [CurrencyCode.PGK]: {
    id: "pgk",
    code: "PGK",
    nativeName: "Papua New Guinean Kina",
    nativeNamePlural: "Papua New Guinean Kina",
    symbol: "K",
  },
  [CurrencyCode.PHP]: {
    id: "php",
    code: "PHP",
    nativeName: "Philippine Peso",
    nativeNamePlural: "Philippine Pesos",
    symbol: "₱",
  },
  [CurrencyCode.PKR]: {
    id: "pkr",
    code: "PKR",
    nativeName: "Pakistani Rupee",
    nativeNamePlural: "Pakistani Rupees",
    symbol: "₨",
  },
  [CurrencyCode.PLN]: {
    id: "pln",
    code: "PLN",
    nativeName: "Polish Złoty",
    nativeNamePlural: "Polish Złotys",
    symbol: "zł",
  },
  [CurrencyCode.PYG]: {
    id: "pyg",
    code: "PYG",
    nativeName: "Paraguayan Guaraní",
    nativeNamePlural: "Paraguayan Guaranís",
    symbol: "₲",
  },
  [CurrencyCode.QAR]: {
    id: "qar",
    code: "QAR",
    nativeName: "Qatari Rial",
    nativeNamePlural: "Qatari Rials",
    symbol: "ر.ق",
  },
  [CurrencyCode.RON]: {
    id: "ron",
    code: "RON",
    nativeName: "Romanian Leu",
    nativeNamePlural: "Romanian Lei",
    symbol: "lei",
  },
  [CurrencyCode.RSD]: {
    id: "rsd",
    code: "RSD",
    nativeName: "Serbian Dinar",
    nativeNamePlural: "Serbian Dinars",
    symbol: "дин",
  },
  [CurrencyCode.RUB]: {
    id: "rub",
    code: "RUB",
    nativeName: "Russian Ruble",
    nativeNamePlural: "Russian Rubles",
    symbol: "₽",
  },
  [CurrencyCode.RWF]: {
    id: "rwf",
    code: "RWF",
    nativeName: "Rwandan Franc",
    nativeNamePlural: "Rwandan Francs",
    symbol: "FRw",
  },
  [CurrencyCode.SAR]: {
    id: "sar",
    code: "SAR",
    nativeName: "Saudi Riyal",
    nativeNamePlural: "Saudi Riyals",
    symbol: "ر.س",
  },
  [CurrencyCode.SBD]: {
    id: "sbd",
    code: "SBD",
    nativeName: "Solomon Islands Dollar",
    nativeNamePlural: "Solomon Islands Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.SCR]: {
    id: "scr",
    code: "SCR",
    nativeName: "Seychellois Rupee",
    nativeNamePlural: "Seychellois Rupees",
    symbol: "₨",
  },
  [CurrencyCode.SDG]: {
    id: "sdg",
    code: "SDG",
    nativeName: "Sudanese Pound",
    nativeNamePlural: "Sudanese Pounds",
    symbol: "ج.س.",
  },
  [CurrencyCode.SEK]: {
    id: "sek",
    code: "SEK",
    nativeName: "Swedish Krona",
    nativeNamePlural: "Swedish Kronor",
    symbol: "kr",
  },
  [CurrencyCode.SGD]: {
    id: "sgd",
    code: "SGD",
    nativeName: "Singapore Dollar",
    nativeNamePlural: "Singapore Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.SHP]: {
    id: "shp",
    code: "SHP",
    nativeName: "Saint Helena Pound",
    nativeNamePlural: "Saint Helena Pounds",
    symbol: "£",
  },
  [CurrencyCode.SLE]: {
    id: "sle",
    code: "SLE",
    nativeName: "Sierra Leonean Leone",
    nativeNamePlural: "Sierra Leonean Leones",
    symbol: "Le",
  },
  [CurrencyCode.SOS]: {
    id: "sos",
    code: "SOS",
    nativeName: "Somali Shilling",
    nativeNamePlural: "Somali Shillings",
    symbol: "Sh.So.",
  },
  [CurrencyCode.SRD]: {
    id: "srd",
    code: "SRD",
    nativeName: "Surinamese Dollar",
    nativeNamePlural: "Surinamese Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.SSP]: {
    id: "ssp",
    code: "SSP",
    nativeName: "South Sudanese Pound",
    nativeNamePlural: "South Sudanese Pounds",
    symbol: "£",
  },
  [CurrencyCode.STN]: {
    id: "stn",
    code: "STN",
    nativeName: "São Tomé and Príncipe Dobra",
    nativeNamePlural: "São Tomé and Príncipe Dobras",
    symbol: "Db",
  },
  [CurrencyCode.SVC]: {
    id: "svc",
    code: "SVC",
    nativeName: "Salvadoran Colón",
    nativeNamePlural: "Salvadoran Colóns",
    symbol: "₡",
  },
  [CurrencyCode.SYP]: {
    id: "syp",
    code: "SYP",
    nativeName: "Syrian Pound",
    nativeNamePlural: "Syrian Pounds",
    symbol: "ل.س",
  },
  [CurrencyCode.SZL]: {
    id: "szl",
    code: "SZL",
    nativeName: "Swazi Lilangeni",
    nativeNamePlural: "Swazi Emalangeni",
    symbol: "L",
  },
  [CurrencyCode.THB]: {
    id: "thb",
    code: "THB",
    nativeName: "Thai Baht",
    nativeNamePlural: "Thai Baht",
    symbol: "฿",
  },
  [CurrencyCode.TJS]: {
    id: "tjs",
    code: "TJS",
    nativeName: "Tajikistani Somoni",
    nativeNamePlural: "Tajikistani Somonis",
    symbol: "ЅМ",
  },
  [CurrencyCode.TMT]: {
    id: "tmt",
    code: "TMT",
    nativeName: "Turkmenistani Manat",
    nativeNamePlural: "Turkmenistani Manats",
    symbol: "T",
  },
  [CurrencyCode.TND]: {
    id: "tnd",
    code: "TND",
    nativeName: "Tunisian Dinar",
    nativeNamePlural: "Tunisian Dinars",
    symbol: "د.ت",
  },
  [CurrencyCode.TOP]: {
    id: "top",
    code: "TOP",
    nativeName: "Tongan Pa'anga",
    nativeNamePlural: "Tongan Pa'anga",
    symbol: "T\\\$",
  },
  [CurrencyCode.TRY]: {
    id: "turkishLira",
    code: "TRY",
    nativeName: "Turkish Lira",
    nativeNamePlural: "Turkish Lira",
    symbol: "₺",
  },
  [CurrencyCode.TTD]: {
    id: "ttd",
    code: "TTD",
    nativeName: "Trinidad and Tobago Dollar",
    nativeNamePlural: "Trinidad and Tobago Dollars",
    symbol: "TT\\\$",
  },
  [CurrencyCode.TWD]: {
    id: "twd",
    code: "TWD",
    nativeName: "New Taiwan Dollar",
    nativeNamePlural: "New Taiwan Dollars",
    symbol: "NT\\\$",
  },
  [CurrencyCode.TZS]: {
    id: "tzs",
    code: "TZS",
    nativeName: "Tanzanian Shilling",
    nativeNamePlural: "Tanzanian Shillings",
    symbol: "TSh",
  },
  [CurrencyCode.UAH]: {
    id: "uah",
    code: "UAH",
    nativeName: "Ukrainian Hryvnia",
    nativeNamePlural: "Ukrainian Hryvnias",
    symbol: "₴",
  },
  [CurrencyCode.UGX]: {
    id: "ugx",
    code: "UGX",
    nativeName: "Ugandan Shilling",
    nativeNamePlural: "Ugandan Shillings",
    symbol: "USh",
  },
  [CurrencyCode.USD]: {
    id: "usd",
    code: "USD",
    nativeName: "United States Dollar",
    nativeNamePlural: "United States Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.USN]: {
    id: "usn",
    code: "USN",
    nativeName: "United States Dollar (Next day)",
    nativeNamePlural: "United States Dollars (Next day)",
    symbol: "USN",
  },
  [CurrencyCode.UYI]: {
    id: "uyi",
    code: "UYI",
    nativeName: "Uruguayan Peso en Unidades Indexadas",
    nativeNamePlural: "Uruguayan Pesos en Unidades Indexadas",
    symbol: "UYI",
  },
  [CurrencyCode.UYU]: {
    id: "uyu",
    code: "UYU",
    nativeName: "Uruguayan Peso",
    nativeNamePlural: "Uruguayan Pesos",
    symbol: "\\\$U",
  },
  [CurrencyCode.UYW]: {
    id: "uyw",
    code: "UYW",
    nativeName: "Unidad Previsional",
    nativeNamePlural: "Unidad Previsionals",
    symbol: "UYW",
  },
  [CurrencyCode.UZS]: {
    id: "uzs",
    code: "UZS",
    nativeName: "Uzbekistan Som",
    nativeNamePlural: "Uzbekistan Soms",
    symbol: "лв",
  },
  [CurrencyCode.VED]: {
    id: "ved",
    code: "VED",
    nativeName: "Venezuelan Bolívar Soberano",
    nativeNamePlural: "Venezuelan Bolívar Soberanos",
    symbol: "VES",
  },
  [CurrencyCode.VES]: {
    id: "ves",
    code: "VES",
    nativeName: "Venezuelan Bolívar",
    nativeNamePlural: "Venezuelan Bolívars",
    symbol: "Bs.",
  },
  [CurrencyCode.VND]: {
    id: "vnd",
    code: "VND",
    nativeName: "Vietnamese Dong",
    nativeNamePlural: "Vietnamese Dong",
    symbol: "₫",
  },
  [CurrencyCode.VUV]: {
    id: "vuv",
    code: "VUV",
    nativeName: "Vanuatu Vatu",
    nativeNamePlural: "Vanuatu Vatus",
    symbol: "VT",
  },
  [CurrencyCode.WST]: {
    id: "wst",
    code: "WST",
    nativeName: "Samoan Tala",
    nativeNamePlural: "Samoan Tala",
    symbol: "WS\\\$",
  },
  [CurrencyCode.XAF]: {
    id: "xaf",
    code: "XAF",
    nativeName: "Central African CFA Franc",
    nativeNamePlural: "Central African CFA Francs",
    symbol: "FCFA",
  },
  [CurrencyCode.XAG]: {
    id: "xag",
    code: "XAG",
    nativeName: "Silver (one troy ounce)",
    nativeNamePlural: "Silver (one troy ounce)",
    symbol: "XAG",
  },
  [CurrencyCode.XAU]: {
    id: "xau",
    code: "XAU",
    nativeName: "Gold (one troy ounce)",
    nativeNamePlural: "Gold (one troy ounce)",
    symbol: "XAU",
  },
  [CurrencyCode.XBA]: {
    id: "xba",
    code: "XBA",
    nativeName: "European Composite Unit",
    nativeNamePlural: "European Composite Units",
    symbol: "XBA",
  },
  [CurrencyCode.XBB]: {
    id: "xbb",
    code: "XBB",
    nativeName: "European Monetary Unit",
    nativeNamePlural: "European Monetary Units",
    symbol: "XBB",
  },
  [CurrencyCode.XBC]: {
    id: "xbc",
    code: "XBC",
    nativeName: "European Unit of Account 9",
    nativeNamePlural: "European Unit of Account 9",
    symbol: "XBC",
  },
  [CurrencyCode.XBD]: {
    id: "xbd",
    code: "XBD",
    nativeName: "European Unit of Account 17",
    nativeNamePlural: "European Unit of Account 17",
    symbol: "XBD",
  },
  [CurrencyCode.XCD]: {
    id: "xcd",
    code: "XCD",
    nativeName: "East Caribbean Dollar",
    nativeNamePlural: "East Caribbean Dollars",
    symbol: "\\\$",
  },
  [CurrencyCode.XDR]: {
    id: "xdr",
    code: "XDR",
    nativeName: "Special Drawing Rights",
    nativeNamePlural: "Special Drawing Rights",
    symbol: "XDR",
  },
  [CurrencyCode.XOF]: {
    id: "xof",
    code: "XOF",
    nativeName: "West African CFA Franc",
    nativeNamePlural: "West African CFA Francs",
    symbol: "CFA",
  },
  [CurrencyCode.XPD]: {
    id: "xpd",
    code: "XPD",
    nativeName: "Palladium (one troy ounce)",
    nativeNamePlural: "Palladium (one troy ounce)",
    symbol: "XPD",
  },
  [CurrencyCode.XPF]: {
    id: "xpf",
    code: "XPF",
    nativeName: "CFP Franc",
    nativeNamePlural: "CFP Francs",
    symbol: "CFPF",
  },
  [CurrencyCode.XPT]: {
    id: "xpt",
    code: "XPT",
    nativeName: "Platinum (one troy ounce)",
    nativeNamePlural: "Platinum (one troy ounce)",
    symbol: "XPT",
  },
  [CurrencyCode.XSU]: {
    id: "xsu",
    code: "XSU",
    nativeName: "SUCRE",
    nativeNamePlural: "SUCRE",
    symbol: "XSU",
  },
  [CurrencyCode.XTS]: {
    id: "xts",
    code: "XTS",
    nativeName: "Codes specifically reserved for testing purposes",
    nativeNamePlural: "Codes specifically reserved for testing purposes",
    symbol: "XTS",
  },
  [CurrencyCode.XUA]: {
    id: "xua",
    code: "XUA",
    nativeName: "ADB Unit of Account",
    nativeNamePlural: "ADB Unit of Accounts",
    symbol: "XUA",
  },
  [CurrencyCode.XXX]: {
    id: "xxx",
    code: "XXX",
    nativeName: "No currency",
    nativeNamePlural: "No currency",
    symbol: "XXX",
  },
  [CurrencyCode.YER]: {
    id: "yer",
    code: "YER",
    nativeName: "Yemeni Rial",
    nativeNamePlural: "Yemeni Rials",
    symbol: "﷼",
  },
  [CurrencyCode.ZAR]: {
    id: "zar",
    code: "ZAR",
    nativeName: "South African Rand",
    nativeNamePlural: "South African Rand",
    symbol: "R",
  },
  [CurrencyCode.ZMW]: {
    id: "zmw",
    code: "ZMW",
    nativeName: "Zambian Kwacha",
    nativeNamePlural: "Zambian Kwachas",
    symbol: "ZK",
  },
  [CurrencyCode.ZMG]: {
    id: "zmg",
    code: "ZMG",
    nativeName: "Zambian Kwacha (pre-2013)",
    nativeNamePlural: "Zambian Kwachas (pre-2013)",
    symbol: "ZMG",
  },
  [CurrencyCode.ZWL]: {
    id: "zwl",
    code: "ZWL",
    nativeName: "Zimbabwean Dollar",
    nativeNamePlural: "Zimbabwean Dollars",
    symbol: "ZWL",
  },
} as const;

// Lookup functions
export function getCurrencyByCode(code: string): Currency | undefined {
  return currencies[code.toUpperCase() as CurrencyCode];
}
