// GENERATED CODE - DO NOT MODIFY BY HAND

import type { Language } from './types';

export enum LanguageCode {
  DA = "da",
  EN = "en",
  AZ = "az",
  DE = "de",
  AB = "ab",
  AA = "aa",
  AF = "af",
  AK = "ak",
  SQ = "sq",
  AM = "am",
  AR = "ar",
  AN = "an",
  HY = "hy",
  AS = "as",
  AV = "av",
  AE = "ae",
  AY = "ay",
  BM = "bm",
  BA = "ba",
  EU = "eu",
  BE = "be",
  BN = "bn",
  BH = "bh",
  BI = "bi",
  BS = "bs",
  BR = "br",
  BG = "bg",
  MY = "my",
  CA = "ca",
  CH = "ch",
  CE = "ce",
  CU = "cu",
  NY = "ny",
  ZH = "zh",
  CV = "cv",
  KW = "kw",
  CO = "co",
  CR = "cr",
  HR = "hr",
  CS = "cs",
  DV = "dv",
  NL = "nl",
  DZ = "dz",
  EO = "eo",
  ET = "et",
  EE = "ee",
  FO = "fo",
  FJ = "fj",
  FI = "fi",
  FR = "fr",
  FY = "fy",
  FF = "ff",
  GD = "gd",
  GL = "gl",
  LG = "lg",
  KA = "ka",
  EL = "el",
  KL = "kl",
  GN = "gn",
  GU = "gu",
  HT = "ht",
  HA = "ha",
  HE = "he",
  HZ = "hz",
  HI = "hi",
  HO = "ho",
  HU = "hu",
  IS = "is",
  IO = "io",
  IG = "ig",
  ID = "id",
  IA = "ia",
  IE = "ie",
  II = "ii",
  IU = "iu",
  IK = "ik",
  GA = "ga",
  IT = "it",
  JA = "ja",
  JV = "jv",
  KN = "kn",
  KR = "kr",
  KS = "ks",
  KK = "kk",
  KM = "km",
  KI = "ki",
  RW = "rw",
  KY = "ky",
  KV = "kv",
  KG = "kg",
  KO = "ko",
  KJ = "kj",
  KU = "ku",
  LO = "lo",
  LA = "la",
  LV = "lv",
  LI = "li",
  LN = "ln",
  LT = "lt",
  LU = "lu",
  LB = "lb",
  MK = "mk",
  MG = "mg",
  MS = "ms",
  ML = "ml",
  MT = "mt",
  GV = "gv",
  MI = "mi",
  MR = "mr",
  MH = "mh",
  MN = "mn",
  NA = "na",
  NV = "nv",
  ND = "nd",
  NR = "nr",
  NG = "ng",
  NE = "ne",
  NO = "no",
  NB = "nb",
  NN = "nn",
  OC = "oc",
  OJ = "oj",
  OR = "or",
  OM = "om",
  OS = "os",
  PI = "pi",
  PS = "ps",
  FA = "fa",
  PL = "pl",
  PT = "pt",
  PA = "pa",
  QU = "qu",
  RO = "ro",
  RM = "rm",
  RN = "rn",
  RU = "ru",
  SE = "se",
  SM = "sm",
  SG = "sg",
  SA = "sa",
  SC = "sc",
  SR = "sr",
  SD = "sd",
  SI = "si",
  SK = "sk",
  SL = "sl",
  SO = "so",
  ST = "st",
  SN = "sn",
  ES = "es",
  SU = "su",
  SW = "sw",
  SS = "ss",
  SV = "sv",
  TL = "tl",
  TY = "ty",
  TG = "tg",
  TA = "ta",
  TT = "tt",
  TE = "te",
  TH = "th",
  BO = "bo",
  TI = "ti",
  TO = "to",
  TS = "ts",
  TN = "tn",
  TR = "tr",
  TK = "tk",
  TW = "tw",
  UG = "ug",
  UK = "uk",
  UR = "ur",
  UZ = "uz",
  VE = "ve",
  VI = "vi",
  VO = "vo",
  WA = "wa",
  CY = "cy",
  WO = "wo",
  XH = "xh",
  YI = "yi",
  YO = "yo",
  ZA = "za",
  ZU = "zu",
}

export const languages: Record<LanguageCode, Language> = {
  [LanguageCode.DA]: {
    id: "danish",
    code: "da",
    nativeName: "dansk",
    dialects: [] as const,
    defaultFlagCode: "dk",
  },
  [LanguageCode.EN]: {
    id: "english",
    code: "en",
    nativeName: "english",
    dialects: [] as const,
    defaultFlagCode: "gb",
  },
  [LanguageCode.AZ]: {
    id: "azerbaijani",
    code: "az",
    nativeName: "azərbaycan dili",
    dialects: [] as const,
    defaultFlagCode: "az",
  },
  [LanguageCode.DE]: {
    id: "german",
    code: "de",
    nativeName: "Deutsch",
    dialects: [] as const,
    defaultFlagCode: "de",
  },
  [LanguageCode.AB]: {
    id: "abkhazian",
    code: "ab",
    nativeName: "аҧсуа",
    dialects: [] as const,
  },
  [LanguageCode.AA]: {
    id: "afar",
    code: "aa",
    nativeName: "Afaraf",
    dialects: [] as const,
  },
  [LanguageCode.AF]: {
    id: "afrikaans",
    code: "af",
    nativeName: "Afrikaans",
    dialects: [] as const,
  },
  [LanguageCode.AK]: {
    id: "akan",
    code: "ak",
    nativeName: "Akan",
    dialects: [] as const,
  },
  [LanguageCode.SQ]: {
    id: "albanian",
    code: "sq",
    nativeName: "Shqip",
    dialects: [] as const,
  },
  [LanguageCode.AM]: {
    id: "amharic",
    code: "am",
    nativeName: "አማርኛ",
    dialects: [] as const,
  },
  [LanguageCode.AR]: {
    id: "arabic",
    code: "ar",
    nativeName: "العربية",
    dialects: [] as const,
  },
  [LanguageCode.AN]: {
    id: "aragonese",
    code: "an",
    nativeName: "aragonés",
    dialects: [] as const,
  },
  [LanguageCode.HY]: {
    id: "armenian",
    code: "hy",
    nativeName: "Հայերեն",
    dialects: [] as const,
  },
  [LanguageCode.AS]: {
    id: "assamese",
    code: "as",
    nativeName: "অসমীয়া",
    dialects: [] as const,
  },
  [LanguageCode.AV]: {
    id: "avaric",
    code: "av",
    nativeName: "авар мацӀ",
    dialects: [] as const,
  },
  [LanguageCode.AE]: {
    id: "avestan",
    code: "ae",
    nativeName: "avesta",
    dialects: [] as const,
  },
  [LanguageCode.AY]: {
    id: "aymara",
    code: "ay",
    nativeName: "aymar aru",
    dialects: [] as const,
  },
  [LanguageCode.BM]: {
    id: "bambara",
    code: "bm",
    nativeName: "bamanankan",
    dialects: [] as const,
  },
  [LanguageCode.BA]: {
    id: "bashkir",
    code: "ba",
    nativeName: "башҡорт теле",
    dialects: [] as const,
  },
  [LanguageCode.EU]: {
    id: "basque",
    code: "eu",
    nativeName: "euskara",
    dialects: [] as const,
  },
  [LanguageCode.BE]: {
    id: "belarusian",
    code: "be",
    nativeName: "беларуская мова",
    dialects: [] as const,
  },
  [LanguageCode.BN]: {
    id: "bengali",
    code: "bn",
    nativeName: "বাংলা",
    dialects: [] as const,
  },
  [LanguageCode.BH]: {
    id: "bihari",
    code: "bh",
    nativeName: "भोजपुरी",
    dialects: [] as const,
  },
  [LanguageCode.BI]: {
    id: "bislama",
    code: "bi",
    nativeName: "Bislama",
    dialects: [] as const,
  },
  [LanguageCode.BS]: {
    id: "bosnian",
    code: "bs",
    nativeName: "bosanski jezik",
    dialects: [] as const,
  },
  [LanguageCode.BR]: {
    id: "breton",
    code: "br",
    nativeName: "brezhoneg",
    dialects: [] as const,
  },
  [LanguageCode.BG]: {
    id: "bulgarian",
    code: "bg",
    nativeName: "български език",
    dialects: [] as const,
  },
  [LanguageCode.MY]: {
    id: "burmese",
    code: "my",
    nativeName: "ဗမာစာ",
    dialects: [] as const,
  },
  [LanguageCode.CA]: {
    id: "catalan",
    code: "ca",
    nativeName: "català",
    dialects: [] as const,
  },
  [LanguageCode.CH]: {
    id: "chamorro",
    code: "ch",
    nativeName: "Chamoru",
    dialects: [] as const,
  },
  [LanguageCode.CE]: {
    id: "chechen",
    code: "ce",
    nativeName: "нохчийн мотт",
    dialects: [] as const,
  },
  [LanguageCode.CU]: {
    id: "churchSlavic",
    code: "cu",
    nativeName: "ѩзыкъ словѣньскъ",
    dialects: [] as const,
  },
  [LanguageCode.NY]: {
    id: "chichewa",
    code: "ny",
    nativeName: "chiCheŵa",
    dialects: [] as const,
  },
  [LanguageCode.ZH]: {
    id: "chinese",
    code: "zh",
    nativeName: "中文",
    dialects: [] as const,
  },
  [LanguageCode.CV]: {
    id: "chuvash",
    code: "cv",
    nativeName: "чӑваш чӗлхи",
    dialects: [] as const,
  },
  [LanguageCode.KW]: {
    id: "cornish",
    code: "kw",
    nativeName: "Kernewek",
    dialects: [] as const,
  },
  [LanguageCode.CO]: {
    id: "corsican",
    code: "co",
    nativeName: "corsu",
    dialects: [] as const,
  },
  [LanguageCode.CR]: {
    id: "cree",
    code: "cr",
    nativeName: "ᓀᐦᐃᔭᐍᐏᐣ",
    dialects: [] as const,
  },
  [LanguageCode.HR]: {
    id: "croatian",
    code: "hr",
    nativeName: "hrvatski jezik",
    dialects: [] as const,
  },
  [LanguageCode.CS]: {
    id: "czech",
    code: "cs",
    nativeName: "čeština",
    dialects: [] as const,
  },
  [LanguageCode.DV]: {
    id: "divehi",
    code: "dv",
    nativeName: "ދިވެހި",
    dialects: [] as const,
  },
  [LanguageCode.NL]: {
    id: "dutch",
    code: "nl",
    nativeName: "Nederlands",
    dialects: [] as const,
  },
  [LanguageCode.DZ]: {
    id: "dzongkha",
    code: "dz",
    nativeName: "རྫོང་ཁ",
    dialects: [] as const,
  },
  [LanguageCode.EO]: {
    id: "esperanto",
    code: "eo",
    nativeName: "Esperanto",
    dialects: [] as const,
  },
  [LanguageCode.ET]: {
    id: "estonian",
    code: "et",
    nativeName: "eesti",
    dialects: [] as const,
  },
  [LanguageCode.EE]: {
    id: "ewe",
    code: "ee",
    nativeName: "Eʋegbe",
    dialects: [] as const,
  },
  [LanguageCode.FO]: {
    id: "faroese",
    code: "fo",
    nativeName: "føroyskt",
    dialects: [] as const,
  },
  [LanguageCode.FJ]: {
    id: "fijian",
    code: "fj",
    nativeName: "vosa Vakaviti",
    dialects: [] as const,
  },
  [LanguageCode.FI]: {
    id: "finnish",
    code: "fi",
    nativeName: "suomi",
    dialects: [] as const,
  },
  [LanguageCode.FR]: {
    id: "french",
    code: "fr",
    nativeName: "français",
    dialects: [] as const,
  },
  [LanguageCode.FY]: {
    id: "westernFrisian",
    code: "fy",
    nativeName: "Frysk",
    dialects: [] as const,
  },
  [LanguageCode.FF]: {
    id: "fulah",
    code: "ff",
    nativeName: "Fulfulde",
    dialects: [] as const,
  },
  [LanguageCode.GD]: {
    id: "gaelic",
    code: "gd",
    nativeName: "Gàidhlig",
    dialects: [] as const,
  },
  [LanguageCode.GL]: {
    id: "galician",
    code: "gl",
    nativeName: "galego",
    dialects: [] as const,
  },
  [LanguageCode.LG]: {
    id: "ganda",
    code: "lg",
    nativeName: "Luganda",
    dialects: [] as const,
  },
  [LanguageCode.KA]: {
    id: "georgian",
    code: "ka",
    nativeName: "ქართული",
    dialects: [] as const,
  },
  [LanguageCode.EL]: {
    id: "greek",
    code: "el",
    nativeName: "Ελληνικά",
    dialects: [] as const,
  },
  [LanguageCode.KL]: {
    id: "greenlandic",
    code: "kl",
    nativeName: "kalaallisut",
    dialects: [] as const,
  },
  [LanguageCode.GN]: {
    id: "guarani",
    code: "gn",
    nativeName: "Avañe'ẽ",
    dialects: [] as const,
  },
  [LanguageCode.GU]: {
    id: "gujarati",
    code: "gu",
    nativeName: "ગુજરાતી",
    dialects: [] as const,
  },
  [LanguageCode.HT]: {
    id: "haitian",
    code: "ht",
    nativeName: "Kreyòl ayisyen",
    dialects: [] as const,
  },
  [LanguageCode.HA]: {
    id: "hausa",
    code: "ha",
    nativeName: "هَوُسَ",
    dialects: [] as const,
  },
  [LanguageCode.HE]: {
    id: "hebrew",
    code: "he",
    nativeName: "עברית",
    dialects: [] as const,
  },
  [LanguageCode.HZ]: {
    id: "herero",
    code: "hz",
    nativeName: "Otjiherero",
    dialects: [] as const,
  },
  [LanguageCode.HI]: {
    id: "hindi",
    code: "hi",
    nativeName: "हिन्दी",
    dialects: [] as const,
  },
  [LanguageCode.HO]: {
    id: "hiriMotu",
    code: "ho",
    nativeName: "Hiri Motu",
    dialects: [] as const,
  },
  [LanguageCode.HU]: {
    id: "hungarian",
    code: "hu",
    nativeName: "magyar",
    dialects: [] as const,
  },
  [LanguageCode.IS]: {
    id: "icelandic",
    code: "is",
    nativeName: "Íslenska",
    dialects: [] as const,
  },
  [LanguageCode.IO]: {
    id: "ido",
    code: "io",
    nativeName: "Ido",
    dialects: [] as const,
  },
  [LanguageCode.IG]: {
    id: "igbo",
    code: "ig",
    nativeName: "Asụsụ Igbo",
    dialects: [] as const,
  },
  [LanguageCode.ID]: {
    id: "indonesian",
    code: "id",
    nativeName: "Bahasa Indonesia",
    dialects: [] as const,
  },
  [LanguageCode.IA]: {
    id: "interlingua",
    code: "ia",
    nativeName: "Interlingua",
    dialects: [] as const,
  },
  [LanguageCode.IE]: {
    id: "interlingue",
    code: "ie",
    nativeName: "Interlingue",
    dialects: [] as const,
  },
  [LanguageCode.II]: {
    id: "sichuanYi",
    code: "ii",
    nativeName: "ꆈꌠ꒿ Nuosuhxop",
    dialects: [] as const,
  },
  [LanguageCode.IU]: {
    id: "inuktitut",
    code: "iu",
    nativeName: "ᐃᓄᒃᑎᑐᑦ",
    dialects: [] as const,
  },
  [LanguageCode.IK]: {
    id: "inupiaq",
    code: "ik",
    nativeName: "Iñupiaq",
    dialects: [] as const,
  },
  [LanguageCode.GA]: {
    id: "irish",
    code: "ga",
    nativeName: "Gaeilge",
    dialects: [] as const,
  },
  [LanguageCode.IT]: {
    id: "italian",
    code: "it",
    nativeName: "italiano",
    dialects: [] as const,
  },
  [LanguageCode.JA]: {
    id: "japanese",
    code: "ja",
    nativeName: "日本語",
    dialects: [] as const,
  },
  [LanguageCode.JV]: {
    id: "javanese",
    code: "jv",
    nativeName: "basa Jawa",
    dialects: [] as const,
  },
  [LanguageCode.KN]: {
    id: "kannada",
    code: "kn",
    nativeName: "ಕನ್ನಡ",
    dialects: [] as const,
  },
  [LanguageCode.KR]: {
    id: "kanuri",
    code: "kr",
    nativeName: "Kanuri",
    dialects: [] as const,
  },
  [LanguageCode.KS]: {
    id: "kashmiri",
    code: "ks",
    nativeName: "कश्मीरी",
    dialects: [] as const,
  },
  [LanguageCode.KK]: {
    id: "kazakh",
    code: "kk",
    nativeName: "қазақ тілі",
    dialects: [] as const,
  },
  [LanguageCode.KM]: {
    id: "khmer",
    code: "km",
    nativeName: "ភាសាខ្មែរ",
    dialects: [] as const,
  },
  [LanguageCode.KI]: {
    id: "kikuyu",
    code: "ki",
    nativeName: "Gĩkũyũ",
    dialects: [] as const,
  },
  [LanguageCode.RW]: {
    id: "kinyarwanda",
    code: "rw",
    nativeName: "Ikinyarwanda",
    dialects: [] as const,
  },
  [LanguageCode.KY]: {
    id: "kirghiz",
    code: "ky",
    nativeName: "Кыргызча",
    dialects: [] as const,
  },
  [LanguageCode.KV]: {
    id: "komi",
    code: "kv",
    nativeName: "коми кыв",
    dialects: [] as const,
  },
  [LanguageCode.KG]: {
    id: "kongo",
    code: "kg",
    nativeName: "Kikongo",
    dialects: [] as const,
  },
  [LanguageCode.KO]: {
    id: "korean",
    code: "ko",
    nativeName: "한국어",
    dialects: [] as const,
  },
  [LanguageCode.KJ]: {
    id: "kuanyama",
    code: "kj",
    nativeName: "Kuanyama",
    dialects: [] as const,
  },
  [LanguageCode.KU]: {
    id: "kurdish",
    code: "ku",
    nativeName: "Kurdî",
    dialects: [] as const,
  },
  [LanguageCode.LO]: {
    id: "lao",
    code: "lo",
    nativeName: "ພາສາລາວ",
    dialects: [] as const,
  },
  [LanguageCode.LA]: {
    id: "latin",
    code: "la",
    nativeName: "latine",
    dialects: [] as const,
  },
  [LanguageCode.LV]: {
    id: "latvian",
    code: "lv",
    nativeName: "latviešu valoda",
    dialects: [] as const,
  },
  [LanguageCode.LI]: {
    id: "limburgish",
    code: "li",
    nativeName: "Limburgs",
    dialects: [] as const,
  },
  [LanguageCode.LN]: {
    id: "lingala",
    code: "ln",
    nativeName: "Lingála",
    dialects: [] as const,
  },
  [LanguageCode.LT]: {
    id: "lithuanian",
    code: "lt",
    nativeName: "lietuvių kalba",
    dialects: [] as const,
  },
  [LanguageCode.LU]: {
    id: "lubaKatanga",
    code: "lu",
    nativeName: "Tshiluba",
    dialects: [] as const,
  },
  [LanguageCode.LB]: {
    id: "luxembourgish",
    code: "lb",
    nativeName: "Lëtzebuergesch",
    dialects: [] as const,
  },
  [LanguageCode.MK]: {
    id: "macedonian",
    code: "mk",
    nativeName: "македонски јазик",
    dialects: [] as const,
  },
  [LanguageCode.MG]: {
    id: "malagasy",
    code: "mg",
    nativeName: "fiteny malagasy",
    dialects: [] as const,
  },
  [LanguageCode.MS]: {
    id: "malay",
    code: "ms",
    nativeName: "Bahasa Melayu",
    dialects: [] as const,
  },
  [LanguageCode.ML]: {
    id: "malayalam",
    code: "ml",
    nativeName: "മലയാളം",
    dialects: [] as const,
  },
  [LanguageCode.MT]: {
    id: "maltese",
    code: "mt",
    nativeName: "Malti",
    dialects: [] as const,
  },
  [LanguageCode.GV]: {
    id: "manx",
    code: "gv",
    nativeName: "Gaelg",
    dialects: [] as const,
  },
  [LanguageCode.MI]: {
    id: "maori",
    code: "mi",
    nativeName: "te reo Māori",
    dialects: [] as const,
  },
  [LanguageCode.MR]: {
    id: "marathi",
    code: "mr",
    nativeName: "मराठी",
    dialects: [] as const,
  },
  [LanguageCode.MH]: {
    id: "marshallese",
    code: "mh",
    nativeName: "Kajin M̧ajeļ",
    dialects: [] as const,
  },
  [LanguageCode.MN]: {
    id: "mongolian",
    code: "mn",
    nativeName: "Монгол хэл",
    dialects: [] as const,
  },
  [LanguageCode.NA]: {
    id: "nauru",
    code: "na",
    nativeName: "Ekakairũ Naoero",
    dialects: [] as const,
  },
  [LanguageCode.NV]: {
    id: "navajo",
    code: "nv",
    nativeName: "Diné bizaad",
    dialects: [] as const,
  },
  [LanguageCode.ND]: {
    id: "northNdebele",
    code: "nd",
    nativeName: "isiNdebele",
    dialects: [] as const,
  },
  [LanguageCode.NR]: {
    id: "southNdebele",
    code: "nr",
    nativeName: "isiNdebele",
    dialects: [] as const,
  },
  [LanguageCode.NG]: {
    id: "ndonga",
    code: "ng",
    nativeName: "Owambo",
    dialects: [] as const,
  },
  [LanguageCode.NE]: {
    id: "nepali",
    code: "ne",
    nativeName: "नेपाली",
    dialects: [] as const,
  },
  [LanguageCode.NO]: {
    id: "norwegian",
    code: "no",
    nativeName: "Norsk",
    dialects: [] as const,
  },
  [LanguageCode.NB]: {
    id: "norwegianBokmal",
    code: "nb",
    nativeName: "Norsk bokmål",
    dialects: [] as const,
  },
  [LanguageCode.NN]: {
    id: "norwegianNynorsk",
    code: "nn",
    nativeName: "Norsk nynorsk",
    dialects: [] as const,
  },
  [LanguageCode.OC]: {
    id: "occitan",
    code: "oc",
    nativeName: "occitan",
    dialects: [] as const,
  },
  [LanguageCode.OJ]: {
    id: "ojibwa",
    code: "oj",
    nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    dialects: [] as const,
  },
  [LanguageCode.OR]: {
    id: "oriya",
    code: "or",
    nativeName: "ଓଡ଼ିଆ",
    dialects: [] as const,
  },
  [LanguageCode.OM]: {
    id: "oromo",
    code: "om",
    nativeName: "Afaan Oromoo",
    dialects: [] as const,
  },
  [LanguageCode.OS]: {
    id: "ossetian",
    code: "os",
    nativeName: "ирон æвзаг",
    dialects: [] as const,
  },
  [LanguageCode.PI]: {
    id: "pali",
    code: "pi",
    nativeName: "पाऴि",
    dialects: [] as const,
  },
  [LanguageCode.PS]: {
    id: "pashto",
    code: "ps",
    nativeName: "پښتو",
    dialects: [] as const,
  },
  [LanguageCode.FA]: {
    id: "persian",
    code: "fa",
    nativeName: "فارسی",
    dialects: [] as const,
  },
  [LanguageCode.PL]: {
    id: "polish",
    code: "pl",
    nativeName: "język polski",
    dialects: [] as const,
  },
  [LanguageCode.PT]: {
    id: "portuguese",
    code: "pt",
    nativeName: "português",
    dialects: [] as const,
  },
  [LanguageCode.PA]: {
    id: "punjabi",
    code: "pa",
    nativeName: "ਪੰਜਾਬੀ",
    dialects: [] as const,
  },
  [LanguageCode.QU]: {
    id: "quechua",
    code: "qu",
    nativeName: "Runa Simi",
    dialects: [] as const,
  },
  [LanguageCode.RO]: {
    id: "romanian",
    code: "ro",
    nativeName: "limba română",
    dialects: [] as const,
  },
  [LanguageCode.RM]: {
    id: "romansh",
    code: "rm",
    nativeName: "rumantsch grischun",
    dialects: [] as const,
  },
  [LanguageCode.RN]: {
    id: "rundi",
    code: "rn",
    nativeName: "Ikirundi",
    dialects: [] as const,
  },
  [LanguageCode.RU]: {
    id: "russian",
    code: "ru",
    nativeName: "русский язык",
    dialects: [] as const,
  },
  [LanguageCode.SE]: {
    id: "northernSami",
    code: "se",
    nativeName: "Davvisámegiella",
    dialects: [] as const,
  },
  [LanguageCode.SM]: {
    id: "samoan",
    code: "sm",
    nativeName: "gagana fa'a Samoa",
    dialects: [] as const,
  },
  [LanguageCode.SG]: {
    id: "sango",
    code: "sg",
    nativeName: "yângâ tî sängö",
    dialects: [] as const,
  },
  [LanguageCode.SA]: {
    id: "sanskrit",
    code: "sa",
    nativeName: "संस्कृतम्",
    dialects: [] as const,
  },
  [LanguageCode.SC]: {
    id: "sardinian",
    code: "sc",
    nativeName: "sardu",
    dialects: [] as const,
  },
  [LanguageCode.SR]: {
    id: "serbian",
    code: "sr",
    nativeName: "српски језик",
    dialects: [] as const,
  },
  [LanguageCode.SD]: {
    id: "sindhi",
    code: "sd",
    nativeName: "सिन्धी",
    dialects: [] as const,
  },
  [LanguageCode.SI]: {
    id: "sinhala",
    code: "si",
    nativeName: "සිංහල",
    dialects: [] as const,
  },
  [LanguageCode.SK]: {
    id: "slovak",
    code: "sk",
    nativeName: "slovenčina",
    dialects: [] as const,
  },
  [LanguageCode.SL]: {
    id: "slovenian",
    code: "sl",
    nativeName: "slovenščina",
    dialects: [] as const,
  },
  [LanguageCode.SO]: {
    id: "somali",
    code: "so",
    nativeName: "Soomaaliga",
    dialects: [] as const,
  },
  [LanguageCode.ST]: {
    id: "southernSotho",
    code: "st",
    nativeName: "Sesotho",
    dialects: [] as const,
  },
  [LanguageCode.SN]: {
    id: "shona",
    code: "sn",
    nativeName: "chiShona",
    dialects: [] as const,
  },
  [LanguageCode.ES]: {
    id: "spanish",
    code: "es",
    nativeName: "español",
    dialects: [] as const,
  },
  [LanguageCode.SU]: {
    id: "sundanese",
    code: "su",
    nativeName: "Basa Sunda",
    dialects: [] as const,
  },
  [LanguageCode.SW]: {
    id: "swahili",
    code: "sw",
    nativeName: "Kiswahili",
    dialects: [] as const,
  },
  [LanguageCode.SS]: {
    id: "swati",
    code: "ss",
    nativeName: "SiSwati",
    dialects: [] as const,
  },
  [LanguageCode.SV]: {
    id: "swedish",
    code: "sv",
    nativeName: "svenska",
    dialects: [] as const,
  },
  [LanguageCode.TL]: {
    id: "tagalog",
    code: "tl",
    nativeName: "Wikang Tagalog",
    dialects: [] as const,
  },
  [LanguageCode.TY]: {
    id: "tahitian",
    code: "ty",
    nativeName: "Reo Tahiti",
    dialects: [] as const,
  },
  [LanguageCode.TG]: {
    id: "tajik",
    code: "tg",
    nativeName: "тоҷикӣ",
    dialects: [] as const,
  },
  [LanguageCode.TA]: {
    id: "tamil",
    code: "ta",
    nativeName: "தமிழ்",
    dialects: [] as const,
  },
  [LanguageCode.TT]: {
    id: "tatar",
    code: "tt",
    nativeName: "татар теле",
    dialects: [] as const,
  },
  [LanguageCode.TE]: {
    id: "telugu",
    code: "te",
    nativeName: "తెలుగు",
    dialects: [] as const,
  },
  [LanguageCode.TH]: {
    id: "thai",
    code: "th",
    nativeName: "ไทย",
    dialects: [] as const,
  },
  [LanguageCode.BO]: {
    id: "tibetan",
    code: "bo",
    nativeName: "བོད་ཡིག",
    dialects: [] as const,
  },
  [LanguageCode.TI]: {
    id: "tigrinya",
    code: "ti",
    nativeName: "ትግርኛ",
    dialects: [] as const,
  },
  [LanguageCode.TO]: {
    id: "tonga",
    code: "to",
    nativeName: "faka Tonga",
    dialects: [] as const,
  },
  [LanguageCode.TS]: {
    id: "tsonga",
    code: "ts",
    nativeName: "Xitsonga",
    dialects: [] as const,
  },
  [LanguageCode.TN]: {
    id: "tswana",
    code: "tn",
    nativeName: "Setswana",
    dialects: [] as const,
  },
  [LanguageCode.TR]: {
    id: "turkish",
    code: "tr",
    nativeName: "Türkçe",
    dialects: [] as const,
  },
  [LanguageCode.TK]: {
    id: "turkmen",
    code: "tk",
    nativeName: "Türkmen",
    dialects: [] as const,
  },
  [LanguageCode.TW]: {
    id: "twi",
    code: "tw",
    nativeName: "Twi",
    dialects: [] as const,
  },
  [LanguageCode.UG]: {
    id: "uighur",
    code: "ug",
    nativeName: "ئۇيغۇرچە‎",
    dialects: [] as const,
  },
  [LanguageCode.UK]: {
    id: "ukrainian",
    code: "uk",
    nativeName: "українська мова",
    dialects: [] as const,
  },
  [LanguageCode.UR]: {
    id: "urdu",
    code: "ur",
    nativeName: "اردو",
    dialects: [] as const,
  },
  [LanguageCode.UZ]: {
    id: "uzbek",
    code: "uz",
    nativeName: "Oʻzbek",
    dialects: [] as const,
  },
  [LanguageCode.VE]: {
    id: "venda",
    code: "ve",
    nativeName: "Tshivenḓa",
    dialects: [] as const,
  },
  [LanguageCode.VI]: {
    id: "vietnamese",
    code: "vi",
    nativeName: "Tiếng Việt",
    dialects: [] as const,
  },
  [LanguageCode.VO]: {
    id: "volapuk",
    code: "vo",
    nativeName: "Volapük",
    dialects: [] as const,
  },
  [LanguageCode.WA]: {
    id: "walloon",
    code: "wa",
    nativeName: "walon",
    dialects: [] as const,
  },
  [LanguageCode.CY]: {
    id: "welsh",
    code: "cy",
    nativeName: "Cymraeg",
    dialects: [] as const,
  },
  [LanguageCode.WO]: {
    id: "wolof",
    code: "wo",
    nativeName: "Wollof",
    dialects: [] as const,
  },
  [LanguageCode.XH]: {
    id: "xhosa",
    code: "xh",
    nativeName: "isiXhosa",
    dialects: [] as const,
  },
  [LanguageCode.YI]: {
    id: "yiddish",
    code: "yi",
    nativeName: "ייִדיש",
    dialects: [] as const,
  },
  [LanguageCode.YO]: {
    id: "yoruba",
    code: "yo",
    nativeName: "Yorùbá",
    dialects: [] as const,
  },
  [LanguageCode.ZA]: {
    id: "zhuang",
    code: "za",
    nativeName: "Saɯ cueŋƅ",
    dialects: [] as const,
  },
  [LanguageCode.ZU]: {
    id: "zulu",
    code: "zu",
    nativeName: "isiZulu",
    dialects: [] as const,
  },
} as const;

// Lookup functions
export function getLanguageByCode(code: string): Language | undefined {
  return languages[code.toLowerCase() as LanguageCode];
}
